### ISSUE TITLE
Disable the warning message when build MIOpen with COMGR

### ISSUE THREAD

**Issue by sunway513** [ROCmSoftwarePlatform/MIOpen#1003]
Using the pytorch whl package with MIOpen-Comgr, the KDB will not be used. However, we still see the following warning messages when trying to launch PyT workloads:
```
MIOpen(HIP): Warning [SQLiteBase] Unable to read system database file:/opt/rocm/miopen/share/miopen/db/gfx906_64.kdb Performance may degrade
```
Is it possible to disable such warning at build time or run time?
cc @jeffdaily

**Comment by atamazov** [comment]
This is possible. But notice that COMGR is just a method of building kernels; it dos not affect how the library reads databases. 

You can use `-DMIOPEN_DISABLE_SYSDB=On` in the CMake command line.

And please let us know how do you build MIOpen. Maybe we'll be able to recommend something better.

/cc @JehandadKhan

**Comment by sunway513** [comment]
Thanks @atamazov , here's the script we use to build MIOpen:
https://github.com/pytorch/builder/blob/master/common/install_miopen.sh

**Comment by atamazov** [comment]
Well, maybe the best way to resolve an issue is adding `-DMIOPEN_DISABLE_SYSDB=On`. Can you please try and let us know if this works for you.
