### ISSUE TITLE
Hard time wrapping this with Go.

### ISSUE THREAD

**Issue by dereklstinson** [ROCmSoftwarePlatform/MIOpen#103]
I am trying to bind miopen with golang.  I made binding for cudnn relatively easily. I set the CGO flags to:

//#cgo LDFLAGS:-L/usr/local/cuda/lib64 -lcudnn -lcuda
//#cgo CFLAGS: -I/usr/local/cuda/include/

and it just works.

I'm having a hard time doing this with miopen.  I installed rocm and miopen-hip using the prebuilt packages.  I can't seem to find documentation to set up miopen and hip to play nice with C and Cgo. Would anyone be able to help me?

**Comment by pfultz2** [comment]
I believe `CFLAGS='-I/opt/rocm/include'` and `LDFLAGS='-L/opt/rocm/lib -lMIOpen -lhip_hcc'` would be the equivalent flags.

**Comment by dereklstinson** [comment]
I changed my cgo flags to that:

#cgo CFLAGS: -I/opt/rocm/include
#cgo LDFLAGS: -L/opt/rocm/lib -lMIOpen -lhip_hcc

Then I get this error:
>

	"resource": "/opt/rocm/hip/include/hip/hip_runtime_api.h",
	"owner": "go",
	"severity": 8,
	"message": "error: #error (\"Must define exactly one of __HIP_PLATFORM_HCC__ or _HIP_PLATFORM_NVCC__\");",
	"source": "go",
	"startLineNumber": 312,
	"startColumn": 1,
	"endLineNumber": 312,
	"endColumn": 2


I tried adding -D__HIP_PLATFORM_HCC__ to the CFLAGS.  

#cgo CFLAGS: -I/opt/rocm/include -D__HIP_PLATFORM_HCC__
#cgo LDFLAGS: -L/opt/rocm/lib -lMIOpen -lhip_hcc

Then, I get two more errors.
> 

	"resource": "/opt/rocm/hip/include/hip/hcc_detail/code_object_bundle.hpp",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "cannot open source file "hsa/hsa.h"",
	"startLineNumber": 25,
	"startColumn": 1,
	"endLineNumber": 25,
	"endColumn": 21


> 

	"resource": "/opt/rocm/include/hip/hcc_detail/code_object_bundle.hpp",
	"owner": "go",
	"severity": 8,
	"message": "fatal error: algorithm: No such file or directory",
	"source": "go",
	"startLineNumber": 27,
	"startColumn": 1,
	"endLineNumber": 27,
	"endColumn": 2

I don't think adding -D__HIP_PLATFORM_HCC__ was the correct thing to do because hsa/hsa.h is in the /opt/rocm/include directory.

**Comment by pfultz2** [comment]
I think you need to install the `hsa-rocr-dev` package to get the hsa headers.

**Comment by dereklstinson** [comment]
It seems I am running into an issue with gcc.  I tried making a small c program and built it using both gcc and hipcc.  Hipcc worked fine, and gcc didn't (I get the same errors as my previous post).    hip_runtime_api.h is supposed to be gcc and c compatable.  Is there something I am missing, or is this a bug with hip. I am running ubuntu 18.04 with gcc  version 7.4.

**Comment by pfultz2** [comment]
>  Is there something I am missing, or is this a bug with hip.

I think this is possibly bug with HIP as its headers are supposed to work with g++.

**Comment by dereklstinson** [comment]
Go has to use gcc not g++.  But the good news is that I was able to get something to compile.  I created a handle then exited.   Changes had to be made to hip_runtime_api.h (which I will not go over here. It also looks like there is a pull request that might fix the stuff I had to change).  For miopen, I had to add #include<stdbool.h> to miopen.h.

**Comment by daniellowell** [comment]
@pfultz2 Do we want to just permanently add in #include<stdbool.h> to miopen.h?

**Comment by dereklstinson** [comment]
I made a pull request. for this issue.
