### ISSUE TITLE
[TESTS][gfx90a] Support gfx90a in tests

### ISSUE THREAD

**Issue by atamazov** [ROCmSoftwarePlatform/MIOpen#1031]
`cmake -DMIOPEN_TEST_GFX90A` ... ? See #1024 for more info and also look there how `MIOPEN_TEST_VEGA` and `MIOPEN_TEST_GFX908` are implemented.

**Comment by muralinr** [comment]
What should I do here? Do I need to use "cmake -DMIOPEN_TEST_GFX90A" for testing?  I will sync-up with you

**Comment by atamazov** [comment]
We need to add support for gfx90a in test/CMakeLists.txt. Please look at how gfx908 is supported and add similar stuff.

**Comment by carlushuang** [comment]
@atamazov here we have a first PR capable of MI200 kernels https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1035 this I believe is a good test material for the CI infrastructure.
cc @shaojiewang

**Comment by atamazov** [comment]
I am going to implement basic support in tests for navi21 and gfx90a, today.

**Comment by atamazov** [comment]
@okakarpa Assigning to you to keep you in the loop.

**Comment by okakarpa** [comment]
> @okakarpa Assigning to you to keep you in the loop.

the navi21 node

     http://micimaster.amd.com/computer/ixt-sjc2-61/

**Comment by shaojiewang** [comment]
Do we have a support for gfx90a in ctest?

**Comment by junliume** [comment]
@atamazov do you have a WIP branch for this issue? If not yet I will ask @shaojiewang to support this issue as a prerequisite for #1035. Thanks!

**Comment by junliume** [comment]
> @atamazov do you have a WIP branch for this issue? If not yet I will ask @shaojiewang to support this issue as a prerequisite for #1035. Thanks!

@shaojiewang we initiated a WIP branch to *completely* mimic gfx 908 behavior in #1067, could you take a look and make necessary changes and fixes please?

**Comment by shaojiewang** [comment]
> > @atamazov do you have a WIP branch for this issue? If not yet I will ask @shaojiewang to support this issue as a prerequisite for #1035. Thanks!
> 
> @shaojiewang we initiated a WIP branch to _completely_ mimic gfx 908 behavior in #1067, could you take a look and make necessary changes and fixes please? (or start from fresh or what you already have :) ... I am just trying to see if I can help a bit)

Yes, I'll use it. Thanks a lot.

**Comment by atamazov** [comment]
Let me repeat the plan here:
- (1) Switch MIOpen CI from SSH to HTTPS auth
  - @okakarpa, can you please test that in the sandbox? 
    - For MIOpen, it is enough to check that develop branch is working fine. But this change may affect other projects in ROCmSoftwarePlatform, specifically AMDMIGraphX and MIOpenTensile
    - Therefore either the SSH->HTTPS switchover should be done for MIOpen only OR other projects should be tested before the switchover
    - @pfultz2, would it be Ok if we switch from SSH to HTTPS auth for the whole ROCmSoftwarePlatform?
- (2) Integrate changes [from here](https://github.com/ROCmSoftwarePlatform/MIOpen/compare/wip-rocmtest-trial-mi100...wip-rocmtest-trial-mi200) into Dockerfile and Jenkinsfile so that the changes only affect testing on gfx90a.
  - If assistance is needed, ask @shurale-nkn  or me.
- (3) Add detection of gfx90a in tests/Cmakelists.txt.
  - Draft implementation in #1067.
- (4) Enable gfx90a on CI
  - (4.1) Run all tests locally on development node. W/A or quickly fix the failing ones (like I did for Navi21 recently) and open relevant tickets.
  - (4.2) Modify Jenkinsfile, but not enable gfx90a testing yet
    - I recommend adding one Smoke stage and one Full Test stage, both FP32 as we have only one (or two?) nodes in CI. Well, one more Smoke stage for FP16 would be also ok. If we add more stages, I would expect a bottleneck.
  - (4.3) Create a gfx90a trial branch and make sure it passed all the tests.
  - (4.4) Update Jenkinsfile -- enable gfx90a testing

When all of the above is done, we have basic MI200 testing in our CI.

**Comment by pfultz2** [comment]
> Switch MIOpen CI from SSH to HTTPS auth 

Whats the reason for this? I switched from https to ssh because https didn't work inside our internal network(due to IT's MITM).

**Comment by atamazov** [comment]
@pfultz2 Please see mail thread, "public docker access". In short:

> @okakarpa: The git clone through ssh doesn’t work but we can still use https.

> @pfultz2: https didn't work inside our internal network(due to IT's MITM).

If this is so, then we are stuck again. But the testing pipeline created by @okakarpa somehow works (see mail)... However I didn't investigated the logs of the testing pipeline in detail yet. Lets discuss further in mail.

**Comment by okakarpa** [comment]
@pfultz2 for git cloning through ssh it uses  port 22 towards GitHub, which seems to be blocked so we have to switch to https.
It's better to use git https cloning just for MI200 rather than changing for all the jobs, @atamazov your thoughts ?

**Comment by atamazov** [comment]
That would be the best solution, but I am wondering if this is possible to do within the same Jenkins ogranization/project. _Lets discuss further in mail._

**Comment by pfultz2** [comment]
> for git cloning through ssh it uses port 22 towards GitHub

The machine should be configured to clone github using port 443(which is not blocked), if not then the machine is not configure correctly. In the fab scripts, I usually just copy the ~/.ssh directory from a machine thats already setup. This will copy the ssh keys and config file which is needed to clone github on port 443. You should do the same for the new gfx90a machines.

**Comment by okakarpa** [comment]
I did run fab scripts setup-Jenkins on the node, for https it uses 443 but for ssh it uses port 22

https://docs.github.com/en/enterprise-server@2.21/admin/configuration/configuring-network-settings/network-ports#administrative-ports

**Comment by pfultz2** [comment]
> I did run fab scripts setup-Jenkins on the node, for https it uses 443 but for ssh it uses port 22

Did you run the `copy-ssh` command to copy the ssh directory from an already setup node?

**Comment by okakarpa** [comment]
I had to manually reset the config file.

The git clone works on ssh as well, @pfultz2  thanks !!!

http://micimaster.amd.com/job/MLLibs/job/MIOpen/job/wip-rocmtest-trial-mi200/7/console

**Comment by shaojiewang** [comment]
>  Integrate changes from here into Dockerfile and Jenkinsfile so that the changes only affect testing on gfx90a

@shurale-nkn In the WIP branch, why we need to avoid reboot for gfx90a? I just copy the wip_gfx90a branch in #1082 , but I do not understand why we do these changes.

**Comment by atamazov** [comment]
implemented
