### ISSUE TITLE
MIOpenBatchNormBwdPerAct.cl kernel bug

### ISSUE THREAD

**Issue by joye** [ROCmSoftwarePlatform/MIOpen#104]
in https://github.com/ROCmSoftwarePlatform/MIOpen/blob/master/src/kernels/MIOpenBatchNormBwdPerAct.cl#L174

the tmp2's calculation is wrong, which should be 

dyelem = (_FLOAT_PREC)(dy_in[index]);
tmp2          = mad((_FLOAT_PREC)N, dyelem * pvt_scale, -tmp1);

please check the formula of this derivative.

After this change, the result can match with cuDNN result for the same input.

**Comment by ce1adon** [comment]
@joye @atamazov 
Thank you Mei! You are right. This calculation is wrong. 

Based on this information the calculation at
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/master/src/kernels/MIOpenBatchNormBwdPerAct.cl#L265
also need to be corrected.

Considering we don't have error report in ctest or driver, I think the verification in ctest and driver also need to be changed. Can you setup a priority level?

**Comment by ce1adon** [comment]
I think instead of doing a patch here, maybe put it in the next release. What do you think? @atamazov

**Comment by atamazov** [comment]
Yes, let's fix during normal development process. Anyone who needs the fix ASAP can ask us explicitly (right here) for the patch.

**Comment by daniellowell** [comment]
I’ll fix it for the next release.

**Comment by daniellowell** [comment]
Fixed in MIOpen 2.0.0
