### ISSUE TITLE
[driver] Update LogCmdRedux() for double.

### ISSUE THREAD

**Issue by atamazov** [ROCmSoftwarePlatform/MIOpen#1041]
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/1ebf0216930f672994c341d3c29c9d670cfd3cf8/src/reducetensor_api.cpp#L44

What is missing there:
```C++
        else if(aDesc.GetType() == miopenDouble)
            ss << "reducefp64";
```

**Comment by qianfengz** [comment]
Ok,   I will do this soon
