### ISSUE TITLE
[Navi21] test_lrn_test (Failed)

### ISSUE THREAD

**Issue by atamazov** [ROCmSoftwarePlatform/MIOpen#1053]
ROCm 4.2, OCL backend, Navi21, Full test: `test_lrn_test (Failed)`.

`WORKAROUND_ISSUE_1053` is used to avoid this error.

**Comment by atamazov** [comment]
`WORKAROUND_ISSUE_1053` used to avoid this error.

**Comment by atamazov** [comment]
@junliume @JehandadKhan Can you please assign this?

**Comment by junliume** [comment]
@ce1adon could you take a look? Possibly related to #1054 ? not applicable to Navi21 for some reasons?

**Comment by ce1adon** [comment]
> @ce1adon could you take a look? Possibly related to #1054 ? not applicable to Navi21 for some reasons?

https://ontrack-internal.amd.com/browse/SWDEV-289454?focusedCommentId=7514219&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-7514219
Previous comments show it's a compiler issue.

**Comment by atamazov** [comment]
@junliume @ce1adon https://ontrack-internal.amd.com/browse/SWDEV-289454 was rejected. It seems that the relevant ticket is https://ontrack-internal.amd.com/browse/SWDEV-288205, which is in closed state now, but fixed Mainline build number of the compiler/runtime was not published there.

**Comment by atamazov** [comment]
I recommend checking the issue with the most recent ROCm 4.3 release candidate, If the issue persists, then SWDEV-288205 can be reopened.

**Comment by junliume** [comment]
@xinlipn  I have tested a few times, and it seems that at least for the HIP backend, this workaround can be removed.
