### ISSUE TITLE
fatal error: 'miopen/config.h' file not found when build from source with ROCm-2.3

### ISSUE THREAD

**Issue by wormwang** [ROCmSoftwarePlatform/MIOpen#106]
With ROCm 2.3 & hcc-1.3.19115 & hip_hcc-1.5.19123

HIP_PLATFORM=hcc ROCM_PATH=/opt/rocm  CXX=/opt/rocm/hcc/bin/hcc cmake  -DMIOPEN_BACKEND=HIP -DCMAKE_PREFIX_PATH="/opt/rocm/hcc;/opt/rocm/hip"    -DHIP_OC_COMPILER=/opt/rocm/bin/clang-ocl ..

miopen181/MIOpen/build# make -j4
Scanning dependencies of target addkernels
[  3%] Building CXX object addkernels/CMakeFiles/addkernels.dir/addkernels.cpp.o
[  3%] Building CXX object addkernels/CMakeFiles/addkernels.dir/include_inliner.cpp.o
[  3%] Linking CXX executable ../bin/addkernels
[  3%] Built target addkernels
[  3%] Inlining MIOpen kernels
Scanning dependencies of target MIOpen
[  3%] Building CXX object src/CMakeFiles/MIOpen.dir/check_numerics.cpp.o
[  3%] Building CXX object src/CMakeFiles/MIOpen.dir/convolution.cpp.o
[  7%] Building CXX object src/CMakeFiles/MIOpen.dir/convolution_api.cpp.o
[  7%] Building CXX object src/CMakeFiles/MIOpen.dir/convolution_fft.cpp.o
/tmp/miopen181/MIOpen/src/convolution.cpp:26:10: fatal error: 'miopen/config.h' file not found
#include <miopen/config.h>
         ^~~~~~~~~~~~~~~~~
In file included from /tmp/miopen181/MIOpen/src/convolution_fft.cpp:26:
In file included from /tmp/miopen181/MIOpen/src/include/miopen/convolution.hpp:29:
/tmp/miopen181/MIOpen/src/include/miopen/common.hpp:30:10: fatal error: 'miopen/miopen.h' file not found
#include <miopen/miopen.h>
         ^~~~~~~~~~~~~~~~~

**Comment by pfultz2** [comment]
What is the output of the cmake command?

**Comment by wormwang** [comment]
fixed by install half.hpp
