### ISSUE TITLE
[gfx908] test_dropout failed without info

### ISSUE THREAD

**Issue by shurale-nkn** [ROCmSoftwarePlatform/MIOpen#1064]
test_dropout failed without 'FAILED' trigger word .

Disabled by default in develop.

```[2021-07-28T15:47:56.349Z]  7/78 Test #17: test_dropout ...............................***Failed  2756.43 sec```
Possible reason:
```[2021-07-28T15:47:56.355Z] Config requires 154619215872 Bytes to write all necessary tensors to GPU. GPU has 34342961152 Bytes of memory```

some test requires 154619215872 bytes / 1024 /1024 /1024 => 144Gb ... That seems like kind of a lot

Failed CI build:
http://micimaster.amd.com/blue/rest/organizations/jenkins/pipelines/MLLibs/pipelines/MIOpen/branches/tests_for_908/runs/6/nodes/1505/steps/1603/log/?start=0

**Comment by junliume** [comment]
test_dropout failed on gfx908 as early as I know (April 3rd) and marked as "Same issue as observed in baseline". @atamazov  do you recall how long has it been like this? :)

@ce1adon from [SWDEV-200503](https://ontrack-internal.amd.com/browse/SWDEV-200503)'s description, could you please check if it is a reoccurrence of the same issue?

**Comment by ce1adon** [comment]
Will need a gfx908 to debug
If the error is due to usage of memory, we shall add a check to skip those large tests.
BTW, I never see memory error before, it could be another compiler issue.

**Comment by atamazov** [comment]
@junliume This is something the CQE is observing for a long time. They are considering this as a "known problem", which means that they do not care if dropout fails. If we disable dropout test, then dropout is vulnerable for future, possibly more important bugs, because neither our CI nor CQE will catch them.

Therefore I think this must be resolved and test re-enabled ASAP.

**Comment by atamazov** [comment]
In other words: W/A disables some test. The missing test is a bug in tests. That is why I set the `bug` label.

**Comment by atamazov** [comment]
Well, maybe blocker is overkill))

**Comment by atamazov** [comment]
>  do you recall how long has it been like this? :)

No, it passed me by...
