### ISSUE TITLE
miopen only supports 4D tensors, dim=5 not allowed

### ISSUE THREAD

**Issue by nuu9323226** [ROCmSoftwarePlatform/MIOpen#107]
I run a 3d conv network.
I have a problem
Has anyone encountered it?

Predict volume shape: (24, 31, 31)
2019-06-06 16:58:04.595653: F tensorflow/stream_executor/rocm/rocm_dnn.cc:494] miopen only supports 4D tensors, dim=5 not allowed

GPU:radeon vii

**Comment by daniellowell** [comment]
What is your ROCm version and MIOpen version? Are you running HIP or OpenCL?

**Comment by nuu9323226** [comment]
I install miopen-opencl
Version is as follows

$ apt-cache policy rocm-dkms
rocm-dkms: 2.4.25

$ apt-cache policy miopen-opencl
miopen-opencl: 1.8.1-84fcb51

**Comment by daniellowell** [comment]
Unfortunately we have an imbalance in our library where we have implemented 3-D convolutions in rocBLAS. This mean it is currently only supported by the HIP backend. We are working on restoring symmetry to our library in a future release.
