### ISSUE TITLE
[Doc] make clean does not remove all generated files in doc/src

### ISSUE THREAD

**Issue by averinevg** [ROCmSoftwarePlatform/MIOpen#1073]
During documentation building several files are copied from other directories and remain after cleaning:

- doc/src/driver.md
- doc/src/install.md

**Comment by junliume** [comment]
@averinevg are you still working on resolving this issue?

**Comment by averinevg** [comment]
@junliume I just created https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1073 and https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1074, and switched to refactoring. I'll do them in parallel then.
