### ISSUE TITLE
[Doc] Proper documentation is generated only after second make doc

### ISSUE THREAD

**Issue by averinevg** [ROCmSoftwarePlatform/MIOpen#1074]
Proper html documentation is generated only after second `make doc`. This is because html files are generated before copying of driver.md and install.md. These files remain after `make clean`. This issue connected with https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1073

**Comment by junliume** [comment]
@averinevg are you working on this issue together with #1073? Thanks!

**Comment by averinevg** [comment]
@junliume I just created https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1073 and https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1074, and switched to refactoring. I'll do them in parallel then.
