### ISSUE TITLE
[NoGPU] Build MIOpen fails when GPU device does not exist

### ISSUE THREAD

**Issue by junliume** [ROCmSoftwarePlatform/MIOpen#1080]
After enablement of #1024 MIOpen cannot build successfully on GPU-less platforms, such as WSL environment

[Task]
Differentiate "ROCMINFO FAILED, GPU TYPE UNKNOWN". and "ROCk module is NOT loaded, possibly no GPU devices".
Community can play with MIOpen build with WSL
MIOpen can be built on GPU-less platforms or servers

**Comment by shurale-nkn** [comment]
@junliume 
Do we have any error logs on this issue? I don't quite understand how MIOpen should be build on WSL system. 
I assume that WSL does not contain ROCm and rocminfo. In this case PR#1081 will not help

**Comment by junliume** [comment]
> @junliume
> Do we have any error logs on this issue? I don't quite understand how MIOpen should be build on WSL system.
> I assume that WSL does not contain ROCm and rocminfo. In this case PR#1081 will not help

It's mostly for dev convenience, previously worked but boke by GPU Detect PR.
You can technically install rocminfo on WSL, just the outcome would be:

❯ rocminfo
ROCk module is NOT loaded, possibly no GPU devices

without the "fix":

❯ make check -j16
... ...
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/c/Users/junliu14/MIOpen/build
*** FATAL: GPU DETECTION FAILED DURING CMAKE PHASE, CHECK CMAKE WARNINGS ***
make[3]: *** [test/CMakeFiles/gpu_detection_check.dir/build.make:58: test/CMakeFiles/gpu_detection_check] Error 1
make[2]: *** [CMakeFiles/Makefile2:9099: test/CMakeFiles/gpu_detection_check.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
[  0%] Built target addkernels
[  0%] Built target sqlite_memvfs
make[1]: *** [CMakeFiles/Makefile2:11402: test/CMakeFiles/check.dir/rule] Error 2
make: *** [Makefile:5072: check] Error 2

**Comment by shurale-nkn** [comment]
Hmmm... For me, the problem with these logs is that I can't "CHECK CMAKE WARNINGS" because they are suppressed

**Comment by atamazov** [comment]
Now we must make it so that our CI does fail when GPU is not found but GPu is required by the Jenkins stage. Why: https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1081#issuecomment-902877375
