### ISSUE TITLE
Missing `#include <limits>`

### ISSUE THREAD

**Issue by tpkessler** [ROCmSoftwarePlatform/MIOpen#1083]
When compiling MIOpen with OpenCL backend (release 4.3.0) on Arch Linux with GCC 11 I get several build errors like
```C++
MIOpen/src/include/miopen/float_equal.hpp:47:39: error: no member named 'numeric_limits' in namespace 'std'
               std::nextafter(x, std::numeric_limits<T>::lowest()) <= y
```
This is fixed by adding `#include <limits>` to `float_equal.hpp`:

```patch
diff --git a/src/include/miopen/float_equal.hpp b/src/include/miopen/float_equal.hpp
index e2441b60c..bd816cb22 100644
--- a/src/include/miopen/float_equal.hpp
+++ b/src/include/miopen/float_equal.hpp
@@ -28,6 +28,7 @@
 
 #include <algorithm>
 #include <cmath>
+#include <limits>
 #include <numeric>
 #ifdef _MSC_VER
 #include <iso646.h>

```

**Comment by junliume** [comment]
@tpkessler Thanks! It seems that GCC 11 started to explicitly require including \<limits\>, \<memory\>, \<utility\>, \<thread\>, according to [gcc-11_header-dep-changes](https://www.gnu.org/software/gcc/gcc-11/porting_to.html#header-dep-changes), it might have happened to clang too.
It ~~might~~ should have been fixed for most header files while this one is missed: have we only recently started testing _"MIOpen with OpenCL backend (release 4.3.0) on Arch Linux with GCC 11"_?
