### ISSUE TITLE
[MLIR] Address precision concerns in xdlops, wrw algorithm

### ISSUE THREAD

**Issue by jerryyin** [ROCmSoftwarePlatform/MIOpen#1085]
https://github.com/ROCmSoftwarePlatform/llvm-project-mlir/pull/310 leads to MIOpenDriver test breakage of following combination of problem config in mlir solvers:
 - fp32
 - xdlops
 - wrw

For breakage CI log please look at [here](http://rocmhead:8080/job/mlir-nightly-all/30/console). Search `failed` in CI log.

According to a discussion between @whchung and @asroy. This is less likely to be a kernel breakage but a test/numerical precision related issue. 

Since this PR is blocking all further MLIR MIOpen integration items this is a high priority item.

To address:
  - In the very short term, please remove this combination of testing and disable solver from it
  - For permanent fix, please adjust the precision level of wrw fp32 sensitivity so that MIOpenDriver does no longer categorize this as failures

I'm assigning this to @ltqin because he is the original author of the MLIR end PR, and this does show up as a regression in both MIOpen and MLIR fp validation.

@whchung @asroy @mvermeulen @junliume @atamazov

**Comment by carlushuang** [comment]
@jerryyin from our perspective, fp32 wrw xdlops should not have precision issue, even if you use atomic add. This is true in both HIP and ASM implementation of igemm. According to [conv_driver.hpp#L3291](https://github.com/ROCmSoftwarePlatform/MIOpen/blob/develop/driver/conv_driver.hpp#L3291), this is already a big tolerance value.
I think before you adjust the fp32 wrw threshold(which may affect all igemm algorithm), double check the kernel implementation would be a good choice?

cc @shaojiewang

**Comment by jerryyin** [comment]
@carlushuang Thanks for your reply. I merely just find the breakage. Since I didn't either develop the kernel code or the validation code, I will abstain from the technical side of discussion.

> I think before you adjust the fp32 wrw threshold(which may affect all igemm algorithm), double check the kernel implementation would be a good choice?

@ltqin Could you please respond?

> fp32 wrw xdlops should not have precision issue, even if you use atomic add

Could you give an example where atomic add has been used in `wrw` and that it can continue to pass existing MIOpen validation? This should further prove that it is not a precision issue but a kernel implementation issue.

**Comment by shaojiewang** [comment]
@jerryyin 
> Could you give an example where atomic add has been used in `wrw` and that it can continue to pass existing MIOpen validation? This should further prove that it is not a precision issue but a kernel implementation issue.

Yes. From our side, fp32 wrw can always pass MIOpen validation. Here are some examples:
**NCHW**
```
export MIOPEN_DEBUG_FIND_ONLY_SOLVER=ConvAsmImplicitGemmGTCDynamicWrwXdlops
./bin/MIOpenDriver conv -n 64 -c 1024 -H 14 -W 14 -k 1024 -y 1 -x 1 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -g 1 -F 4 -w 1 -t 1 
./bin/MIOpenDriver conv -n 128 -c 128 -H 28 -W 28 -k 128 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -g 1 -F 4 -t 1 -w 1 
./bin/MIOpenDriver conv  -n 128 -c 256 -H 30 -W 30 -k 256 -y 3 -x 3 -p 0 -q 0 -u 2 -v 2 -l 1 -j 1 -g 1 -F 4 -t 1 -w 1 
```
**NHWC**
```
export MIOPEN_DEBUG_FIND_ONLY_SOLVER=ConvAsmImplicitGemmGTCDynamicWrwXdlopsNHWC
export LAYOUT_ARG="--in_layout NHWC --fil_layout NHWC --out_layout NHWC"
./bin/MIOpenDriver conv -n 64 -c 1024 -H 14 -W 14 -k 1024 -y 1 -x 1 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -g 1 -F 4 -w 1 -t 1 ${LAYOUT_ARG}
./bin/MIOpenDriver conv -n 128 -c 128 -H 28 -W 28 -k 128 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -g 1 -F 4 -t 1 -w 1 ${LAYOUT_ARG}
./bin/MIOpenDriver conv  -n 128 -c 256 -H 30 -W 30 -k 256 -y 3 -x 3 -p 0 -q 0 -u 2 -v 2 -l 1 -j 1 -g 1 -F 4 -t 1 -w 1 ${LAYOUT_ARG}
```

**Comment by jerryyin** [comment]
@whchung @ltqin Please follow up if necessary. Meanwhile I'm going to mark fp32 wrw xdlops as inapplicable before this is fixed, just so that MIOpen integration work can be unblocked.

**Comment by jerryyin** [comment]
Solution merged with https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1104. New atomic add instruction requires set zero to wrw tensor.
