### ISSUE TITLE
[Test][CI][gfx90a] ROCm4.3 Clang tidy issue

### ISSUE THREAD

**Issue by junliume** [ROCmSoftwarePlatform/MIOpen#1089]
As shown here: http://micimaster.amd.com/blue/rest/organizations/jenkins/pipelines/MLLibs/pipelines/MIOpen/branches/jenkins_and_docker_file_for_90a/runs/12/nodes/12/steps/80/log/?start=0

There are lots of errors for:
>> error: avoid repeating the return type from the declaration; use a braced initializer list instead [modernize-return-braced-init-list,-warnings-as-errors]

We suspect it could be caused by:

- Build with HIP 4.3.21254
- Clang tidy found: 13.0.0git

[reproduce]:
Only reproducible with ROCm4.3 as the CI frame, most of our current CI environments are ROCm4.2

[Symptom]:
**modernize-return-braced-init-list,-warnings-as-errors**

[Proposal]:
We have enabled options at (start from): https://github.com/ROCmSoftwarePlatform/MIOpen/blob/868261fcfd4325264ab124776d84cc8604c0ea47/CMakeLists.txt#L509

- [ ] Can we have a disabled check option list? Or if it is a whitelist only approach, why would **modernize-return-braced-init-list** be added as a default?
- [ ] Can we move **checks** and **`WarningsAsErrors:`** to .clang-tidy file instead?

CC: @shurale-nkn @JehandadKhan @atamazov

**Comment by JehandadKhan** [comment]
I dont think we should disable the check, since its useful. We can however, move our CI to ROCm 4.3 and update the code to satisfy the tidy checks. @junliume  Do you agree ?

**Comment by junliume** [comment]
@JehandadKhan it could be a fair amount of work to clean all of them, but I am on board with making the quality improvement :)
BTW~ so far I have seen they are all from our own code, nothing 3rd party, hopefully that is always true. 

>Foo bar() {
  Bar bar;
  return Foo(bar);
}

// transforms to:

>Foo bar() {
  Bar bar;
  return {bar};
}

**Comment by junliume** [comment]
Issue resolved with #1099
