### ISSUE TITLE
MIOpen(HIP): Warning [FindRecordUnsafe] File is unreadable: /opt/rocm/miopen/share/miopen/db/gfx803_32.cd.pdb.txt

### ISSUE THREAD

**Issue by bwang365** [ROCmSoftwarePlatform/MIOpen#109]
I'm currently getting this warning whenever I run training.
![Screenshot from 2019-06-17 01-48-31](https://user-images.githubusercontent.com/51182834/59581189-1ac91c00-90a2-11e9-9e19-59648b98376b.png)

**Comment by atamazov** [comment]
The easiest workaround is to copy the gfx803_36.cd.pdb.txt file into gfx803_32.cd.pdb.txt in the same directory where the System PerfDb is installed.

- PerfDb docs: https://github.com/ROCmSoftwarePlatform/MIOpen/blob/master/doc/src/perfdatabase.md
- Related issue: https://github.com/ROCmSoftwarePlatform/MIOpen/issues/26#issuecomment-354366590
