### ISSUE TITLE
[Test][CI][gfx90a]compile error for asm kernels

### ISSUE THREAD

**Issue by shaojiewang** [ROCmSoftwarePlatform/MIOpen#1101]
For gfx90a arch, some asm kernels use .amdhsa_reserve_xnack_mask, it seems like to cause a compile error: ```.amdhsa_reserve_xnack_mask does not match target id```
CI is blocked: http://micimaster.amd.com/blue/organizations/jenkins/MLLibs%2FMIOpen/detail/asm_igemm_wrw_nhwc_gfx90a/9/pipeline/213/

**Comment by junliume** [comment]
Is this a duplication of https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1093?
These tests are temporarily blocked in develop line

**Comment by shaojiewang** [comment]
> Is this a duplication of #1093?
> These tests are temporarily blocked in develop line

@junliume Yes, I see. It is more like a sub question of 1093. I'll move it to that ticket. But we need to open it for 90a kernels' integration.
