### ISSUE TITLE
Prebuilt MIOpen for ROCm 2.6 is compiled with Debug enabled?

### ISSUE THREAD

**Issue by ghostplant** [ROCmSoftwarePlatform/MIOpen#111]
I pulled the latest Docker image `rocm/dev-ubuntu-18.04:2.6`, and then compiled applications that uses MIOpen ConvFwd algorithms, but the execution is very slow. By profiling the kernel execution time, I found that strange kernels like `miog_alphaab`, `miog_betac_alphaab` and `miog_betac` cost most of the execution time but I never intend to call them.

```sh
    35.87%        11520        962.32(ms)  [miog_alphaab]
    23.83%          555        639.31(ms)  [Cijk_Ailk_Bljk_SB_MT128x64x8_SE_APM1_AF0EM1_AF1EM1_AMAS0_ASE..]
    11.73%         4800        314.91(ms)  [miog_betac_alphaab]
    6.505%        16320        174.49(ms)  [Im2d2Col]
    6.463%          795        173.37(ms)  [MIOpenBatchNormFwdInferSpatialEst]
    1.948%          330         52.27(ms)  [transpose_CNHW2NCHW_opt]
    1.556%          240         41.76(ms)  [transpose_NCHW2CNHW_opt]
    1.292%        11520         34.66(ms)  [miog_betac]
```
 These `miog_*` kernels seem to be enable only in MIOpen debug mode, so I want to ensure whether there are something wrong with the prebuilt Docker image `rocm/dev-ubuntu-18.04:2.6` which is not expected to launch such expensive debugging kernels.

**Comment by daniellowell** [comment]
Do you just want to run some MIOpen tests?
You can pull the latest "just MIOpen" docker here:
https://cloud.docker.com/u/rocm/repository/docker/rocm/miopen

The latest tag is: `rocm/miopen:2.0.0.hip` or `rocm/miopen:2.0.0.opencl`

**Comment by ghostplant** [comment]
Thanks, seems like if I use the `ConvFindFwdAlgo()` to select recommended forward algorithm, the slow-run problem can be solved.
