### ISSUE TITLE
[NFC] asm igemm kernels integrate as tar.bz2, instead of plain text files

### ISSUE THREAD

**Issue by carlushuang** [ROCmSoftwarePlatform/MIOpen#1113]
Currently asm igemm kernels are placed under `src/kernels/dynamic_igemm/` as plain text files. And each kernel will have a single `.s` file. This will lead to MIOpen source file with hundreds ~  thousands of asm files, which may have following pitfalls:

- github clone time will be longer.
- When up load new PRs for new kernels, there will be hundreds of kernels (like #1035), will make review more difficult. Reviewers may be distracted by hundreds of asm files which may have little interests of, and hard to locate the only several `cpp` files need to review.
- When have bugs or add new features that apply for all asm files and need re-generate from generator (like #1114, #552), the PR will still have lot of asm files.
- When future hardware need add asm igemm kernels, above problem may become worse.

Here I propose a solution to this problem.
When put the assembly kernel into MIOpen, put all the kernel inside a folder and compress as `*.tar.bz2` under `src/kernels/dynamic_igemm/`. Untar the kernel when build from source, before `add_kernels()` function like here:[src/CMakeLists.txt](https://github.com/ROCmSoftwarePlatform/MIOpen/blob/develop/src/CMakeLists.txt#L467).
All the kernels after decompress still can go into `inlined_kernels/batch_*.cpp.hpp` as inline data. the Hence we can still enjoy 1 kernel 1 asm file, but only group all the kernels into a tarball.
Runtime compilation/cache is not affected.

e.g. `src/kernels/dynamic_igemm/igemm_gtc_xdlops_nhwc` currently is **27M**, 418 files. if we create bz2 of this(`tar -cjf igemm_gtc_xdlops_nhwc.tar.bz2 igemm_gtc_xdlops_nhwc`), it becauses **727K**

pros:
- solve above problem.
- reduce source code file size

cons:
- when build from source may need decompress stage, so build time may be longer.
- when someone want to check the asm souce code, they need manually decompress the tar file.
- PR review now unable to review inside the asm source code(because everything becomes a tar file.). We need to make sure this in the generator stage.

Need your comments/feedback on this proposal
@atamazov @junliume @JehandadKhan @shaojiewang @asroy

**Comment by shaojiewang** [comment]
> PR review unable to review inside the asm source code(because everything becomes a tar file.).

If so, we could upload a code object, so that decompression will not be needed.

**Comment by carlushuang** [comment]
> > PR review unable to review inside the asm source code(because everything becomes a tar file.).
> 
> If so, we could upload a code object, so that decompression will not be needed.

If upload a single code object, we may violate the purpose of splitting kernels (https://github.com/ROCmSoftwarePlatform/MIOpen/pull/957), that multiple kernel inside a single code object may slow down the wall time. Again, if we have a single code object per kernel, there seems no quite difference of current approach. we still has the problem as in the description.

**Comment by carlushuang** [comment]
Close this issue since already have a consensus. If still have problem will reopen this issue again
