### ISSUE TITLE
[post-merge review] PR 1108, [SWDEV-281541][MSRCHA-100] Implementation of Dynamic Generic Reduction

### ISSUE THREAD

**Issue by atamazov** [ROCmSoftwarePlatform/MIOpen#1120]
- [x] Review by @asroy, https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1108#pullrequestreview-739054615
- [ ] Review by @atamazov, https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1108#pullrequestreview-740455376
- [x] Review by @asroy, https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1108#pullrequestreview-740752154

All the review comments must be resolved in order to close this.

**Comment by qianfengz** [comment]
So,  should I make a P.R to have those issues corrected as soon as possible ?

**Comment by atamazov** [comment]
Basically, yes. Unless you have something more urgent related to release(s). Let's not accumulate imperfections. Thanks.
