### ISSUE TITLE
Dynamic reduction GPU access fault

### ISSUE THREAD

**Issue by asroy** [ROCmSoftwarePlatform/MIOpen#1123]
GPU access fault when running on Vega20 (tested with MI-60) on ROCm4.3 HIP backend

```bin/test_reduce_test --all --double```

Error msg, when using HIP backend, and on ROCm4.3
```
bin/test_reduce_test --double --D 64 3 280 81 --R 0 2 --ReduceOp 4 --CompType 6 --N 1 --I 1 --scales 1 0
MIOpen(HIP): Info2 [AddKernel] Key: dynamic_generic_reduction "666_TUN_256_8_2_2_I4_RED0_2_BSIZE_256_1_P410"
MIOpen(HIP): Info2 [SystemCmd] cd /tmp/miopen-gridwise_generic_reduction_first_call_multiblock_reduce_partial_dims.cpp-a374-cf41-d2fa-6551;  /opt/rocm/llvm/bin/clang++  -std=c++17  --std=c++17 -DCK_AMD_GPU_GFX906 -DCK_USE_AMD_BUFFER_ATOMIC_FADD=0 -DCK_BLOCK_SYNC_LDS_WITHOUT_SYNC_VMEM=1 -DCK_USE_AMD_BUFFER_ADDRESSING=1 -DCK_PARAM_SRC_DATATYPE=6 -DCK_PARAM_DST_DATATYPE=6 -DCK_PARAM_REDUCE_COMPTYPE=6  -DCK_PARAM_BLOCKSIZE=256 -DCK_PARAM_THREAD_BUFFER_LENGTH=8 -DCK_PARAM_ACCESSES_PER_THREAD_INBLOCK=2 -DCK_PARAM_ACCESSES_PER_THREAD_INWARP=2 -DCK_PARAM_TOREDUCE_DIMS=0,2 -DCK_PARAM_INVARIANT_DIMS=1,3 -DCK_PARAM_REDUCE_OP=4 -DCK_PARAM_NAN_PROPAGATE=1 -DCK_PARAM_REDUCE_INDICES=1 -DCK_PARAM_IN_DIMS=4 -DCK_PARAM_OUT_DIMS=2 -DCK_PARAM_SRC2D_PADDING=1 -DCK_PARAM_DST1D_PADDING=0 -mcpu=gfx906 -Werror -Weverything -Wno-c++98-compat -Wno-c++98-compat-pedantic -Wno-conversion -Wno-double-promotion -Wno-exit-time-destructors -Wno-extra-semi -Wno-float-conversion -Wno-gnu-anonymous-struct -Wno-gnu-zero-variadic-macro-arguments -Wno-missing-noreturn -Wno-missing-prototypes -Wno-nested-anon-types -Wno-padded -Wno-return-std-move-in-c++11 -Wno-shorten-64-to-32 -Wno-sign-conversion -Wno-unknown-warning-option -Wno-unused-command-line-argument -Wno-weak-vtables -Wno-covered-switch-default -Wno-disabled-macro-expansion -Wno-undefined-reinterpret-cast --cuda-gpu-arch=gfx906:xnack- --cuda-device-only -c -O3  -Wno-unused-command-line-argument -I. -mllvm -amdgpu-early-inline-all=true -mllvm -amdgpu-function-calls=false -xhip -isystem /opt/rocm-4.3.0/hip/../include -isystem /opt/rocm/llvm/lib/clang/13.0.0/include/.. -D__HIP_PLATFORM_HCC__=1 -D__HIP_PLATFORM_AMD__=1 -isystem /opt/rocm-4.3.0/hip/include -isystem /opt/rocm/include -L"/opt/rocm/llvm/lib/clang/13.0.0/include/../lib/linux" -lclang_rt.builtins-x86_64 --hip-link -L"/opt/rocm/llvm/lib/clang/13.0.0/include/../lib/linux" -lclang_rt.builtins-x86_64 -mllvm --amdgpu-spill-vgpr-to-agpr=0 -DHIP_PACKAGE_VERSION_FLAT=4003021300 gridwise_generic_reduction_first_call_multiblock_reduce_partial_dims.cpp -o /tmp/miopen-gridwise_generic_reduction_first_call_multiblock_reduce_partial_dims.cpp-a374-cf41-d2fa-6551/gridwise_generic_reduction_first_call_multiblock_reduce_partial_dims.cpp.o
MIOpen(HIP): Info2 [Log] Kernel gridwise_generic_reduction_first_call_multiblock_reduce_partial_dims.cpp Compile Time, ms: 3296.71
MIOpen(HIP): Info2 [AddKernel] Key: dynamic_generic_reduction "666_TUN_256_8_2_2_I4_RED0_2_BSIZE_256_1410"
Memory access fault by GPU node-5 (Agent handle: 0xafad50) on address 0x7f8c80a00000. Reason: Page not present or supervisor privilege.
```

Note
* It doesn't fail if dynamic reduction is disabled
* It doesn't fail if using OpenCL backend
* It doesn't fail if running a single config
* It doesn't fail if using ROCm4.1

**Comment by atamazov** [comment]
UPDATE:

Manually verified on ixt-rack-54 that:
- PASS: ROCm4.2
- FAIL: ROCm4.3 
- PASS: ROCm4.3.1
Also PASS on a more recent docker (not released yet). So that I am upgrading ROCm for CI to v4.3.1. 
Monitor CI for the weekend, if not working, will revert the last commit.

_Originally posted by @junliume in https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1125#issuecomment-907562514_

**Comment by carlushuang** [comment]
@junliume @atamazov 
If fail in some rocm version and not fail in other, it still could be a kernel issue. When kernel have out-of-bound access, a specific rocm version may or may not crash (see:https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1040#issuecomment-884191006) due to different runtime/driver behavior.
I would suggest upgrade rocm-ci as WA, and a more closer look at the kernel implementation is still needed @qianfengz

**Comment by qianfengz** [comment]
This can be re-produced with ROCM 4.3 on other HW (MI100, MI25),  but very hard to debug since running single failed case could not produce the failure,   have to run `bin/test_reduce_test --all --double`

**Comment by asroy** [comment]
@carlushuang How did you find out the bug in #1040? Maybe @qianfengz can do the same debugging

**Comment by asroy** [comment]
> This can be re-produced with ROCM 4.3 on other HW (MI100, MI25), but very hard to debug since running single failed case could not produce the failure, have to run `bin/test_reduce_test --all --double`

I think the first thing to do is to find the minimal set of tests that can reproduce the access fault. @qianfengz

**Comment by carlushuang** [comment]
@asroy this is not found till I switched to that rocm version. Out-of-bound depends on runtime behavior, so once found one (even if it will random fail), just keep that rocm version, then narrow down the configs. But still, a deep look at the kernel is needed.

**Comment by qianfengz** [comment]
[PR. 1131](https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1131) has been pushed for fixing the issue.  For double,  the bug causes 4096 * 8 / (4+8) bytes deviation while accessing the workspace buffer 2;  for float, the corresponding deviation is  4096 * 4 / (4 + 4);  for half, the deviation is 4096 * 2 / (4+2).   So under the bug situation, using double leads to higher probability of  accessing overflowed address.   

The reason that the failure only occurred with ROCM 4.3 is not investigated.    One possibility is that different runtime implementations have discrepancy in  hipMalloc() implementations,  for example,  implementation A could allocate exact same number of pages as requuested,  while implementation B could allocate one additional pages as gaps to prevent memory access fault.
