### ISSUE TITLE
Reduce dropout test time

### ISSUE THREAD

**Issue by ce1adon** [ROCmSoftwarePlatform/MIOpen#1128]
- [x] step 1. Reduce number of test case  #1129 
- [ ] step 2. separate rng and dropout test procedure

**Comment by atamazov** [comment]
#1129 is qualified as a workaround yet, so the original defect shouldn't be closed.

**Comment by junliume** [comment]
> #1129 is qualified as a workaround yet, so the original defect shouldn't be closed.

After original discussion with @ce1adon, this PR (reduce of number of tests) is more of a permanent approach to fix the issue.  
@ce1adon : what do you think?

**Comment by atamazov** [comment]
Let's discuss this topic [there](https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1129#issuecomment-918421792).

**Comment by atamazov** [comment]
Let's close this when step 2 is done.

**Comment by atamazov** [comment]
@junliume This should be reopened. The only config which is tested right now (even with `--all`!) is 
```
--input-dim 16 4 8 1 4 --dropout 0.5 --seed 0 --use-mask 0 --rng-mode 0 
```
which opens path for bugs. In fact, dropout is only smoke tested.

Recommended labels are with https://github.com/ROCmSoftwarePlatform/MIOpen/labels/urgency_blocker and https://github.com/ROCmSoftwarePlatform/MIOpen/labels/workaround

I have no idea who should be assigned to this (but please feel free to assign me)

/cc @ce1adon

**Comment by atamazov** [comment]
[Notice] Separating rng mode seems more or less trivial.
