### ISSUE TITLE
miopentensile fails in GemmWrw1x1_stride1 solver path in vega20/gfx90a

### ISSUE THREAD

**Issue by ce1adon** [ROCmSoftwarePlatform/MIOpen#1134]
Observed in http://micimaster.amd.com/blue/organizations/jenkins/MLLibs%2FMIOpen/detail/miopentensile-gfx90a/14/pipeline in PR #1115

**Comment by junliume** [comment]
GemmWrw1x1_stride1 was created by a split in #852 

@DrizztDoUrden  could you please take a look at this issue? Thanks!

**Comment by atamazov** [comment]
BTW how GemmWrw1x1_stride1 works with non-latest MIOpenTenslie? Any problems?

**Comment by atamazov** [comment]
The feature is still experimental.
