### ISSUE TITLE
Undefined Reference - MIOpenGEMM

### ISSUE THREAD

**Issue by kiritigowda** [ROCmSoftwarePlatform/MIOpen#115]
Below is the link error I am getting with 

```
miopen-opencl                              2.0.1.7405-rocm-rel-2.7-22-4e39a83                  amd64        AMD's DNN Library
miopengemm                                 1.1.6.645-rocm-rel-2.7-22-6275a87                   amd64        A tool for generating OpenCL matrix multiplication (GEMM) kernels
```
```
/opt/rocm/lib/libMIOpen.so.1: undefined reference to `MIOpenGEMM::Geometry::initialise(bool, bool, bool, bool, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, char)@MIOPENGEMM_1'
/opt/rocm/lib/libMIOpen.so.1: undefined reference to `MIOpenGEMM::find(float, _cl_command_queue*, _cl_mem*, _cl_mem*, _cl_mem*, bool, MIOpenGEMM::Geometry const&, bool, bool)@MIOPENGEMM_1'
collect2: error: ld returned 1 exit status

```

**Comment by kiritigowda** [comment]
Downgrading to `MIOpen - 1.8.1` & `MIOpenGEMM 1.1.5` solves this issue temporarly.

**Comment by daniellowell** [comment]
Does down grading just MIOpenGEMM fix the issue?

**Comment by kiritigowda** [comment]
@daniellowell I tried with `MIOpen - 2.0.1` & `MIOpen - 2.0.0` with `MIOpenGEMM 1.1.5`, the problems still persists.

**Comment by JehandadKhan** [comment]
@kiritigowda do you have a docker we can try ?

**Comment by kiritigowda** [comment]
@JehandadKhan follow the steps to reproduce on docker

* Docker Launch
````
sudo docker run -it --device=/dev/kfd --device=/dev/dri --cap-add=SYS_RAWIO --device=/dev/mem --group-add video --network host --env DISPLAY=unix$DISPLAY --privileged --volume $XAUTH:/root/.Xauthority --volume /tmp/.X11-unix/:/tmp/.X11-unix mivisionx/ubuntu-18.04:miopen-bug
````

* Resnet50 OpenVX Graph
````
cd && ls
````

* Create build folder, cmake and make
````
mkdir build && cd build && cmake ../resnet50-openvx && make
````

Should produce error
````
//opt/rocm/lib/libMIOpen.so.1: undefined reference to `MIOpenGEMM::Geometry::initialise(bool, bool, bool, bool, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, char)@MIOPENGEMM_1'
//opt/rocm/lib/libMIOpen.so.1: undefined reference to `MIOpenGEMM::find(float, _cl_command_queue*, _cl_mem*, _cl_mem*, _cl_mem*, bool, MIOpenGEMM::Geometry const&, bool, bool)@MIOPENGEMM_1'
collect2: error: ld returned 1 exit status
CMakeFiles/anntest.dir/build.make:112: recipe for target 'anntest' failed
make[2]: *** [anntest] Error 1
CMakeFiles/Makefile2:141: recipe for target 'CMakeFiles/anntest.dir/all' failed
make[1]: *** [CMakeFiles/anntest.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
````

**Comment by paveltc** [comment]
Is there any update on this issue? It is currently blocking me from running tests on MI100.

**Comment by paveltc** [comment]
Is there any update on this issue? It is blocking some of my work.

**Comment by daniellowell** [comment]
To unblock yourself, can you try building MIOpen on your local system and doing `make install`
Please remove the previous package before installing. There may be an issue with the packaging.
Flow the instructions here:
https://rocmsoftwareplatform.github.io/MIOpen/doc/html/install.html#building-miopen-from-source

**Comment by paolodalberto** [comment]
@daniellowell 

From source:
mkdir build
cd build/
cmake -DMIOPEN_BACKEND=OpenCL ..
sudo make -j8 install

[100%] Linking CXX executable anntest
//opt/rocm/lib/libMIOpen.so.1: undefined reference to `MIOpenGEMM::Geometry::initialise(bool, bool, bool, bool, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, char)@MIOPENGEMM_1'
//opt/rocm/lib/libMIOpen.so.1: undefined reference to `MIOpenGEMM::find(float, _cl_command_queue*, _cl_mem*, _cl_mem*, _cl_mem*, bool, MIOpenGEMM::Geometry const&, bool, bool)@MIOPENGEMM_1'

it looks like installing from source still missing something

**Comment by kiritigowda** [comment]
@paolodalberto if you rerun the MIVisionX-setup.py again, this issue will be fixed. 

Else, get MIOpenGEMM 1.1.5 build and install it, then rebuild MIOpen 2.1.0 and install it.

**Comment by paolodalberto** [comment]
sudo python MIVisionX-setup.py
MIVisionX Dependencies Installed

MIVisionX-setup.py ... how do I uninstall it ?

**Comment by paolodalberto** [comment]
paolo@fastmmw:~/FastMM/MIVisionX/ONNX/squeezenet-openvx/build$ make 
Scanning dependencies of target annmodule
[ 16%] Building CXX object CMakeFiles/annmodule.dir/annmodule.cpp.o
[ 33%] Linking CXX shared library libannmodule.so
[ 33%] Built target annmodule
Scanning dependencies of target annpython
[ 50%] Building CXX object CMakeFiles/annpython.dir/annpython.cpp.o
[ 66%] Linking CXX shared library libannpython.so
[ 66%] Built target annpython
Scanning dependencies of target anntest
[ 83%] Building CXX object CMakeFiles/anntest.dir/anntest.cpp.o
[100%] Linking CXX executable anntest
[100%] Built target anntest

**Comment by aserio** [comment]
@dagamayank has mentioned in an internal [ticket](http://ontrack-internal.amd.com/browse/SWDEV-207462?focusedCommentId=5694783&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-5694783) that MIOpenGEMM will no longer be supported. Should we note this here and close the ticket?

**Comment by aserio** [comment]
@daniellowell, has this issue been addressed?

**Comment by kiritigowda** [comment]
Any update on this? @daniellowell @paolodalberto

**Comment by junliume** [comment]
Close due to inactivity. @kiritigowda if the issue still persists in newer versions of MIOpen, please comment and reopen. Thanks!
