### ISSUE TITLE
After a reboot, MIOPEN_FIND_ENFORCE=3 finds a different set of best operations

### ISSUE THREAD

**Issue by Wulfsta** [ROCmSoftwarePlatform/MIOpen#118]
I'm running ROCm 2.6 on a Radeon VII with the current release of PyTorch on Ubuntu 19.04. I'm training a VGG-like network using a modified version of the example code provided in the tutorials. Setting MIOPEN_FIND_ENFORCE=3 prior to running the training populates my performance database as expected, and reduces the runtime of each epoch by around an hour or so. After a reboot I noticed that the performance gains did not seem to be the same, so I renamed the files generated to preserve them while generating new files. Upon completion the performance returned to where it was, but the performance databases appear drastically different. I can provide the performance database files if requested. I'm not sure how to explain the behavior, but am concerned about hardware degredation.

**Comment by atamazov** [comment]
> but the performance databases appear drastically different

Basically, this is normal. Two or more very-different-looking performance configs may reveal very close performance vs to each other. Which one "wins" during specific tuning session depends on many factors, and there always some "jutter" during time measurements performed by the library.

That is why tuning sessions performed on the same machine may produce different performance databases. However, the resulting performance of the library should be nearly the same. As a rule of thumb, the perf diff should be within 5%. If difference if higher, then let's investigate this case.

That would take time, of course. If you decide to investigate, please provide a high-level description of your experiments, step by step.

Please also consider possible side effects of rebooting your specific system. For example, GPU board clock settings are usually resetting to their defaults during reboot.

**Comment by atamazov** [comment]
Please also indicate how important is this for you (set a `priority_...` label as appropriate). Thanks.

**Comment by Wulfsta** [comment]
Closing this because I can't seem to replicate the issue.
