### ISSUE TITLE
Wrong args voided at that line

### ISSUE THREAD

**Issue by stmuxa** [ROCmSoftwarePlatform/MIOpen#119]
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/93074ff720ba8745e7f94d38f69b88c2d9dfaa36/src/convolution.cpp#L393

**Comment by atamazov** [comment]
Thanks for this finding. Please also indicate how important is this for you (set a priority_... label as appropriate in this ticket) and let us know do you need a patch asap.

/cc @DrizztDoUrden

**Comment by stmuxa** [comment]
Somehow I cannot edit labels after issue is created.
There is a compilation error in case MIOPEN_USE_GEMM is not defined, so I guess it is a bug.

**Comment by daniellowell** [comment]
@atamazov please open a PR asap. We can fold this into the next release.

**Comment by atamazov** [comment]
@stmuxa This is hotfix for you: [issue-miopen-119.patch.txt](https://github.com/ROCmSoftwarePlatform/MIOpen/files/3566767/issue-miopen-119.patch.txt)

**Comment by stmuxa** [comment]
Thanks for patch

**Comment by daniellowell** [comment]
Resolved in 2.1.0
