### ISSUE TITLE
4 megabyte array allocated on a stack in src/db.cpp::Copy method

### ISSUE THREAD

**Issue by stmuxa** [ROCmSoftwarePlatform/MIOpen#120]
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/93074ff720ba8745e7f94d38f69b88c2d9dfaa36/src/db.cpp#L230

Please, consider to lower stack usage at that function. On some platforms this value itself exceeds default stack size.

**Comment by atamazov** [comment]
This makes sense. BTW which platforms do you mean? I think it is worth use heap and thus get rid of dependency of available stack space.

**Comment by stmuxa** [comment]
> This makes sense. BTW which platforms do you mean? 
We build miopen for Win/Linux/OSx
The problem caught under Windows 10, when debugging from MSVC

**Comment by pfultz2** [comment]
You most likely need to increase the stack size when building on MSVC.

**Comment by atamazov** [comment]
@stmuxa please try this out [miopen-issue-120.diff.txt](https://github.com/ROCmSoftwarePlatform/MIOpen/files/3574620/miopen-issue-120.diff.txt)

**Comment by stmuxa** [comment]
thanks

**Comment by stmuxa** [comment]
> You most likely need to increase the stack size when building on MSVC.

I think this is not always possible. 
Imagine, I am the developer of lib (using miopen), and my lib is a third party resource of the application which developed by some one else.

**Comment by daniellowell** [comment]
Fixed.
