### ISSUE TITLE
Vega 64: hipoc_program.cpp:286: Code object build failed. Source: MIOpenIm2d2Col.cl

### ISSUE THREAD

**Issue by Sigura** [ROCmSoftwarePlatform/MIOpen#1204]
python3.6.6
pytorch 1.9.1 with ROCm support
Ubuntu:20.04

```
MIOpen(HIP): Warning [SQLiteBase] Unable to read system database file:/opt/rocm/miopen/share/miopen/db/gfx900_64.kdb Performance may degrade
MIOpen(HIP): Error [SetIsaName] 'amd_comgr_action_info_set_isa_name(handle, isa.c_str())' amdgcn-amd-amdhsa--gfx900:sramecc-:xnack-: INVALID_ARGUMENT (2)
MIOpen(HIP): Error [BuildOcl] comgr status = INVALID_ARGUMENT (2)
MIOpen(HIP): Warning [BuildOcl] amdgcn-amd-amdhsa--gfx900:sramecc-:xnack-
MIOpen Error: /MIOpen/src/hipoc/hipoc_program.cpp:286: Code object build failed. Source: MIOpenIm2d2Col.cl

Traceback (most recent call last):
  File "/home/sigura/.pyenv/versions/3.6.6/lib/python3.6/site-packages/detectron2/engine/train_loop.py", line 149, in train
    self.run_step()
  File "/home/sigura/.pyenv/versions/3.6.6/lib/python3.6/site-packages/detectron2/engine/defaults.py", line 493, in run_step
    self._trainer.run_step()
  File "/home/sigura/.pyenv/versions/3.6.6/lib/python3.6/site-packages/detectron2/engine/train_loop.py", line 273, in run_step
    loss_dict = self.model(data)
  File "/home/sigura/.pyenv/versions/3.6.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sigura/.pyenv/versions/3.6.6/lib/python3.6/site-packages/detectron2/modeling/meta_arch/rcnn.py", line 154, in forward
    features = self.backbone(images.tensor)
  File "/home/sigura/.pyenv/versions/3.6.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sigura/.pyenv/versions/3.6.6/lib/python3.6/site-packages/detectron2/modeling/backbone/fpn.py", line 126, in forward
    bottom_up_features = self.bottom_up(x)
  File "/home/sigura/.pyenv/versions/3.6.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sigura/.pyenv/versions/3.6.6/lib/python3.6/site-packages/detectron2/modeling/backbone/resnet.py", line 445, in forward
    x = self.stem(x)
  File "/home/sigura/.pyenv/versions/3.6.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sigura/.pyenv/versions/3.6.6/lib/python3.6/site-packages/detectron2/modeling/backbone/resnet.py", line 356, in forward
    x = self.conv1(x)
  File "/home/sigura/.pyenv/versions/3.6.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sigura/.pyenv/versions/3.6.6/lib/python3.6/site-packages/detectron2/layers/wrappers.py", line 107, in forward
    x, self.weight, self.bias, self.stride, self.padding, self.dilation, self.groups
RuntimeError: miopenStatusUnknownError
```

based on RadeonOpenCompute/ROCm#1572

PS: but! those lines from 1572 work for me

```
import torch
import torchvision

device = torch.device('cuda')
print(f"using device: {device}")
model = torchvision.models.detection.maskrcnn_resnet50_fpn(pretrained=True).to(device)
model.eval()

rand_input = torch.rand(3, 1920, 1080, device=device)
model([rand_input])

```

**Comment by atamazov** [comment]
@Sigura Please show output of `/opt/rocm/opencl/bin/clinfo | grep gfx`.

**Comment by atamazov** [comment]
@Sigura Another question if why you use COMGR for building kernels. Currently the default build path is offline compilation. Please consult PyTorch guys who work on AMD support.

**Comment by Sigura** [comment]
> @Sigura Please show output of `/opt/rocm/opencl/bin/clinfo | grep gfx`.

 Name:						 gfx900:xnack-

**Comment by Sigura** [comment]
> @Sigura Another question if why you use COMGR for building kernels. Currently the default build path is offline compilation. Please consult PyTorch guys who work on AMD support.

Could you please help to check my understanding – you are a mean question about how to change the path to MIOpen for PyTorch?

**Comment by Sigura** [comment]
@atamazov I'm open to any questions. I will be glad to help with your great work!

**Comment by Sigura** [comment]
<details>
<summary>/opt/rocm/opencl/bin/clinfo</summary>
<p>

Number of platforms:				 1
  Platform Profile:				 FULL_PROFILE
  Platform Version:				 OpenCL 2.0 AMD-APP (3305.0)
  Platform Name:				 AMD Accelerated Parallel Processing
  Platform Vendor:				 Advanced Micro Devices, Inc.
  Platform Extensions:				 cl_khr_icd cl_amd_event_callback 


  Platform Name:				 AMD Accelerated Parallel Processing
Number of devices:				 1
  Device Type:					 CL_DEVICE_TYPE_GPU
  Vendor ID:					 1002h
  Board name:					 Vega 10 XL/XT [Radeon RX Vega 56/64]
  Device Topology:				 PCI[ B#3, D#0, F#0 ]
  Max compute units:				 64
  Max work items dimensions:			 3
    Max work items[0]:				 1024
    Max work items[1]:				 1024
    Max work items[2]:				 1024
  Max work group size:				 256
  Preferred vector width char:			 4
  Preferred vector width short:			 2
  Preferred vector width int:			 1
  Preferred vector width long:			 1
  Preferred vector width float:			 1
  Preferred vector width double:		 1
  Native vector width char:			 4
  Native vector width short:			 2
  Native vector width int:			 1
  Native vector width long:			 1
  Native vector width float:			 1
  Native vector width double:			 1
  Max clock frequency:				 1630Mhz
  Address bits:					 64
  Max memory allocation:			 7287183768
  Image support:				 Yes
  Max number of images read arguments:		 128
  Max number of images write arguments:		 8
  Max image 2D width:				 16384
  Max image 2D height:				 16384
  Max image 3D width:				 16384
  Max image 3D height:				 16384
  Max image 3D depth:				 8192
  Max samplers within kernel:			 26751
  Max size of kernel argument:			 1024
  Alignment (bits) of base address:		 1024
  Minimum alignment (bytes) for any datatype:	 128
  Single precision floating point capability
    Denorms:					 Yes
    Quiet NaNs:					 Yes
    Round to nearest even:			 Yes
    Round to zero:				 Yes
    Round to +ve and infinity:			 Yes
    IEEE754-2008 fused multiply-add:		 Yes
  Cache type:					 Read/Write
  Cache line size:				 64
  Cache size:					 16384
  Global memory size:				 8573157376
  Constant buffer size:				 7287183768
  Max number of constant args:			 8
  Local memory type:				 Scratchpad
  Local memory size:				 65536
  Max pipe arguments:				 16
  Max pipe active reservations:			 16
  Max pipe packet size:				 2992216472
  Max global variable size:			 7287183768
  Max global variable preferred total size:	 8573157376
  Max read/write image args:			 64
  Max on device events:				 1024
  Queue on device max size:			 8388608
  Max on device queues:				 1
  Queue on device preferred size:		 262144
  SVM capabilities:				 
    Coarse grain buffer:			 Yes
    Fine grain buffer:				 Yes
    Fine grain system:				 No
    Atomics:					 No
  Preferred platform atomic alignment:		 0
  Preferred global atomic alignment:		 0
  Preferred local atomic alignment:		 0
  Kernel Preferred work group size multiple:	 64
  Error correction support:			 0
  Unified memory for Host and Device:		 0
  Profiling timer resolution:			 1
  Device endianess:				 Little
  Available:					 Yes
  Compiler available:				 Yes
  Execution capabilities:				 
    Execute OpenCL kernels:			 Yes
    Execute native function:			 No
  Queue on Host properties:				 
    Out-of-Order:				 No
    Profiling :					 Yes
  Queue on Device properties:				 
    Out-of-Order:				 Yes
    Profiling :					 Yes
  Platform ID:					 0x7f59a80a4e10
  Name:						 gfx900:xnack-
  Vendor:					 Advanced Micro Devices, Inc.
  Device OpenCL C version:			 OpenCL C 2.0 
  Driver version:				 3305.0 (HSA1.1,LC)
  Profile:					 FULL_PROFILE
  Version:					 OpenCL 2.0 
  Extensions:					 cl_khr_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_fp16 cl_amd_device_attribute_query cl_amd_media_ops cl_amd_media_ops2 cl_khr_image2d_from_buffer cl_khr_subgroups cl_khr_depth_images cl_amd_copy_buffer_p2p cl_amd_assembly_program 

</p>
</details>  

<details>
<summary>traceback</summary>
<p>

RuntimeError                              Traceback (most recent call last)
<ipython-input-9-f8bb285625be> in <module>
      1 trainer = DefaultTrainer(cfg)
      2 trainer.resume_or_load(resume=False) # (resume=False)
----> 3 trainer.train()

/home/sigura/.pyenv/versions/3.6.6/lib/python3.6/site-packages/detectron2/engine/defaults.py in train(self)
    481             OrderedDict of results, if evaluation is enabled. Otherwise None.
    482         """
--> 483         super().train(self.start_iter, self.max_iter)
    484         if len(self.cfg.TEST.EXPECTED_RESULTS) and comm.is_main_process():
    485             assert hasattr(

/home/sigura/.pyenv/versions/3.6.6/lib/python3.6/site-packages/detectron2/engine/train_loop.py in train(self, start_iter, max_iter)
    147                 for self.iter in range(start_iter, max_iter):
    148                     self.before_step()
--> 149                     self.run_step()
    150                     self.after_step()
    151                 # self.iter == max_iter can be used by `after_train` to

/home/sigura/.pyenv/versions/3.6.6/lib/python3.6/site-packages/detectron2/engine/defaults.py in run_step(self)
    491     def run_step(self):
    492         self._trainer.iter = self.iter
--> 493         self._trainer.run_step()
    494 
    495     @classmethod

/home/sigura/.pyenv/versions/3.6.6/lib/python3.6/site-packages/detectron2/engine/train_loop.py in run_step(self)
    271         If you want to do something with the losses, you can wrap the model.
    272         """
--> 273         loss_dict = self.model(data)
    274         if isinstance(loss_dict, torch.Tensor):
    275             losses = loss_dict

/home/sigura/.pyenv/versions/3.6.6/lib/python3.6/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1049         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1050                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1051             return forward_call(*input, **kwargs)
   1052         # Do not call functions when jit is used
   1053         full_backward_hooks, non_full_backward_hooks = [], []

/home/sigura/.pyenv/versions/3.6.6/lib/python3.6/site-packages/detectron2/modeling/meta_arch/rcnn.py in forward(self, batched_inputs)
    152             gt_instances = None
    153 
--> 154         features = self.backbone(images.tensor)
    155 
    156         if self.proposal_generator is not None:

/home/sigura/.pyenv/versions/3.6.6/lib/python3.6/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1049         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1050                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1051             return forward_call(*input, **kwargs)
   1052         # Do not call functions when jit is used
   1053         full_backward_hooks, non_full_backward_hooks = [], []

/home/sigura/.pyenv/versions/3.6.6/lib/python3.6/site-packages/detectron2/modeling/backbone/fpn.py in forward(self, x)
    124                 ["p2", "p3", ..., "p6"].
    125         """
--> 126         bottom_up_features = self.bottom_up(x)
    127         results = []
    128         prev_features = self.lateral_convs[0](bottom_up_features[self.in_features[-1]])

/home/sigura/.pyenv/versions/3.6.6/lib/python3.6/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1049         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1050                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1051             return forward_call(*input, **kwargs)
   1052         # Do not call functions when jit is used
   1053         full_backward_hooks, non_full_backward_hooks = [], []

/home/sigura/.pyenv/versions/3.6.6/lib/python3.6/site-packages/detectron2/modeling/backbone/resnet.py in forward(self, x)
    443         assert x.dim() == 4, f"ResNet takes an input of shape (N, C, H, W). Got {x.shape} instead!"
    444         outputs = {}
--> 445         x = self.stem(x)
    446         if "stem" in self._out_features:
    447             outputs["stem"] = x

/home/sigura/.pyenv/versions/3.6.6/lib/python3.6/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1049         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1050                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1051             return forward_call(*input, **kwargs)
   1052         # Do not call functions when jit is used
   1053         full_backward_hooks, non_full_backward_hooks = [], []

/home/sigura/.pyenv/versions/3.6.6/lib/python3.6/site-packages/detectron2/modeling/backbone/resnet.py in forward(self, x)
    354 
    355     def forward(self, x):
--> 356         x = self.conv1(x)
    357         x = F.relu_(x)
    358         x = F.max_pool2d(x, kernel_size=3, stride=2, padding=1)

/home/sigura/.pyenv/versions/3.6.6/lib/python3.6/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1049         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1050                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1051             return forward_call(*input, **kwargs)
   1052         # Do not call functions when jit is used
   1053         full_backward_hooks, non_full_backward_hooks = [], []

/home/sigura/.pyenv/versions/3.6.6/lib/python3.6/site-packages/detectron2/layers/wrappers.py in forward(self, x)
    105 
    106         x = F.conv2d(
--> 107             x, self.weight, self.bias, self.stride, self.padding, self.dilation, self.groups
    108         )
    109         if self.norm is not None:

RuntimeError: miopenStatusUnknownError
</p>
</details>

**Comment by atamazov** [comment]
@Sigura Please expect feedback tomorrow, sorry for delaying.

**Comment by atamazov** [comment]
I need to know the ROCm version that you use. I remember that some versions have problems with the kernel mode driver, and that problems are gfx900-specific.

**Comment by ffleader1** [comment]
Hey
I just want to report that I came across this exact problem, with VEGA 56.
So it does seem to affect quite a lot of people
```
MIOpen(HIP): Warning [SQLiteBase] Unable to read system database file:gfx900_56.kdb Performance may degrade
MIOpen(HIP): Error [SetIsaName] 'amd_comgr_action_info_set_isa_name(handle, isa.c_str())' amdgcn-amd-amdhsa--gfx900:sramecc-:xnack-: INVALID_ARGUMENT (2)
MIOpen(HIP): Error [BuildOcl] comgr status = INVALID_ARGUMENT (2)
MIOpen(HIP): Warning [BuildOcl] amdgcn-amd-amdhsa--gfx900:sramecc-:xnack-
MIOpen Error: /MIOpen/src/hipoc/hipoc_program.cpp:286: Code object build failed. Source: MIOpenIm2d2Col.cl
  0%|          | 0/1000000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/ffleader1/PycharmProjects/AOT-GAN-for-Inpainting/src/train.py", line 51, in <module>
    main_worker(0, 1, args)
  File "/home/ffleader1/PycharmProjects/AOT-GAN-for-Inpainting/src/train.py", line 31, in main_worker
    trainer.train()
  File "/home/ffleader1/PycharmProjects/AOT-GAN-for-Inpainting/src/trainer/trainer.py", line 108, in train
    pred_img = self.netG(images_masked, masks)
  File "/home/ffleader1/PycharmProjects/AOT-GAN-for-Inpainting/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ffleader1/PycharmProjects/AOT-GAN-for-Inpainting/src/model/aotgan.py", line 37, in forward
    x = self.encoder(x)
  File "/home/ffleader1/PycharmProjects/AOT-GAN-for-Inpainting/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ffleader1/PycharmProjects/AOT-GAN-for-Inpainting/venv/lib/python3.8/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/ffleader1/PycharmProjects/AOT-GAN-for-Inpainting/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ffleader1/PycharmProjects/AOT-GAN-for-Inpainting/venv/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 443, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/ffleader1/PycharmProjects/AOT-GAN-for-Inpainting/venv/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 439, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: miopenStatusUnknownError

Process finished with exit code 1
```
what can be a quick/painless option to solve this? Thank you.

**Comment by atamazov** [comment]
> No. MIOpen can use different ways to build kernels. The default way is offline compiler, i.e. /opt/rocm/bin/clang++ which is capable to build HIP, OpenCL and assembly kernels. But in your case MIOpen was built to use COMGR library (which can build HIP, OpenCL and assembly kernels as well). This feature is still experimental and not guaranteed to work in all cases.

@ffleader1 @Sigura The question to both of you still remains: why the MIOpen used by PyTorch was built with the `-DMIOPEN_USE_COMGR=On` CMake option. Do you use PyTorch wheels?

**Comment by ffleader1** [comment]
> > No. MIOpen can use different ways to build kernels. The default way is offline compiler, i.e. /opt/rocm/bin/clang++ which is capable to build HIP, OpenCL and assembly kernels. But in your case MIOpen was built to use COMGR library (which can build HIP, OpenCL and assembly kernels as well). This feature is still experimental and not guaranteed to work in all cases.
> 
> @ffleader1 @Sigura The question to both of you still remains: why the MIOpen used by PyTorch was built with the `-DMIOPEN_USE_COMGR=On` CMake option. Do you use PyTorch wheels?

It was the version that was published on pytorch homepage.
Anyway, I really want to try out your patch, but I am normally a Windows kinda guy, so all this building HIP/MIOpen/Rocm from source seem overwhelming to me. I guess I will wait for a better release of pytorch then.

**Comment by Sigura** [comment]
It looks like now it may be closed

https://github.com/RadeonOpenCompute/ROCm/issues/1572#issuecomment-992589243
