### ISSUE TITLE
Comparing iterators from different containers

### ISSUE THREAD

**Issue by stmuxa** [ROCmSoftwarePlatform/MIOpen#121]
In general, it is not allowed to compare iterators originated from two different containers. 
MSVC implementation of standard lib raises an exception (in debug mode) at that lines:

https://github.com/ROCmSoftwarePlatform/MIOpen/blob/7a1833b9e645848b470fdb3e279aa2423f60282c/src/include/miopen/db_record.hpp#L84
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/7a1833b9e645848b470fdb3e279aa2423f60282c/src/include/miopen/db_record.hpp#L90
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/7a1833b9e645848b470fdb3e279aa2423f60282c/src/include/miopen/db_record.hpp#L96
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/7a1833b9e645848b470fdb3e279aa2423f60282c/src/include/miopen/db_record.hpp#L125

Consider this code to rework.

**Comment by atamazov** [comment]
Good catch, thanks.

**Comment by stmuxa** [comment]
Please, post a patch as soon as it is ready.
Thanks.

**Comment by atamazov** [comment]
Please note that Win10/MSVC environment is not officially supported. Just in case.

**Comment by stmuxa** [comment]
Suggested solution:
[db_record.hpp.patch.txt](https://github.com/ROCmSoftwarePlatform/MIOpen/files/3573449/db_record.hpp.patch.txt)

**Comment by DrizztDoUrden** [comment]
The solution I used: [db_record.hpp.diff.txt](https://github.com/ROCmSoftwarePlatform/MIOpen/files/3574574/db_record.hpp.diff.txt)

It's based on your patch but with pointer instead of a reference to make iterator copiable and movable.

**Comment by stmuxa** [comment]
thanks

**Comment by daniellowell** [comment]
Fixed.
