### ISSUE TITLE
Why does MIOpen building require using personal pfultz stuff?

### ISSUE THREAD

**Issue by srinivamd** [ROCmSoftwarePlatform/MIOpen#123]
Could MIOpen build use released versions of tools instead of tools from someone's personal repo?
WHat are the hard dependencies that MIOpen depends on that cannot be evolved to using public tools?

https://github.com/ROCmSoftwarePlatform/MIOpen/blob/7a1833b9e645848b470fdb3e279aa2423f60282c/install_deps.cmake#L41

**Comment by pfultz2** [comment]
This is just downloading a tool to install the dependencies. Those dependencies can be installed manually. They are all listed in the requirements.txt file. Although we prefer people to use one of the tools to get the dependencies, as dependency version could change or a new dependency could be added.

> Could MIOpen build use released versions of tools instead of tools from someone's personal repo?

That is the release version of the tool.

> WHat are the hard dependencies that MIOpen depends on that cannot be evolved to using public tools?

CMakeGet is a public tool. You can also you use cget as well which is public tool, but you need to install it with `pip install cget`. Even better, the `rbuild` tool was created to utilize `cget`, plus it can ignore internal rocm dependencies, and doesn't reinstall if the dependencies hasn't changed. This should be the preferred choice by devops. The rbuild repo is [here](https://github.com/RadeonOpenCompute/rbuild).

The install_deps.cmake is a simple script provided to install the dependencies without the user needing to install python or `cget`. It just install the dependencies, and provides no features such as caching or upgrading a single dependency. For that the user should install `cget`.

**Comment by srinivamd** [comment]
> This is just downloading a tool to install the dependencies. Those dependencies can be installed manually. They are all listed in the requirements.txt file. Although we prefer people to use one of the tools(ie CMakeGet, cget, or rbuild) to get the dependencies, as dependency version could change or a new dependency could be added(and thus manual scripts will fail).
> 
Your preference is also my preference, to use the tools directly so it is clear what they are,
instead of using someone's wrapper around it. Nothing against your wrappers but
please document the exact steps needed to build MIOpen in the README, so we
are not forced to use personal tools or have to reverse engineer it to get the details.
Could you elaborate details encompassed in this step:
           cmake -P install_deps.cmake --minimum --prefix /some/local/dir
that is mentioned on the MIOpen page?

> > Could MIOpen build use released versions of tools instead of tools from someone's personal repo?
> 
> That is the release version of the tool.
Could you add links to the required tools to build MIOpen? And any minimum version needed?

> 
> > WHat are the hard dependencies that MIOpen depends on that cannot be evolved to using public tools?
> 
> CMakeGet is a public tool. You can also you use cget as well which is public tool, but you need to install it with `pip install cget`. Even better, the `rbuild` tool was created to utilize `cget`, plus it can ignore internal rocm dependencies, and doesn't reinstall if the dependencies hasn't changed. This should be the preferred choice by devops. The rbuild repo is [here](https://github.com/RadeonOpenCompute/rbuild).
> 
> The install_deps.cmake is a simple script provided to install the dependencies without the user needing to install python or `cget`. It just install the dependencies, and provides no features such as caching or upgrading a single dependency. For that the user should install `cget`.

I think it would safe to assume that users downloading MIOpen sources to build it probably
have python and other development tools, and would be willing to install and use other
tools or figure out how to avoid them if given the steps and description on how those
tools are invoked in order to build MIOpen.

Is rbuild developed and promoted as part of RadeonOpenCompute (ROCm)? Do any other 
ROCm depend on rbuild?

Is it a must to download boost libraries from sourceforge instead of using them from
CentOS distribution?
