### ISSUE TITLE
[Documentation] [Question] GetWti() mechanism on roughly evaluate performance of a kernel

### ISSUE THREAD

**Issue by junliume** [ROCmSoftwarePlatform/MIOpen#1285]
_opened on behalf of @zpwenjh_ 

**[Category of Issue]**
Documentation and Question

**[Question]**
From MIOpen's Open Issue, I saw that the MIOpen team wanted to use the GetWti() function to roughly evaluate the performance of a kernel. From the code, we can also see that part of the solver has implemented the GetWti() function. 

However, the implementation mechanism of GetWti() cannot be clearly understood from the code and Issue. I would like to ask about the mechanism of GetWti() and how MIOpen can predict the performance of the kernel by inputting parameters without actually running the kernel.

**Comment by atamazov** [comment]
Basically `GetWti()` should be written by individuals who know the details of kernel implementation and know how it works on the HW. This is how this function was implemented for some Winograd Solver (and it was confirmed by reasonable amount of testing). For Gemm, we have very approximate computations.

> I would like to ask about the mechanism of GetWti() 

It should model the timing characteristics of the specific Solver. No other requirements, no predefined mechanism -- all this is up to its designer.

> and how MIOpen can predict the performance of the kernel by inputting parameters without actually running the kernel.

Maybe you need to elaborate your question. Right now I can only tell that just like the majority of computer programs written by humans, MIOpen's capabilities (including GetWti) depend on capabilities and dedication of individuals who participate in it's design and implementation.

**Comment by Kirpich30000** [comment]
The GetWti() for the Winograd Solver is based on a granularity loss model. Given a dispatch parameters (including geometry) and asic we know exactly how many works are asigned to each CU and how many FMAs are required in internal loop. Internaly we tryed more detailed model including shader's callbacks invokation and linear regression of the resulting formula. It showed impressive prediction. However we haven't yet implemented in code.

**Comment by atamazov** [comment]
@Kirpich30000 @JehandadKhan I am thinking about leveraging multivariate interpolation to predict WTI basing on results of a number of measurements (which we already have in Tuna). Perhaps it is worth to begin some small research. 

If this works, then the similar approach can be used to predict perf-configs as well.

What do you think?
