### ISSUE TITLE
[Question][Enhancement] Kernels under “direct” methods are not dynamic. 

### ISSUE THREAD

**Issue by junliume** [ROCmSoftwarePlatform/MIOpen#1287]
_opened on behalf of @zpwenjh_

**[Category of Issue]**
Issues, Questions, and Enhancement Recommendations

**[Question]**
- [x] Kernels under “direct” methods are not dynamic. So when they upgraded ROCm version where dynamic-hybrid becomes default, the performance is actually much lower for them, because the direct kernels are not selected by default.

**Comment by JehandadKhan** [comment]
@junliume I think a better approach would be to ensure that the Dynamic kernels from iGEMM would have performance on part with the direct algorithm.

**Comment by atamazov** [comment]
@zpwenjh 
> So when they upgraded ROCm version where dynamic-hybrid becomes default, the performance is actually much lower for them, because the direct kernels are not selected by default.

- (1) This applies only to "unknown" configs and to GPUs that we do not officially support. Please adjust the original question.
- (2) The limitations of dynamic_hybrid mode is known aspect of MIOpen's behavior.
  - (2.1) Would you like to change it?
    - (2.1.1) For example, would you like to enable Direct methods for "unknown" configs? or for unsupported GPUs? or for both?
  - (2.2) Or maybe you need some workaround for some specific use case?

**Comment by zpwenjh** [comment]
@atamazov @junliume I think the dynamic kernel effectively avoids the problem of runtime compilation, so I prefer to use dynamic_hybrid find mode. Before the faster kernels came out, I may modify some commonly used direct kernels to dynamic kernels to meet user's requests.
