### ISSUE TITLE
Duplicate code in ConvHipImplicitGemmWrwV4R4Xdlops::IsApplicable

### ISSUE THREAD

**Issue by atamazov** [ROCmSoftwarePlatform/MIOpen#1291]
Duplicate code

_Originally posted by @atamazov in https://github.com/ROCmSoftwarePlatform/MIOpen/pull/553#r750235273_

**Comment by averinevg** [comment]
@atamazov @junliume Fixed in https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1811

**Comment by atamazov** [comment]
@averinevg Thanks!
