### ISSUE TITLE
Feature Request: multiple simultaneous CLANG invocation.

### ISSUE THREAD

**Issue by emerth** [ROCmSoftwarePlatform/MIOpen#130]
Miopen runs clang to build object files that implement shaders that run layers or operations in ML/AI models. Which is fine. However it appears to run clang once, then run it once more, then once more, then... . 

Logically the model graph should be available before forking out clang, and the shaders are object files, independent of each other, so it should be possible to count the cores in the host PC and then fork off that many clang instances.

Which leads to my feature request: parallelize the clang shader compilation code, make it invoke multiple clangs simultaneously.

**Comment by daniellowell** [comment]
The Find calls for convolution are now parallelized per algorithm. That is, each algorithm compiles the solvers' kernels in parallel. Expect future improvements in this area.
