### ISSUE TITLE
naive_conv.cpp build errors in Debug builds.

### ISSUE THREAD

**Issue by atamazov** [ROCmSoftwarePlatform/MIOpen#1314]
Use of reserved identifiers lead to kernel build errors in Debug builds. This hinders triaging of bugs at least.

https://github.com/ROCmSoftwarePlatform/MIOpen/blob/037e006c19be0d810c5cf1ced53b02e10d99702d/src/kernels/gpu_reference_kernel/naive_conv.cpp#L32

https://github.com/ROCmSoftwarePlatform/MIOpen/blob/037e006c19be0d810c5cf1ced53b02e10d99702d/src/kernels/gpu_reference_kernel/naive_conv.cpp#L47

**Comment by junliume** [comment]
@carlushuang @atamazov Just curious why this issue is not caught in CI. I think we have debug configurations in the pipeline.

**Comment by atamazov** [comment]
This is visible in Full tests. Debug builds are very slow, so we do not run Full tests with them.

**Comment by carlushuang** [comment]
@atamazov I use `-DCMAKE_BUILD_TYPE=Debug` to build miopen, and managed to run MIOpenDriver that internally call to naive conv (`ConvDirectNaiveConvFwd`), but everything is just fine, no error prompt out?
How can I reproduce this failure?

**Comment by atamazov** [comment]
@carlushuang Make sure to select proper problem, so that HIP kernel is selected, not ASM. Maybe also you need to use recent mainline build, e.g. compute-artifactory.amd.com:5000/rocm-plus-docker/compute-rocm-dkms-no-npi-hipclang:9148-ubuntu-18.04-stg2, and OCL backend. Example:
```
root@hpe-rack-12:/dockerx/github/MIOpen/build/debug.opencl# ls -l /opt
total 4
lrwxrwxrwx 1 root root   22 Nov 16 06:26 rocm -> /etc/alternatives/rocm
drwxr-xr-x 1 root root 4096 Nov 16 06:26 rocm-5.0.0-9148
<...>
root@hpe-rack-12:/dockerx/github/MIOpen/build/debug.opencl# cmake \
-DMIOPEN_BACKEND=OpenCL \
-DBUILD_DEV=On \
-DCMAKE_BUILD_TYPE=Debug \
-DMIOPEN_TEST_ALL=On \
-DMIOPEN_TEST_FLAGS="--verbose --disable-verification-cache" \
-DCMAKE_PREFIX_PATH=/root/miopen-deps \
-DMIOPEN_USE_COMGR=Off \
-DMIOPEN_USE_MLIR=Off \
../..
<...>
root@hpe-rack-12:/dockerx/github/MIOpen/build/debug.opencl# make tests -j 96
<...>
root@hpe-rack-12:/dockerx/github/MIOpen/build/debug.opencl# MIOPEN_DEBUG_CONV_IMPLICIT_GEMM_ASM_FWD_GTC_XDLOPS_NHWC=0 \
MIOPEN_DEBUG_CONV_GEMM=0 \
MIOPEN_LOG_LEVEL=5 \
./bin/test_conv2d --float --cmode conv --pmode default --group-count 3 --input 16 9 224 224 --weights 63 3 3 3 \
--batch_size 16 --input_channels 9 --output_channels 63 --spatial_dim_elements 224 224 \
--filter_dims 3 3 --pads_strides_dilations 1 1 1 1 1 1 --trans_output_pads 0 0 \
--in_layout NCHW --fil_layout NCHW --out_layout NCHW \
--disable-backward-data \
--disable-backward-weights \
--verbose --disable-verification-cache
<...>
```
See attached output: [issue-16-9-224-224.opencl.ll5.dev-debug.build-failure.txt](https://github.com/ROCmSoftwarePlatform/MIOpen/files/7643942/issue-16-9-224-224.opencl.ll5.dev-debug.build-failure.txt)
