### ISSUE TITLE
HIP/ASM Naive solver ignore debug ENV

### ISSUE THREAD

**Issue by asroy** [ROCmSoftwarePlatform/MIOpen#1319]
All naive solvers are not controlled by use_asm_kernels or use_hip_kernels, for example:

https://github.com/ROCmSoftwarePlatform/MIOpen/blob/037e006c19be0d810c5cf1ced53b02e10d99702d/src/solver/conv_direct_naive_conv_fwd.cpp#L37

@JehandadKhan @atamazov  @carlushuang

**Comment by atamazov** [comment]
And in some cases Naive Solvers use ASM kernels (that shall be controlled by `use_asm_kernels`):
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/037e006c19be0d810c5cf1ced53b02e10d99702d/src/solver/conv_direct_naive_conv.cpp#L86-L95
