### ISSUE TITLE
Implement and use an abstraction that represents a multi-buffer workspace

### ISSUE THREAD

**Issue by atamazov** [ROCmSoftwarePlatform/MIOpen#1326]
This seems Ok as a hotfix. However we should hide details in some suitable abstraction instead hacky code here and there. In this specific case, I can propose some class that can represents metrics of a workspace that logically consists of two sub-buffers, each with its own size and alignment. Very basic example:
```C++
WorkspaceBuf2Traits wt(size_0, size_1, alignment_1);
...
wt.GetSize(); // total workspace size
wt.GetOffset1(); // offset of subbuffer 1
```

_Originally posted by @atamazov in https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1324#issuecomment-985808818_

**Comment by atamazov** [comment]
FYI C++ features related to alignment: https://en.cppreference.com/w/cpp/memory/align

**Comment by shaojiewang** [comment]
> 

OK, I will do it.

**Comment by shurale-nkn** [comment]
@atamazov 
Kernel arguments are a great example of such abstraction. Everything has already been thought up, just need to add a buffer to save pointers.

https://github.com/ROCmSoftwarePlatform/MIOpen/blob/c701af3ba83f8fb99d7efab30ee0b22de57f2f42/src/include/miopen/hipoc_kernel.hpp#L140-L159
