### ISSUE TITLE
CMake version needs to be 3.15.1 or higher

### ISSUE THREAD

**Issue by junliume** [ROCmSoftwarePlatform/MIOpen#1330]
While building MIOpen in docker images, very frequently we meet the following problem:

```
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.15.1 or higher is required.  You are running version 3.10.2
```

- [x]  Which component needs higher than default cmake version in Ubuntu 18.04 and why?
- [x] Ways to resolve the issue
https://askubuntu.com/questions/355565/how-do-i-install-the-latest-version-of-cmake-from-the-command-line

**Comment by carlushuang** [comment]
https://github.com/ROCmSoftwarePlatform/llvm-project-mlir/blob/miopen-dialect/CMakeLists.txt
MLIR require at least `3.15.1`, and we now depends on MLIR, so.
