### ISSUE TITLE
In Jenkinsfile, Agent label is set to "vega" while stage is gfx908 or gfx90a

### ISSUE THREAD

**Issue by shaojiewang** [ROCmSoftwarePlatform/MIOpen#1331]
In jenkins file:

https://github.com/ROCmSoftwarePlatform/MIOpen/blob/4b37632a60b222f378bdc3228f15a1f149289a02/Jenkinsfile#L792-L811

@atamazov @junliume Noticed that the agent label is vega when stage is gfx908 or gfx90a. Is it a mistake?

**Comment by atamazov** [comment]
Sure, this is a bug.

**Comment by atamazov** [comment]
Originated from #1321
