### ISSUE TITLE
[Navi21] test_activation quietly fails

### ISSUE THREAD

**Issue by atamazov** [ROCmSoftwarePlatform/MIOpen#1334]
```
35/92 Test  #1: test_activation .......................................***Failed  394.89 sec
/dockerx/github/MIOpen/build/release.hip-clang.nodev/bin/test_activation --float --input 1, 1, 1, 1 --alpha 0.95 --beta 2.3 --gamma 3.4 --mode ELU --packed 1.
error: 0
Max diff: 0
Forward Activation: miopenActivationELU
Input tensor: 1, 1, 1, 1...
/dockerx/github/MIOpen/build/release.hip-clang.nodev/bin/test_activation --float --input 1, 16, 4096, 4096 --alpha 0.95 --beta 2.3 --gamma 3.4 --mode ELU --packed 1.
error: 0
Max diff: 0
Forward Activation: miopenActivationELU
Input tensor: 1, 16, 4096, 4096
/dockerx/github/MIOpen/build/release.hip-clang.nodev/bin/test_activation --float --input 1, 16, 4096, 4096 --alpha 0.95 --beta 2.3 --gamma 3.4 --mode ELU --packed 1.
CMake Error at test_test_activation.cmake:7 (message):
  Test failed
```
but no other signs of error.

_Originally posted by @atamazov in https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1333#issuecomment-989256733_

**Comment by atamazov** [comment]
The test quietly fails when input tensor size reaches 1 GiB and if CTEST_PARALLEL_LEVEL=4. When the test runs exclusively, it passes, so it seems the root of the issue is lack of GPU resources. We can run the test in RUN_SERIAL mode, but I would consider this is as a workaround for now.

What needs to be done:
- (1) Find out the reason of the failure. Maybe this is normal.
- (2) Definitely, the problem is that the test fails **_quietly_**, which needs to be fixed.

**Comment by atamazov** [comment]
Assume a bug an set normal urgency until the reason is identified found (see (1) from previous comment).

**Comment by junliume** [comment]
@shaojiewang  could you please take a look at this issue?

**Comment by shaojiewang** [comment]
> @shaojiewang could you please take a look at this issue?

Yes, sure. But not so familiar with activation kernel code.
