### ISSUE TITLE
Finish handling of W/A for SWDEV-271887

### ISSUE THREAD

**Issue by atamazov** [ROCmSoftwarePlatform/MIOpen#1342]
@zjing14 On April 7 2021 https://ontrack-internal.amd.com/browse/SWDEV-271887 was set to implemented state. It needs to find out ROCm release the fix is included in, and disable the W/A starting from that release. Then we can check that the issue is gone and close the Jira.

_Originally posted by @atamazov in https://github.com/ROCmSoftwarePlatform/MIOpen/pull/739#discussion_r763317708_

**Comment by zjing14** [comment]
@atamazov Checked with ROCm 4.3. Confirmed that the issue has been resolved.

**Comment by atamazov** [comment]
_> It needs to find out ROCm release the fix is included in, and disable the W/A starting from that release._

@junliume ___This is not done yet.___ Also we have WORKAROUND_SWDEV_271887 in tests which needs to be removed as well.

> Then we can check that the issue is gone and close the Jira...

...and this ticket.

**Comment by atamazov** [comment]
Let's create a PR that:

> ...find out ROCm release the fix is included in, and disable the W/A starting from that release. 

and removes

> WORKAROUND_SWDEV_271887 in tests

**Comment by ppanchad-amd** [comment]
@atamazov Is this ticket still relevant? Thanks!

**Comment by JonathanLichtnerAMD** [comment]
Closing since MIOpen is being migrated to [ROCm/rocm-libraries](https://github.com/ROCm/rocm-libraries).  Please re-open there if you believe this is still an issue.
