### ISSUE TITLE
[MI200][NCHW][SWDEV-312112] The find-db NCHW records for ConvAsmImplicitGemmGTCDynamic*XdlopsNHWC must be updated

### ISSUE THREAD

**Issue by atamazov** [ROCmSoftwarePlatform/MIOpen#1349]
The find-db NCHW records for
- ConvAsmImplicitGemmGTCDynamicBwdXdlopsNHWC
- ConvAsmImplicitGemmGTCDynamicFwdXdlopsNHWC
- ConvAsmImplicitGemmGTCDynamicWrwXdlopsNHWC

must be refreshed.

_Originally posted by @atamazov in https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1324#issuecomment-996793474_

**Comment by atamazov** [comment]
#1324 increases WS up to 3 bytes, but the system find-db remains the same. The library may run into fatal errors from time to time.

The problem may manifest in develop, Staging tests and in 5.0 Release Staging tests. The latter is potentially the most problematic.

## How we can fix this

We do not need to actually run tuning sessions to update find-db files. Adding 3 to the "required workspace size" field for ConvAsmImplicitGemmGTCDynamic*XdlopsNHWC solvers in NCHW records should be enough.

Alternatives:
- Regenerate find-db for MI100/MI200 (@JehandadKhan) from the existing Tuna db.
- Patch existing find-db files using some script (@DrizztDoUrden )

Let's decide which way we prefer (assuming that the goal is to have the fix ASAP).

**Comment by atamazov** [comment]
Maybe it is better to accommodate for #1327 in advance and increase requires WS size not by 3, but by (255*3).

**Comment by JehandadKhan** [comment]
@atamazov  Thanks for highlighting this. Can we hold off on merging #1324  until January ?

**Comment by atamazov** [comment]
Sure. But the immediate problem is that we have this issue in 5.0 staging.

**Comment by junliume** [comment]
AFAIK, we tune after the branch is cut, and will need to regenerate find-db then anyway?

**Comment by atamazov** [comment]
Of course, but we do not want to receive bug reports before that, right?

**Comment by atamazov** [comment]
...And currently we have this problem in Staging branch. After promotion it will be replicated to Master branch and will remain there (i.e. in all Mainline builds) until the fix is promoted.

**Comment by junliume** [comment]
@atamazov  @JehandadKhan : which way is "faster", a.k.a. can be completed by next Tuesday?  I will vote for "Patch existing find-db files using some script (@DrizztDoUrden )" since Chris is off and patching looks like a more "direct" way to ensure problems are fixed. What do you think?

**Comment by atamazov** [comment]
Either variant works for me.

**Comment by JehandadKhan** [comment]
I vote for @DrizztDoUrden to update it since that sounds the safest to me as well.

**Comment by atamazov** [comment]
@DrizztDoUrden Let's update MI100/MI200 fdb as per https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1349#issuecomment-996806479. I am available for a call at any time.

**Comment by atamazov** [comment]
@shaojiewang FYI. Please share your opinion about this. Thanks.

**Comment by shaojiewang** [comment]
@atamazov Thanks for findings and updates. I think that patching the existing find-db is a better way. 

In the future, for the find db part, could it be possible to remove the Workspace_size from the db and just let it be computed on the fly? Or else, is it possible to have some reserved space for WS?

**Comment by atamazov** [comment]
@JehandadKhan FYI There are none records with `ConvAsmImplicitGemmGTCDynamic*XdlopsNHWC` in MI100 find-db files.

**Comment by atamazov** [comment]
> @JehandadKhan FYI There are none records with `ConvAsmImplicitGemmGTCDynamic*XdlopsNHWC` in MI100 find-db files.

I mean, is it expected in `develop`?

**Comment by JehandadKhan** [comment]
> > @JehandadKhan FYI There are none records with `ConvAsmImplicitGemmGTCDynamic*XdlopsNHWC` in MI100 find-db files.
> 
> I mean, is it expected in `develop`?

Not according to my data

**Comment by atamazov** [comment]
@JehandadKhan Still unclear... ;) So there is nothing to fix in MI100 System find-db files, right?

**Comment by JehandadKhan** [comment]
@atamazov  That is correct, no records for gfx908 of the above/mentioned solvers

**Comment by JehandadKhan** [comment]
Perhaps I could have worded my earlier response better !
