### ISSUE TITLE
AsmConv1x1U may produce wrong results on gfx803

### ISSUE THREAD

**Issue by huanzhang12** [ROCmSoftwarePlatform/MIOpen#135]
**Test environment:**
MIOpen v2.3.0 (commit 869a484)
Tensorflow-rocm v2.1.0
Rocm v3.1
Ubuntu 19.10 (kernel version 5.3.0-45-generic)

**Test script:**
The test script is based on https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/issues/519
```
pip install numpy scikit-image tensorflow-rocm efficientnet
wget https://upload.wikimedia.org/wikipedia/commons/f/fe/Giant_Panda_in_Beijing_Zoo_1.JPG
cat <<EOF >test_efficientnet_gfx803.py

import numpy as np
from skimage.io import imread
import efficientnet.tfkeras as efn
from efficientnet.tfkeras import center_crop_and_resize, preprocess_input


model = efn.EfficientNetB0(weights='imagenet')
image = imread('Giant_Panda_in_Beijing_Zoo_1.JPG')
image_size = model.input_shape[1]
x = center_crop_and_resize(image, image_size=image_size)
x = preprocess_input(x)
x = np.expand_dims(x, 0)
y = model.predict(x)
print('Top-10 prediction values:\n', np.sort(y[0])[:-11:-1])

EOF
```

**Results:**
Results on CPU (reference):
```
HIP_VISIBLE_DEVICES=-1 python test_efficientnet_gfx803.py
Top-10 prediction values:
 [0.7587872  0.00835475 0.00720724 0.00413023 0.00402107 0.00319306
 0.00221962 0.0021532  0.00194688 0.00153865]
```

Results on gfx906 (correct):
```
HIP_VISIBLE_DEVICES=1 python test_efficientnet_gfx803.py
Top-10 prediction values:
 [0.75878704 0.00835476 0.00720722 0.00413022 0.00402108 0.00319307
 0.00221963 0.0021532  0.00194688 0.00153866]
```

Results on gfx803 (wrong numbers; each run generates different result):
```
HIP_VISIBLE_DEVICES=1 python test_efficientnet_gfx803.py
Top-10 prediction values:
 [0.46198544 0.09125268 0.03395936 0.03032065 0.02977441 0.02380551
 0.01966209 0.01934384 0.01164374 0.01030718]
```

Results on gfx803 disabling 1x1 ASM kernel (correct):
```
MIOPEN_DEBUG_CONV_DIRECT_ASM_1X1U=0 HIP_VISIBLE_DEVICES=0 python test_efficientnet_gfx803.py
Top-10 prediction values:
 [0.75878704 0.00835476 0.00720722 0.00413022 0.00402108 0.00319307
 0.00221963 0.0021532  0.00194688 0.00153866]
```

MIOpen v2.2.0 does produce correct results as all ASM kernels were disabled on gfx803.

It seems the problem is related to 1x1 convolution kernel [conv_asm_1x1u.cpp](https://github.com/ROCmSoftwarePlatform/MIOpen/blob/master/src/solver/conv_asm_1x1u.cpp) and [conv1x1u.s](https://github.com/ROCmSoftwarePlatform/MIOpen/blob/master/src/kernels/conv1x1u.s), since setting `MIOPEN_DEBUG_CONV_DIRECT_ASM_1X1U=0` eliminates this bug. Additionally, I ran the  test with `MIOPEN_ENABLE_LOGGING_CMD` and dump all `MIOpenDriver` commands. However, when running each 1x1 convolution individually using `MIOpenDriver`, none of them fail. I guess this is possibly a memory related bug on gfx803 since the wrong prediction values are different each time.

**Comment by atamazov** [comment]
Thanks for the detailed report. The support for gfx803 we can provide is very limited, so I think we will disable 1x1U asm kernel for a while and fix later, when time permits. We have quite fast new ImplicitGemm kernels so I do not expect notable performance drop.

**Comment by huanzhang12** [comment]
@atamazov Thank you for looking into this issue! 

BTW I dumped all the convolution kernel invocations when running the test script, and filtered out all kernels that are not `ConvAsm1x1U`. There are only 7 calls to `ConvAsm1x1U`, so hopefully it is not hard to find the culprit :)

```
./bin/MIOpenDriver conv -n 1 -c 10 -H 1 -W 1 -k 240 -y 1 -x 1 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -F 1 -t 1
./bin/MIOpenDriver conv -n 1 -c 240 -H 1 -W 1 -k 10 -y 1 -x 1 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -F 1 -t 1
./bin/MIOpenDriver conv -n 1 -c 24 -H 56 -W 56 -k 144 -y 1 -x 1 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -F 1 -t 1
./bin/MIOpenDriver conv -n 1 -c 48 -H 1 -W 1 -k 1152 -y 1 -x 1 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -F 1 -t 1
./bin/MIOpenDriver conv -n 1 -c 4 -H 1 -W 1 -k 96 -y 1 -x 1 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -F 1 -t 1
./bin/MIOpenDriver conv -n 1 -c 6 -H 1 -W 1 -k 144 -y 1 -x 1 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -F 1 -t 1
./bin/MIOpenDriver conv -n 1 -c 8 -H 1 -W 1 -k 32 -y 1 -x 1 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -F 1 -t 1
```

Hope this is helpful for you, and hope this issue can be fixed in a future MIOpen release.
