### ISSUE TITLE
find-db for gfx908 is missing

### ISSUE THREAD

**Issue by atamazov** [ROCmSoftwarePlatform/MIOpen#136]
Found during looking into Jenkins logs.

**Comment by alexandraBara** [comment]
@daniellowell  do i just run this as part of the next tuna cycle or do i need to do this now?

**Comment by aserio** [comment]
@alexandraBara, is this issue still at large?

**Comment by alexandraBara** [comment]
> @alexandraBara, is this issue still at large?

@cderb did a round of tuning this time, I am not sure if we had enough time to do gfx908 as well but he can update us with status.
