### ISSUE TITLE
[Tidy][Quality] MIOpen_Source include header files which are redundant and easy to miss

### ISSUE THREAD

**Issue by junliume** [ROCmSoftwarePlatform/MIOpen#1365]
**[Keywords]:**
Tidy; Quality; CMakeLists; Maintenance

**[Issue]:** 
The file `src/CMakeLists.txt` contains a set of `MIOpen_Source` which includes lots of header files. 
e.g. https://github.com/ROCmSoftwarePlatform/MIOpen/commit/96bc894860ce2211e73e25d891843c2a09758b17 and https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1350

This list is easy to miss in future updates. (maintenance issue)

**[Target]:** 
Remove the header files from tidy checks since they are checked as parts of the files that include them anyway.

**Comment by atamazov** [comment]
via #1369
