### ISSUE TITLE
[Kernel] Compilation error of conv3x3.s

### ISSUE THREAD

**Issue by zpwenjh** [ROCmSoftwarePlatform/MIOpen#1374]
I am using develop of miopen, the command line as follows:
```
MIOpenDriver conv -n 2 -c 64 -H 192 -W 288 -k 128 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -m conv -g 2 -F 1 -t 1 -V 0
```
Then I get errors list in the picture:
![image](https://user-images.githubusercontent.com/63989327/149296463-dbcd14db-9f82-4cec-a083-b654880c6e00.png)

The following lines in conv3x3.s seems to cause the error. 
![image](https://user-images.githubusercontent.com/63989327/149298307-9be6be4e-5959-40d2-8bba-6a52e734962a.png)

Then I modify the file, the error is eliminated:
![image](https://user-images.githubusercontent.com/63989327/149298687-71da8be3-59f6-4efe-8e58-f67e5bb8c018.png)

**Comment by atamazov** [comment]
@Slimakanzer @Kirpich30000 Please review this, thanks.
