### ISSUE TITLE
[cppcheck][warning][invalidFunctionArg] cppcheck 2.6 warnings on unsupported tensor datatype

### ISSUE THREAD

**Issue by junliume** [ROCmSoftwarePlatform/MIOpen#1384]
**[Keywords]:**
cppcheck; warning;
**[Urgency: Low; Importance: Low]**

**[Env]:**
cppcheck@2.6

**[Description]:**
The issue is [invalidFunctionArg] warning with cppcheck upgrade
[LOG]: [Jenkins Log](http://micimaster.amd.com/blue/rest/organizations/jenkins/pipelines/MLLibs/pipelines/MIOpen/branches/jenkins-ci-rocm-4.5/runs/11/nodes/13/steps/73/log/?start=0)
Nothing logically is wrong with the codes, we just wish to silent a few warnings and improve quality in static checks.

https://github.com/ROCmSoftwarePlatform/MIOpen/blob/622dd718138da185e98fbecd0e05961c1748c162/test/tensor_vec.cpp#L181

There are three other places with the same code above in the same file. For double datatype it might evaluate as 0 and cause issues with `log2(vec_size)` later.

[Recommendation]:
1. If double datatype of a tensor is not supported in the test, please assert so and guard these cases;
2. If we plan to support double or derived datatype now or future, maybe change this line to prevent `vec_size` from becoming zero? It will lead to `log2(vec_size)` becoming an issue.

**Comment by pfultz2** [comment]
The test driver will still instantiate this for double here:

https://github.com/ROCmSoftwarePlatform/MIOpen/blob/622dd718138da185e98fbecd0e05961c1748c162/test/driver.hpp#L1361

We could remove this instantiation and just throw an error when `double` is passed to the driver. I dont think we support double for any of our inputs currently so it doesn't seem necessary.

**Comment by junliume** [comment]
@zjing14  do we have a quick fix for this? we support double reduction and that's the only double datatype AFAIK.

**Comment by atamazov** [comment]
I am wondering what is `vec_size`?

**Comment by junliume** [comment]
consolidated with https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1807
