### ISSUE TITLE
[cppcheck][warning][overlappingWriteUnion] issue and question about type pruning in bf16 header file

### ISSUE THREAD

**Issue by junliume** [ROCmSoftwarePlatform/MIOpen#1385]
**[Keywords]:**
cppcheck; warning;
**[Urgency: Low; Importance: Low]**

**[Env]:**
cppcheck@2.6

**[Description]:**
It first appeared as a simple warning:
<pre>
bfloat16_dev.hpp:106:24: warning: Overlapping read/write of union is undefined behavior [overlappingWriteUnion]
         target_val.u32 += (0x7fff + (target_val.ushortvec[1] & 1));
                        ^
</pre>
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/8f09af3671b0f4926464a2ca965e7ac0289dfd92/src/kernels/bfloat16_dev.hpp#L106

We are doing type pruning in a very interesting way (lines above the above line are explanations). Leave alone the endianness and system portability, I am not sure if HIP or LLVM can actually support such behavior in cpp:
```cpp
typedef union
{
    uint u32;
    ushort2 ushortx2;

// Composable kernels are written in HIP language. The language doesnt support
// ushort2.hi or ushort2.low.
#ifdef __HIP_PLATFORM_HCC__
    ushort ushortvec[2];
#endif // MIOPEN_BACKEND_HIP
    float f32;
} cvt_bf16_fp32_t;
```
So ... it has been working perfectly before and we expect the same in the future? I know that we should not lose sleep over this issue and rely on the good mercy of compiler implementation, but if we only need type pruning, why not `reinterpret_cast<foo>(bar)`? Because this way as is is much easier or HIP does not support such cast?

**Comment by atamazov** [comment]
cppcheck does not allow to use different members of union in RHS and LHS of the assignment op. Possible fix:
```C++
const uint temp = target_val.ushortvec[1] & 1;
target_val.u32 += (0x7fff + temp);
```

**Comment by atamazov** [comment]
Note that use of unions for "type punning" in C++ is UB but always works in practice. We can migrate to `std::bit_cast` when C++20 becomes available.

**Comment by pfultz2** [comment]
> but if we only need type pruning, why not reinterpret_cast<foo>(bar)?

It has the same problem even though it might not have a warning from cppcheck. The type aliasing rules for `reinterpret_cast` are the same rules applied to accessing the inactive member of a union. A `reinterpret_cast` is mostly only valid to and from `char*`. 

> Note that use of unions for "type punning" in C++ is UB but always works in practice.

Yes, most compilers relax the rules, but there is no guarantee in the future.

> We can migrate to std::bit_cast when C++20 becomes available.

`bit_cast` doesn't work with references or pointers. So you can't use it as an lvalue, so this would need to be written something like this:

```cpp
const uint delta = (0x7fff + target_val.ushortvec[1] & 1);
target_val.ushortvec = std::bit_cast<decltype(target_val.ushortvec)>(
    std::bit_cast<uint>(target_val.ushortvec) + delta);
```

We dont need to wait for C++20 for `std::bit_cast`(unless we need this for `constexpr`) as this can be implemented with `memcpy`:

```cpp
template <class To, class From>
To bit_cast(const From &src) noexcept
{
  static_assert(std::is_trivially_constructible<To>{} and
                    std::is_trivially_constructible<From>{} and
                    sizeof(To) == sizeof(From),
                "Types must be trivially constructible and the same size");

  To dst;
  std::memcpy(&dst, &src, sizeof(To));
  return dst;
}
```

**Comment by atamazov** [comment]
@junliume :warning: Note that with current implementation, all the objects of type `cvt_bf16_fp32_t` must be defined as `volatile` to avoid optimizations that compiler may apply to the members: after writing to one member, it can optimize out re-reading the just writtien value when another member is being read.

**Comment by atamazov** [comment]
@pfultz2 `memcpy` seems too expensive ;( What we need is reading/writing bits from memory (actually, registers) and interpreting them as different types. Union is an ideal solution for C (and it is free!), but in C++ it may lead to UB... Any other ideas?

**Comment by pfultz2** [comment]
> memcpy seems too expensive ;( What we need is reading/writing bits from memory (actually, registers) and interpreting them as different types.

Its actually not expensive. The compiler optimizes it down to just manipulating the bits in register with no calls to `std::memcpy`:

https://godbolt.org/z/bxGsf5eob

> Union is an ideal solution for C (and it is free!), but in C++ it may lead to UB... Any other ideas?

The only other option it to pass to a function that get compiled as C99.

**Comment by junliume** [comment]
consolidated with https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1807

**Comment by atamazov** [comment]
@junliume Can you please update https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1807#issue-1396677690 by adding a link to this ticket, like this:
```
- [ ] overlappingWriteUnion - see #1385 for discussion
```
Thanks.
