### ISSUE TITLE
[cuDNN] `cudnnSetTensor4dDescriptorEx` support in MIOpen is needed

### ISSUE THREAD

**Issue by emankov** [ROCmSoftwarePlatform/MIOpen#1430]
[Reasons]
1. `cudnnSetTensor4dDescriptorEx` is used in the `Apollo` project [here](https://github.com/ApolloAuto/apollo/blob/266afbf68d83fa6fac7a812ff8a950223f5ab2c0/modules/perception/inference/tensorrt/plugins/softmax_plugin.cu#L39), its support is needed in `MIOpen` as `MIOpen` support is going to appear in `Apollo` along with `AMD GPU` support.
2. `cudnnSetTensor4dDescriptorEx` has already been supported by the obsolete [hipDNN](https://github.com/ROCmSoftwarePlatform/hipDNN/blob/e7579a4ed8d38acf054c2a4c2796ce895d03cfcf/library/include/hipdnn.h#L437).

**Comment by junliume** [comment]
@JehandadKhan  could you take a look at this feature request? Is it something aligned with our roadmap?
@sunway513 How about framework support on Apollo project?

**Comment by JehandadKhan** [comment]
Hello @emankov ,

Thanks for reaching out. Can you please look at the [`miopenSetTensorDescriptor`](https://github.com/ROCmSoftwarePlatform/MIOpen/blob/349928c032a42275a64a1f39c10c83daf20c1d75/include/miopen/miopen.h#L620) API call. `miopenSetTensorDescriptor` allows you to set the data type, strides and dimensions for a 4-DImensional tensor. If this API does not satisfy the requirements please update the description of the issue.

**Comment by emankov** [comment]
Hi @JehandadKhan,

MIOpen already has an analogue for `cudnnGetTensor4dDescriptor` - [miopenGet4dTensorDescriptor](https://github.com/ROCmSoftwarePlatform/MIOpen/blob/master/include/miopen/miopen.h#L586), where all four strides are presented as arguments (as well as four dimension arguments). 
Adding `miopenSet4dTensorDescriptorEx` analogous to `cudnnSetTensor4dDescriptorEx` seems logical as it also has four arguments for strides (and four arguments for dimension), so the function's signatures are the same.

Using [miopenSetTensorDescriptor](https://github.com/ROCmSoftwarePlatform/MIOpen/blob/master/include/miopen/miopen.h#L608) as analogue for `cudnnSetTensor4dDescriptorEx` is also possible, but it will need additional code for packing dims and strides into arrays. Automatic hipification of  `cudnnSetTensor4dDescriptorEx` to `miopenSetTensorDescriptor` will need additional code generation by the [HIPIFY](https://github.com/ROCm-Developer-Tools/HIPIFY) tools for such packing as well. Introducing of `miopenSet4dTensorDescriptorEx` will incapsulate such additional code for arguments population on the user side and make the code smaller and more readable.

**Comment by atamazov** [comment]
@emankov 
> Automatic hipification of cudnnSetTensor4dDescriptorEx to miopenSetTensorDescriptor will need additional code generation by the [HIPIFY](https://github.com/ROCm-Developer-Tools/HIPIFY) tools for such packing as well. Introducing of miopenSet4dTensorDescriptorEx will incapsulate such additional code for arguments population on the user side and make the code smaller and more readable.

Please tell us how important is this for you (high, moderate or low). We'll discuss your request internally and let you know.

**Comment by atamazov** [comment]
@emankov Implemented in #1446
