### ISSUE TITLE
[Solvers] ConvBiasActivAsm1x1U solver - mix of performance configs

### ISSUE THREAD

**Issue by averinevg** [ROCmSoftwarePlatform/MIOpen#1432]
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/develop/src/include/miopen/solver.hpp#L306
```cpp
struct ConvBiasActivAsm1x1U : ConvAsm1x1U
{
    const std::string& SolverDbId() const override { return GetSolverDbId<ConvBiasActivAsm1x1U>(); }

    PerformanceConfigConvBiasActivAsm1x1U GetPerformanceConfig(const ConvolutionContext&) const;

    PerformanceConfigConvBiasActivAsm1x1U Search(const ConvolutionContext&,
                                                 const AnyInvokeParams& invoke_ctx) const;
    ConvSolution GetSolution(const ConvolutionContext& params,
                             const PerformanceConfigConvAsm1x1U& config,
                             bool disableConfigOverrideFromEnv = false) const;
};
```
Solver `ConvBiasActivAsm1x1U` derived from `ConvAsm1x1U`, and it has its own performance config `PerformanceConfigConvBiasActivAsm1x1U`, but `GetSolution()` uses `PerformanceConfigConvAsm1x1U`. `IsValidPerformanceConfig()` derived from `ConvAsm1x1U` and hence uses `PerformanceConfigConvAsm1x1U` too.

Blocker for https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1433

**Comment by junliume** [comment]
@DrizztDoUrden  could you take a look at this issue?

**Comment by atamazov** [comment]
@averinevg 🎉
