### ISSUE TITLE
[BN] checkNumericsInput is called with nullptr

### ISSUE THREAD

**Issue by atamazov** [ROCmSoftwarePlatform/MIOpen#1442]
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/df658f382c5af02133836a8fa5700a23b58c2ca0/src/ocl/batchnormocl.cpp#L171-L172

These numeric checks must not be performed when `(estimatedMean == nullptr)` or `(estimatedVariance == nullptr)`.

I highly recommend checking for similar issues in the rest of BN code.

**Comment by DrizztDoUrden** [comment]
I can fix it, it's less than an hour of work.

**Comment by atamazov** [comment]
No objections. Or maybe @dmikushin is eager to to fix this? :smile:

**Comment by DrizztDoUrden** [comment]
I think, I'll just do it.
