### ISSUE TITLE
[CI][Navi21] add unit test to cover inconsistent warpSize between different HIP kernel building methods issue

### ISSUE THREAD

**Issue by junliume** [ROCmSoftwarePlatform/MIOpen#1468]
> > ./bin/test_reduce_test --float --D 64 3 280 81 --R 0 --ReduceOp 0 --CompType 1 --N 0 --I 0 --scales 1 0

Sadly, this PR does not add this test case, and I am unable to find it in ./test/CMakeLists.txt. Maybe we shall add it to `test_reduce_custom_fp32_fp16` or to `test_reduce_custom_fp32`?

_Originally posted by @atamazov in https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1436#issuecomment-1074041499_

**Comment by atamazov** [comment]
@junliume Well, I just extended the scope of #1431 with the same task ;), see https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1431#issuecomment-1074043979. Shall we close this or revert changes in #1431?

**Comment by junliume** [comment]
@atamazov  thanks!
Close this one since duplicated changes in #1431
