### ISSUE TITLE
[MLIR] tuning search space is different when `MIOPEN_COMPILE_PARALLEL_LEVEL=1`

### ISSUE THREAD

**Issue by whchung** [ROCmSoftwarePlatform/MIOpen#1472]
Discovered while working on enabling KPACK for backward weight convolution in MLIR solver. More details to follow.

+ @jerryyin .

**Comment by jerryyin** [comment]
@jerryyin Could you fill out all the details you can remember? I can guarantee to reproduce when I got time to look at this with only information from the linked PR.

**Comment by aserio** [comment]
Work complete. @whchung to verify that this issue was resolved.
