### ISSUE TITLE
Post-merge review of #1419 "Universal tensor transform feature" and #1481...

### ISSUE THREAD

**Issue by atamazov** [ROCmSoftwarePlatform/MIOpen#1476]
UPDATE: Leftovers:
- https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1419#discussion_r846165878
- https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1419#discussion_r834377391

@junliume Currently this is of `normal_urgency`

----
<details><summary><b><i>The 1st version of this ticket (outdated)</i></b></summary>

All review comments must be resolved (the most important ones are marked with :red_circle:).
- https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1419#pullrequestreview-920308419
- https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1481#pullrequestreview-936525781

/cc @aska-0096 @shaojiewang @DrizztDoUrden 

@junliume Currently this is of high_urgency
</details>

**Comment by junliume** [comment]
@aska-0096 could you follow up with Artem's comments in #1419 asap?

**Comment by aska-0096** [comment]
@atamazov @junliume I send the PR #1481 to cover these review suggestions, hope it works.

**Comment by DrizztDoUrden** [comment]
Is there any specific reason for not basing this on TransposingSolver?https://github.com/ROCmSoftwarePlatform/MIOpen/blob/0c6bdeb3ff46505d65f69a8c6e72ec0eef29835a/src/include/miopen/utility/transposing_solver.hpp#L411
That removes a whole lot of duplications and doesn't require any modification to the transposed solver.
Example of usage: https://github.com/ROCmSoftwarePlatform/MIOpen/blob/0c6bdeb3ff46505d65f69a8c6e72ec0eef29835a/src/include/miopen/pooling/solvers.hpp#L140
If your kernel is universal, just replace this pseudo-solver: https://github.com/ROCmSoftwarePlatform/MIOpen/blob/0c6bdeb3ff46505d65f69a8c6e72ec0eef29835a/src/include/miopen/utility/transposing_solver.hpp#L164

**Comment by junliume** [comment]
@aska-0096 could you take a look and respond to @DrizztDoUrden 's inquiries above? Thanks!

**Comment by aska-0096** [comment]
@DrizztDoUrden Sorry for late reply. I'd like to give three main advantage in tensor reorder solver.

Performance:
1. In tensor reorder method, we re-utilize the exist batched-transpose kernel for higher performance. You can refer to performance data in PR# 1419.
2. All Tensor reorder kernel is compiled in compile-time, and chosen via specific reorder sequence(i.e. Reorder NCHW to NHWC is (0,2,3,1)). This kind of design will decrease the run-time workload.

Completeness:
1.We support various of datatype, int8, fp16, fp32 and fp64.

**Comment by junliume** [comment]
Can we close this one since #1481 is merged?

**Comment by atamazov** [comment]
@junliume This can be closed after resolving all comments in

> - https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1419#pullrequestreview-920308419

**Comment by atamazov** [comment]
7 comments from https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1419#pullrequestreview-920308419 are not resolved yet; couple of them are red.

**Comment by atamazov** [comment]
Description updated with https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1481#pullrequestreview-936525781.

**Comment by aska-0096** [comment]
Updated in #1515. @atamazov

**Comment by atamazov** [comment]
Description updated. @junliume Currently this is of `normal_urgency`
