### ISSUE TITLE
[ROCm 5.0] test_conv_for_implicit_gemm Failed

### ISSUE THREAD

**Issue by junliume** [ROCmSoftwarePlatform/MIOpen#1477]
[Log]:

[Here](http://micimaster.amd.com/blue/rest/organizations/jenkins/pipelines/MLLibs/pipelines/MIOpen/branches/update_docker_rocm502/runs/11/nodes/266/log/?start=0) 
[gfx90a_bf16.log](https://github.com/ROCmSoftwarePlatform/MIOpen/files/8348272/gfx90a_bf16.log)
and attached

[Steps to Reproduce]
MI200 with ROCm 5.0

**Comment by atamazov** [comment]
```
[2022-03-25T03:39:00.295Z] Filter: conv2d, miopenConvolution, miopenPaddingDefault, {0, 0}, {1, 1}, {1, 1}, 
[2022-03-25T03:39:00.295Z] MIOpen(HIP): Error [Compile] 'hiprtcCompileProgram(prog.get(), c_options.size(), c_options.data())' static_kernel_gridwise_convolution_backward_data_implicit_gemm_v4r1_xdlops_nchw_kcyx_nkhw.cpp: HIPRTC_ERROR_COMPILATION (6)
[2022-03-25T03:39:00.295Z] MIOpen(HIP): Error [BuildHip] HIPRTC status = HIPRTC_ERROR_COMPILATION (6), source file: static_kernel_gridwise_convolution_backward_data_implicit_gemm_v4r1_xdlops_nchw_kcyx_nkhw.cpp
[2022-03-25T03:39:00.295Z] MIOpen(HIP): Warning [BuildHip] error: register rewriting failed: cycle in copy bundle
[2022-03-25T03:39:00.295Z] 1 error generated.
[2022-03-25T03:39:00.295Z] Error: Creating the executable from LLVM IRs failed.
```
This is internal compiler error. I recommend opening Jira ticket.

**Comment by atamazov** [comment]
Does it work fine with offline compiler or with COMGR?

**Comment by atamazov** [comment]
@junliume The only quick W/A that I can recommend for now is disabling the failing solver (`ConvHipImplicitGemmBwdDataV4R1Xdlops`) for BF16 && MI200.

**Comment by atamazov** [comment]
> It still fails with 5.0 stock docker image ... something is wrong here.

please attach failing log.

**Comment by junliume** [comment]
> > It still fails with 5.0 stock docker image ... something is wrong here.
> 
> please attach failing log.

> **/root/MIOpen/build/bin/test_conv2d --bfloat16 --cmode conv --pmode default --group-count 1 --input 64 256 35 35 --weights 48 256 1 1 --batch_size 64 --input_channels 256 --output_channels 48 --spatial_dim_elements 35 35 --filter_dims 3 3 --pads_strides_dilations 0 0 1 1 1 1 --trans_output_pads 0 0 --in_layout NCHW --fil_layout NCHW --out_layout NCHW**
MIOpen(HIP): Error [Do] 'amd_comgr_do_action(kind, handle, in.GetHandle(), out.GetHandle())' AMD_COMGR_ACTION_CODEGEN_BC_TO_RELOCATABLE: ERROR (1)
MIOpen(HIP): Error [BuildHip] comgr status = ERROR (1)
MIOpen(HIP): Warning [BuildHip] error: register rewriting failed: cycle in copy bundle
1 error generated.
/root/MIOpen/build/bin/test_conv2d --bfloat16 --cmode conv --pmode default --group-count 1 --input 64 256 35 35 --weights 48 256 1 1 --batch_size 64 --input_channels 256 --output_channels 48 --spatial_dim_elements 35 35 --filter_dims 3 3 --pads_strides_dilations 0 0 1 1 1 1 --trans_output_pads 0 0 --in_layout NCHW --fil_layout NCHW --out_layout NCHW
FAILED: /root/MIOpen/src/hipoc/hipoc_program.cpp:300: Code object build failed. Source: static_kernel_gridwise_convolution_backward_data_implicit_gemm_v4r1_xdlops_nchw_kcyx_nkhw.cpp


> **/root/MIOpen/build/bin/test_conv2d --bfloat16 --cmode conv --pmode default --group-count 1 --input 64 256 35 35 --weights 64 256 1 1 --batch_size 64 --input_channels 256 --output_channels 64 --spatial_dim_elements 35 35 --filter_dims 3 3 --pads_strides_dilations 0 0 1 1 1 1 --trans_output_pads 0 0 --in_layout NCHW --fil_layout NCHW --out_layout NCHW**
> MIOpen(HIP): Error [Do] 'amd_comgr_do_action(kind, handle, in.GetHandle(), out.GetHandle())' AMD_COMGR_ACTION_CODEGEN_BC_TO_RELOCATABLE: ERROR (1)
> MIOpen(HIP): Error [BuildHip] comgr status = ERROR (1)
> MIOpen(HIP): Warning [BuildHip] error: register rewriting failed: cycle in copy bundle
> 1 error generated.
/root/MIOpen/build/bin/test_conv2d --bfloat16 --cmode conv --pmode default --group-count 1 --input 64 256 35 35 --weights 64 256 1 1 --batch_size 64 --input_channels 256 --output_channels 64 --spatial_dim_elements 35 35 --filter_dims 3 3 --pads_strides_dilations 0 0 1 1 1 1 --trans_output_pads 0 0 --in_layout NCHW --fil_layout NCHW --out_layout NCHW
FAILED: /root/MIOpen/src/hipoc/hipoc_program.cpp:300: Code object build failed. Source: static_kernel_gridwise_convolution_backward_data_implicit_gemm_v4r1_xdlops_nchw_kcyx_nkhw.cpp

**Comment by atamazov** [comment]
So the compiler fails with both COMGR and HIPRTC, with the same Solver. What about offline compiler? (-DMIOPEN_USE_COMGR=Off) It's good to know when creating Jira ticket.

The quick W/A is still the same -- https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1477#issuecomment-1079095273.

**Comment by junliume** [comment]
> bin/test_conv2d --bfloat16 --cmode conv --pmode default --group-count 1 --input 64 256 35 35 --weights 64 256 1 1 --batch_size 64 --input_channels 256 --output_channels 64 --spatial_dim_elements 35 35 --filter_dims 3 3 --pads_strides_dilations 0 0 1 1 1 1 --trans_output_pads 0 0 --in_layout NCHW --fil_layout NCHW --out_layout NCHW

Still failed with offline compiler. It looks like something we need to file them a ticket on :
> root@hpe-sjc2-43:/root/MIOpen/build# bin/test_conv2d --bfloat16 --cmode conv --pmode default --group-count 1 --input 64 256 35 35 --weights 64 256 1 1 --batch_size 64 --input_channels 256 --output_channels 64 --spatial_dim_elements 35 35 --filter_dims 3 3 --pads_strides_dilations 0 0 1 1 1 1 --trans_output_pads 0 0 --in_layout NCHW --fil_layout NCHW --out_layout NCHW
**error: register rewriting failed: cycle in copy bundle**
1 error generated when compiling for gfx90a.
bin/test_conv2d --bfloat16 --cmode conv --pmode default --group-count 1 --input 64 256 35 35 --weights 64 256 1 1 --batch_size 64 --input_channels 256 --output_channels 64 --spatial_dim_elements 35 35 --filter_dims 3 3 --pads_strides_dilations 0 0 1 1 1 1 --trans_output_pads 0 0 --in_layout NCHW --fil_layout NCHW --out_layout NCHW
FAILED: /root/MIOpen/src/tmp_dir.cpp:45: Can't execute cd /tmp/miopen-static_kernel_gridwise_convolution_backward_data_implicit_gemm_v4r1_xdlops_nchw_kcyx_nkhw.cpp-359e-243d-6fb2-d0fb;  /opt/rocm/llvm/bin/clang++  -DCK_PARAM_PROBLEM_N=64 -DCK_PARAM_PROBLEM_K=64 -DCK_PARAM_PROBLEM_C=256 -DCK_PARAM_PROBLEM_HI=35 -DCK_PARAM_PROBLEM_WI=35 -DCK_PARAM_PROBLEM_HO=35 -DCK_PARAM_PROBLEM_WO=35 -DCK_PARAM_PROBLEM_Y=1 -DCK_PARAM_PROBLEM_X=1 -DCK_PARAM_PROBLEM_CONV_STRIDE_H=1 -DCK_PARAM_PROBLEM_CONV_STRIDE_W=1 -DCK_PARAM_PROBLEM_CONV_DILATION_H=1 -DCK_PARAM_PROBLEM_CONV_DILATION_W=1 -DCK_PARAM_PROBLEM_IN_LEFT_PAD_H=0 -DCK_PARAM_PROBLEM_IN_LEFT_PAD_W=0 -DCK_PARAM_PROBLEM_IN_RIGHT_PAD_H=0 -DCK_PARAM_PROBLEM_IN_RIGHT_PAD_W=0 -DCK_PARAM_PROBLEM_CONV_GROUP_COUNTS=1 -DCK_PARAM_TUNABLE_BLOCK_SIZE=128 -DCK_PARAM_TUNABLE_GEMM_M_PER_BLOCK=256 -DCK_PARAM_TUNABLE_GEMM_N_PER_BLOCK=64 -DCK_PARAM_TUNABLE_GEMM_K_PER_BLOCK=8 -DCK_PARAM_GEMM_M_PER_WAVE=128 -DCK_PARAM_GEMM_N_PER_WAVE=64 -DCK_PARAM_TUNABLE_GEMM_A_BLOCK_COPY_CLUSTER_LENGTHS_GEMM_K=2 -DCK_PARAM_TUNABLE_GEMM_A_BLOCK_COPY_CLUSTER_LENGTHS_GEMM_M=32 -DCK_PARAM_DEPENDENT_GEMM_A_BLOCK_COPY_CLUSTER_LENGTHS_GEMM_KPACK=2 -DCK_PARAM_TUNABLE_GEMM_A_BLOCK_COPY_SRC_DATA_PER_READ_GEMM_M=8 -DCK_PARAM_TUNABLE_GEMM_B_BLOCK_COPY_CLUSTER_LENGTHS_GEMM_K=2 -DCK_PARAM_TUNABLE_GEMM_B_BLOCK_COPY_CLUSTER_LENGTHS_GEMM_N=64 -DCK_PARAM_DEPENDENT_GEMM_B_BLOCK_COPY_CLUSTER_LENGTHS_GEMM_KPACK=1 -DCK_PARAM_TUNABLE_GEMM_B_BLOCK_COPY_SRC_DATA_PER_READ_GEMM_N=1 -DCK_PARAM_DEPENDENT_GRID_SIZE=1225 -DCK_USE_AMD_XDLOPS=1 -DCK_USE_AMD_XDLOPS_INLINE_ASM=0 -DCK_USE_AMD_XDLOPS_EMULATE=0 -DCK_PARAM_GEMM_ID=0 --std=c++14 -DCK_USE_AMD_BUFFER_ATOMIC_FADD=0 -DCK_BLOCK_SYNC_LDS_WITHOUT_SYNC_VMEM=1 -DCK_WORKAROUND_SWDEV_229564=1 -DCK_WORKAROUND_SWDEV_231101=1 -DCK_USE_AMD_BUFFER_ADDRESSING=1 -DCK_USE_AMD_V_FMAC_F32=0 -DMIOPEN_USE_FP16=0 -DMIOPEN_USE_FP32=0 -DMIOPEN_USE_INT8=0 -DMIOPEN_USE_INT8x4=0 -DMIOPEN_USE_BFP16=1 -DMIOPEN_USE_INT32=0 -DMIOPEN_USE_RNE_BFLOAT16=1 -DCK_PARAM_KPACK_LENGTH=2 -DCK_PARAM_TUNABLE_GEMM_A_BLOCK_COPY_DST_DATA_PER_WRITE_GEMM_KPACK=1 -DCK_PARAM_TUNABLE_GEMM_B_BLOCK_COPY_DST_DATA_PER_WRITE_GEMM_KPACK=2 -mcpu=gfx90a -Wno-everything --cuda-gpu-arch=gfx90a:xnack- --cuda-device-only -c -O3  -Wno-unused-command-line-argument -I. -mllvm -amdgpu-early-inline-all=true -mllvm -amdgpu-function-calls=false -x hip -isystem /opt/rocm-5.0.0/hip/../include -isystem /opt/rocm/llvm/lib/clang/14.0.0/include/.. -D__HIP_PLATFORM_HCC__=1 -D__HIP_PLATFORM_AMD__=1 -isystem /opt/rocm-5.0.0/hip/include -isystem /opt/rocm/include -l--hip-link -l -l -l -l -l  -DHIP_PACKAGE_VERSION_FLAT=4004022013 static_kernel_gridwise_convolution_backward_data_implicit_gemm_v4r1_xdlops_nchw_kcyx_nkhw.cpp -o /tmp/miopen-static_kernel_gridwise_convolution_backward_data_implicit_gemm_v4r1_xdlops_nchw_kcyx_nkhw.cpp-359e-243d-6fb2-d0fb/static_kernel_gridwise_convolution_backward_data_implicit_gemm_v4r1_xdlops_nchw_kcyx_nkhw.cpp.o
Backward convolution: ConvHipImplicitGemmForwardV4R4Xdlops
Input tensor: 64, 256, 35, 35
Weights tensor: 64, 256, 1, 1
Output tensor: 64, 64, 35, 35
Filter: conv2d, miopenConvolution, miopenPaddingDefault, {0, 0}, {1, 1}, {1, 1},

**Comment by atamazov** [comment]
Yes. This is compiler error (see https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1477#issuecomment-1079089221 :sunglasses:).

If `MIOPEN_DEBUG_CONV_IMPLICIT_GEMM_HIP_BWD_V4R1_XDLOPS=0` helps, then I can quickly create W/A.

**Comment by junliume** [comment]
> Yes. This is compiler error (see [#1477 (comment)](https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1477#issuecomment-1079089221) 😎).
> 
> If `MIOPEN_DEBUG_CONV_IMPLICIT_GEMM_HIP_BWD_V4R1_XDLOPS=0` helps, then I can quickly create W/A.

Yes, `MIOPEN_DEBUG_CONV_IMPLICIT_GEMM_HIP_BWD_V4R1_XDLOPS=0` helps.
I've disabled `test_conv_for_implicit_gemm` in #1463 but seems that we can narrow down to this particular solver only.

**Comment by junliume** [comment]
Issue tracked at: [SWDEV-329642](https://ontrack-internal.amd.com/browse/SWDEV-329642)

**Comment by atamazov** [comment]
@junliume #1480 created.
