### ISSUE TITLE
[CI] http://www.zlib.net/zlib-1.2.11.tar.gz no longer available

### ISSUE THREAD

**Issue by aska-0096** [ROCmSoftwarePlatform/MIOpen#1483]
When I running CI for PR #1481, it failed in OpenCL tidy docker build step with error:
```
[2022-03-28T06:10:54.917Z] Downloading http://www.zlib.net/zlib-1.2.11.tar.gz

[2022-03-28T06:10:55.178Z] Download failed with error 404 for: //www.zlib.net/zlib-1.2.11.tar.gz

[2022-03-28T06:10:55.178Z] Failed to build package boost

```
And I try to access the zlib url manually but failed again with:
```
haocongwang@rocm-framework-11:~$ wget http://www.zlib.net/zlib-1.2.11.tar.gz
--2022-03-28 06:28:09--  http://www.zlib.net/zlib-1.2.11.tar.gz
Resolving www.zlib.net (www.zlib.net)... 85.187.148.2
Connecting to www.zlib.net (www.zlib.net)|85.187.148.2|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-03-28 06:28:09 ERROR 404: Not Found.
```
I think the reason is that zlib has updated their version from 1.2.11 to 1.2.12 and the _**old version url**_ no longer accessible. 
(https://www.zlib.net/) and tensor flow has met this kind of zlib version update problem 5 years ago.(https://github.com/tensorflow/tensorflow/issues/6594)

I think we should find a permanent fix for this kind of problem.

cc @junliume @pfultz2

**Comment by junliume** [comment]
@pfultz2 it seems to be a blocker now for all CI processes. zlib seems to be from cget and needs to be changed there? It seems that 1.2.12 may just work.

**Comment by carlushuang** [comment]
http://zlib.net/fossils/ this link has some archived address, like http://zlib.net/fossils/zlib-1.2.11.tar.gz

**Comment by pfultz2** [comment]
> I think we should find a permanent fix for this kind of problem.

If you define the `ROCM_USE_MIOPEN_DEPS` env variable then it will pull zlib from the zigzag local machine.

**Comment by whchung** [comment]
https://github.com/ROCmSoftwarePlatform/rocm-recipes/pull/3
