### ISSUE TITLE
Boost dependency can be (mostly) upgraded

### ISSUE THREAD

**Issue by JP-Ellis** [ROCmSoftwarePlatform/MIOpen#1489]
Previously, there was an incompatibility between Boost's `noinline` and what was provided within the HIP compiler which was initially reported in #658.  Since then, the Boost library has been patched through boostorg/config#393 which was included in Boost version 1.78.  As a result, I have tried again to see if I can avoid having to recompile Boost and use the system version and it mostly works.

In particular, the compilation works fine for all files except for the following 9 files:
- `src/find_db.cpp`
- `src/binary_cache.cpp`
- `src/sqlite_db.cpp`
- `src/solver/conv_asm_3x3u.cpp`
- `src/ocl/gcn_asm_utils.cpp`
- `src/ocl/mloNeuron.cpp`
- `src/ocl/mloPooling.cpp`
- `src/ocl/mloNorm.cpp`
- `src/hip/hip_build_utils.cpp`

The error message is similar to the original issue:

```text
In file included from /tmp/makepkg/miopen-hip/src/MIOpen-rocm-5.0.2/src/find_db.cpp:29:
In file included from /tmp/makepkg/miopen-hip/src/MIOpen-rocm-5.0.2/src/include/miopen/handle.hpp:30:
In file included from /tmp/makepkg/miopen-hip/src/MIOpen-rocm-5.0.2/src/include/miopen/kernel_info.hpp:33:
In file included from /tmp/makepkg/miopen-hip/src/MIOpen-rocm-5.0.2/src/include/miopen/kernel.hpp:53:
In file included from /tmp/makepkg/miopen-hip/src/MIOpen-rocm-5.0.2/src/include/miopen/hipoc_kernel.hpp:34:
In file included from /tmp/makepkg/miopen-hip/src/MIOpen-rocm-5.0.2/src/include/miopen/op_kernel_args.hpp:8:
In file included from /usr/include/boost/container/small_vector.hpp:27:
/usr/include/boost/container/vector.hpp:2754:4: error: use of undeclared identifier 'noinline'; did you mean 'inline'?
   BOOST_CONTAINER_NOINLINE iterator priv_insert_forward_range_no_capacity
   ^
/usr/include/boost/container/detail/workaround.hpp:116:37: note: expanded from macro 'BOOST_CONTAINER_NOINLINE'
   #define BOOST_CONTAINER_NOINLINE BOOST_NOINLINE
                                    ^
/usr/include/boost/config/detail/suffix.hpp:639:46: note: expanded from macro 'BOOST_NOINLINE'
#      define BOOST_NOINLINE __attribute__ ((__noinline__))
                                             ^
/opt/rocm/hip/../include/hip/amd_detail/host_defines.h:50:37: note: expanded from macro '__noinline__'
#define __noinline__ __attribute__((noinline))
                                    ^
```

and in all of the above cases, the addition of `#include <hip/hip_version.h>` as an additional header in each `.cpp` file with no other change to the code fixes the compilation error.  I did also try adding this header to `hipoc_kernel.hpp` but that did not resolve the issue.

I'm happy to create a PR to address this issue, though I would like to understand why adding the missing `hip_version.h` header to `hipoc_kernel.hpp` does not appear to resolve the issue.

I have checked this against the latest develop commit, and the issue (at least when compiling `find_db.cpp`) is still there.

**Comment by junliume** [comment]
Thanks! We are planning on removing dependency on boost (especially since it is 1.72 now) when upgrading to C++17. 
@JehandadKhan  and @pfultz2  could you help to take a look is the current fix could helpful till the removal actually happens?
