### ISSUE TITLE
[CTEST] "--weight" flag won't pass the expected value to weight tensor

### ISSUE THREAD

**Issue by aska-0096** [ROCmSoftwarePlatform/MIOpen#1494]
When I running CTEST in `/MIOpen/test/CMakeLists.txt` like:
```
add_custom_test(test_conv_for_implicit_gemm SKIP_UNLESS_ALL BF16_ENABLED HALF_ENABLED GFX1030_ENABLED
...
COMMAND ${IMPLICITGEMM_TESTING_ENV} $<TARGET_FILE:test_conv2d> ${IMPLICITGEMM_ARGS} --verbose   --input 64  16  28  28  --weights 64  16  1 7 --pads_strides_dilations 0 0 2 2 1 1 | grep -v "cannot be executed due to incorrect params"
...
```
I found that in the output 
```
/miopen-aska/MIOpen/build/bin/test_conv2d --float --cmode conv --pmode default --group-count 1 --input 64 16 28 28 --weights 64 16 1 7 --batch_size 64 --input_channels 16 --output_channels 64 --spatial_dim_elements 28 28 --filter_dims 3 3 --pads_strides_dilations 0 0 2 2 1 1 --trans_output_pads 0 0 --in_layout NCHW --fil_layout NCHW --out_layout NCHW 
Backward convolution: ConvCkIgemmFwdV6r1DlopsNchw
Input tensor: 64, 16, 28, 28
Weights tensor: 64, 16, 1, 7
Output tensor: 64, 64, 14, 11
```
`--filter_dimis` does not give the expected filter_dims (1, 7) we passed to `--weight`, but the default one (3,3,) set by the `/miopen-aska/MIOpen/test/conv2d.cpp`.
And I check the relative part
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/0c6bdeb3ff46505d65f69a8c6e72ec0eef29835a/test/conv_common.hpp#L1769-L1773
I think we forgot to overwrite the value given by `--weight` flag to `filter_dims` by:
`std::copy(weight_tensor_dims.begin() + 2, weight_tensor_dims.end(), filter_dims.begin());`
like what we do before construct the input tensor:
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/0c6bdeb3ff46505d65f69a8c6e72ec0eef29835a/test/conv_common.hpp#L1744-L1750

cc @junliume @pfultz2 @atamazov

**Comment by junliume** [comment]
@aska-0096 Can you generate a PR to fix this issue? Thanks!

**Comment by aska-0096** [comment]
PR #1498 is created.

**Comment by junliume** [comment]
@atamazov @aska-0096 will merge #1498 asap. Thanks!
