### ISSUE TITLE
Unneccesary files written to filesystem during HIP compilation

### ISSUE THREAD

**Issue by atamazov** [ROCmSoftwarePlatform/MIOpen#150]
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/a02171c92e3213ca30f930b7ff0b362934b856fb/src/hip/hip_build_utils.cpp#L92-L93

`.inc` files are assembly includes and not needed during HIP build.

**Comment by aserio** [comment]
@asroy, is this issues still at large?

**Comment by atamazov** [comment]
By #810
