### ISSUE TITLE
[SWDEV-327397] Need to enable HIPRTC by default (revert PR #1470)

### ISSUE THREAD

**Issue by junliume** [ROCmSoftwarePlatform/MIOpen#1512]
hipRTC is disabled for ROCm 5.1

[Potential Impacts]:
1. @atamazov  @JehandadKhan : how would it impact PyTorch wheel?
2. Blocking for future releases. Currently tracked by https://ontrack-internal.amd.com/browse/SWDEV-328784

**Comment by atamazov** [comment]
> how would it impact PyTorch wheel?

There shouldn't be any impact unless COMGR-specific issues arise (no known ones at the moment IIRC).

**Comment by atamazov** [comment]
@junliume Can you please suggest what the `[Mainline]` tag in the title means?

**Comment by junliume** [comment]
@atamazov I just removed the flag. Removing hipRTC support is getting a lot of questions especially from PyTorch side.

**Comment by atamazov** [comment]
@junliume Can you please remind me why we had to disable HIPRTC?

I recommend renaming this to "Enable HIPRTC by default (revert PR #1470 + more?)" or something alike as current title may confuse the reader. Thanks!

**Comment by junliume** [comment]
> @junliume We can dynamically switch from HIPRTC to COMGR when SRIOV is detected. It's easy, except detection maybe.

@atamazov  but it only works at build time not runtime, right? For example, if user does not have hip-clang compiler installed on their nodes and decides to use SRIOV.

**Comment by atamazov** [comment]
It works at run time.

**Comment by junliume** [comment]
@atamazov Mmm ... okay let me try two approaches in parallel then:
1. "detected SRIOV" and enable/disable hipRTC at runtime. CC: @JehandadKhan 
2. Analyze discrepancies when using hipRTC with SRIOV (current WIP).

**Comment by atamazov** [comment]
@junliume 
> 1. "detected SRIOV" and enable/disable hipRTC at runtime.

This can be considered as an improvement of W/A for SRIOV (which is currently simply disables hipRTC), which can be done quickly and may make some of our customers happier)) Then we'll have more time for detailed investigations of hipRTC/SRIOV issue. Does it sound reasonable?

**Comment by junliume** [comment]
re-enabled by #1545
