### ISSUE TITLE
[Navi21] test_conv_ck_igemm_fwd_v6r1_dlops_nchw fails

### ISSUE THREAD

**Issue by Slimakanzer** [ROCmSoftwarePlatform/MIOpen#1516]
FP16, HIP backend

> 59/99 Test #94: test_conv_ck_igemm_fwd_v6r1_dlops_nchw ................***Failed   40.40 sec
>
> build/bin/test_conv2d --half --cmode conv --pmode default --group-count 1 --disable-backward-data --disable-backward-weights --input 128 1024 14 14 --weights 2048 1024 1 1 --batch_size 128 --input_channels 1024 --output_channels 2048 --spatial_dim_elements 14 14 --filter_dims 1 1 --pads_strides_dilations 0 0 2 2 1 1 --trans_output_pads 0 0 --in_layout NCHW --fil_layout NCHW --out_layout NCHW
> 
> Memory access fault by GPU node-1 (Agent handle: 0x10d4e30) on address 0x7f9e8fd8e000. Reason: Page not present or supervisor privilege.

**Comment by atamazov** [comment]
@Slimakanzer Good finding! GPU type, ROCm version, Linux version, AMDGPU driver version? Is it reproducible in our CI?

**Comment by junliume** [comment]
@Slimakanzer @atamazov This issue has been observed recently and not only on Navi21s. It happens occasionally and restart the pipeline most times it will pass. I tested it locally on a Navi21 with 5.1 for both base OS and docker, and it consistently passes.
@asroy @zjing14 @carlushuang AFAIK this is a legacy CK kernel which will be replaced soon?

**Comment by atamazov** [comment]
@junliume 

> This issue has been observed recently and not only on Navi21s. It happens occasionally and restart the pipeline most times it will pass. 

This looks like a stability issue. Added to #1147.

If this error happens on our CI, and we still use 4.3.1 there, then I recommend postponing this until CI is upgraded.
