### ISSUE TITLE
Please enable two factor authentication in your github account

### ISSUE THREAD

**Issue by DeeptimayeeSethi** [ROCmSoftwarePlatform/MIOpen#1526]
@JP-Ellis;@newling;@alvano;@qianfengz;@zpwenjh;@reidkwja;@averinevg;

We are going to enforce two factor authentication in (https://github.com/ROCmSoftwarePlatform/) organization on 29th April, 2022 . 
Since we identified you as outside collaborator for ROCmSoftwarePlatform organization, you need to enable two factor authentication in your github account else you shall be removed from the organization after the enforcement. 
Please skip if already done.

To set up two factor authentication, please go through the steps in below link:

https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/configuring-two-factor-authentication

Please email "Deeptimayee.Sethi@amd.com" for queries

**Comment by junliume** [comment]
@averinevg @qianfengz @zpwenjh  could you confirm if the procedure is implemented in your accounts? I am looking to close this issue by the end of May.

**Comment by qianfengz** [comment]
[AMD Official Use Only - General]

@Liu, ***@***.***>

I have two factor authentication enabled using Microsoft Authenticator


Qianfeng
________________________________

**Comment by zpwenjh** [comment]
@junliume I have two factor authentication enabled too.
