### ISSUE TITLE
[build] How to set HALF_INCLUDE_DIR when build MIOpen with HIP backend

### ISSUE THREAD

**Issue by zjunweihit** [ROCmSoftwarePlatform/MIOpen#153]
Hi 

when I build MIOpen in ROCm 3.0 on Ubuntu18.04.3 env, it requires to set HALF_INCLUDE_DIR for cmake.
How should I set this path? any guide for that?
Thanks.

error log:

$ CXX=/opt/rocm/hcc/bin/hcc cmake .. -DMIOPEN_BACKEND=HIP -DCMAKE_PREFIX_PATH="/opt/rocm/hcc;/opt/rocm/hip" -DCMAKE_INSTALL_PREFIX=/home/zjunwei/mathlib/miopen-lib/
-- Hip compiler flags:  -isystem /opt/rocm-3.1.0/hip/../include   -isystem /opt/rocm-3.1.0/hip/include -isystem /opt/rocm/include  -hc -Wl,--enable-new-dtags -hc -L $<TARGET_FILE_DIR:hcc::mcwamp> -Wl,-rpath $<TARGET_FILE_DIR:hcc::mcwamp> -Wl,--whole-archive  -hc -fPIC -std=c++14 -isystem /opt/rocm/hcc/include  -isystem /opt/rocm/include -ldl  -hc -fPIC -std=c++14 -isystem /opt/rocm/hcc/include  -isystem /opt/rocm/include -Wl,--no-whole-archive -ldl -lm  -hc -fPIC -std=c++14 -isystem /opt/rocm/hcc/include  -isystem /opt/rocm/include
-- hip compiler: /opt/rocm/bin/clang-ocl
-- Build with rocblas
-- Build without scgemm
-- HIP backend selected.
-- extractkernel found: /opt/rocm/hcc/bin/extractkernel
-- AMDGCN assembler: /opt/rocm/hcc/bin/clang
-- Build without miopengemm
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   filesystem
--   system
-- Clang tidy found: 10.0.0svn
-- Clang tidy checks: *,-android-cloexec-fopen,-cert-msc30-c,-bugprone-exception-escape,-cert-env33-c,-cert-msc32-c,-cert-msc50-cpp,-cert-msc51-cpp,-clang-analyzer-alpha.core.CastToStruct,-clang-analyzer-optin.performance.Padding,-clang-diagnostic-deprecated-declarations,-clang-diagnostic-extern-c-compat,-clang-diagnostic-unused-command-line-argument,-cppcoreguidelines-avoid-c-arrays,-cppcoreguidelines-avoid-magic-numbers,-cppcoreguidelines-explicit-virtual-functions,-cppcoreguidelines-init-variables,-cppcoreguidelines-macro-usage,-cppcoreguidelines-non-private-member-variables-in-classes,-cppcoreguidelines-pro-bounds-array-to-pointer-decay,-cppcoreguidelines-pro-bounds-constant-array-index,-cppcoreguidelines-pro-bounds-pointer-arithmetic,-cppcoreguidelines-pro-type-member-init,-cppcoreguidelines-pro-type-reinterpret-cast,-cppcoreguidelines-pro-type-union-access,-cppcoreguidelines-pro-type-vararg,-cppcoreguidelines-special-member-functions,-fuchsia-*,-google-explicit-constructor,-google-readability-braces-around-statements,-google-readability-todo,-google-runtime-int,-google-runtime-references,-hicpp-braces-around-statements,-hicpp-explicit-conversions,-hicpp-no-array-decay,-hicpp-avoid-c-arrays,-hicpp-signed-bitwise,-hicpp-special-member-functions,-hicpp-uppercase-literal-suffix,-hicpp-use-auto,-hicpp-use-equals-default,-hicpp-use-override,-llvm-header-guard,-llvm-include-order,-misc-misplaced-const,-misc-non-private-member-variables-in-classes,-modernize-avoid-c-arrays,-modernize-pass-by-value,-modernize-use-auto,-modernize-use-default-member-init,-modernize-use-equals-default,-modernize-use-trailing-return-type,-modernize-use-transparent-functors,-performance-unnecessary-value-param,-readability-braces-around-statements,-readability-else-after-return,-readability-isolate-declaration,-readability-magic-numbers,-readability-named-parameter,-readability-uppercase-literal-suffix,-readability-convert-member-functions-to-static,-modernize-use-override,-readability-non-const-parameter
-- MIOpen_VERSION= 2.4.0.8000-451df725
-- CMAKE_BUILD_TYPE= Release
-- Librt: /usr/lib/x86_64-linux-gnu/librt.so
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
/home/zjunwei/gitroot/mathlib/MIOpen/speedtests/HALF_INCLUDE_DIR
   used as include directory in directory /home/zjunwei/gitroot/mathlib/MIOpen/speedtests

-- Configuring incomplete, errors occurred!
See also "/home/zjunwei/gitroot/mathlib/MIOpen/build/CMakeFiles/CMakeOutput.log".
See also "/home/zjunwei/gitroot/mathlib/MIOpen/build/CMakeFiles/CMakeError.log".

**Comment by daniellowell** [comment]
@zjunweihit Where and how are you installing MIOpen's dependencies?
Typically I do it like this:

Install minimum deps for building in an ROCm environment:
```
cmake -P install_deps.cmake --minimum --prefix <PATH TO DEPS>
```

Then configure the build dir:
```
CXX=/opt/rocm/hcc/bin/hcc cmake .. -DMIOPEN_BACKEND=HIP -DCMAKE_PREFIX_PATH="/opt/rocm/hcc;/opt/rocm/hip;<PATH TO DEPS>" ..
```

See docs here:
https://rocmsoftwareplatform.github.io/MIOpen/doc/html/install.html

**Comment by zjunweihit** [comment]
@daniellowell Thanks for your reply.
I did forget to add the dep path. However, unfortunately it has save error after setting the dep path.
```
$ CXX=/opt/rocm/hcc/bin/hcc cmake  -DMIOPEN_BACKEND=HIP -DCMAKE_PREFIX_PATH="/opt/rocm/hcc;/opt/rocm/hip;/home/zjunwei/gitroot/mathlib/miopen-dep" -DCMAKE_INSTALL_PREFIX=/home/zjunwei/mathlib/miopen-lib/ ..

-- Hip compiler flags:  -isystem /opt/rocm-3.1.0/hip/../include   -isystem /opt/rocm-3.1.0/hip/include -isystem /opt/rocm/include  -hc -Wl,--enable-new-dtags -hc -L $<TARGET_FILE_DIR:hcc::mcwamp> -Wl,-rpath $<TARGET_FILE_DIR:hcc::mcwamp> -Wl,--whole-archive  -hc -fPIC -std=c++14 -isystem /opt/rocm/hcc/include  -isystem /opt/rocm/include -ldl  -hc -fPIC -std=c++14 -isystem /opt/rocm/hcc/include  -isystem /opt/rocm/include -Wl,--no-whole-archive -ldl -lm  -hc -fPIC -std=c++14 -isystem /opt/rocm/hcc/include  -isystem /opt/rocm/include
-- hip compiler: /home/zjunwei/gitroot/mathlib/miopen-dep/bin/clang-ocl
-- Build with rocblas
-- Build without scgemm
-- HIP backend selected.
-- extractkernel found: /opt/rocm/hcc/bin/extractkernel
-- AMDGCN assembler: /opt/rocm/hcc/bin/clang
-- Build without miopengemm
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   filesystem
--   system
-- Clang tidy found: 10.0.0svn
-- Clang tidy checks:
<snip>
-- MIOpen_VERSION= 2.4.0.8000-451df725
-- CMAKE_BUILD_TYPE= Release
-- Librt: /usr/lib/x86_64-linux-gnu/librt.so
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
/home/zjunwei/gitroot/mathlib/MIOpen/speedtests/HALF_INCLUDE_DIR
   used as include directory in directory /home/zjunwei/gitroot/mathlib/MIOpen/speedtests

-- Configuring incomplete, errors occurred!
See also "/home/zjunwei/gitroot/mathlib/MIOpen/build/CMakeFiles/CMakeOutput.log".
```

* My miopen-dep is below
```
$ cmake -P install_deps.cmake --prefix /home/zjunwei/gitroot/mathlib/miopen-dep
<snip>
$ ~/gitroot/mathlib/miopen-dep» tree -L 2
.
├── bin
│   └── clang-ocl
├── etc
│   └── cget
├── include
│   └── miopengemm
├── lib
│   ├── cmake
│   └── libmiopengemm.so -> ../miopengemm/lib/libmiopengemm.so
├── miopengemm
│   ├── include
│   └── lib
├── share
│   ├── cmake
│   └── rocm
└── tmp
```

**Comment by daniellowell** [comment]
It seems as if you're missing the half dependencies. What is the contents of include folder?
Also, if your environment is a fully installed ROCm environment you can add the `--minimum` to that `cmake -P install_deps.cmake` command so you don't need to install all ROCm components once again.

I would delete the dependency directory and try once again, but with the minimum flag.

**Comment by zjunweihit** [comment]
@daniellowell Thanks for your kind detail info. I have ROCm environment 3.1 installed.
Going to try it with clean folder by `--minimun`.

BTW, if my network cannot access the some webset stably, Is that OK to download them all locally one by one and install them manually?

**Comment by zjunweihit** [comment]
@daniellowell , thanks for your advice. it works well now.
closing the issue.
