### ISSUE TITLE
MIOPEN jenkinsfile fails with method code too large after reboot

### ISSUE THREAD

**Issue by rocm-mici** [ROCmSoftwarePlatform/MIOpen#1542]
solution is to add this in jenkins script console but doesn't survive reboot need to make sure these can be a permanent fix
org.jenkinsci.plugins.pipeline.modeldefinition.parser.RuntimeASTTransformer.SCRIPT_SPLITTING_TRANSFORMATION=true

**Comment by junliume** [comment]
A good approach to start is to delete commented and outdated entries. Expect a PR this week for this.
