### ISSUE TITLE
[OpenCL] Several tests fail for OpenCL backend

### ISSUE THREAD

**Issue by averinevg** [ROCmSoftwarePlatform/MIOpen#1557]
Several tests fail for OpenCL backend:
```
./bin/MIOpenDriver rnn -n 1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1 -m relu -k 51 -H 127 -W 127 -l 1 -F 0 -r 1 -b 0 -p 1 -U 0
Backward Data RNN vanilla: 
/home/user/MIOpen/build/bin/test_rnn_vanilla --float --batch-size 1 --seq-len 51 --vector-len 31 --hidden-size 127 --num-layers 1 --use-dropout 0 --in-mode 1 --bias-mode 0 --dir-mode 1 --rnn-mode 0 --batch-seq 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 
MIOpen Error: /home/user/MIOpen/src/ocl/rnnocl.cpp:4866: GEMM is not supported
```
```
The following tests FAILED:
	 24 - test_gru (Failed)
	 42 - test_rnn_vanilla (Failed)
	 69 - test_rnn_extra (Failed)
	 70 - test_gru_extra (Failed)
```
Branch: 8ecc622c254282a71881a0833182e2a7238dded5

**Comment by junliume** [comment]
@averinevg MIOpenGEMM is not optional for OpenCL backend :) You need to enable this library using the cmake configuration flag `-DMIOPEN_USE_MIOPENGEMM=On`
If it is missing in the documentation, I think we need to fix the documentation too.

**Comment by averinevg** [comment]
@junliume Wouldn't it be better to add this flag automatically for OpenCL, or at least check that it is set?

**Comment by DrizztDoUrden** [comment]
Actually, it is on by default with opencl.

**Comment by DrizztDoUrden** [comment]
Unless it is not installed. And I don't think it is mandatory overall. Only when gemm would be the only applicable solver/whatever.

**Comment by DrizztDoUrden** [comment]
@averinevg do you have miopengemm-dev installed? It looks like MIOpen cmake didn't find it. It should have logged something like `Built without gemm`

**Comment by DrizztDoUrden** [comment]
> Unless it is not installed. And I don't think it is mandatory overall. Only when gemm would be the only applicable solver/whatever.
In that case you would get an error you see for legacy code primitives and something like no applicable solver found for solver primitives.

**Comment by averinevg** [comment]
> @averinevg do you have miopengemm-dev installed? It looks like MIOpen cmake didn't find it. It should have logged something like `Built without gemm`

I don't have it installed

**Comment by DrizztDoUrden** [comment]
I guess, rnn requires any gemm implementation.

**Comment by averinevg** [comment]
In my understanding it should be solved as follows:

- Cmake prints error message and exits
- Or checks if miopengemm installed, and silently add `-DMIOPEN_USE_MIOPENGEMM=On`, or throw an error otherwise
- Or just give a warning and continue execution by disabling some tests

**Comment by junliume** [comment]
@averinevg Yes, it makes perfect sense that we should emit errors when OpenCL backend is selected while miopengemm is not installed.
