### ISSUE TITLE
Unable to locate package miopenkernels

### ISSUE THREAD

**Issue by xiaoyu-work** [ROCmSoftwarePlatform/MIOpen#1563]
Hi,

When I run my training code, I saw a warning: "MIOpen(HIP): Warning [SQLiteBase] Missing system database file: gfx90878.kdb Performance may degrade. Please follow instructions to install: https://github.com/ROCmSoftwarePlatform/MIOpen#installing-miopen-kernels-package", so I was trying to download miopenkernels packages. By running this script: https://github.com/ROCmSoftwarePlatform/MIOpen/blob/develop/utils/install_precompiled_kernels.sh, the package cannot be found:
```
using rocminfo at /usr/bin/rocminfo
sudo apt install -y miopenkernels-gfx908-120pkg
Hit:1 https://packages.microsoft.com/ubuntu/18.04/prod bionic InRelease
Hit:2 http://archive.ubuntu.com/ubuntu focal InRelease
Hit:3 https://repo.radeon.com/amdgpu/22.10.1/ubuntu focal InRelease
Get:4 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Hit:5 http://ppa.launchpad.net/criu/ppa/ubuntu focal InRelease
Get:6 https://repo.radeon.com/rocm/apt/debian ubuntu InRelease [2,603 B]
Hit:7 http://archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:8 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Get:9 https://repo.radeon.com/rocm/apt/debian ubuntu/main amd64 Packages [26.3 kB]
Fetched 143 kB in 1s (143 kB/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
10 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package miopenkernels-gfx908-120pkg
```
 
My image uses rocm/dev-ubuntu-20.04:5.1.1-complete as base image. Is there any missing apt repository for miopenkernels packages?

Thanks

**Comment by junliume** [comment]
Most likely the pre-compiled kernels are not uploaded to the public place for downloads.
@cderb  do you know how to ping Zhongyu for this issue?

**Comment by xiaoyu-work** [comment]
@junliume If it's not public, should the doc update this?

**Comment by junliume** [comment]
@xiaoyu-work  could you try `apt install -y miopenkernels-gfx908-120kdb`?

@JehandadKhan It seems there could be an issue with https://github.com/ROCmSoftwarePlatform/MIOpen/blob/develop/utils/install_precompiled_kernels.sh
or something has changed and this script is not updated
