### ISSUE TITLE
[MIOpenDriver] currently no int8 available solver in most of the cases

### ISSUE THREAD

**Issue by carlushuang** [ROCmSoftwarePlatform/MIOpen#1569]
We should add naive conv to support `int8`, since currently not all configurations will be support in MIOpenDriver. Let naive conv has a fallback to support any cases.

e.g.: ` ./bin/MIOpenDriver convint8 -c 1 -H 24 -W 24 -y 1 -x 1 -k 1 -n 1 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -F 1 -V 1 -i 1 -t 1`

- add `IsInt8()` in `ConvolutionDescriptor`
- let naive conv solver `IsApplicable()` pass if input is int8

cc @jerryyin , please use `IsInt8()` in `IsApplicable()` to check if current is int8 computation in your solver, when this issue is done.

**Comment by aska-0096** [comment]
Got it.

**Comment by aska-0096** [comment]
Close since PR#1572 has been merged.
