### ISSUE TITLE
Errors when running Winograd

### ISSUE THREAD

**Issue by cderb** [ROCmSoftwarePlatform/MIOpen#159]
using commit: 9216cc08e20c56c257862446904ee0c53fa12172
tested on gfx906 60

**environment:**
MIOPEN_LOG_LEVEL=7 
MIOPEN_DEBUG_CONV_GEMM=0 
MIOPEN_DEBUG_CONV_DIRECT=0 
MIOPEN_DEBUG_CONV_IMPLICIT_GEMM=0 
MIOPEN_DEBUG_CONV_FFT=0 
MIOPEN_DEBUG_CONV_SCGEMM=0

**Configs expected to work for Winograd, but failing with 'incorrect parameters':**
```
MIOpenDriver conv -c 256 -H 28 -W 28 -x 3 -y 3 -k 512 -n 32 -p 1 -q 1 -u 1 -v 1 -F 1 -i 1
MIOpenDriver convfp16 -c 256 -H 28 -W 28 -x 3 -y 3 -k 512 -n 32 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -V 1 -t 1 -F 1 -i 1
MIOpenDriver conv -c 256 -H 28 -W 28 -x 3 -y 3 -k 512 -n 32 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -V 1 -t 1 -F 2 -i 1
MIOpenDriver convfp16 -c 256 -H 28 -W 28 -x 3 -y 3 -k 512 -n 32 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -V 1 -t 1 -F 2 -i 1
MIOpenDriver conv -c 32 -H 149 -W 149 -x 3 -y 3 -k 32 -n 32 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -V 1 -t 1 -F 1 -i 1
MIOpenDriver conv -c 32 -H 149 -W 149 -x 3 -y 3 -k 32 -n 32 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -V 1 -t 1 -F 2 -i 1
MIOpenDriver conv -c 64 -H 147 -W 147 -x 3 -y 3 -k 96 -n 32 -p 0 -q 0 -u 2 -v 2 -l 1 -j 1 -V 1 -t 1 -F 2 -i 1
MIOpenDriver conv -c 3 -H 2048 -W 1024 -x 7 -y 7 -k 64 -n 1 -p 3 -q 3 -u 2 -v 2 -l 1 -j 1 -V 1 -t 1 -F 1 -i 1
MIOpenDriver convfp16 -c 3 -H 1030 -W 1030 -x 7 -y 7 -k 64 -n 4 -p 0 -q 0 -u 2 -v 2 -l 1 -j 1 -V 1 -t 1 -F 1 -i 1
MIOpenDriver convfp16 -c 128 -H 28 -W 28 -x 7 -y 7 -k 160 -n 32 -p 1 -q 1 -u 2 -v 2 -l 1 -j 1 -V 1 -t 1 -F 2 -i 1
MIOpenDriver conv -c 512 -H 13 -W 13 -x 3 -y 3 -k 1024 -n 1 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -V 1 -t 1 -F 1 -i 1
MIOpenDriver conv -c 64 -H 512 -W 256 -x 3 -y 3 -k 192 -n 1 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -V 1 -t 1 -F 2 -i 1
```
In the output log, many of the fields are reported as not found in the config table.

shellscript
[winograd_run.txt](https://github.com/ROCmSoftwarePlatform/MIOpen/files/4488467/winograd_run.txt)
output log
[winograd_output.txt](https://github.com/ROCmSoftwarePlatform/MIOpen/files/4488468/winograd_output.txt)

**Comment by JehandadKhan** [comment]
Please clean your user perf db and remove any previously installed system perf db at `/opt/rocm/miopen/share/miopen/db/*` and reinstall MIOpen. That should take care of the fields issue.

**Comment by cderb** [comment]
Yes, that fixes the fields print outs.
The invalid parameters error is still present though.

**Comment by JehandadKhan** [comment]
I am unable to reproduce this, both with OpenCL and HIP backends

**Comment by JehandadKhan** [comment]
The version of MIOpen in the logs is `2.3.0`

**Comment by cderb** [comment]
I ran it again after a fresh build/install with: 9216cc08e20c56c257862446904ee0c53fa12172
removed the .config/miopen direction
made sure miopen.db in rocm directory was latest

[winograd_miopenFreshInstall_noCfgDir.txt](https://github.com/ROCmSoftwarePlatform/MIOpen/files/4490032/winograd_miopenFreshInstall_noCfgDir.txt)

**Comment by cderb** [comment]
I'm not sure what the issue is yet, but It seems there is a way to build MIOpen such that this problem doesn't arise. I'll report again when I find out what the source is.

**Comment by cderb** [comment]
The incorrect parameter error seems to be a result of clang not installing correctly, or being in the wrong directory.
Following the errors to the external interface, we get to src/ocl/gcn_asm_utils.cpp. The failure is at ValidateGcnAssemblerImpl, where the path returned by GetGcnAssemblerPath is tested invalid. It should point to a clang version supporting amdgcn, but in my case it was pointing to an empty directory. This string is normally populated by cmake, but can also be controlled by an environment variable MIOPEN_EXPERIMENTAL_GCN_ASM_PATH (perhaps a sign that this has been a problem). Having re-installed the rocm opencl package and run cmake with a clean build directory multiple times, I suspect that this process is volatile on a system that isn’t sparkly clean.

short:
Winograd wanted to use assembly kernels, but MIOpen didn't find the compiler.
