### ISSUE TITLE
[MLIR] Include directory for libMLIRMIOpen not set correctly when it's installed separate from other dependencies

### ISSUE THREAD

**Issue by krzysz00** [ROCmSoftwarePlatform/MIOpen#1604]
Steps to reproduce (extracted from attempts to simplify MLIR's CI).
1. Install all the requirements _except_ `llvm-project-mlir` (by deleting that line) to `/usr/local` or somewhere else in the global search path
2. Build `llvm-project-mlir` with `-DBUILD_FAT_LIBMLIRMIOPEN=1` and `cmake --install . --component libMLIRMIOpen --prefix /a/directory`
3. `cmake . -G Unix\ Makefiles -B build -DMIOPEN_USE_MLIR=On -DMIOPEN_BACKEND=HIP -DCMAKE_PREFIX_PATH="/a/directory" -DMIOPEN_USER_DB_PATH=${PWD}/build/MIOpenUserDB -DMIOPEN_TEST_FLAGS=\'--verbose\ --disable-verification-cache\' -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_CXX_COMPILER=/opt/rocm/llvm/bin/clang++ -DCMAKE_C_COMPILER=/opt/rocm/llvm/bin/clang`
4. Go to `build` and build `MIOpenDriver`

Expected results:
Either configuring the project fails or building succeeds.

Actual results:
```
/var/kdrewnia/llvm-project-mlir/MIOpen/src/conv/invokers/mlir_impl_gemm.cpp:35:10: fatal error: 'Miir.h' file not found
#include <Miir.h>
```

Potential solutions:
1. The workaround (which I'll be using MLIR-side until we come up with something better): add `-DCMAKE_CXX_FLAGS="/a/directory/include/"` to the CMake arguments
2. Have MLIR actually send in a cmake module defining the flags it wants
3. Update the CMakeFile in MIOpen to find the header file

**Comment by v01dXYZ** [comment]
Hello,

It seems the cmake file solely use `find_library`, which doesn't return any include directory. So maybe it would be necessary to create a cmake package for `MLIR-MIOPEN` or to induce the include directory from the path to library (by doing something sort of `DIRNAME(LIBMLIRMIOPEN)/../include`).

1. MIOPEN CMakeFiles.txt https://github.com/ROCmSoftwarePlatform/MIOpen/blob/8d67ae8b6a84b48debd3f140482b077b104c32dd/CMakeLists.txt#L319
2. MLIR MIOPEN `CMakeFiles.txt` https://github.com/ROCmSoftwarePlatform/llvm-project-mlir/tree/46c93e8018b3491e1b7d3741901055a61ef55b48/mlir/tools/mlir-miopen-lib

**Comment by junliume** [comment]
@jerryyin Could you take on the request from @v01dXYZ ? Thanks!

**Comment by atamazov** [comment]
> So maybe it would be necessary to create a cmake package for MLIR-MIOPEN

I agree with the above recommendation. If this is a way to go, then this ticket should be moved to https://github.com/ROCmSoftwarePlatform/llvm-project-mlir

**Comment by krzysz00** [comment]
Yeah, having MLIR generate a CMake package is probably the cleanest solution - I'll raise an issue on our end to look into it, but keep this open so we have an issue number for when this gets fixed

**Comment by krzysz00** [comment]
Closing as complete
