### ISSUE TITLE
Missing gfx1030_40

### ISSUE THREAD

**Issue by jnordberg** [ROCmSoftwarePlatform/MIOpen#1606]
Getting this warning when using my 6900XT with pytorch:

```
MIOpen(HIP): Warning [SQLiteBase] Missing system database file: gfx1030_40.kdb Performance may degrade. Please follow instructions to install: https://github.com/ROCmSoftwarePlatform/MIOpen#installing-miopen-kernels-package
```

Tried following the instructions as well as building from source but still getting the warning

**Comment by junliume** [comment]
@jnordberg could you please try the following:
```
sudo apt install -y miopenkernels-gfx1030-36kdb
```
then change the name of `gfx1030_36.kdb` to `gfx1030_40.kdb`

This is a temporary workaround and we will fix it in the next release

**Comment by jnordberg** [comment]
I've tried that but still getting the error, is there some other place where I need to rename it as well?

```
$ ll /opt/rocm/miopen/share/miopen/db
total 681M
-rw-r--r-- 1 root root 341M Apr  2 06:35 gfx1030_36.kdb
-rw-r--r-- 1 root root 341M Jun 29 22:57 gfx1030_40.kdb
```

**Comment by junliume** [comment]
CC: @JehandadKhan  strange it does not work even with renamed KDB

I have a W6800 where the CU number is different from 36 too, @jnordberg  could you let me know the minimal steps to reproduce this issue so that I can try from my end too?

**Comment by atamazov** [comment]
@jnordberg 
> I've tried that but still getting the error, is there some other place where I need to rename it as well?
> 
> ```
> -rw-r--r-- 1 root root 341M Jun 29 22:57 gfx1030_40.kdb
> ```

Please notice that this is not an error, but **_warning_**. And copying the system .kdb file (or making a link) _**must**_ resolve issue with .kdb warning message.

Maybe now you see some other warning -- something similar, but related to find-db or perf-db. This should not happen as well, because we have machinery for selection of the closest .fdb and .db files when the number of CUs is "non-standard", and, therefore, warnings should not appear as well.

If you see some warnings after creating *_40.kdb, the PLEASE capture output of MIOpen with `export MIOPEN_LOG_LEVEL=6` and attach to this ticket (drag'n'drop *.txt file into your new comment).

Please also notice even if you do not see warnings, then after hacking filenames the performance still may be somewhat worse than the best possible one (but better than what you see when databases are missing).

**Comment by CapsAdmin** [comment]
I also have this issue (?). I tried copying the kdb file to gfx1030_40.kdb but I get the same warning.

This is some of the output from log level 6 around the warning.

```
MIOpen(HIP): Info2 [SQLiteBase] Initializing In Memory system database file gfx1030_40.kdb
MIOpen(HIP): Info [CreateInMemDb] Unknown database: gfx1030_40.kdb in internal file cache
MIOpen(HIP): Warning [SQLiteBase] Missing system database file: gfx1030_40.kdb Performance may degrade. Please follow instructions to install: https://github.com/ROCmSoftwarePlatform/MIOpen#installing-miopen-kernels-package
MIOpen(HIP): Info [KernDb] database not present
MIOpen(HIP): Info2 [SQLiteBase] Initializing In Memory user database file /home/huggingface/.cache/miopen/2.16.0.31534a6a1/gfx1030_40.ukdb

MIOpen(HIP): Info [SQLiteBase] SQLite does not support WAL
MIOpen(HIP): Info2 [KernDb] Database created successfully
```

This is the entire log
[output.txt](https://github.com/ROCmSoftwarePlatform/MIOpen/files/9509447/output.txt)

For context I'm running stable diffusion in a docker container building an image from prompt. I'm suspicious that there's CPU performance bottleneck as my GPU is active for 15 seconds out of 180 seconds in total. The culprit could be many things, but I thought this warning was part of it.

**Comment by junliume** [comment]
@CapsAdmin are you using pytorch wheel? We are looking into this issue 
https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1709#issuecomment-1220033318

**Comment by CapsAdmin** [comment]
> @CapsAdmin are you using pytorch wheel? We are looking into this issue [#1709 (comment)](https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1709#issuecomment-1220033318)

Yes I think so, I'm not 100% sure. I'm not very familiar with python.

This is how it's setup in the Dockerfile
```dockerfile
FROM tensorflow/tensorflow:latest-gpu
RUN pip install diffusers pillow torch transformers \
  --extra-index-url https://download.pytorch.org/whl/rocm5.1.1
```

I'll look into that discussion and try the solutions

**Comment by atamazov** [comment]
@jnordberg PyTorch wheels shall be self-contained. Therefore, for PyTorch wheels, MIOpen embeds kernel databases during the build. The wheel you are using is missing embedded image of gfx1030_40.kdb. Adding it to the file system won't help. The wheel needs to be rebuilt; see https://github.com/ROCmSoftwarePlatform/MIOpen/blob/develop/doc/src/embed.md.

I recommend requesting for official support for gfx1030 with 40CUs in MIOpen. Currently we support GPUs listed [here](https://docs.amd.com/bundle/ROCm-Getting-Started-Guide-v5.2.3/page/Introduction_to_AMD_ROCm_Getting_Started_Guide_for_Linux.html).

**Comment by xinlipn** [comment]
I'm having similar issues on Ubuntu 20.04.05 LTS

1. when run ./utils/install_precompiled_kernels.sh
Unable to locate package miopen-hip-gfx1030-30kdb

2. when run ./opt/rocm-5.2.0/bin/install_precompiled_kernels.sh
Unable to locate package miopen-hip-gfx1030-60kdb

**Comment by junliume** [comment]
@xinlipn with latest MIOpen, you can use `git lfs --exclude= --include=gfx1030_36.kdb` and then copy the file `src/kernels/gfx1030_36.kdb` to `/opt/rocm/share/miopen/db/`, rename it to `gfx1030_40.kdb`
Please check file size and make sure it is pulled correctly.

**Comment by atamazov** [comment]
@junliume I hate to say this, but AFAICS this ticket is about PyTorch wheel problems with missing db, which [can't be resolved by copying databases](https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1606#issuecomment-1239919712).

The problem described by @xinlipn looks similar but it is actually different -- it's an issue with installing precompiled kernels. Can we move it into dedicated ticket?

**Comment by CapsAdmin** [comment]
After having used [automatic1111's version of stable diffusion](https://github.com/AUTOMATIC1111/stable-diffusion-webui) for a while now and getting a little more familiar with python and the pytorch ecosystem, I just ignore this warning. 

**The inference and training performance is good and on par with other gpus** in the same performance class.

I understand this is very high level and out of scope for you guys, but if you see the warning in a terminal and google it this issue is the first result.

**Comment by Stechnr54** [comment]
having the same issue and output as @xinlipn  , any fixes or does it not affect performance? 
is there any way to suppress this warning?

**Comment by CapsAdmin** [comment]
This warning and long initial load time disappeared after upgrading to pytorch 2.0
