### ISSUE TITLE
Documentation: Keep only one markup language

### ISSUE THREAD

**Issue by v01dXYZ** [ROCmSoftwarePlatform/MIOpen#1610]
Proposition to convert all the restructuredTxt to myST.

Update:
The associated PR actually  converts the rst to md

**Comment by atamazov** [comment]
Motivation (from https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1607#issuecomment-1169369839):

@v01dXYZ 
> It is not necessary to enforce rst. But I thought it would have been an amelioration to only have one markup language for the documentation (there are currently two). We can also enforce `MyST` instead which is as much as powerful as `rst`. I didn't take this path but actually it is the most efficient one as the `api_reference` files are the easiest to change.
> 
> In the two cases, GitHub won't be able to nicely render them.
> 
> The aim of the MR is to simplify as much as possible the docs:
>     * use only one markup language
>     * have an arborescence of files instead of a flat directory
>     * use sphinx directives to ameliorate the way the documentation is rendered.
> 
> I hope it would be helpful if new topics are added to the documentation in the future (such as documenting the assembly files in `src/kernels` or LLVM/MLIR for code generation with custom passes...).

**Comment by atamazov** [comment]
> * use only one markup language

In the documentation, yes. But the developers would need to learn reStructuredText, while Markdown is already well known to all github users. So maybe this point is not an advantage (I am not objecting, just to note)

> * have an arborescence of files instead of a flat directory

This makes it easier for developers to find the right file. However, it will be necessary to come up with unambiguous criteria for placing files on one or another branch of the tree. Does this approach provide any other benefits?

**Comment by v01dXYZ** [comment]
You're right. My suggestions are a little bit too opinionated without strong arguments (file renaming, rst over md).

I should provide instead a small MR that converts the rst to md without anything else.

**Comment by atamazov** [comment]
> Proposition to convert all the markdown files to rst, which means we can fully utilise Sphinx.

Note that the implementation at #1612 does just the opposite. Maybe it worth to update the topmost comment.
