### ISSUE TITLE
GPU dependent MIOpen tests disabled/present without supporting GPU?

### ISSUE THREAD

**Issue by xinlipn** [ROCmSoftwarePlatform/MIOpen#1617]
Had a discussion with Jun, not 100% sure if GPU dependent tasks such as test_activation should be present when no supporting GPU is found. 

Here is the partial list of the results after calling "make check" to initiate tests on a no GPU platform:
.....
Start   1: test_activation
  8/103 Test   #1: test_activation .......................................***Not Run (Disabled)   0.00 sec

....
Start  28: test_include_inliner
 31/103 Test  #28: test_include_inliner ..................................   Passed    0.06 sec

test_include_inliner  in on the SKIP_ALL_EXCEPT_TESTS as shown below, but test_activation is not. 
Here the In MIOpen/test/CmakeLists.txt blurb. 

if (MIOPEN_NO_GPU)

    set(SKIP_ALL_EXCEPT_TESTS test_include_inliner test_kernel_build_params test_lstm test_lstm_dropout

            test_test_errors test_type_name test_tensor_test test_sqlite_perfdb test_sequences

            test_pooling3d test_perfdb)

endif()

**Comment by atamazov** [comment]
> test_include_inliner in on the SKIP_ALL_EXCEPT_TESTS as shown below, but test_activation is not.

And this is why test_include_inliner runs, while test_activation does not. Is there something wrong?

**Comment by atamazov** [comment]
Please feel free to rename `SKIP_ALL_EXCEPT_TESTS` to `SKIP_ALL_EXCEPT_THESE_TESTS` ))

**Comment by junliume** [comment]
Resolved by #1635
