### ISSUE TITLE
[Tests] MIOpen CTest use GPU for verification

### ISSUE THREAD

**Issue by JehandadKhan** [ROCmSoftwarePlatform/MIOpen#1626]
The MIOpen Driver has a mode, where the verification is done on the GPU using naive convolution kernels. A similar functionality in the tests would allow us to improve the performance of our tests and reduce the time required for our CI pipeline.

@atamazov  Can I bother you to take a look at this task? I think this would have a huge impact on developer productivity.

**Comment by atamazov** [comment]
Let me look into this after July 20

**Comment by junliume** [comment]
@JehandadKhan  I think this is at least mostly completed by #1677 shall we close this issue?

**Comment by JehandadKhan** [comment]
Implemented via #1677
