### ISSUE TITLE
MIOPEN/CK fails if /dev/dri and /dev/kfd has render group instead of video

### ISSUE THREAD

**Issue by okakarpa** [ROCmSoftwarePlatform/MIOpen#1636]
MIOPEN/CK CI fails if /dev/dri and /dev/kfd has render group instead of video group on baremetal

For ubuntu-20.04 the default group of /dev/dri and /dev/kfd is render but CI expects them to be in video group causing cliinfo failing the CI.

The reboot job is taking care of changing permissions but the solution isn't ideal.

**Comment by JehandadKhan** [comment]
Then what is the solution?

**Comment by junliume** [comment]
@okakarpa Are we moving forward with this issue?

**Comment by illsilin** [comment]
I haven't observed any CI crashes due to GPU not detected in any of CK branches since last Monday. So as far as CK team is concerned, the issue seems to be resolved.

**Comment by atamazov** [comment]
@okakarpa @junliume Let's try to get some experience out of this. _What has changed?_

**Comment by junliume** [comment]
Has CK updated based OS from 18.04 to 20.04 in the time frame? @illsilin

**Comment by illsilin** [comment]
We are still using the same docker file with Ubuntu 18.04 for CK. 
I suspect the solution was to change the group of the offending folders /dev/dri and /dev/kfd from render to video on all the jenkins nodes that run Ubuntu 20.04.
Is that correct, @okakarpa ?
