### ISSUE TITLE
[driver][pool] #1313 is missing fixes in Pooling_logging_cmd().

### ISSUE THREAD

**Issue by atamazov** [ROCmSoftwarePlatform/MIOpen#1647]
#1313 is missing some changes in `Pooling_logging_cmd()`. Example of symptoms: https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1642#issuecomment-1192114173.

@junliume @DrizztDoUrden This is a bug of normal priority (formally) because it affects debugging only, but...

**Comment by DrizztDoUrden** [comment]
Yeah, I guess, I should just fix that. Missed that completely. At some point we should probably make the args parsing a two-way process so we would be able to reuse it to produce command line without duplicating the logic.

**Comment by atamazov** [comment]
Yes, there is dependence. I missed that too during review.
