### ISSUE TITLE
Issue related to changes in PR [API] NCHWc tensor layout support #1532

### ISSUE THREAD

**Issue by junliume** [ROCmSoftwarePlatform/MIOpen#1653]
issue related to changes in PR [API] NCHWc tensor layout support #1532

https://github.com/ROCmSoftwarePlatform/MIOpen/blob/d19c2575ca918f6b63a022f004d591795afcd85d/driver/conv_driver.hpp#L1278

https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1532/files#diff-2d7eb26c166e89e679bd68a41a7510ac3b8a66c1c2894e9dcf584e40711801ceL1232-L1238

before this PR was called tensor constructor from line:120
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/d19c2575ca918f6b63a022f004d591795afcd85d/test/tensor_holder.hpp#L120-L124

but now we are using constructor from line 164
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/d19c2575ca918f6b63a022f004d591795afcd85d/test/tensor_holder.hpp#L164-L170

so ```Tref=float``` => ```miopen_type<T> = miopen_type<float>```
but  ``(outputTensor type is half )`` => ```(rhs.GetType() = miopen_type<half_float::half>)```
which means 
```(  miopen_type<T> != rhs.GetType() )```

_Originally posted by @shurale-nkn in https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1644#discussion_r931348514_

**Comment by junliume** [comment]
@aska-0096 could you take a look at the above issue found by @shurale-nkn ?

**Comment by aska-0096** [comment]
Hi @junliume
Thanks for found the bug, it seems like I'm not using the debug mode build and the ASSERT was ignored when I developing the this code.
@shurale-nkn shot the bug accurately, let me explain why this not fail the correctness when assertion is suppressed, the failing 3 tensor constructors construct the destination host tensor, feed to the CPU verification part latter. The tensor member hold the data type of `Tref ` and member `std::vector<T> data` resize to the `rhs.GetElementSize()`, a vector with correct data type and element size is created here, that's all what we want in the CPU verification function.
The solution is, just use other tensor constructors to avoid the data type check.
Let me fire a hotfix PR.

**Comment by DrizztDoUrden** [comment]
In most cases it is better to throw than assert if the execution of the following code would be incorrect anyway.

**Comment by aska-0096** [comment]
> In most cases it is better to throw than assert if the execution of the following code would be incorrect anyway.

Thanks for the advice.
Since the issue has been solved, let me close this issue : )

**Comment by atamazov** [comment]
Another post-merge issue found in the same PR:
- [x] https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1532#discussion_r1290451889 - `ValidateGroupCount` fails ~shall observe convolution mode (conv/trans)~.

@junliume Can you please re-open the issue. Same urgency, same assignee. Thanks!

UPDATE: Checkmarked as defect moved to #2459

**Comment by atamazov** [comment]
@junliume Let's move `ValidateGroupCount` related work to #2459 and close this.
