### ISSUE TITLE
[BUG] Incorrect result of GetElementSize

### ISSUE THREAD

**Issue by Slimakanzer** [ROCmSoftwarePlatform/MIOpen#1661]
`TensorDescriptor::GetElementSize()` returns an incorrect result if the tensor size is 2^31 or more. The reason is the `vector_length` type which is an integer and could produce overflow.

https://github.com/ROCmSoftwarePlatform/MIOpen/blob/d70e8730865c542e676fd7d3d93bed26a1a0a2d0/src/include/miopen/tensor.hpp#L249-L250

Case example:
```
./build/bin/MIOpenDriver conv -W 5078 -H 4903 -c 24 -n 5 -k 1 --fil_w 3 --fil_h 3 --pad_w 6 --pad_h 4 -F 1
```

**Comment by aska-0096** [comment]
@Slimakanzer 
Thanks for the bug shooting. 
This a bug related to the NCHWC PR, please feel free to assign it to me.

**Comment by atamazov** [comment]
@junliume @aska-0096 @Slimakanzer This is correctness issue so I recommend `urgency_high` or even blocker.
