### ISSUE TITLE
`ConvCkIgemmFwdV6r1DlopsNchw` should not be marked Dynamic in MIOpen

### ISSUE THREAD

**Issue by JehandadKhan** [ROCmSoftwarePlatform/MIOpen#1738]
The solver `ConvCkIgemmFwdV6r1DlopsNchw` is marked Dynamic in MIOpen, however as [evidenced from here ](https://github.com/ROCmSoftwarePlatform/MIOpen/blob/1d454f6ed6df2dc469dba43bca783df3e2451903/src/composable_kernel/host/solver/include/conv_igemm_fwd_v6r1_dlops_nchw_kcyx_nkhw.hpp#L12) and [used here ](https://github.com/ROCmSoftwarePlatform/MIOpen/blob/1d454f6ed6df2dc469dba43bca783df3e2451903/src/solver/conv_ck_igemm_fwd_v6r1_dlops_nchw.cpp#L166) the solver requires a recompile with every run. 

cc  @asroy

**Comment by asroy** [comment]
It is dynamic kernel, but it has many choices of tile sizes, and each tile size will support many tensor sizes (this is the dynamic part of it), but tile size also needs a separate compilation.

If the kernel is compiled many tiles, it just means each time a different tile size is chosen.

**Comment by atamazov** [comment]
@JehandadKhan Yep, "dynamic kernel" is a fuzzy notion. @asroy How many different kernels this Solver needs in order to cover all the applicable configs?
