### ISSUE TITLE
System freeze when using viewport shading on blender 3D

### ISSUE THREAD

**Issue by jeanmartin13** [ROCmSoftwarePlatform/MIOpen#1756]
I have system freeze when using viewport shading in Blender 3.3 (also 3.2) on high poly objects. Try to open the blend file provided, go in wiewport shading view, cycles render engine GPU enable, and try to rotate the object named body_linux  (using MMB), after a few times the system freezes (ugly scren, can go back to session login screen with several "ctrl-alt-del". Blender devs said that it is not a blender issue but a driver issue. No issue if I use RadeonProRender render engine. You may be able to reproduce the issue with the default cube subdivided 32 ou 64 times.

Happens on all kernel tested : 
- 5.13.0.35 generic and lowlatency
- 5.13.0.51 generic and low-latency
- rocm version : 5.2.3

Ubuntu 20.04.4, Radeon RX 6800XT, mesa kisak drivers.

[dmesg.txt](https://github.com/ROCmSoftwarePlatform/MIOpen/files/9574275/dmesg.txt)
[journalctl-b-1.txt](https://github.com/ROCmSoftwarePlatform/MIOpen/files/9574285/journalctl-b-1.txt)
[aegis_V4_crash.zip](https://github.com/ROCmSoftwarePlatform/MIOpen/files/9574286/aegis_V4_crash.zip)

**Comment by junliume** [comment]
@jeanmartin13 it is likely not (or not only) an MIOpen issue, let's see if I have other channels of escalating it internally.

**Comment by jeanmartin13** [comment]
> @jeanmartin13 it is likely not (or not only) an MIOpen issue, let's see if I have other channels of escalating it internally.

Thanks for your answer. I don't really understand what it means except that I may have opened a ticket in the wrong place and you try to find other channels more related to my issue. As I'm not a developper I just tried to find a rocm related bug report because this bug is really annoying and it seems I'm not the only one experimenting it. 

Anyway thanks a lot to see if you can find a better place to report it !

**Comment by xuhuisheng** [comment]
@jeanmartin13 
The blender cycles use HIP directly, it didn't based on MIOpen.
I think the right place to feedback blender's issue is the blender community.

**Comment by jeanmartin13** [comment]
@xuhuisheng that's what I did first, but they answered that it wasn't a Blender issue but a driver issue...

**Comment by junliume** [comment]
Not MIOpen related and escalated through other channels for related teams
