### ISSUE TITLE
[CK] Integration with the latest composable_kernel project

### ISSUE THREAD

**Issue by zhanglx13** [ROCmSoftwarePlatform/MIOpen#1777]
During the static check stage, the following error occurs (CI build can be found [here](http://micimaster.amd.com/blue/organizations/jenkins/MLLibs%2FMIOpen/detail/find-MLIR/71/pipeline/13))
```
/home/jenkins/workspace/MLLibs_MIOpen_find-MLIR/src/solver/conv_hip_implicit_gemm_fwd_xdlops.cpp:34:10: fatal error: 'ck/library/host/host_interface.hpp' file not found
#include <ck/library/host/host_interface.hpp>
```
The header file in question seems to be removed by this PR: https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/281.

I rebuilt the docker image using the latest commit from composable_kernel project in requirements.txt after some changes, which can be found in PR https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1673.
To reproduce the issue, one needs to modify `Jenkinksfile` to use the docker image: `rocm/miopen:ci_find_MLIR_a6b9a56`.

@junliume @JehandadKhan @asroy please help since this is blocking PR https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1673

The docker image used for CI (`rocm/miopen:ci`) was updated 11 days ago while the commit id of ck in requirements.txt was updated 9 days ago. So the image is not updated when the dependency changes. Maybe it's time to reconsider the proposal: https://github.com/ROCmSoftwarePlatform/MIOpen/discussions/1702.

**Comment by Yanxing-Shi** [comment]
@zhanglx13 As you said, The header file host_interface. hpp removed in this PR [#281](https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/281)
In merged PR [#281](https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1692) Dockerfile
`ARG CK_COMMIT=91d8b7d67ae9dbf8a6e691ea3e17c0b9705c6ba7`
So, you can change can change the composable_kernel commit_id in requirements.txt.
`
ROCmSoftwarePlatform/composable_kernel@91d8b7d67ae9dbf8a6e691ea3e17c0b9705c6ba7 
`

**Comment by zhanglx13** [comment]
@Yanxing-Shi I also noticed in a more recent PR https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1737, the commit id of CK was changed to `7589116121f80189f47cfd8692f300ee8c6377ad` and @junliume requested to change CK's commit id to a more recent one in [here](https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1733#issuecomment-1235792832).
Does it mean MIOpen decided to bound with the old CK commit id that still has `host_interface.cpp` present?

**Comment by Yanxing-Shi** [comment]
@zhanglx13 
- Sorry, I hadn't noticed that before. Because the CK's code corresponding to the commit id `7589116121f80189f47cfd8692f300ee8c6377ad`no longer has the `host_interface.hpp`, your PR [#1673](https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1673) didn't go through.
-  If use CK's more recent commit id, the integration with the CK project some modifications are required for the latest CK's code, this needs to be decided by @junliume @JehandadKhan.
