### ISSUE TITLE
[gfx908][ROCm 5.3][SWDEV-353150] Soft hang with test_miopendriver_big_tensor

### ISSUE THREAD

**Issue by junliume** [ROCmSoftwarePlatform/MIOpen#1787]
**[Symptoms]**:
https://ontrack-internal.amd.com/browse/SWDEV-353150
http://micimaster.amd.com/blue/organizations/jenkins/MLLibs%2FMIOpen/detail/ci_rocm530_ubuntu2004/8/pipeline/1391/

This issue is a regression, when base OS and docker ROCM versions are both ROCm5.2 it worked as expected. However, when the baseOS is still ROCm 5.2 and docker ROCM is 5.3 we have **soft hang** with:
```
export MIOPEN_ENABLE_LOGGING=1
export MIOPEN_ENABLE_LOGGING_CMD=1
export MIOPEN_LOG_LEVEL=6
MIOPEN_DRIVER_USE_GPU_REFERENCE=1 ./bin/MIOpenDriver conv -W 5078 -H 4903 -c 24 -n 5 -k 1 --fil_w 3 --fil_h 3 --pad_w 6 --pad_h 4 -F 1
```

The same configuration still works on gfx90a and gfx1030

**[Discussions}**:
The test itself was introduced here:
https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1679

@aska-0096  could you investigate what might be causing the soft hang?

**Comment by junliume** [comment]
@aska-0096 @carlushuang  actually, I see that the process is stuck at verification phase: 
[rocm530.log](https://github.com/ROCmSoftwarePlatform/MIOpen/files/9650438/rocm530.log)
Do you know why it is using `miopenConvolutionFwdAlgoImplicitGEMM`?
```
MIOpen(HIP): Command [LogCmdConvolution] ./bin/MIOpenDriver conv -n 5 -c 24 -H 4903 -W 5078 -k 1 -y 3 -x 3 -p 4 -q 6 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -F 1 -t 1
MIOpen(HIP): Info [ConvolutionForward] algo = 5, workspace = 11950769408
MIOpen(HIP): Info2 [GetInvoker] Returning an invoker for problem 24x4903x5078x3x3x1x4909x5088x5xNCHWxFP32x4x6x1x1x1x1x1xF and algorithm miopenConvolutionFwdAlgoImplicitGEMM

**Comment by junliume** [comment]
[rocm530.log](https://github.com/ROCmSoftwarePlatform/MIOpen/files/9650489/rocm530.log)
[rocm523.log](https://github.com/ROCmSoftwarePlatform/MIOpen/files/9650491/rocm523.log)

**Comment by aska-0096** [comment]
it looks very strange that in rocm5.3:
```
MIOpen(HIP): miopenStatus_t miopenGetNdTensorDescriptorVectorLength(miopenTensorDescriptor_t, std::size_t *){
MIOpen(HIP): 	tensorDesc = 1, 24, 3, 3
MIOpen(HIP): 	vectorLength = 24
MIOpen(HIP): }
```
while the vectorLength should be 1 because it is not a vectorized tensor. Let me why it becomes that

**Comment by junliume** [comment]
> it looks very strange that in rocm5.3:
> 
> ```
> MIOpen(HIP): miopenStatus_t miopenGetNdTensorDescriptorVectorLength(miopenTensorDescriptor_t, std::size_t *){
> MIOpen(HIP): 	tensorDesc = 1, 24, 3, 3
> MIOpen(HIP): 	vectorLength = 24
> MIOpen(HIP): }
> ```
> 
> ~while the vectorLength should be 1 because it is not a vectorized tensor. Let me why it becomes that~ The above is just log info mistake, this part is safe, still trying to figure out why only failed on gfx908.
> 
> BTW, compilation cost much more time than 2 or 3 months ago, is there any method could speed-up it? cc: @junliume @atamazov

@aska-0096  which part is taking too long to compile? If you are pulling the `rocm/miopen:ci_rocm530_ubuntu2004` docker, you do not need to build the dependencies such as CK or MLIR, building MIOpen itself should be really quick.

**Comment by junliume** [comment]
@aska-0096 could you check the following?
In the failed case:
`Info2 [PrepareInvoker] Preparing kernel: naive_conv_fwd_nchw_float_double_float`
while in the passing case:
`Info2 [PrepareInvoker] Preparing kernel: naive_conv_fwd_nchw_fp32`

**Comment by aska-0096** [comment]
> @aska-0096 could you check the following? In the failed case: `Info2 [PrepareInvoker] Preparing kernel: naive_conv_fwd_nchw_float_double_float` while in the passing case: `Info2 [PrepareInvoker] Preparing kernel: naive_conv_fwd_nchw_fp32`

Hi @junliume , this part is related to GPU verification kernel, I think it's less possible to hang here because the issue still exist with CPU verification

**Comment by aska-0096** [comment]
Hi @junliume 
I've found the root cause is:
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/ad9779dede0a36d86013ddf86fafe31998c3fc5c/driver/conv_driver.hpp#L1902

It's observed out of memory fault when code try allocate workspace size to `workspace_dev `unique_ptr. 
`[hiperror](2) fail to call hipMalloc(static_cast<void**>(&buf), data_sz * sz),(out of memory)`
However, it should not have this kind of problem since the total memory usage, input tensor, output tensor weight tensor cose ~18 Gigabyte and workspace is ~12 Gigabyte, totally under mi100's 32 Gigabyte limitation.

I've try several ways to find where the problem is and checked that:
1. MIOPEN_FIND_MODE=1, 3, 5 all failed in same place.
2. Try to disable the correspond solver by `export MIOPEN_DEBUG_CONV_IMPLICIT_GEMM_ASM_FWD_GTC_XDLOPS_NHWC=0` -> Segmentation fault
3. Add print function in everywhere `hipMalloc ` and `hipFree` appeared, checked they were function well until last hit to `hipMalloc` (out of memory)

Unfortunately, I've not find a way to fix it, I think we should find a memory system specialist to debug this issue.

cc. @atamazov @JehandadKhan

**Comment by junliume** [comment]
> Reference

@aska-0096 thanks! Can we establish a minimal example about the exact line? So that we can issue a ticket to runtime.

**Comment by aska-0096** [comment]
@junliume 
Hi Jun. I have not find a way to reproduce this issue in a standalone hip file until now.
However I have found a related hip API issue during my debug experiment, the `hipMemGetInfo()` not works correctly on both ROCm 5.3.0 and ROCm 5.4.0.10738, it works well on ROCm 5.0.0 using this example file.
[get_meminfo.hip.cpp.zip](https://github.com/ROCmSoftwarePlatform/MIOpen/files/9670412/get_meminfo.hip.cpp.zip)

**HIP memory management experiment on gfx908, 32 GB Memory:**

-  ROCm 5.0.0 
```
total----------AvailableMem size: 34342961152
After static allocation----------AvailableMem size: 21823210496
After dynamic allocation----------AvailableMem size: 9303460864
buffer address:0x7f2500000000
After dynamic free----------AvailableMem size: 21823210496
After dynamic allocation----------AvailableMem size: 9303460864
buffer address:0x7f2500000000
After dynamic free----------AvailableMem size: 21823210496
After dynamic allocation----------AvailableMem size: 9303460864
buffer address:0x7f2500000000
After dynamic free----------AvailableMem size: 21823210496
After dynamic allocation----------AvailableMem size: 9303460864
buffer address:0x7f2500000000
After dynamic free----------AvailableMem size: 21823210496
After dynamic allocation----------AvailableMem size: 9303460864
buffer address:0x7f2500000000
After dynamic free----------AvailableMem size: 21823210496
```
Here total 34342961152 Bytes ~32 GB, output as expected during repeated `hipMalloc()` and `hipFree()`
- ROCm 5.3.0
```
Total----------AvailableMem size: 140735806818304
Static allocation----------AvailableMem size: 140735806818304
Dynamic allocation----------AvailableMem size: 140735806818304
buffer address:0x7f00b7000000
Dynamic free----------AvailableMem size: 140735806818304
Dynamic allocation----------AvailableMem size: 140735806818304
buffer address:0x7f00b7000000
Dynamic free----------AvailableMem size: 140735806818304
Dynamic allocation----------AvailableMem size: 140735806818304
buffer address:0x7f00b7000000
Dynamic free----------AvailableMem size: 140735806818304
```
AvailableMem size is over 100 TB and never changed during Repeated memory allocation and free, obvious wrong.
- ROCm 5.4.0.10738
```
140725798761472total----------AvailableMem size: 140725798761472
140725798761472After static allocation----------AvailableMem size: 140725798761472
140725798761472After dynamic allocation----------AvailableMem size: 140725798761472
buffer address:0x7fc2dde00000
140725798761472After dynamic free----------AvailableMem size: 140725798761472
140725798761472After dynamic allocation----------AvailableMem size: 140725798761472
buffer address:0x7fc2dde00000
140725798761472After dynamic free----------AvailableMem size: 140725798761472
```
AvailableMem size is over 100 TB and never changed during Repeated memory allocation and free, obvious wrong.

**Another thing**
From my experiment on hip memory management API, we can say there are something wrong inside, and cause MIOpen memory allocation guarder( use `hipMemGetInfo()` ) fail to throw the error. Although this API is broken, we can still find some meaningful phenomenon:

```
-MIOPEN-DRIVER----------buffer allocated size:11857824000
-MIOPEN-DRIVER----------AvailableMem size: 3472328313441629184
-MIOPEN-DRIVER----------buffer allocated: 0x7f45fb600000, size:11857824000
-MIOPEN-DRIVER----------buffer allocated size:864
-MIOPEN-DRIVER----------AvailableMem size: 3762256111365783552
-MIOPEN-DRIVER----------buffer allocated: 0x7f5094400000, size:864
-MIOPEN-DRIVER----------buffer allocated size:495664120
-MIOPEN-DRIVER----------AvailableMem size: 3472892362973656064
-MIOPEN-DRIVER----------buffer allocated: 0x7f45d9200000, size:495664120
-----------------Enter Target Point---------------------
-----------------Enter FindForward---------------------
-workspace-dev-reseted----------AvailableMem size: 1879405568
-MIOPEN-DRIVER----------buffer allocated size:11857825024
-MIOPEN-DRIVER----------AvailableMem size: 3761121643841729536
-MIOPEN-DRIVER----------buffer allocated: 0x7f4316200000, size:11857825024
```
Just focus on the log line start with `-MIOPEN-DRIVER----------AvailableMem size:`, the value is not correct but it changed, from a weird value to a weird value, and just before `hipMalloc()` failed:
```
-workspace-dev-reseted----------AvailableMem size: 0
-MIOPEN-DRIVER----------buffer allocated size:11857825024
-MIOPEN-DRIVER----------AvailableMem size: 3761121643841729536
[hiperror](2) fail to call hipMalloc(static_cast<void**>(&buf), data_sz * sz),(out of memory)
```
`-workspace-dev-reseted----------AvailableMem size: 0` 
is output after release the memory hold by `workspace_dev `unique_ptr `workspace_dev.reset();` , strange right? 

Then we call `workspace_dev = std::unique_ptr<GPUMem>(new GPUMem(ctx, size, 1));` a `GPUMem `object will be created via its constructor:
```
GPUMem(uint32_t ctx, size_t psz, size_t pdata_sz) : _ctx(ctx), sz(psz), data_sz(pdata_sz)
    {
        std::cout<<"-MIOPEN-DRIVER----------buffer allocated size:"<<(data_sz * sz)<<std::endl<<std::flush;
        size_t free, total;
        auto status = hipMemGetInfo(&free, &total);
        if(status != hipSuccess)
            MIOPEN_THROW_HIP_STATUS(status, "Failed getting available memory");
        std::cout<<"-MIOPEN-DRIVER----------AvailableMem size: "<<free<<std::endl<<std::flush;
        HIP_CALL(hipMalloc(static_cast<void**>(&buf), data_sz * sz));
        std::cout<<"-MIOPEN-DRIVER----------buffer allocated: "<<buf<<", size:"<<(data_sz * sz)<<std::endl<<std::flush;
    }
```

A more strange thing 
`-MIOPEN-DRIVER----------AvailableMem size: 3761121643841729536` 
outputed before we try to call a `hipMalloc()` inside this constructor, the `AvailableMem size` change back from 0 to a weird number.

**What we can learn from this issue**
The root cause is HIP memory management but we MIOpen also need a HIP API call guarder like `HIP_CALL` macro used in MISA, this kind of call guarder can help us locate the bug.
```
#define HIP_CALL(call)                                                         \
    do {                                                                       \
        hipError_t err = call;                                                 \
        if (err != hipSuccess) {                                               \
            printf("[hiperror](%d) fail to call %s,(%s)", (int)err, #call,     \
                   hipGetErrorString(err));                                    \
            exit(1);                                                           \
        }                                                                      \
    } while (0)
```
cc @JehandadKhan @atamazov

**Comment by junliume** [comment]
> @junliume Hi Jun. I have not find a way to reproduce this issue in a standalone hip file until now. However I have found a related hip API issue during my debug experiment, the `hipMemGetInfo()` not works correctly on both ROCm 5.3.0 and ROCm 5.4.0.10738, it works well on ROCm 5.0.0 using this example file. [get_meminfo.hip.cpp.zip](https://github.com/ROCmSoftwarePlatform/MIOpen/files/9670412/get_meminfo.hip.cpp.zip)
> 
> **HIP memory management experiment on gfx908, 32 GB Memory:**
> 
> * ROCm 5.0.0
> 
> ```
> total----------AvailableMem size: 34342961152
> After static allocation----------AvailableMem size: 21823210496
> After dynamic allocation----------AvailableMem size: 9303460864
> buffer address:0x7f2500000000
> After dynamic free----------AvailableMem size: 21823210496
> After dynamic allocation----------AvailableMem size: 9303460864
> buffer address:0x7f2500000000
> After dynamic free----------AvailableMem size: 21823210496
> After dynamic allocation----------AvailableMem size: 9303460864
> buffer address:0x7f2500000000
> After dynamic free----------AvailableMem size: 21823210496
> After dynamic allocation----------AvailableMem size: 9303460864
> buffer address:0x7f2500000000
> After dynamic free----------AvailableMem size: 21823210496
> After dynamic allocation----------AvailableMem size: 9303460864
> buffer address:0x7f2500000000
> After dynamic free----------AvailableMem size: 21823210496
> ```
> 
> Here total 34342961152 Bytes ~32 GB, output as expected during repeated `hipMalloc()` and `hipFree()`
> 
> * ROCm 5.3.0
> 
> ```
> Total----------AvailableMem size: 140735806818304
> Static allocation----------AvailableMem size: 140735806818304
> Dynamic allocation----------AvailableMem size: 140735806818304
> buffer address:0x7f00b7000000
> Dynamic free----------AvailableMem size: 140735806818304
> Dynamic allocation----------AvailableMem size: 140735806818304
> buffer address:0x7f00b7000000
> Dynamic free----------AvailableMem size: 140735806818304
> Dynamic allocation----------AvailableMem size: 140735806818304
> buffer address:0x7f00b7000000
> Dynamic free----------AvailableMem size: 140735806818304
> ```
> 
> AvailableMem size is over 100 TB and never changed during Repeated memory allocation and free, obvious wrong.
> 
> * ROCm 5.4.0.10738
> 
> ```
> 140725798761472total----------AvailableMem size: 140725798761472
> 140725798761472After static allocation----------AvailableMem size: 140725798761472
> 140725798761472After dynamic allocation----------AvailableMem size: 140725798761472
> buffer address:0x7fc2dde00000
> 140725798761472After dynamic free----------AvailableMem size: 140725798761472
> 140725798761472After dynamic allocation----------AvailableMem size: 140725798761472
> buffer address:0x7fc2dde00000
> 140725798761472After dynamic free----------AvailableMem size: 140725798761472
> ```
> 
> AvailableMem size is over 100 TB and never changed during Repeated memory allocation and free, obvious wrong.
> 
> **Another thing** From my experiment on hip memory management API, we can say there are something wrong inside, and cause MIOpen memory allocation guarder( use `hipMemGetInfo()` ) fail to throw the error. Although this API is broken, we can still find some meaningful phenomenon:
> 
> ```
> -MIOPEN-DRIVER----------buffer allocated size:11857824000
> -MIOPEN-DRIVER----------AvailableMem size: 3472328313441629184
> -MIOPEN-DRIVER----------buffer allocated: 0x7f45fb600000, size:11857824000
> -MIOPEN-DRIVER----------buffer allocated size:864
> -MIOPEN-DRIVER----------AvailableMem size: 3762256111365783552
> -MIOPEN-DRIVER----------buffer allocated: 0x7f5094400000, size:864
> -MIOPEN-DRIVER----------buffer allocated size:495664120
> -MIOPEN-DRIVER----------AvailableMem size: 3472892362973656064
> -MIOPEN-DRIVER----------buffer allocated: 0x7f45d9200000, size:495664120
> -----------------Enter Target Point---------------------
> -----------------Enter FindForward---------------------
> -workspace-dev-reseted----------AvailableMem size: 1879405568
> -MIOPEN-DRIVER----------buffer allocated size:11857825024
> -MIOPEN-DRIVER----------AvailableMem size: 3761121643841729536
> -MIOPEN-DRIVER----------buffer allocated: 0x7f4316200000, size:11857825024
> ```
> 
> Just focus on the log line start with `-MIOPEN-DRIVER----------AvailableMem size:`, the value is not correct but it changed, from a weird value to a weird value, and just before `hipMalloc()` failed:
> 
> ```
> -workspace-dev-reseted----------AvailableMem size: 0
> -MIOPEN-DRIVER----------buffer allocated size:11857825024
> -MIOPEN-DRIVER----------AvailableMem size: 3761121643841729536
> [hiperror](2) fail to call hipMalloc(static_cast<void**>(&buf), data_sz * sz),(out of memory)
> ```
> 
> `-workspace-dev-reseted----------AvailableMem size: 0` is output after release the memory hold by `workspace_dev `unique_ptr `workspace_dev.reset();` , strange right?
> 
> Then we call `workspace_dev = std::unique_ptr<GPUMem>(new GPUMem(ctx, size, 1));` a `GPUMem `object will be created via its constructor:
> 
> ```
> GPUMem(uint32_t ctx, size_t psz, size_t pdata_sz) : _ctx(ctx), sz(psz), data_sz(pdata_sz)
>     {
>         std::cout<<"-MIOPEN-DRIVER----------buffer allocated size:"<<(data_sz * sz)<<std::endl<<std::flush;
>         size_t free, total;
>         auto status = hipMemGetInfo(&free, &total);
>         if(status != hipSuccess)
>             MIOPEN_THROW_HIP_STATUS(status, "Failed getting available memory");
>         std::cout<<"-MIOPEN-DRIVER----------AvailableMem size: "<<free<<std::endl<<std::flush;
>         HIP_CALL(hipMalloc(static_cast<void**>(&buf), data_sz * sz));
>         std::cout<<"-MIOPEN-DRIVER----------buffer allocated: "<<buf<<", size:"<<(data_sz * sz)<<std::endl<<std::flush;
>     }
> ```
> 
> A more strange thing `-MIOPEN-DRIVER----------AvailableMem size: 3761121643841729536` outputed before we try to call a `hipMalloc()` inside this constructor, the `AvailableMem size` change back from 0 to a weird number.
> 
> **What we can learn from this issue** The root cause is HIP memory management but we MIOpen also need a HIP API call guarder like `HIP_CALL` macro used in MISA, this kind of call guarder can help us locate the bug.
> 
> ```
> #define HIP_CALL(call)                                                         \
>     do {                                                                       \
>         hipError_t err = call;                                                 \
>         if (err != hipSuccess) {                                               \
>             printf("[hiperror](%d) fail to call %s,(%s)", (int)err, #call,     \
>                    hipGetErrorString(err));                                    \
>             exit(1);                                                           \
>         }                                                                      \
>     } while (0)
> ```
> 
> cc @JehandadKhan @atamazov

Well done! Please create a JIRA ticket so that I can assign to related component :) Thanks!

**Comment by aska-0096** [comment]
Hi @junliume , JIRA ticket is created: https://ontrack-internal.amd.com/browse/SWDEV-359453
please feel free to modify its ticket description if any inappropriate.

cc @carlushuang
