### ISSUE TITLE
Does MIOpen in ROCm >= 5.2.3 still depend on boost 1.72.0?

### ISSUE THREAD

**Issue by dipietrantonio** [ROCmSoftwarePlatform/MIOpen#1797]
In your documentation, version 1.72.0 of boost is explicitly requested. It has been like that for a while. As the title says, can later versions of boost be used to install MIOpen from source?

**Comment by junliume** [comment]
Hi @dipietrantonio from the readme file:
```
Version 1.79 is recommended, older version may need patches to work on newer systems, e.g. boost1{69,70,72} w/glibc-2.34
```
the documentation needs to be updated in the next release.

**Comment by junliume** [comment]
@JehandadKhan could you re-assign some one on updating the following page:
https://rocmsoftwareplatform.github.io/MIOpen/doc/html/install.html?highlight=boost

**Comment by dipietrantonio** [comment]
Thank you for your reply! Looking forward to trying rocm5.3

**Comment by junliume** [comment]
> Thank you for your reply! Looking forward to trying rocm5.3

Let us know if you have any questions! :)

**Comment by dipietrantonio** [comment]
Hi @junliume, Indeed I have one more question, but not related to this issue in particular. Do you know anything about building LLVM with OpenMP offloading support?

https://github.com/RadeonOpenCompute/ROCm/issues/1822

**Comment by junliume** [comment]
> Hi @junliume, Indeed I have one more question, but not related to this issue in particular. Do you know anything about building LLVM with OpenMP offloading support?
> 
> [RadeonOpenCompute/ROCm#1822](https://github.com/RadeonOpenCompute/ROCm/issues/1822)

We have asked internal teams to take a look at that ticket, it is not related to MIOpen while we will find relative support for it.

**Comment by dipietrantonio** [comment]
Thanks, I have been provided with useful links that helped me finding the solution.

Best regards,
Cristian
