### ISSUE TITLE
Porting Guide must be revised.

### ISSUE THREAD

**Issue by atamazov** [ROCmSoftwarePlatform/MIOpen#1815]
- https://github.com/ROCmSoftwarePlatform/MIOpen/blob/develop/doc/src/MIOpen_Porting_Guide.md#the-key-differences-between-miopen-and-cudnn section is seriously outdated
- https://github.com/ROCmSoftwarePlatform/MIOpen/blob/develop/doc/src/MIOpen_Porting_Guide.md#helpful-miopen-environment-variables
  - duplicates info from [DebugAndLogging.md](https://github.com/ROCmSoftwarePlatform/MIOpen/blob/develop/doc/src
  - outdated (e.g. description of MIOPEN_DEBUG_AMD_ROCM_PRECOMPILED_BINARIES is incorrect)
  - incomplete

I recommend revising the whole document when time permits.

----
_Originally posted by @atamazov in https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1633#discussion_r989404587_

**Comment by atamazov** [comment]
@junliume `urgency_low`, `documentation`

**Comment by atamazov** [comment]
The topmost comment updated.

[attribution] @junliume @johnny-keker https://github.com/ROCmSoftwarePlatform/MIOpen/labels/urgency_normal https://github.com/ROCmSoftwarePlatform/MIOpen/labels/value_middle

**Comment by ppanchad-amd** [comment]
@atamazov Internal ticket has been created to fix documentation. Thanks!
