### ISSUE TITLE
How should I use the batchnormalization kernel?

### ISSUE THREAD

**Issue by MOLOjl** [ROCmSoftwarePlatform/MIOpen#1819]
Hi, the code below got an error as "Segmentation fault (core dumped)", I checked the parameters, but they seems all right, I counldn't fix this bug, please help me.
```c++
#include "miopen/miopen.h"
#include <hip/hip_runtime.h>

// hipcc bn.cpp -o bn -lMIOpen -I/opt/rocm/include -L/opt/rocm/lib
int main(){
    float *src1, *dst1;
    miopenTensorDescriptor_t src_d1, dst_d1, _bnScaleBiasMeanVarDesc;
    
    hipMalloc(&src1, 10*3*224*224*sizeof(float));
    hipMemset(src1, 1, 10*3*224*224*sizeof(float));
    hipMalloc(&dst1, 10*3*224*224*sizeof(float));
    hipMemset(dst1, 1, 10*3*224*224*sizeof(float));

    miopenCreateTensorDescriptor(&src_d1);
    miopenCreateTensorDescriptor(&dst_d1);
    miopenSet4dTensorDescriptor(src_d1, miopenFloat, 10, 3, 224, 224);
    miopenSet4dTensorDescriptor(dst_d1, miopenFloat, 10, 3, 224, 224);

    // derive bntensordesc
    miopenCreateTensorDescriptor(&_bnScaleBiasMeanVarDesc);
    auto status = miopenDeriveBNTensorDescriptor(_bnScaleBiasMeanVarDesc, src_d1, miopenBNSpatial);
    
    float alpha = 1.0f;
    float beta = 0;
    float alpha1 = 1.0f;
    float beta1 = 0;
    miopenHandle_t handle;
    
    miopenBatchNormalizationForwardInference(handle, miopenBNSpatial, &alpha, &beta, src_d1, src1,
                                             dst_d1, dst1, _bnScaleBiasMeanVarDesc,
                                             &alpha, &beta, NULL, NULL, 0.001);
}
```
My environment is:
```
AMD DCU Vega 20 [Radeon VII]
ubuntu 20.04
rocm v4.5.2
miopen v2.14
```

**Comment by junliume** [comment]
@muralinr could you take a look at the above issue? CC: @zjing14

**Comment by muralinr** [comment]
It looks like "alpha and beta" are sent two times in the called API .  They should be used like below. Can you please use API like below and let me know if you see this issue? 

miopenBatchNormalizationForwardInference(handle, miopenBNSpatial, &alpha, &beta, src_d1, src1,
                                             dst_d1, dst1, _bnScaleBiasMeanVarDesc,
                                              NULL, NULL, 0.001);

**Comment by MOLOjl** [comment]
@muralinr
This function needs 14 arguments, providing 12 will cause the below error.
```shell
bn.cpp:41:5: error: no matching function for call to 'miopenBatchNormalizationForwardInference'
    miopenBatchNormalizationForwardInference(handle, miopenBNSpatial, &alpha, &beta, src_d1, src1,
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/rocm/include/miopen/miopen.h:2399:1: note: candidate function not viable: requires 14 arguments, but 12 were provided
miopenBatchNormalizationForwardInference(miopenHandle_t handle,
^
1 error generated when compiling for gfx906.
```
I tried to use other alpha and beta arguments, but they still don't work.
```c
miopenBatchNormalizationForwardInference(handle, miopenBNSpatial, &alpha, &beta, src_d1, src1,
                                         dst_d1, dst1, _bnScaleBiasMeanVarDesc,
                                         &alpha1, &beta1, NULL, NULL, 0.001);
```

**Comment by muralinr** [comment]
> @muralinr This function needs 14 arguments, providing 12 will cause the below error.
> 
> ```shell
> bn.cpp:41:5: error: no matching function for call to 'miopenBatchNormalizationForwardInference'
>     miopenBatchNormalizationForwardInference(handle, miopenBNSpatial, &alpha, &beta, src_d1, src1,
>     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /opt/rocm/include/miopen/miopen.h:2399:1: note: candidate function not viable: requires 14 arguments, but 12 were provided
> miopenBatchNormalizationForwardInference(miopenHandle_t handle,
> ^
> 1 error generated when compiling for gfx906.
> ```
> 
> I tried to use other alpha and beta arguments, but they still don't work.
> 
> ```c
> miopenBatchNormalizationForwardInference(handle, miopenBNSpatial, &alpha, &beta, src_d1, src1,
>                                          dst_d1, dst1, _bnScaleBiasMeanVarDesc,
>                                          &alpha1, &beta1, NULL, NULL, 0.001);
> ```

This is on old code base.  Can you please upgrade to the latest ROCM release and use API as mentioned in the release?

**Comment by MOLOjl** [comment]
I checked the `miopen.h` file in this repository, and only find one function named `miopenBatchNormalizationForwardInference()`, which takes 14 arguments.
I don't understand why I need to update my ROCm since I'm using the API from MIOpen, I'm not the manager of the server I'm using, there are other people who also use this server.  So upgrading ROCm is a risky attempt and may affect other people's work.
I thought this API should work well on the old version ROCm, as I know, the latest ROCm(v5.3) is just released recently and MIOpen is a library that appeared years ago.
Is there some benchmark or examples that use this API, I still thought there are something missing in my code.

**Comment by muralinr** [comment]
> I checked the `miopen.h` file in this repository, and only find one function named `miopenBatchNormalizationForwardInference()`, which takes 14 arguments. I don't understand why I need to update my ROCm since I'm using the API from MIOpen, I'm not the manager of the server I'm using, there are other people who also use this server. So upgrading ROCm is a risky attempt and may affect other people's work. I thought this API should work well on the old version ROCm, as I know, the latest ROCm(v5.3) is just released recently and MIOpen is a library that appeared years ago. Is there some benchmark or examples that use this API, I still thought there are something missing in my code.

As you said, MIOpen library is years ago.  I will find machine with your configuration on Vega20 and reproduce this issue.  I will update you once I reproduce it.

**Comment by junliume** [comment]
@MOLOjl greetings! MIOpen is part of ROCm release, so if you are using and older version of ROCm but building the latest MIOpen library in it we may encounter compatibility issues.

@JehandadKhan and @atamazov  could you help to check if the API has changed recently?

**Comment by MOLOjl** [comment]
@junliume Thanks for your attention!
I didn't build the MIOpen library from the source code, it was installed while I was installing the ROCm, like this:
```shell
sudo apt-get install ./amdgpu-install_21.40.2.40502-1_all.deb
```
I mean my MIOpen library was bonded with the ROCm, I don't think there exist some version issues between them.

**Comment by muralinr** [comment]
I reproduced this issue. Crash is happening in recently introduced batchnorm solver code.  This is not reaching batchnorm OCL kernel code.  I will ask Kamil @shurale-nkn to look at this issue who made batchnorm solver code.

**Comment by atamazov** [comment]
@DrizztDoUrden maybe you can have a look at this, too.

**Comment by JehandadKhan** [comment]
Hello @MOLOjl,

Thanks for your interest in MIOpen. Can you please update your code so that it actually creates the MIOpen Handle.

```C++
#include "miopen/miopen.h"
#include <hip/hip_runtime.h>

// hipcc bn.cpp -o bn -lMIOpen -I/opt/rocm/include -L/opt/rocm/lib
int main(){
    float *src1, *dst1;
    hipStream_t q; 
    miopenHandle_t mio_h;
    hipStreamCreate(&q); // TODO: Please check the return values to make sure the APIs succeed
    miopenCreateWithStream(&mio_h, q);
    miopenTensorDescriptor_t src_d1, dst_d1, _bnScaleBiasMeanVarDesc;
    
    hipMalloc(&src1, 10*3*224*224*sizeof(float));
    hipMemset(src1, 1, 10*3*224*224*sizeof(float));
    hipMalloc(&dst1, 10*3*224*224*sizeof(float));
    hipMemset(dst1, 1, 10*3*224*224*sizeof(float));

    miopenCreateTensorDescriptor(&src_d1);
    miopenCreateTensorDescriptor(&dst_d1);
    miopenSet4dTensorDescriptor(src_d1, miopenFloat, 10, 3, 224, 224);
    miopenSet4dTensorDescriptor(dst_d1, miopenFloat, 10, 3, 224, 224);

    // derive bntensordesc
    miopenCreateTensorDescriptor(&_bnScaleBiasMeanVarDesc);
    auto status = miopenDeriveBNTensorDescriptor(_bnScaleBiasMeanVarDesc, src_d1, miopenBNSpatial);
    
    float alpha = 1.0f;
    float beta = 0;
    float alpha1 = 1.0f;
    float beta1 = 0;
    
    miopenBatchNormalizationForwardInference(mio_h, miopenBNSpatial, &alpha, &beta, src_d1, src1,
                                             dst_d1, dst1, _bnScaleBiasMeanVarDesc,
                                             &alpha, &beta, NULL, NULL, 0.001);
}
```

**Comment by JehandadKhan** [comment]
@MOLOjl Please let us know if we can help you further.

**Comment by MOLOjl** [comment]
It seems the second alpha and beta argument should be in device memory, you should mention this in the [MIOpen API Reference](https://rocmsoftwareplatform.github.io/MIOpen/doc/html/batchnorm.html). Especially considering other APIs seems don't take a constant parameter from device memory.
The code below will return successfully.
Thanks for your help. @junliume @JehandadKhan  @atamazov @muralinr  @zjing14 
```c++
#include "miopen/miopen.h"
#include <hip/hip_runtime.h>

// hipcc bn1.cpp -o bn1 -lMIOpen -I/opt/rocm/include -L/opt/rocm/lib
int main(){
    hipSetDevice(0);

    float *src1, *dst1;
    hipStream_t q; 
    miopenHandle_t mio_h;
    auto error = hipStreamCreate(&q); // TODO: Please check the return values to make sure the APIs succeed
    printf("status: %s\n", hipGetErrorName(error)); // which is success

    miopenCreateWithStream(&mio_h, q);
    miopenTensorDescriptor_t src_d1, dst_d1, _bnScaleBiasMeanVarDesc;
    
    hipMalloc(&src1, 10*3*224*224*sizeof(float));
    hipMemset(src1, 1, 10*3*224*224*sizeof(float));
    hipMalloc(&dst1, 10*3*224*224*sizeof(float));
    hipMemset(dst1, 1, 10*3*224*224*sizeof(float));

    miopenCreateTensorDescriptor(&src_d1);
    miopenCreateTensorDescriptor(&dst_d1);
    miopenSet4dTensorDescriptor(src_d1, miopenFloat, 10, 3, 224, 224);
    miopenSet4dTensorDescriptor(dst_d1, miopenFloat, 10, 3, 224, 224);

    // derive bntensordesc
    miopenCreateTensorDescriptor(&_bnScaleBiasMeanVarDesc);
    auto status = miopenDeriveBNTensorDescriptor(_bnScaleBiasMeanVarDesc, src_d1, miopenBNSpatial);
    assert(status==miopenStatusSuccess);
    
    float alpha = 1.0f;
    float beta = 0;

    float *d_alpha, *d_beta;
    hipMalloc(&d_alpha, sizeof(float));
    hipMalloc(&d_beta, sizeof(float));
    hipMemcpyHtoD(d_alpha, &alpha, sizeof(float));
    hipMemcpyHtoD(d_beta, &beta, sizeof(float));

    status = miopenBatchNormalizationForwardInference(mio_h, miopenBNSpatial, &alpha, &beta, src_d1, src1,
                                             dst_d1, dst1, _bnScaleBiasMeanVarDesc,
                                             d_alpha, d_beta, NULL, NULL, 0.001);
    
    printf("over, status: %d\n", status==miopenStatusSuccess);
}
```

**Comment by MOLOjl** [comment]
Like [this](https://docs.nvidia.com/deeplearning/cudnn/api/index.html#cudnnBatchNormalizationForwardInference)
