### ISSUE TITLE
Move GoogleTest dependency to requirements.txt

### ISSUE THREAD

**Issue by JehandadKhan** [ROCmSoftwarePlatform/MIOpen#1838]
Currently, GoogleTest is installed via CMake directive, while all the other dependencies are installed via cget. This creates a discrepancy which should be aligned.

**Comment by pfultz2** [comment]
Since its a developer dependency it would be better in the dev-requirements.txt, but this will require to use the `BUILD_TESTING` cmake variable to enable tests and have it disabled by default. Although we could default it to enabled when `BUILD_DEV` is set as well.

**Comment by atamazov** [comment]
@pfultz2
> this will require to use the BUILD_TESTING cmake variable to enable tests and have it disabled by default.

In our CI we test non-DEV builds in many stages, and I believe we want to test non-DEV builds fully. The more tests moved to GoogleTest the more important is this. Can we always enable GoogleTest on our CI regardless of the build type?

**Comment by ppanchad-amd** [comment]
@JehandadKhan Has this been completed? Thanks!

**Comment by JehandadKhan** [comment]
We can close this "as will not fix"
