### ISSUE TITLE
Moving SQLite calls to cpp files

### ISSUE THREAD

**Issue by JehandadKhan** [ROCmSoftwarePlatform/MIOpen#184]
Currently we are not linking in the static version of sqlite, however, when we link in the static version the test breaks when the symbols are hidden. This is because part of the sqlite code is in the header and some other code is in the cpp file which cause two different instances of sqlite to be used in the test which is a problem because of the global variables used in sqlite

We need to put all the code that calls the sqlite api in cpp files, this should also improve compile time

**Comment by JehandadKhan** [comment]
@pfultz2 I will start working on this and should have a PR soon.

**Comment by pfultz2** [comment]
We need to probably use the pimpl idiom so we dont leak any sqlite objects into the headers.

**Comment by JehandadKhan** [comment]
Will do
