### ISSUE TITLE
dataType – Only fp32 currently supported for RNNs (input)

### ISSUE THREAD

**Issue by MissyDu** [ROCmSoftwarePlatform/MIOpen#1842]
It seems there is a contradiction [here](https://rocmsoftwareplatform.github.io/MIOpen/doc/html/datatypes.html):
"dataType – Only fp32 currently supported for RNNs (input)"  
                                 & 
"Of these types only miopenFloat and miopenHalf are fully supported across all layers in MIOpen."

Whether RNN do not support half?

Thank you.

**Comment by atamazov** [comment]
RNN supports half.

**Comment by atamazov** [comment]
Fixed in #1844
