### ISSUE TITLE
[Find-2.0][SWDEV-366795] MIOpen Error of unknown type name “FLOAT”

### ISSUE THREAD

**Issue by junliume** [ROCmSoftwarePlatform/MIOpen#1866]
[miopen_failed.log](https://github.com/ROCmSoftwarePlatform/MIOpen/files/9963047/miopen_failed.log)

Creating an issue for @umangyadav for higher visibility (@atamazov @DrizztDoUrden ):

I was trying to run “saved” solution of InceptionV3 model with MIGraphX with Find.2.0 API with Mainline 11064 build on MI100. Even though, it failed on 11064, it fails on earlier builds as well i.e. 11006. 
I am running into error of unknown type name “FLOAT”.  Please see the attached Logs and scroll down to very end. 

I did some debugging and found following: 
•	during the `miopenRunSolution` it fails to find compiled kernel in KerbDB and also doesn’t find tuned params in perf DB.  
•	It then tries to compile the kernel by supplying some compile time parameters and heuristics config params.
•	Those compile time parameters are missing `-DMIOPEN_USE_FP32` and similar type flags, and t[here](https://github.com/ROCmSoftwarePlatform/MIOpen/blob/88aee19b4a152f4f29fbea940607cba456067db6/src/solution.cpp#L165)fore when it includes `float_types.h`, it fails to parse `FLOAT` properly. 
•	I added `ctx.SetupFloats()` [here](https://github.com/ROCmSoftwarePlatform/MIOpen/blob/88aee19b4a152f4f29fbea940607cba456067db6/src/solution.cpp#L165) , and built MIOpen again and then it passes. 

I was trying to come up with small re-producible unit-test but when I try to run `test_conv2d_find2` with necessary parameters, it passes and doesn’t fail. 
./test_conv2d_find2 --float --cmode conv --pmode default --group-count 1 --disable-backward-data --disable-backward-weights --batch_size 1 --input_channels 3 --output_channels 32 --spatial_dim_elements 299 299 --filter_dims 3 3 --pads_strides_dilations 0 0 2 2 1 1 --trans_output_pads 0 0 --in_layout NCHW

1.	Can you help me identify if there is any other way, I can re-create this failure using any other existing tests if possible? 
2.	Alternatively, Do you think it is obvious enough that it is missing a call to `ctx.SetupFloats()` here for such cases where it would require hipRTC compilation ? 

Thanks, 
-Umang

**Comment by DrizztDoUrden** [comment]
> Do you think it is obvious enough that it is missing a call to ctx.SetupFloats() here for such cases where it would require hipRTC compilation ?

Yes, thank you for investigating. I would create a PR with exactly that right now.
