### ISSUE TITLE
Failing assert(x.size() == sizeof...(Ns)); in miopen::tien()

### ISSUE THREAD

**Issue by dmikushin** [ROCmSoftwarePlatform/MIOpen#1881]
I believe the `miopen::tien()` function has a legitimate use within MIOpen source code with `x.size()` greater than `Ns`, please see the GDB capture below:

Indeed, the user may wish to retrieve only 2 elements of vector out of 5, and the parameter pack expansion would perfectly allow this.

![simplescreenrecorder-2022-11-14_14 27 11](https://user-images.githubusercontent.com/5672874/202131779-aa2c8204-a071-4d2b-9179-9db4e1690aa1.gif)

Context: the issue was found while running superbenchmark RNN test case with MIOpen compiled in debug mode.

**Comment by atamazov** [comment]
@dmikushin Please set https://github.com/ROCmSoftwarePlatform/MIOpen/labels/debugging and https://github.com/ROCmSoftwarePlatform/MIOpen/labels/bug

**Comment by averinevg** [comment]
@dmikushin @junliume https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1879 was merged, can this be closed?

**Comment by dmikushin** [comment]
Yes, thank you all!
