### ISSUE TITLE
MIOpen with BinaryBuilder

### ISSUE THREAD

**Issue by pxl-th** [ROCmSoftwarePlatform/MIOpen#1891]
Hi! I'm building MIOpen using [BinaryBuilder](https://binarybuilder.org/) so that it can be installed as a standalone package using [Julia's](https://julialang.org/) package manager system in [AMDGPU.jl](https://github.com/JuliaGPU/AMDGPU.jl).
This way users are not required to build/install it manually, it will be installed automatically.

So far I've [targeted](https://github.com/JuliaGPU/AMDGPU.jl/blob/master/test/dnn/miopen.jl) only convolutions and managed to make it work on gfx1030, but only for `Float16` and `Float32`.
For other types I get errors, for example for `Float64`:

```
MIOpen(HIP): Warning [SetupFloats] Unsupported data types configuration: FP64xFP64xFP64
MIOpen(HIP): Warning [SetupFloats] Unsupported data types configuration: FP64xFP64xFP64
MIOpen(HIP): Warning [SetupFloats] Unsupported data types configuration: FP64xFP64xFP64
MIOpen(HIP): Error [Do] 'amd_comgr_do_action(kind, handle, in.GetHandle(), out.GetHandle())' AMD_COMGR_ACTION_COMPILE_SOURCE_WITH_DEVICE_LIBS_TO_BC: ERROR (1)
MIOpen(HIP): Error [BuildOcl] comgr status = ERROR (1)
MIOpen(HIP): Warning [BuildOcl] /tmp/comgr-70f67f/input/MIOpenIm2d2Col.cl:107:29: error: unknown type name 'data_t'
                    global data_t* im,
                           ^
/tmp/comgr-70f67f/input/MIOpenIm2d2Col.cl:121:29: error: unknown type name 'data_t'
                    global data_t* col)
                           ^
/tmp/comgr-70f67f/input/MIOpenIm2d2Col.cl:131:12: error: unknown type name 'data_t'
   global data_t* im_off = im + im_offset;
          ^
/tmp/comgr-70f67f/input/MIOpenIm2d2Col.cl:139:11: error: unknown type name 'data_t'
   local data_t local_im[LOCAL_MEM_SIZE];
         ^
4 errors generated.

MIOpen(HIP): Error [EvaluateInvokers] /workspace/srcdir/MIOpen-rocm-5.2.3/src/hipoc/hipoc_program.cpp:300: Code object build failed. Source: MIOpenIm2d2Col.cl
MIOpen Error: /workspace/srcdir/MIOpen-rocm-5.2.3/src/ocl/convolutionocl.cpp:518: Forward Convolution cannot be executed due to incorrect params
```

Also, while on gfx1030 I've manager to make it work for at least some types, on MI200 it errors on any type.
However, if using pre-built MIOpen from `apt` it works fine.

So most likely it is due to misconfigured build recipe, which you can find here: [link](https://github.com/JuliaPackaging/Yggdrasil/blob/master/M/MIOpen/common.jl).
I'm targeting ROCm 5.2.3.

I've tried rebuilding MIOpen with `clang-ocl`, but that didn't help...
If you have any suggestions at what can be done, they are greatly appreciated!

**Comment by dmikushin** [comment]
Hi @pxl-th , the best way to build MIOpen is using the provided Docker container. That container essentially resolves all issues that may encounter during the build, including the one you mentioned. I'm not sure whether you could containerize the build and then ship binaries to Julia users. Does the Julia user have to build the package on his own machine?

**Comment by pxl-th** [comment]
> Does the Julia user have to build the package on his own machine?

No. Once you submit the recipe it is built only once for all platforms and configurations that you've specified.
Then, when user adds a package (simply typing `add MIOpen`) it downloads prebuilt binaries.

This is how all other packages from the ROCm stack work.
See for example [`Project.toml`](https://github.com/JuliaGPU/AMDGPU.jl/blob/d9b7f34f18b6ad7d95794c5af6e360fea24c3eac/Project.toml#L32) from [AMDGPU.jl](https://github.com/JuliaGPU/AMDGPU.jl) that has lots of components from ROCm stack.

This has multiple advantages, like lazy downloading libraries, only when they are actually used.
Or installing correct ROCm version, because different Julia versions use different LLVM versions, which requires respective ROCm version.

All this greatly reduces entry barrier for the end user (at the very least).

**Comment by dmikushin** [comment]
I see, thanks! So is it getting any better, if you prepend cmake with CXX definition as in the [guide](https://github.com/ROCmSoftwarePlatform/MIOpen#for-the-hip-backend-rocm-35-and-later-run)? Sorry, I'm not sure if your script is doing this already or not. You seem to be using some other instructions, where do they come from? Perhaps from some older MIOpen releases?

```
export CXX=/opt/rocm/llvm/bin/clang++ && \
cmake -DMIOPEN_BACKEND=HIP -DCMAKE_PREFIX_PATH="/opt/rocm/;/opt/rocm/hip;/root/MIOpen/install_dir" ..
```

**Comment by pfultz2** [comment]
Does MIOpen support Float64?

**Comment by atamazov** [comment]
@pxl-th @pfultz2 
> Unsupported data types configuration: FP64xFP64xFP64

MIOpen fully supports FP32, FP16, BF16. INT8/32/8x4 is only supported for inference (forward convolutions). FP64 is only supported for ReduceTensor operations.

**Comment by pxl-th** [comment]
I'm going to close this, since we no longer ship MIOpen with BinaryBuilder.
