### ISSUE TITLE
Supported formats combinations for convolution

### ISSUE THREAD

**Issue by densamoilov** [ROCmSoftwarePlatform/MIOpen#1910]
I noticed that when source and destination tensors are in NHWC format but the weights in NCHW format MIOpen returns an error with a message that such case is not supported. When I change weights format to NHWC then everything works fine. 

Can you please clarify what combinations of formats are supported for convolution?

**Comment by JehandadKhan** [comment]
Hello @densamoilov  Indeed, that is the case. I assume the combination of layouts you are asking about would not be performant. Can you elaborate on the use case for such a scenario?

**Comment by ppanchad-amd** [comment]
Hi @densamoilov. Closing ticket for now.  Please feel free to re-open ticket if you still need assistance. Thanks!
