### ISSUE TITLE
[tests][MLIR][gfx103x] test_conv_igemm_mlir failures with old libMLIR

### ISSUE THREAD

**Issue by atamazov** [ROCmSoftwarePlatform/MIOpen#1913]
@jerryyin The reason is #1897.

E.g. with stock ROCm 5.2.3, these tests fail:
```
test_conv_igemm_mlir_fwd (Failed)
test_conv_igemm_mlir_bwd_wrw (Failed)
```

We can disable MLIR tests on GFX10 with old libMLIR but we need to know the libMLIR version in tests/CMakeLists.txt (and that version should be > than version of older libMLIR).

@junliume https://github.com/ROCmSoftwarePlatform/MIOpen/labels/testing https://github.com/ROCmSoftwarePlatform/MIOpen/labels/urgency_normal

The W/A is using `-DMIOPEN_TEST_MLIR=Off` when running CMake on GFX10.

**Comment by atamazov** [comment]
@jerryyin
> We can disable MLIR tests on GFX10 with old libMLIR but we need to know the libMLIR version in tests/CMakeLists.txt (and that version should be > than version of older libMLIR).

FYI the fix is partially implemented in #1914.

**Comment by atamazov** [comment]
@jerryyin Another option is do not make any changes and use the W/A (see description of this ticket) when necessary. Why: https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1914#discussion_r1058530284.

**Comment by atamazov** [comment]
Finally decided to provide a fix, see https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1914#discussion_r1060687570

**Comment by ppanchad-amd** [comment]
@atamazov Can we close this ticket? Thanks!
