### ISSUE TITLE
[MI200][FP16] ConvHipImplicitGemmBwdXdlops does not handle FP16_ALT attribute

### ISSUE THREAD

**Issue by atamazov** [ROCmSoftwarePlatform/MIOpen#1932]
This is critical as this may lead to convergence issues of FP16 networks on MI200 HW.

@junliume @johnny-keker https://github.com/ROCmSoftwarePlatform/MIOpen/labels/correctness https://github.com/ROCmSoftwarePlatform/MIOpen/labels/urgency_blocker https://github.com/ROCmSoftwarePlatform/MIOpen/labels/bug

~I will provide a hotfix very soon.~ Hotfix: #1933

@iq136boy Is it possible to support FP16_ALT attribute in this solver to keep performance at the best level?

**Comment by atamazov** [comment]
@iq136boy @JehandadKhan [Performance] Related question: The "forward" counterpart of this solver (`ConvHipImplicitGemmFwdXdlops`) is not applicable for MI200. Is it really so or we need to enable it for MI200?

**Comment by atamazov** [comment]
@iq136boy 
> Is it possible to support FP16_ALT attribute in this solver to keep performance at the best level?

This is important to know, because if the answer is positive, then #1933 should be considered as a workaround.

**Comment by junliume** [comment]
> @iq136boy @JehandadKhan [Performance] Related question: The "forward" counterpart of this solver (`ConvHipImplicitGemmFwdXdlops`) is not applicable for MI200. Is it really so or we need to enable it for MI200?

@carlushuang  , and @JehandadKhan  @zjing14 please check if this is indeed missed. I am under the impression that it should have been fixed. Your inputs would be appreciated.

**Comment by iq136boy** [comment]
Checking it.

**Comment by iq136boy** [comment]
>  @iq136boy @JehandadKhan [Performance] Related question: The "forward" counterpart of this solver (`ConvHipImplicitGemmFwdXdlops`) is not applicable for MI200. Is it really so or we need to enable it for MI200?
> 

I have enabled the ConvHipImplicitGemmFwdXdlops for MI200 and did the hotfix as in #1933 
The fix is in #1936

**Comment by atamazov** [comment]
@junliume @iq136boy #1933 is merged, so labeling can be changed to https://github.com/ROCmSoftwarePlatform/MIOpen/labels/performance https://github.com/ROCmSoftwarePlatform/MIOpen/labels/urgency_normal.

Further, if the answer to the question https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1932#issuecomment-1382255308 is negative, then the ticket can simply be closed.

**Comment by atamazov** [comment]
@iq136boy @junliume Ping. Are we going to fully support FP16_ALT in ConvHipImplicitGemmFwdXdlops and in ConvHipImplicitGemmBwdXdlops? If not, then this ticket can be closed.

**Comment by junliume** [comment]
I believe not in the fwd direction. @atamazov

**Comment by atamazov** [comment]
@junliume @iq136boy Yes, support for FP16_ALT is not very important for ConvHipImplicitGemmFwdXdlops because normally (by default) frameworks do not use it.

What about ConvHipImplicitGemmBwdXdlops? The same decision? I have nothing against that, just would like to make the ticket as clear as possible ;)
