### ISSUE TITLE
[Find-2.0] ENABLE_LOGGING_CMD is not printing MIOpenDriver commands for the convolution

### ISSUE THREAD

**Issue by umangyadav** [ROCmSoftwarePlatform/MIOpen#1937]
The issue is as the title says. 

when i do `export MIOPEN_ENABLE_LOGGING_CMD=1`, i am not seeing `LogCmdConvolution` prints for the convolution when Find-2.0 API is used. 

It would be nice to get the functionality of dumping miopen driver commands for the convolution when Find-2.0 APIs are used. It is helpful in debugging.

**Comment by umangyadav** [comment]
@atamazov FYI

**Comment by atamazov** [comment]
@umangyadav 
> It would be nice to get the functionality of dumping miopen driver commands for the convolution when Find-2.0 APIs are used. It is helpful in debugging.

Absolutely.

Please set https://github.com/ROCmSoftwarePlatform/MIOpen/labels/enhancement, https://github.com/ROCmSoftwarePlatform/MIOpen/labels/debugging and some urgency label (from https://github.com/ROCmSoftwarePlatform/MIOpen/labels/urgency_low to https://github.com/ROCmSoftwarePlatform/MIOpen/labels/urgency_high, depending on your needs). That would help to prioritize this.

**Comment by atamazov** [comment]
@umangyadav BTW do you know that MIOpenDriver does not support Find 2.0 yet?

**Comment by umangyadav** [comment]
> @umangyadav BTW do you know that MIOpenDriver does not support Find 2.0 yet?

No, I didn't. But it would be good to have an option in Driver for Find-2.0

**Comment by atamazov** [comment]
Then I recommend including this work right into this ticket. Can you please change the title and edit the topmost comment to reflect this need. You may wish to change also the urgency label.

**Comment by umangyadav** [comment]
I think `LogCmdConvolution` command is an easy add as done here : https://github.com/ROCmSoftwarePlatform/MIOpen/blob/a6837540fbbe19d7fc59c114a9f3568ee45308ff/src/convolution_api.cpp#L488 

Supporting FInd-2.0 in MIOpenDriver looks more involved. I would rather keep them separate issues. 
MIOpenDriver commands for convolution can be printed for Find-2.0 API calls even without having it supported in MIOpenDriver.

**Comment by umangyadav** [comment]
@atamazov  @DrizztDoUrden  Is this issue fixed ? MIGraphX by default uses Find-2.0 and we can not log MIOpen CMD commands. 
cc: @kahmed10

**Comment by atamazov** [comment]
@umangyadav 
> Is this issue fixed ? MIGraphX by default uses Find-2.0 and we can not log MIOpen CMD commands. cc: @kahmed10

Not yet. Please update the urgency label.

@DrizztDoUrden Maybe it's time to do this. This should be easy. If you do not have time, just let me know.

**Comment by junliume** [comment]
@atamazov @DrizztDoUrden @JehandadKhan 
If this feature is not too complex to fix, can we raise it to a recent sprint? It is needed for lots of debugging processes. Thanks!

**Comment by DrizztDoUrden** [comment]
No, it should not be complex. I think I can implement logging in about a day, exact time depending on what exactly we plan. Simply adding a `LogCmdConvolution` is trivial enough, can we start with that.

**Comment by junliume** [comment]
@DrizztDoUrden yes this is a high priority issue now for MIGraphX, let's see the approach you proposed have any side-effects? If not let's get on it asap. Thanks!

**Comment by DrizztDoUrden** [comment]
Done, you can try it out.
