### ISSUE TITLE
Outdated sha256 hashes in requirements file.

### ISSUE THREAD

**Issue by cderb** [ROCmSoftwarePlatform/MIOpen#1955]
half,https://github.com/pfultz2/half/archive/1.12.0.tar.gz -X header -H sha256:0a08660b68abb176ebc2a0cdf8de46e3182a7f46c66443bb80dbfaaec98cf969 --build
ROCmSoftwarePlatform/rocMLIR@rocm-5.5.0 -H sha256:a5f62769d28a73e60bc8d61022820f050e97c977c8f6f6275488db31512e1f42 -DBUILD_FAT_LIBROCKCOMPILER=1

sha256sum 1.12.0.tar.gz
a203e1525a3096d6977c9fd7b0e51c9708140702d0e6f508d718d61f54800bb6  1.12.0.tar.gz
sha256sum rocm-5.5.0.tar.gz
f3535b96f1fc112bbdf8131969fdffd0b71b91e9baa2aabb4ec24a7071b52611  rocm-5.5.0.tar.gz

**Comment by junliume** [comment]
@cderb what might have been changed? The repo has been renamed?

**Comment by atamazov** [comment]
@pfultz2 Can you please look at this, thanks!

**Comment by pfultz2** [comment]
This is a bug with github, they are rolling back the change: https://github.com/orgs/community/discussions/45830

> The repo has been renamed?

Yea it might be good to switch to the correct repo name, but thats not related to this issue.

**Comment by cderb** [comment]
Appears to have been resolved.
