### ISSUE TITLE
Support for Deconvolution in MIOpen

### ISSUE THREAD

**Issue by AryanKarumuri** [ROCmSoftwarePlatform/MIOpen#1967]
Does MIOpen supports Deconvolution? 

I am referring to this [documentation](https://rocmsoftwareplatform.github.io/MIOpen/doc/html/apireference.html) for Deconvolution and couldn't find any API's specific to Deconvolution.
If there are any API's relevant to Deconvolution could you please point me to that. 

Or will it uses the API's of Convolution to implement Deconvolution?

**Comment by atamazov** [comment]
Yes. There is `miopenTranspose` mode of convolution which implements Transposed convolution a.k.a. Deconvolution.

**Comment by atamazov** [comment]
[Attribution] @junliume @johnny-keker This can be closed now.
