### ISSUE TITLE
Details on MIOpen driver options

### ISSUE THREAD

**Issue by amitkumarhyd** [ROCmSoftwarePlatform/MIOpen#1975]
I was trying to use MIOpen Driver command and checked this document [https://rocmsoftwareplatform.github.io/MIOpen/doc/html/driver.html](url) to understand option used for MIOpen Driver.
But could not get much information about it for this options:
-k, -x, -y, -s, -F, -V, -i, -p, -q

Can you please provide me more info about this options or point me to document having information about it.

**Comment by atamazov** [comment]
```bash
$ ./bin/MIOpenDriver
FAILED: Invalid Number of Input Arguments
Usage: ./driver *base_arg* *other_args*
Supported Base Arguments: conv[fp16|int8|bfp16], CBAInfer[fp16], pool[fp16], lrn[fp16], activ[fp16], softmax[fp16], bnorm[fp16], rnn[fp16], gemm, ctc, dropout[fp16], tensorop[fp16], reduce[fp16,fp64]
$ ./bin/MIOpenDriver conv --help
MIOpenDriver conv --help
MIOpen Driver Input Flags:
...
# (list of options/flags skipped)
# Try --help and see the descriptions of options/flags for conv.
# Note that each *base_arg* has its own set of options/flags.
```

**Comment by junliume** [comment]
@JehandadKhan could you assign someone to update the usage description for options:
`-k, -x, -y, -s, -F, -V, -i, -p, -q`

**Comment by atamazov** [comment]
Currently we do not provide documentation about specific options of MIOpenDriver. Instead, the information can be found by running `MIOpenDriver *base_arg* --help`. Extending the documentation with all this info looks like duplication of work.
