### ISSUE TITLE
[bug] found igemm solver does not support group conv

### ISSUE THREAD

**Issue by junliume** [ROCmSoftwarePlatform/MIOpen#1979]
*kernel*:
 `igemm_bwd_gtcx2_nhwc_fp16_bx0_ex1_bt128x32x8_wt64x16x4_ws1x1_wr1x1_ta1x1x4x1_1x8x1x32_tb1x1x1x1_1x8x1x32_mh_me` 
 does not support group-conv

However, it is not explicitly disabled and could cause problems (crash) in some DL models.
For example it could be related to:
https://github.com/mosaicml/composer/issues/1165

Proposed Workaround:
disable group conv in asm igemm solver

**Comment by junliume** [comment]
@atamazov @carlushuang  @zjing14 @asroy : tracking for https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1978

**Comment by atamazov** [comment]
Is it so that this solver is expected to support group convolutions?

**Comment by atamazov** [comment]
[Off-topic] @junliume I suspect that "workaround" is not applicable to defects ;)

**Comment by junliume** [comment]
@carlushuang I would think the solver is expected to support group conv but the kernel has defects which need to be resolved, right?

**Comment by carlushuang** [comment]
> @carlushuang I would think the solver is expected to support group conv but the kernel has defects which need to be resolved, right?

Yes, originally this solver can support group-conv, however there is a potential issue with the kernel for group-conv case that will have memory access fault during a resnet training after hundreds of epoch. So we decide to close the support of group-conv of these solvers, which is what we already did in https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1601 (but not merged anywhere)
