### ISSUE TITLE
GPU Kernel Time Elapsed reported in MIOpenDriver invalid for certain specific scenarios

### ISSUE THREAD

**Issue by TejashShah** [ROCmSoftwarePlatform/MIOpen#199]
./bin/MIOpenDriver conv -n 128 -V 0 -c 1024 -H 14 -W 14 -k 1024 -y 3 -x 3 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -g 32 -F 5 -t 1 -i 1

IOpen(HIP): Info [FindConvBwdWeightsAlgorithm] miopenConvolutionBwdWeightsAlgoImplicitGEMM     8.52753 0
MIOpen(HIP): Info [FindConvBwdWeightsAlgorithm] BWrW Chosen Algorithm: ConvHipImplicitGemmV4R4GenWrWXdlops , 0, 8.52753

MIOpen Backward Weights Conv. Algorithm: 5, Solution: 52/ConvHipImplicitGemmV4R4GenWrWXdlops
**GPU Kernel Time Backward Weights Conv. Elapsed:** 6.396966 ms (average)

GPU Kernel Time 6.396966 is lower than Chosen Algorithm 8.52753

The same problem exists for fp16 and bfp16.

**Comment by aserio** [comment]
@TejashShah, Can this issue be closed as #200 has been merged?
