### ISSUE TITLE
Are there any network model example using miopen ？

### ISSUE THREAD

**Issue by wangzy0327** [ROCmSoftwarePlatform/MIOpen#1993]
Can you help me？ep：Googlenet3

**Comment by junliume** [comment]
@wangzy0327 at model example level I can refer you to another open source repository below:
- Composable Kernel: https://github.com/ROCmSoftwarePlatform/composable_kernel 
   - Performance Portable Programming Model for Machine Learning Tensor Operators
- AI Template: https://github.com/facebookincubator/AITemplate
   - Using Composable Kernel as one of their backends: AITemplate is a Python framework which renders neural network into high performance CUDA/HIP C++ code. Specialized for FP16 TensorCore (NVIDIA GPU) and MatrixCore (AMD GPU) inference.
- A blog from Meta about CK and AI Template: https://ai.facebook.com/blog/gpu-inference-engine-nvidia-amd-open-source/
   - You can check out some performance comparisons there (mainly the data are in the repository instead)
