### ISSUE TITLE
MiOpen kernel installed, but there is still the "Missing system database file: gfx1030_18.kdb" error

### ISSUE THREAD

**Issue by Title666645** [ROCmSoftwarePlatform/MIOpen#1996]
Hi,
I'm trying out stable diffusion, generating works but it's long and it says this error:
`MIOpen(HIP): Warning [SQLiteBase] Missing system database file: gfx1030_18.kdb Performance may degrade. Please follow instructions to install: https://github.com/ROCmSoftwarePlatform/MIOpen#installing-miopen-kernels-package
`
I installed MiOpen using: `sudo apt install miopenkernels-gfx1030-36kbk`
and later: `sudo apt install miopen-hip-gfx1030-36kbk`
and: `sudo apt install miopen-hip`
None of these changed anything.
I also used the script in utils/, but again nothing changed.

Hardware information:
GPU: Radeon RX 5700 (with XT bios)
Software information:
Ubuntu 22.10

**Comment by junliume** [comment]
@Title666645 could you check if anything changes with the typo correction? it should be Kernel Data Base `36kdb` instead of `36kbk` :)
BTW~ please also check if the GPU and OS distribution are listed in the officially supported list  https://docs.amd.com/

**Comment by Title666645** [comment]
@junliume My bad, it's kbd, I forgot.
I'm probably gonna close this issue, because the error happens only on the first generation, and later it's fast

**Comment by wsippel** [comment]
I had a 5700XT, what you're seeing is normal as far as I can tell. Navi10/ RDNA1/ gfx1010 was never officially supported (a shame, considering it works quite well), so the kernels have to be compiled at runtime. Takes a few seconds, but as you noticed, it only happens on the first generation.

**Comment by atamazov** [comment]
> Navi10/ RDNA1/ gfx1010 was never officially supported (a shame, considering it works quite well)

Please submit a request to https://github.com/RadeonOpenCompute/ROCm. We cannot officially support GPUs that are not officially supported by ROCm. 

Please note that at the request of users, some of our engineers used their personal time to support GPUs not included in the official list.

**Comment by atamazov** [comment]
@wsippel 
> Navi10/ RDNA1/ gfx1010 was never officially supported (a shame, considering it works quite well)

Please submit a request to https://github.com/RadeonOpenCompute/ROCm. We cannot officially support GPUs that are not officially supported by ROCm. 

Please note that at the request of users, some of our engineers used their personal time to support GPUs not included in the official list.
