### ISSUE TITLE
src/gemm.cpp and src/gemm_geometry.cpp contents seems to be swapped

### ISSUE THREAD

**Issue by vicproon** [ROCmSoftwarePlatform/MIOpen#2]
It looks like the contents of gemm.cpp and gemm_geometry.cpp are swapped: the first one containts geometry code while the second provides an interafce to GEMM calls.

**Comment by dagamayank** [comment]
@vicproon Thanks for your comment. It is actually up to one's interpretation. `gemm_geometry.cpp` contains methods of the `GemmGeometry` class which actually execute Gemm operations. Whereas `gemm.cpp` contains methods that create various GemmGeometries.

Please let us know if the contents of these files cause any errors on your end.

I am closing this issue as this is technically not an "issue" but a question to the developers. Soon we will have a developer mailing list which would be a better forum for such questions.
