### ISSUE TITLE
Dropout layer support

### ISSUE THREAD

**Issue by masahi** [ROCmSoftwarePlatform/MIOpen#20]
Hi, for benchmarking MIOpen with popular Imagenet models, I want Dropout layer implemented in MIOpen.

Sure, it is not hard to implement it myself using hcRNG library,  as done in hipcaffe [here](https://github.com/ROCmSoftwarePlatform/hipCaffe/blob/hip/src/caffe/layers/dropout_layer_hip.cpp). But it would be nice if you could implement an optimized one in MIOpen.

Is Dropout layer coming?

Thanks

**Comment by daniellowell** [comment]
@masahi Hello, in the near-term a dropout layer is not planned in MIOpen, at least internally. We of course welcome contributions to the library from the open source community. In the longer term it is likely that dropouts will be part of the MIOpen library.

**Comment by masahi** [comment]
@daniellowell I understand dropout has less priority right now. All deep learning frameworks I checked implements their own dropout layer, rather than using the one in cudnn.
So, I see it as a frameworks' problem.

Thanks anyway, and keep up the good work on open source library development.
