### ISSUE TITLE
How to apply NHWC Convolution?

### ISSUE THREAD

**Issue by PeixuanZuo** [ROCmSoftwarePlatform/MIOpen#2001]
I try to use Convolution with NHWC layout.
input layout : NHWC
weight layout : OHWC
output layout : NHWO.
config {N=2, C=4, O=320, H=64, W=64}
ENV : export MIOPEN_ENABLE_LOGGING_CMD=1

The main API I used
```
miopenSetNdTensorDescriptorWithLayout
miopenFindConvolutionForwardAlgorithm
miopenConvolutionForward
```

Question: How to set `miopenSetNdTensorDescriptorWithLayout` params with NHWC layout and apply miopenConvolutionForward with NHWC tensor descriptor?
I call miopenSetNdTensorDescriptorWithLayout(tensor, type, miopenTensorNHWC, {n, h, w, c}.begin(), 4) to set input/weight/output but the log seems not correct.
`MIOpen(HIP): Command [LogCmdFindConvolution] ./bin/MIOpenDriver convfp16 -n 2 -c 64 -H 64 -W 4 -k 320 -y 3 -x 4 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -F 1 -t 1`

I call miopenSetNdTensorDescriptorWithLayout(tensor, type, miopenTensorNHWC, {n, c, h, w}.begin(), 4), the log is shown as below:
`MIOpen(HIP): Command [LogCmdFindConvolution] ./bin/MIOpenDriver convfp16 -n 2 -c 4 -H 64 -W 64 -k 320 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -F 1 -t 1
`
I think configurations are right, but it miss `--in_layout NHWC --fil_layout NHWC --out_layout NHWC` which I expected. It seems `miopenTensorNHWC` not works.

Did I use the correct API for NHWC Convolution? Is there any example or links for that?

**Comment by PeixuanZuo** [comment]
@atamazov @junliume Could you please help to take a look? Thanks!

**Comment by PeixuanZuo** [comment]
Another Question is:
Does `miopenConvolutionForwardbias` or `miopenOpTensor` support NHWC Layout? I test ./MIOpenDriver with NCHW layout and NHWC layout, the test case of NHWC layout with bias didn't pass the verify.
The MIOpen version I used is `MIOpen (version: 2.19.0)`

1.NCHW layout with bias ` ./MIOpenDriver conv -n 1 -c 1 -H 3 -W 3 -k 2 -y 2 -x 2 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1  -m conv -g 1 -F 1 -t 1 -b 1`
the output is:
```
MIOpenDriver conv -n 1 -c 1 -H 3 -W 3 -k 2 -y 2 -x 2 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -F 1 -t 1 -b 1
MIOpen(HIP): Command [LogCmdFindConvolution] ./bin/MIOpenDriver conv -n 1 -c 1 -H 3 -W 3 -k 2 -y 2 -x 2 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -F 1 -t 1
MIOpen(HIP): Command [LogCmdConvolution] ./bin/MIOpenDriver conv -n 1 -c 1 -H 3 -W 3 -k 2 -y 2 -x 2 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -F 1 -t 1
MIOpen(HIP): Command [LogCmdConvolution] ./bin/MIOpenDriver conv -n 1 -c 1 -H 3 -W 3 -k 2 -y 2 -x 2 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -F 1 -t 1
MIOpen(HIP): Command [LogCmdConvolution] ./bin/MIOpenDriver conv -n 1 -c 1 -H 3 -W 3 -k 2 -y 2 -x 2 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -F 1 -t 1
MIOpen(HIP): Command [LogCmdConvolution] ./bin/MIOpenDriver conv -n 1 -c 1 -H 3 -W 3 -k 2 -y 2 -x 2 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -F 1 -t 1
MIOpen(HIP): Command [LogCmdConvolution] ./bin/MIOpenDriver conv -n 1 -c 1 -H 3 -W 3 -k 2 -y 2 -x 2 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -F 1 -t 1
MIOpen(HIP): Command [LogCmdConvolution] ./bin/MIOpenDriver conv -n 1 -c 1 -H 3 -W 3 -k 2 -y 2 -x 2 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -F 1 -t 1
MIOpen(HIP): Command [LogCmdConvolution] ./bin/MIOpenDriver conv -n 1 -c 1 -H 3 -W 3 -k 2 -y 2 -x 2 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -F 1 -t 1
MIOpen(HIP): Command [LogCmdConvolution] ./bin/MIOpenDriver conv -n 1 -c 1 -H 3 -W 3 -k 2 -y 2 -x 2 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -F 1 -t 1
MIOpen(HIP): Command [LogCmdConvolution] ./bin/MIOpenDriver conv -n 1 -c 1 -H 3 -W 3 -k 2 -y 2 -x 2 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -F 1 -t 1
MIOpen(HIP): Command [LogCmdConvolution] ./bin/MIOpenDriver conv -n 1 -c 1 -H 3 -W 3 -k 2 -y 2 -x 2 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -F 1 -t 1
MIOpen Forward Conv. Algorithm: 1, Solution: 85/ConvDirectNaiveConvFwd
GPU Kernel Time Forward Conv. Elapsed: 0.011947 ms (average)
stats: name, n, c, ho, wo, x, y, k, flopCnt, bytesRead, bytesWritten, GFLOPs, GB/s, timeMs
stats: fwd-conv2x2u1, 1, 1, 2, 2, 2, 2, 2,  64, 68, 32, 0, 0, 0.011947
GPU Kernel Time Forward Conv. Bias Elapsed: 0.012320 ms
Forward Convolution Verifies OK on CPU reference (0)
```
2. NHWC layout without bias `./MIOpenDriver conv -n 1 -c 1 -H 3 -W 3 -k 2 -y 2 -x 2 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 --in_layout NHWC --fil_layout NHWC --out_layout NHWC -m conv -g 1 -F 1 -t 1`
the output is:
```
MIOpenDriver conv -n 1 -c 1 -H 3 -W 3 -k 2 -y 2 -x 2 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 --in_layout NHWC --fil_layout NHWC --out_layout NHWC -m conv -g 1 -F 1 -t 1
MIOpen(HIP): Command [LogCmdFindConvolution] ./bin/MIOpenDriver conv -n 1 -c 1 -H 3 -W 3 -k 2 -y 2 -x 2 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 --in_layout NHWC --fil_layout NHWC --out_layout NHWC -m conv -g 1 -F 1 -t 1
MIOpen(HIP): Command [LogCmdConvolution] ./bin/MIOpenDriver conv -n 1 -c 1 -H 3 -W 3 -k 2 -y 2 -x 2 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 --in_layout NHWC --fil_layout NHWC --out_layout NHWC -m conv -g 1 -F 1 -t 1
MIOpen(HIP): Command [LogCmdConvolution] ./bin/MIOpenDriver conv -n 1 -c 1 -H 3 -W 3 -k 2 -y 2 -x 2 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 --in_layout NHWC --fil_layout NHWC --out_layout NHWC -m conv -g 1 -F 1 -t 1
MIOpen(HIP): Command [LogCmdConvolution] ./bin/MIOpenDriver conv -n 1 -c 1 -H 3 -W 3 -k 2 -y 2 -x 2 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 --in_layout NHWC --fil_layout NHWC --out_layout NHWC -m conv -g 1 -F 1 -t 1
MIOpen(HIP): Command [LogCmdConvolution] ./bin/MIOpenDriver conv -n 1 -c 1 -H 3 -W 3 -k 2 -y 2 -x 2 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 --in_layout NHWC --fil_layout NHWC --out_layout NHWC -m conv -g 1 -F 1 -t 1
MIOpen(HIP): Command [LogCmdConvolution] ./bin/MIOpenDriver conv -n 1 -c 1 -H 3 -W 3 -k 2 -y 2 -x 2 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 --in_layout NHWC --fil_layout NHWC --out_layout NHWC -m conv -g 1 -F 1 -t 1
MIOpen(HIP): Command [LogCmdConvolution] ./bin/MIOpenDriver conv -n 1 -c 1 -H 3 -W 3 -k 2 -y 2 -x 2 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 --in_layout NHWC --fil_layout NHWC --out_layout NHWC -m conv -g 1 -F 1 -t 1
MIOpen(HIP): Command [LogCmdConvolution] ./bin/MIOpenDriver conv -n 1 -c 1 -H 3 -W 3 -k 2 -y 2 -x 2 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 --in_layout NHWC --fil_layout NHWC --out_layout NHWC -m conv -g 1 -F 1 -t 1
MIOpen(HIP): Command [LogCmdConvolution] ./bin/MIOpenDriver conv -n 1 -c 1 -H 3 -W 3 -k 2 -y 2 -x 2 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 --in_layout NHWC --fil_layout NHWC --out_layout NHWC -m conv -g 1 -F 1 -t 1
MIOpen(HIP): Command [LogCmdConvolution] ./bin/MIOpenDriver conv -n 1 -c 1 -H 3 -W 3 -k 2 -y 2 -x 2 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 --in_layout NHWC --fil_layout NHWC --out_layout NHWC -m conv -g 1 -F 1 -t 1
MIOpen(HIP): Command [LogCmdConvolution] ./bin/MIOpenDriver conv -n 1 -c 1 -H 3 -W 3 -k 2 -y 2 -x 2 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 --in_layout NHWC --fil_layout NHWC --out_layout NHWC -m conv -g 1 -F 1 -t 1
MIOpen Forward Conv. Algorithm: 1, Solution: 85/ConvDirectNaiveConvFwd
GPU Kernel Time Forward Conv. Elapsed: 0.012764 ms (average)
stats: name, n, c, ho, wo, x, y, k, flopCnt, bytesRead, bytesWritten, GFLOPs, GB/s, timeMs
stats: fwd-conv2x2u1, 1, 1, 2, 2, 2, 2, 2,  64, 68, 32, 0, 0, 0.012764
Forward Convolution Verifies OK on CPU reference (0)
```

3.NHWC layout with bias ` ./MIOpenDriver conv -n 1 -c 1 -H 3 -W 3 -k 2 -y 2 -x 2 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 --in_layout NHWC --fil_layout NHWC --out_layout NHWC -m conv -g 1 -F 1 -t 1 -b 1`
the output is
```
MIOpenDriver conv -n 1 -c 1 -H 3 -W 3 -k 2 -y 2 -x 2 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 --in_layout NHWC --fil_layout NHWC --out_layout NHWC -m conv -g 1 -F 1 -t 1 -b 1
MIOpen(HIP): Command [LogCmdFindConvolution] ./bin/MIOpenDriver conv -n 1 -c 1 -H 3 -W 3 -k 2 -y 2 -x 2 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 --in_layout NHWC --fil_layout NHWC --out_layout NHWC -m conv -g 1 -F 1 -t 1
MIOpen(HIP): Command [LogCmdConvolution] ./bin/MIOpenDriver conv -n 1 -c 1 -H 3 -W 3 -k 2 -y 2 -x 2 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 --in_layout NHWC --fil_layout NHWC --out_layout NHWC -m conv -g 1 -F 1 -t 1
MIOpen(HIP): Command [LogCmdConvolution] ./bin/MIOpenDriver conv -n 1 -c 1 -H 3 -W 3 -k 2 -y 2 -x 2 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 --in_layout NHWC --fil_layout NHWC --out_layout NHWC -m conv -g 1 -F 1 -t 1
MIOpen(HIP): Command [LogCmdConvolution] ./bin/MIOpenDriver conv -n 1 -c 1 -H 3 -W 3 -k 2 -y 2 -x 2 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 --in_layout NHWC --fil_layout NHWC --out_layout NHWC -m conv -g 1 -F 1 -t 1
MIOpen(HIP): Command [LogCmdConvolution] ./bin/MIOpenDriver conv -n 1 -c 1 -H 3 -W 3 -k 2 -y 2 -x 2 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 --in_layout NHWC --fil_layout NHWC --out_layout NHWC -m conv -g 1 -F 1 -t 1
MIOpen(HIP): Command [LogCmdConvolution] ./bin/MIOpenDriver conv -n 1 -c 1 -H 3 -W 3 -k 2 -y 2 -x 2 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 --in_layout NHWC --fil_layout NHWC --out_layout NHWC -m conv -g 1 -F 1 -t 1
MIOpen(HIP): Command [LogCmdConvolution] ./bin/MIOpenDriver conv -n 1 -c 1 -H 3 -W 3 -k 2 -y 2 -x 2 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 --in_layout NHWC --fil_layout NHWC --out_layout NHWC -m conv -g 1 -F 1 -t 1
MIOpen(HIP): Command [LogCmdConvolution] ./bin/MIOpenDriver conv -n 1 -c 1 -H 3 -W 3 -k 2 -y 2 -x 2 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 --in_layout NHWC --fil_layout NHWC --out_layout NHWC -m conv -g 1 -F 1 -t 1
MIOpen(HIP): Command [LogCmdConvolution] ./bin/MIOpenDriver conv -n 1 -c 1 -H 3 -W 3 -k 2 -y 2 -x 2 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 --in_layout NHWC --fil_layout NHWC --out_layout NHWC -m conv -g 1 -F 1 -t 1
MIOpen(HIP): Command [LogCmdConvolution] ./bin/MIOpenDriver conv -n 1 -c 1 -H 3 -W 3 -k 2 -y 2 -x 2 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 --in_layout NHWC --fil_layout NHWC --out_layout NHWC -m conv -g 1 -F 1 -t 1
MIOpen(HIP): Command [LogCmdConvolution] ./bin/MIOpenDriver conv -n 1 -c 1 -H 3 -W 3 -k 2 -y 2 -x 2 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 --in_layout NHWC --fil_layout NHWC --out_layout NHWC -m conv -g 1 -F 1 -t 1
MIOpen Forward Conv. Algorithm: 1, Solution: 85/ConvDirectNaiveConvFwd
GPU Kernel Time Forward Conv. Elapsed: 0.012729 ms (average)
stats: name, n, c, ho, wo, x, y, k, flopCnt, bytesRead, bytesWritten, GFLOPs, GB/s, timeMs
stats: fwd-conv2x2u1, 1, 1, 2, 2, 2, 2, 2,  64, 68, 32, 0, 0, 0.012729
GPU Kernel Time Forward Conv. Bias Elapsed: 0.012320 ms
Forward Convolution FAILED: 0.592905 > 1.5e-06
```

**Comment by junliume** [comment]
Hi @carlushuang  and @JehandadKhan could you take a look at this question too?

**Comment by carlushuang** [comment]
@PeixuanZuo 
Currently `miopenSetNdTensorDescriptorWithLayout()` do not support the use of NHWC. If you need NHWC layout a quick solution is to use the `miopenSetTensorDescriptor()` API which is heavily used in frameworks like https://github.com/pytorch/pytorch/blob/4bfe2a24505049fa4fe43d24c2e3a5f5d99d9f00/aten/src/ATen/miopen/Descriptors.h#L85

e.g. if the 4d tensor is `N=2, C=4, H=8, W=6`
```
int dims = [2, 4, 8, 6]; // N*C*H*W
int strides = [192, 1, 24, 4]; // stride for N: H*W*C, stride for C: 1, stride for H: W*C, stride for W: C
miopenSetTensorDescriptor(desc, miopenHalf, 4, dims, strides);
```

sorry for the inconvenience/confusion, but due to the priority we need first accommodate API design for framework first.


For conv+bias MIOpenDriver issue. @JehandadKhan @atamazov please help take a look at

**Comment by PeixuanZuo** [comment]
@carlushuang Thanks for your example and this method works for me. 

One suggestion is the comment on https://github.com/ROCmSoftwarePlatform/MIOpen/blob/develop/include/miopen/miopen.h#L608  may need update if this API not support NHWC layout.

**Comment by carlushuang** [comment]
@PeixuanZuo thanks for this suggestion. Will sync internally on this topic and find a solution, either have a plan to fix it or update the document

**Comment by atamazov** [comment]
> @PeixuanZuo Currently `miopenSetNdTensorDescriptorWithLayout()` do not support the use of NHWC...

This is a bug or omission in `TensorDescriptor::CalculateStrides()`. It should observe `tensorLayout == miopenTensorNHWC` and calculate strides accordingly.

UPDATE: Moved to #2008

**Comment by atamazov** [comment]
@PeixuanZuo 
> Does miopenConvolutionForwardbias support NHWC Layout?

No.

**Comment by atamazov** [comment]
@PeixuanZuo asked at https://github.com/ROCmSoftwarePlatform/MIOpen/issues/2001#issuecomment-1447787881:
> Does miopenOpTensor support NHWC Layout?

I think it should, because TensorOps are layout-agnostic.

@dmikushin Can you please check?

**Comment by PeixuanZuo** [comment]
I try to replace `miopenConvolutionForwardbias` with `miopenOpTensor(miopenTensorOp_t tensorOp = miopenTensorOpAdd)` to add a bias, but no matter how I adjust the strides of the bias, it seems `miopenOpTensor` doesn't support NHWC Layout either.

method1 I tried(For cudnnAddTensor, this method works):
```
bias dims [1, C, 1, 1]
bias strides [C, 1, 1, 1]
y dims [N, C, H , W]
y strides [H*W*C, 1, W*C, C]
```

method2 I tried:
```
bias dims [1, C, 1, 1]
bias strides [C, 1, C, C]
y dims [N, C, H , W]
y strides [H*W*C, 1, W*C, C]
```

Could you please provide a right way to use `miopenOpTensor` if it support NHWC Layout?

**Comment by dmikushin** [comment]
Hi @PeixuanZuo , the kernels in MIOpen are usually written with one particular layout in mind. This is due to the fact that GPU threads are usually assigned to dimension with fastest growing index for best performance. Any striding tricks would very likely hit the performance.

A reasonable workaround is to transpose the tensor beforehand.  Would you like to provide a small full test program, so that I can show how you could modify it?

**Comment by PeixuanZuo** [comment]
Hi @dmikushin , Thank you very much for your explanation. My understanding of the reasonable workaround you mentioned is add two transpose before and after `miopenOpTensor/miopenConvolutionForwardbias`, that means we run a Conv use `miopenConvolutionForward(NHWC) + TransposeNHWC2NCHW + miopenOpTensor/miopenConvolutionForwardbias + TransposeNCHW2NHWC`. I believe it can work, but I guess the execution time of these two Transpose operators may similar to the execution time of miopenOpTensor/miopenConvolutionForwardbias. On my profile result, the execution time of Transpose operators are not very small. Here is a profile case which used `miopenConvolutionForward(NCHW) + miopenConvolutionForwardbias`:
![image](https://user-images.githubusercontent.com/94887879/223314805-79323e56-4e96-4c89-90ca-fcb1280f83fc.png)

Please correct me if I understand wrong. Thanks!


> Would you like to provide a small full test program, so that I can show how you could modify it?

Thanks for your help, I will provide a demo if there is something I cannot understand.

**Comment by PeixuanZuo** [comment]
Close this issue because use an internal AddBias operator to implement NHWC Convbias. Thanks for your help!
