### ISSUE TITLE
Limitations of MIOpen Deconvolution

### ISSUE THREAD

**Issue by AryanKarumuri** [ROCmSoftwarePlatform/MIOpen#2007]
What are possible combinations of datatypes and format tags that MIOpen Deconvolution supports?
Do limitations of Convolution apply for Deconvolution as well? Please let us know if there are any references.
How to test the combination of Deconvolution using the MIOpen driver?

**Comment by atamazov** [comment]
> Do limitations of Convolution apply for Deconvolution as well?

Yes.

> How to test the combination of Deconvolution using the MIOpen driver?

Use `-m trans` and engage `--trans_output_pad_d/w/h` as needed. Run `./bin/MIOpenDriver conv --help` for more info.

**Comment by AryanKarumuri** [comment]
I have tried the below tensor inputs for both Convolution and Deconvolution (ref attachment). 
**Src:**
miopenStatus_t miopenSetTensorDescriptor(miopenTensorDescriptor_t, miopenDataType_t, int, int *, int *){
MIOpen(HIP):    tensorDesc = 
MIOpen(HIP):    dataType = 1
MIOpen(HIP):    nbDims = 4
MIOpen(HIP):    dim.values = { 256 96 1 55 }
MIOpen(HIP):    stride.values = { 5280 55 55 1 }
MIOpen(HIP): }

**Weight:**
miopenStatus_t miopenSetTensorDescriptor(miopenTensorDescriptor_t, miopenDataType_t, int, int *, int *){
MIOpen(HIP):    tensorDesc = 
MIOpen(HIP):    dataType = 1
MIOpen(HIP):    nbDims = 4
MIOpen(HIP):    dim.values = { 3 96 1 11 }
MIOpen(HIP):    stride.values = { 1056 11 11 1 }
MIOpen(HIP): }

**Dst:**
miopenStatus_t miopenSetTensorDescriptor(miopenTensorDescriptor_t, miopenDataType_t, int, int *, int *){
MIOpen(HIP):    tensorDesc = 
MIOpen(HIP):    dataType = 1
MIOpen(HIP):    nbDims = 4
MIOpen(HIP):    dim.values = { 256 3 1 227 }
MIOpen(HIP):    stride.values = { 681 227 227 1 }
MIOpen(HIP): }

While Convolution is running fine and Deconvolution exited with "**Invalid filter channel number**" MIOpen error. 
Please let us know if I'm missing something in understanding the limitations of Deconvolution. 

Thanks in advance!
[Deconv_test.log](https://github.com/ROCmSoftwarePlatform/MIOpen/files/10898976/Deconv_test.log)
[Conv_test.log](https://github.com/ROCmSoftwarePlatform/MIOpen/files/10898977/Conv_test.log)

**Comment by atamazov** [comment]
https://medium.com/apache-mxnet/transposed-convolutions-explained-with-ms-excel-52d13030c7e8

I think you need to use use CKYX layout instead of KCYX for weights (i.e. `{96 3 1 11}`)

**Comment by AryanKarumuri** [comment]
Thanks for the suggestion.

**Comment by atamazov** [comment]
@AryanKarumuri Please close the issue if it is resolved.
