### ISSUE TITLE
Issue with int8 datatype for miopenBatchNormalizationForwardInference

### ISSUE THREAD

**Issue by RambabuSwargam** [ROCmSoftwarePlatform/MIOpen#2010]
**For int8 inference case we are facing some issues and we tried to confirm with the reproducer.**
And we checked with different combinations, all are passing in the float32 cases and for int8 some are giving core dump and some are failing.
Attached the examples for float32 and int8 and also the results.

Could some one help us regarding this, what could be the issue in the example and **is there any limitations with int8 datatype**

And **is NHWC format is supported for miopenBatchNormalizationForwardInference and miopenBatchNormalizationForwardTraining** ?

Note :
Compilation command:
clang++ <filename.cpp> -I/opt/rocm/include -L/opt/rocm/lib -D__HIP_PLATFORM_HCC__= -D__HIP_PLATFORM_AMD__= -I/opt/rocm/hip/include -I/opt/rocm/llvm/bin/../lib/clang/14.0.0 -I/opt/rocm/hsa/include -L/opt/rocm/rocblas/lib -lMIOpen -lamdhip64 -v -lrocblas

[s8IssueCase.log](https://github.com/ROCmSoftwarePlatform/MIOpen/files/10879400/s8IssueCase.log)
[f32Case.log](https://github.com/ROCmSoftwarePlatform/MIOpen/files/10879402/f32Case.log)
[FWD_Inference_f32Pass_Code.txt](https://github.com/ROCmSoftwarePlatform/MIOpen/files/10879406/FWD_Inference_f32Pass_Code.txt)

[FWD_Inference_s8_CoreFailCaes_Code.txt](https://github.com/ROCmSoftwarePlatform/MIOpen/files/10879407/FWD_Inference_s8_CoreFailCaes_Code.txt)

Attached code files in .txt since here it not allowing to attach cpp file.

**Comment by ppanchad-amd** [comment]
@RambabuSwargam Can you please test with latest ROCm 6.1.2 and see if issue still exists? Thanks!

**Comment by ppanchad-amd** [comment]
@RambabuSwargam Closing ticket for now.  Please feel free to re-open ticket if you still require assistance. Thanks!
