### ISSUE TITLE
How to specify datatype and layout format to MIOpenDriver for bnorm

### ISSUE THREAD

**Issue by RambabuSwargam** [ROCmSoftwarePlatform/MIOpen#2012]
I have some bnorm cases were i am getting in correct results if i change datatype and format, is there any to specify datatype and format when running driver command
./bin/MIOpenDriver bnorm -n 5 -c 33 -H 27 -W 1 -m 1 --forw 2 -b 0 -s 1
For one of my case the above driver command is same for float32 and int8. But i am facing issue if i use int8 data.
Similarly,
./bin/MIOpenDriver bnorm -n 1 -c 32 -H 30 -W 1 -m 1 --forw 1 -b 0
above driver command is same for NCHW and NHWC . But i am facing issue with NHWC.

Could you please help me regarding this.

**Comment by atamazov** [comment]
> ./bin/MIOpenDriver bnorm -n 5 -c 33 -H 27 -W 1 -m 1 --forw 2 -b 0 -s 1

This driver command executes FP32 BN. For FP16, use `./bin/MIOpenDriver bnormfp16 ...`. The library does not support INT8 for batchnorm yet.

> ./bin/MIOpenDriver bnorm -n 1 -c 32 -H 30 -W 1 -m 1 --forw 1 -b 0

This driver command works with NCHW layout. For now, the library does not support NHWC for batchnorm. As a workaround, you can use `miopenTransformTensor()` to switch from NHWC to NCHW and back.

**Comment by atamazov** [comment]
WRT the question in the title, specifically:

> How to specify datatype and layout format to MIOpenDriver for bnorm

The datatype is specified in the 1st argument of the driver, together with the primitive. For BN:
- `MIOpenDriver bnorm` - FP32
- `MIOpenDriver bnormfp16` - FP16

Other options are primitive-specific. For example, the BN-specific options:
```bash
# ./bin/MIOpenDriver bnorm --help
MIOpenDriver bnorm --help
MIOpen Driver Input Flags:

      --alpha              -A        Alpha (Default=1.0)
      --beta               -B        Beta (Default=0.)
      --in_d               -D        Input Depth (Default=0)
      --forw               -F        Run Forward Train (off: 0, train: 1, inference: 2) Batch Normalization (Default=1)
      --in_h               -H        Input Height (Default=32)
      --printconv          -P        Print Convolution Dimensions (Default=1)
      --verify             -V        Verify Each Layer (Default=1)
      --in_w               -W        Input Width (Default=32)
      --back               -b        Backwards Propagation (off: 0, on: 1) Batch Normalization (Default=0)
      --in_channels        -c        Number of Input Channels (Default=3)
      --help               -h        Print Help Message
      --iter               -i        Number of Iterations (Default=1)
      --mode               -m        Normalization Mode (per-activation (0) or spatial (1)) (Default=0)
      --batchsize          -n        Mini-batch size (Default=32)
      --run                -r        Keep running mean and variance, or on inference, use these values. (Default=0)
      --save               -s        Save off mean and inverse variance, or on backprop, use these values. (Default=0)
      --time               -t        Time Each Layer (Default=0)
      --wall               -w        Wall-clock Time Each Layer, Requires time == 1 (Default=0)
```
As you can see, there is no option related to layout.

Generally, the driver supports only functionality supported by the library. Consequently, there is no INT8 BN or NHWC BN support in the driver yet.

**Comment by kothapraveen** [comment]
@atamazov 
Thankyou for the confirmation.

**Comment by RambabuSwargam** [comment]
Hi @atamazov ,
Thankyou for the confirmation.
