### ISSUE TITLE
Is int8 supported for miopenBatchNormalizationForwardInference

### ISSUE THREAD

**Issue by RambabuSwargam** [ROCmSoftwarePlatform/MIOpen#2015]
Is int8 supported for miopenBatchNormalizationForwardInference ?

**Comment by ppanchad-amd** [comment]
@RambabuSwargam Do you still need assistance with this ticket? If not, please close ticket. Thanks!

**Comment by ppanchad-amd** [comment]
@RambabuSwargam Closing ticket for now.  Please feel free to re-open ticket if you still require assistance. Thanks!
