### ISSUE TITLE
Is NHWC format is supported for miopenBatchNormalizationForwardInference and miopenBatchNormalizationForwardTraining

### ISSUE THREAD

**Issue by RambabuSwargam** [ROCmSoftwarePlatform/MIOpen#2016]
Is NHWC format is supported for miopenBatchNormalizationForwardInference and miopenBatchNormalizationForwardTraining ?

**Comment by ppanchad-amd** [comment]
@RambabuSwargam Do you still need assistance with this ticket? If not, please close ticket. Thanks!

**Comment by ppanchad-amd** [comment]
@RambabuSwargam Closing ticket. Please re-open if you still need assistance with this ticket. Thanks!
