### ISSUE TITLE
Performance drops with different libMLIR version

### ISSUE THREAD

**Issue by atamazov** [ROCmSoftwarePlatform/MIOpen#2017]
MLIR tuning configs may become obsolete (and invalid) when MIOpen is built with a version of libMLIR other than the version that was used for generation of the system perf-db. This may happen when the recent MIOpen is built with some older ROCm or vice versa. For example, the problems shown below reveal on MI50 with relatively recent develop aa087c18f and ROCm 5.3.0.

Invalid tuning is ignored and MLIR kernels are produced with the default tuning and, thus, became much slower. As a result, performance degrades in cases where find-db says that MLIR solver is the best one.

The root reason is combination of two factors:
- (1) MIOpen delegates to libMLIR to perform validation of tuning configs AND
- (2) libMLIR is not an integral part of MIOpen.

⚠️ When ROCm (together with libMLIR) is changed, the MLIR tuning configs may become invalid in spite of MIOpen remains the same. This could lead to false regressions during QA testing! Also this might affect triaging/bisecting!

## Partial solution
- libMLIR maintains the "tuning version". Each time when libMLIR changes algorithm of validation of tuning configs (and, thus, introduces some backward incompatibility) this version is incremented
- libMLIR exports the tuning version number via its API. This could be even a macro.
- MIOpen appends the "MLIR tuning version" to the names of MLIR solvers.

### Effects
- When "MLIR tuning version" is changed, MLIR solvers in find-db become non-applicable.
  - This can partially mitigate the performance drops (see Example 2 below).
  - With #1987, the performance will be restored even better (see Example 1).
- Several versions of MLIR tuning configs reside in Perf-db. The user can run MIOpen in Normal mode and restore performance to its full potential.
- No more errors/warnings in the logs.
  - Whether this is good or not depends on the point of view. Good thing there are no error messages. It's not good that the performance degradation becomes silent. But with #1987, very little degradation is expected.

I do not see how this problem could be fully (i.e. transparently) resolved unless libMLIR becomes the integral part of MIOpen.

## Example 1
```
MIOpenDriver conv -x 3 -y 3 -W 17 -H 17 -c 192 -n 128 -k 192 -p 0 -q 0 -u 2 -v 2 -l 1 -j 1 -g 1 -F 2 -V 1 -s 0 -S 0 -w 2 -t 1 -i 6
...
- id: 100 algo: 5, time: 1.19488 ms, ws: 0, name: ConvMlirIgemmWrW
- id: 23 algo: 1, time: 12.2173 ms, ws: 169869312, name: ConvOclBwdWrW2NonTunable
- id: 102 algo: 0, time: 298.239 ms, ws: 442368, name: GemmWrwUniversal
- id: 40 algo: 3, time: 331.057 ms, ws: 82329600, name: ConvWinograd3x3MultipassWrW<3-2>
...
MIOpen(HIP): Error [FindSolutionImpl] Invalid config loaded from Perf Db: ConvMlirIgemmWrW: 128,64,32,16,4,2. Performance may degrade.
...
MIOpen Backward Weights Conv. Algorithm: 5, Solution: 100/ConvMlirIgemmWrW
GPU Kernel Time Backward Weights Conv. Elapsed: 3.575805 ms (average)
```
So we have 3.6 ms instead of 1.2 ms promised by find-db.

### Analysis

The sub-optimal MLIR solver may hide the next-good Implicit Gemm solver. A quick check in NORMAL find mode confirms that:
```
MIOpenDriver conv -x 3 -y 3 -W 17 -H 17 -c 192 -n 128 -k 192 -p 0 -q 0 -u 2 -v 2 -l 1 -j 1 -g 1 -F 4 -V 1 -s 0 -w 2 -t 1 -i 6
MIOpen(HIP): Info [get_device_name] Raw device name: gfx906:sramecc+:xnack-
MIOpen(HIP): Info [Handle] stream: 0x24543e0, device_id: 0
MIOpen(HIP): Info [GetFindModeValueImpl] MIOPEN_FIND_MODE = NORMAL(1)
MIOpen(HIP): Info [AmdRocmMetadataVersionDetect] ROCm MD version AMDHSA_COv3, HIP version 5.3.22374, MIOpen version 2.19.0.aa087c18f
...
MIOpen(HIP): Error [FindSolutionImpl] Invalid config loaded from Perf Db: ConvMlirIgemmWrW: 128,64,32,16,4,2. Performance may degrade.
MIOpen(HIP): Info [EvaluateInvokers] GemmWrwUniversal: : 8.56064 < 3.40282e+38
MIOpen(HIP): Info [EvaluateInvokers] Selected: GemmWrwUniversal: : 8.56064, workspace_sz = 442368
MIOpen(HIP): Info [EvaluateInvokers] ConvOclBwdWrW2NonTunable: MIOpenCvBwdWrW/MIOpenCvBwdWrW_rdc: 13.6412 < 3.40282e+38
MIOpen(HIP): Info [EvaluateInvokers] ConvDirectNaiveConvWrw: naive_conv_wrw_nchw_float_double_float: 28.0361 >= 13.6412
MIOpen(HIP): Info [EvaluateInvokers] Selected: ConvOclBwdWrW2NonTunable: MIOpenCvBwdWrW/MIOpenCvBwdWrW_rdc: 13.6412, workspace_sz = 169869312
MIOpen(HIP): Info [EvaluateInvokers] ConvWinograd3x3MultipassWrW<3-2>: miopenGcnAsmWinogradXformData_3_3_2_2/miopenGcnAsmWinogradXformFilter_3_3_2_2/miopenGcnAsmWinogradXformOut_3_3_2_2: 1.12833 < 3.40282e+38
MIOpen(HIP): Info [EvaluateInvokers] ConvWinograd3x3MultipassWrW<3-3>: miopenGcnAsmWinogradXformData_3_3_3_3/miopenGcnAsmWinogradXformFilter_3_3_3_3/miopenGcnAsmWinogradXformOut_3_3_3_3: 1.05312 < 1.12833
MIOpen(HIP): Info [EvaluateInvokers] ConvWinograd3x3MultipassWrW<3-4>: miopenGcnAsmWinogradXformData_3_3_4_4/miopenGcnAsmWinogradXformFilter_3_3_4_4/miopenGcnAsmWinogradXformOut_3_3_4_4: 1.04 < 1.05312
MIOpen(HIP): Info [EvaluateInvokers] ConvWinograd3x3MultipassWrW<3-5>: miopenGcnAsmWinogradXformData_3_3_5_5/miopenGcnAsmWinogradXformFilter_3_3_5_5/miopenGcnAsmWinogradXformOut_3_3_5_5: 1.80289 >= 1.04
MIOpen(HIP): Info [EvaluateInvokers] ConvWinograd3x3MultipassWrW<3-6>: miopenGcnAsmWinogradXformData_3_3_6_6/miopenGcnAsmWinogradXformFilter_3_3_6_6/miopenGcnAsmWinogradXformOut_3_3_6_6: 2.76385 >= 1.04
MIOpen(HIP): Info [EvaluateInvokers] Selected: ConvWinograd3x3MultipassWrW<3-4>: miopenGcnAsmWinogradXformData_3_3_4_4/miopenGcnAsmWinogradXformFilter_3_3_4_4/miopenGcnAsmWinogradXformOut_3_3_4_4: 1.04, workspace_sz = 75644928
MIOpen(HIP): Info [EvaluateInvokers] ConvHipImplicitGemmV4R1WrW: gridwise_convolution_implicit_gemm_v4r1_nchw_kcyx_nkhw_lds_double_buffer: 1.29697 < 3.40282e+38
MIOpen(HIP): Info [EvaluateInvokers] ConvHipImplicitGemmV4R4WrW: gridwise_convolution_backward_weights_implicit_gemm_v4r4_nchw_kcyx_nkhw: 1.13376 < 1.29697
MIOpen(HIP): Info [GetSolution] wrw workspace size: 169869312
MIOpen(HIP): Info [CallImplicitGemmWrwDynamic] wrw_reduction_hip with groups: 32
MIOpen(HIP): Info [EvaluateInvokers] ConvAsmImplicitGemmV4R1DynamicWrw: igemm_v4r1_dynamic_wrw_32x32x4_4x4_2x2x4x2x4x2_4x2x8x1_4x16/wrw_reduction_hip: 1.32673 >= 1.13376
MIOpen(HIP): Info [EvaluateInvokers] ConvMlirIgemmWrW: mlir_gen_igemm_conv2d_v4r4_wrw0: 3.44226 >= 1.13376
MIOpen(HIP): Info [EvaluateInvokers] Selected: ConvHipImplicitGemmV4R4WrW: gridwise_convolution_backward_weights_implicit_gemm_v4r4_nchw_kcyx_nkhw: 1.13376, workspace_sz = 0
MIOpen(HIP): Info [FindConvBwdWeightsAlgorithm] miopenConvolutionBwdWeightsAlgoWinograd	1.04	75644928
MIOpen(HIP): Info [FindConvBwdWeightsAlgorithm] miopenConvolutionBwdWeightsAlgoImplicitGEMM	1.13376	0
MIOpen(HIP): Info [FindConvBwdWeightsAlgorithm] miopenConvolutionBwdWeightsAlgoGEMM	8.56064	442368
MIOpen(HIP): Info [FindConvBwdWeightsAlgorithm] miopenConvolutionBwdWeightsAlgoDirect	13.6412	169869312
MIOpen(HIP): Info [FindConvBwdWeightsAlgorithm] BWrW Chosen Algorithm: ConvWinograd3x3MultipassWrW<3-4> , 75644928, 1.04
...
Wall-clock Time Backward Weights Conv. Elapsed: 1.09751 ms, Auxiliary API calls: 6774.04 ms (GWSS: 0.226562)
MIOpen Backward Weights Conv. Algorithm: 3, Solution: 35/ConvWinograd3x3MultipassWrW<3-4>
GPU Kernel Time Backward Weights Conv. Elapsed: 0.996388 ms (average)
```
As you can see, there are some other iGemm solvers, and all of them are better than MLIR with default tuning:
- ConvHipImplicitGemmV4R1WrW 1.30ms
- ConvHipImplicitGemmV4R4WrW 1.13ms
- ConvAsmImplicitGemmV4R1DynamicWrw 1.32ms

Note that Normal Find shows different times for Multipass Winograd and for GEMM than find-db contains, but that is different story.

## Example 2
```
MIOpenDriver conv -x 1 -y 1 -W 7 -H 7 -c 2048 -n 16 -k 512 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -g 1 -F 1 -V 1 -s 0 -S 0 -w 2 -t 1 -i 6 
...
Forward Conv solutions available: 4
- id: 98 algo: 5, time: 0.43904 ms, ws: 0, name: ConvMlirIgemmFwd
- id: 2 algo: 1, time: 0.46352 ms, ws: 0, name: ConvAsm1x1U
- id: 88 algo: 0, time: 0.6408 ms, ws: 0, name: GemmFwd1x1_0_1
- id: 37 algo: 3, time: 0.8464 ms, ws: 0, name: ConvBinWinogradRxSf3x2
...
MIOpen(HIP): Error [FindSolutionImpl] Invalid config loaded from Perf Db: ConvMlirIgemmFwd: 256,32,64,16,2,2. Performance may degrade.
...
MIOpen Forward Conv. Algorithm: 5, Solution: 98/ConvMlirIgemmFwd
GPU Kernel Time Forward Conv. Elapsed: 1.027517 ms (average)
```
As you can see, the performance of MLIR kernel generated with heuristically generated tuning data is worse than expected. And all the three other solvers in find-db are really better then MLIR. Disabling MLIR solver restores performance almost fully.

### Analysis

Let's check in Normal Find mode:
```
MIOpenDriver conv -x 1 -y 1 -W 7 -H 7 -c 2048 -n 16 -k 512 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -g 1 -F 1 -V 1 -s 0 -w 2 -t 1 -i 6 -C /home/atamazov/dockerx/miopen-verify2
MIOpen(HIP): Info [get_device_name] Raw device name: gfx906:sramecc+:xnack-
MIOpen(HIP): Info [Handle] stream: 0x26723e0, device_id: 0
MIOpen(HIP): Info [GetFindModeValueImpl] MIOPEN_FIND_MODE = NORMAL(1)
MIOpen(HIP): Info [AmdRocmMetadataVersionDetect] ROCm MD version AMDHSA_COv3, HIP version 5.3.22374, MIOpen version 2.19.0.aa087c18f
...
MIOpen(HIP): Error [FindSolutionImpl] Invalid config loaded from Perf Db: ConvMlirIgemmFwd: 256,32,64,16,2,2. Performance may degrade.
MIOpen(HIP): Info [EvaluateInvokers] GemmFwd1x1_0_1: : 0.61456 < 3.40282e+38
MIOpen(HIP): Info [EvaluateInvokers] Selected: GemmFwd1x1_0_1: : 0.61456, workspace_sz = 0
MIOpen(HIP): Info [EvaluateInvokers] ConvBinWinogradRxSf3x2: miopenSp3AsmConv_v21_1_3_gfx9_fp32_f3x2_stride1: 0.839359 < 3.40282e+38
MIOpen(HIP): Info [EvaluateInvokers] ConvBinWinogradRxSf2x3g1: miopenSp3AsmConv_v21_1_3_gfx9_fp32_f2x3_stride1: 1.24752 >= 0.839359
MIOpen(HIP): Info [EvaluateInvokers] ConvBinWinogradRxS: miopenSp3AsmConvRxSU: 1.3616 >= 0.839359
MIOpen(HIP): Info [EvaluateInvokers] Selected: ConvBinWinogradRxSf3x2: miopenSp3AsmConv_v21_1_3_gfx9_fp32_f3x2_stride1: 0.839359, workspace_sz = 0
MIOpen(HIP): Info [EvaluateInvokers] ConvAsm1x1U: miopenGcnAsmConv1x1U: 0.415039 < 3.40282e+38
MIOpen(HIP): Info [EvaluateInvokers] ConvOclDirectFwd1x1: MIOpenConv1x1: 0.49968 >= 0.415039
MIOpen(HIP): Info [EvaluateInvokers] ConvDirectNaiveConvFwd: naive_conv_fwd_nchw_float_double_float: 12.4946 >= 0.415039
MIOpen(HIP): Info [EvaluateInvokers] Selected: ConvAsm1x1U: miopenGcnAsmConv1x1U: 0.415039, workspace_sz = 0
MIOpen(HIP): Info [EvaluateInvokers] ConvMlirIgemmFwd: mlir_gen_igemm_conv2d_v4r4_fwd0: 0.893279 < 3.40282e+38
MIOpen(HIP): Info [EvaluateInvokers] Selected: ConvMlirIgemmFwd: mlir_gen_igemm_conv2d_v4r4_fwd0: 0.893279, workspace_sz = 0
MIOpen(HIP): Info [FindConvFwdAlgorithm] miopenConvolutionFwdAlgoDirect	0.415039	0
MIOpen(HIP): Info [FindConvFwdAlgorithm] miopenConvolutionFwdAlgoGEMM	0.61456	0
MIOpen(HIP): Info [FindConvFwdAlgorithm] miopenConvolutionFwdAlgoWinograd	0.839359	0
MIOpen(HIP): Info [FindConvFwdAlgorithm] miopenConvolutionFwdAlgoImplicitGEMM	0.893279	0
MIOpen(HIP): Info [FindConvFwdAlgorithm] FW Chosen Algorithm: ConvAsm1x1U , 0, 0.415039
...
Wall-clock Time Forward Conv. Elapsed: 0.434791 ms, Auxiliary API calls: 1161.41 ms (GWSS: 0.0244141)
MIOpen Forward Conv. Algorithm: 1, Solution: 2/ConvAsm1x1U
```

[Attribution] @junliume @johnny-keker https://github.com/ROCmSoftwarePlatform/MIOpen/labels/performance https://github.com/ROCmSoftwarePlatform/MIOpen/labels/urgency_high https://github.com/ROCmSoftwarePlatform/MIOpen/labels/value_high.

Recommended assignments: @jerryyin @atamazov @JehandadKhan

**Comment by jerryyin** [comment]
@atamazov Thanks a lot for the detailed documentation of the issue! Let's first clarify with the background section.

> MLIR tuning configs may become obsolete (and invalid) when MIOpen is built with a version of libMLIR other than the version that was used for generation of the system perf-db.

How does this happen? I thought MLIR commit hash got "locked into" MIOpen with MIOpen's `requirements.txt`. In addition, MLIR doesn't ship with ROCm, MLIR only got implicitly ship with MIOpen in MIOpen's build. So if someone force to build MIOpen with a MLIR different from the commit hash in requirements.txt, they should rebuild it with the right version of MLIR.

A more aggressive way to address this is:
 - Bump mlir package version at every release
 - Make MIOpen to throw an exception at its cmake logic that when wrong mlir is supplied

> libMLIR maintains the "tuning version". Each time when libMLIR changes algorithm of validation of tuning configs (and, thus, introduces some backward incompatibility) this version is incremented

This looks to be a more moderate way to do it. But the applicability of tuning config is usually tied with kernel's implementation.  With MLIR actively working in its kernel implementation algorithm, it is hard to give the guarantee of that performance config is fully backward compatible with past versions. Implementing this would more or less be equivalent with the "more aggressive" approach I mentioned above. It is a good idea to invalidate the find db when such scenario happens.

**Comment by atamazov** [comment]
@jerryyin 
> So if someone force to build MIOpen with a MLIR different from the commit hash in requirements.txt, they should rebuild it with the right version of MLIR.

Possibly this comment resolves the whole issue. It seems like I am wrong here:

> The root reason is combination of two factors:
> - (1) MIOpen delegates to libMLIR to perform validation of tuning configs AND
> - (2) libMLIR is not an integral part of MIOpen.

The bullet (2) is wrong. It is implied that each MIOpen version should be built with some specific version of libMLIR. Therefore it seems like the whole ticket is incorrect. Let me check if this works for 5.3.0. Thanks.

Related discussion: https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1897#issuecomment-1360366088

**Comment by atamazov** [comment]
@jerryyin 
> it is hard to give the guarantee of that performance config is fully backward compatible with past versions

We do not need this guarantee. On the contrary, the idea is to make the incompatibility explicit by changing the SolverDbId. The idea is: when "tuning version" in incremented (or decremented), the **SolverDbId**'s of MLIR solvers change, and perf-db (as well as find-db) entries become unreachable. MLIR solvers will not be selected as the "best" ones. Perf-db records won't be read and used for MLIR solvers.

But maybe this is not necessary at all.

**Comment by atamazov** [comment]
Why: https://github.com/ROCmSoftwarePlatform/MIOpen/issues/2017#issuecomment-1457206993. Will be reopened if/when necessary.

**Comment by jerryyin** [comment]
@atamazov If MIOpen is really concerned that MLIR can drag down performance, we can reject heuristic configs. So, together with your suggestions, in summary:
 - When `Invalid config loaded from Perf Db`, somehow skip MLIR solver but instead try the next fastest one
   - I think this in general would make sense that the fall back shouldn't be heuristic mode, but next fastest in find db 
 - When MIOpen ask MLIR to generate a kernel without `perf_config`, the solver would reject the config as invalid

Do you see above approach as a somewhat reasonable workaround?

**Comment by atamazov** [comment]
@jerryyin Thanks for the idea. Let's think about it later if the need arises. So far I don't see a problem, provided that MIOpen is built with the correct libMLIR (the one taken from requirements.txt). Sorry for the false alarm.

**Comment by atamazov** [comment]
[off-topic] @junliume Just in case. I remember that some time ago we run into some performance regression related to MLIR and removing MLIR solvers from find-db (#1984) resolves the issue. Are we sure the performance hit was observed with the correct version of libMLIR?
