### ISSUE TITLE
Is it possible to specify convolution algorithm as miopenConvolutionFwdAlgoImplicitGEMM for 3D convolution?

### ISSUE THREAD

**Issue by akankshabaranwal** [ROCmSoftwarePlatform/MIOpen#2018]
When I specify the algorithm as miopenConvolutionFwdAlgoImplicitGEMM for 3D convolution, I run into this error: 
```
MIOpen Error: /tmp/spack/spack-stage/spack-stage-miopen-hip-5.4.3-ow45oosheu4sig6ribgawitfphdis47x/spack-src/src/ocl/convolutionocl.cpp:704: No invoker was registered for convolution forward. Was find executed?
terminate called after throwing an instance of 'std::runtime_error'
  what():  MIOPEN failure: 7 in miopen_conv.cpp at line: 147
```
I am able to specify the algorithms miopenConvolutionFwdAlgoGEMM and miopenConvolutionFwdAlgoDirect. 
I found this #1864 :  which lists 3 reasons for why this might be happening. Is the first one the reason in this case? 
1. > Implicit GEMM algo is not applicable for the desired convolution. 

But according to this release [version 2.4.0](https://docs.amd.com/en-US/bundle/MIOpen_gh-pages/page/releasenotes.html#id10) onwards should include implicit gemm ? 

2. > GEMM algo is globally disabled : 

I am still able to specify the algorithm "miopenConvolutionFwdAlgoGEMM", so maybe this is not the issue? Otherwise how can I enable build for implicit gemm specifically?

3.  >  The library is operating in the one of the optimized [Find Modes](https://github.com/ROCmSoftwarePlatform/MIOpen/blob/develop/doc/src/find_and_immediate.md#find-modes) and the library "knows" that the GEMM algorithm is not the fastest one.

I have set this environment variable export MIOPEN_FIND_MODE=1 and then run it. The miopenFindConvolutionForwardAlgorithm returns requestedalgocount as 2 and the perfResults have results for algorithms 0 and 1 (miopenConvolutionFwdAlgoGEMM and miopenConvolutionFwdAlgoDirect ).

**Comment by atamazov** [comment]
> I have set this environment variable export MIOPEN_FIND_MODE=1 and then run it. The miopenFindConvolutionForwardAlgorithm returns requestedalgocount as 2 and the perfResults have results for algorithms 0 and 1 (miopenConvolutionFwdAlgoGEMM and miopenConvolutionFwdAlgoDirect ).

This is the answer to your question. The library was unable to find any ImplicitGEMM solution applicable for the particular 3D convolution problem you've specified. 

>> Implicit GEMM algo is not applicable for the desired convolution.
>>
> But according to this release [version 2.4.0](https://docs.amd.com/en-US/bundle/MIOpen_gh-pages/page/releasenotes.html#id10) onwards should include implicit gemm ?

There is no algorithm that can cover all possible convolution configurations, except the naive implementation (but it lacks performance). In this particular case, the library does not contain any ImplicitGEMM solvers that can execute the 3D conv configuration you would like to run.

I think this can be closed. CC @junliume

**Comment by akankshabaranwal** [comment]
I understand, thank you for the quick response. Is there some documentation where I could check which configurations are supported in the implicit gemm implementation ?

**Comment by atamazov** [comment]
No, and such a documentation can't be written. You can check the source code (look for `IsApplicable()` in the implicit gemm solvers).
