### ISSUE TITLE
 Unknown CMake command "rocm_package_setup_component"

### ISSUE THREAD

**Issue by jinz2014** [ROCmSoftwarePlatform/MIOpen#2025]
Building the dependency manually shows the error.

Another thing is that the script will build ROCm 5.5. Since an early version of ROCm has already been installed in the system, would this cause some conflicts ?

Thanks.

```
Downloading https://github.com/ROCmSoftwarePlatform/composable_kernel/archive/eef009d001b928db1bb377a105c93b75e0dccc7b.tar.gz

Extracting archive /$HOME/MIOpen/install_deps/cget/build/tmp-a15177850ae64c36a65427bd8494db17/eef009d001b928db1bb377a105c93b75e0dccc7b
Extracting archive /$HOME/MIOpen/install_deps/cget/build/tmp-a15177850ae64c36a65427bd8494db17/eef009d001b928db1bb377a105c93b75e0dccc7b.tar.gz ...
-- The C compiler identification is Clang 14.0.0
-- The CXX compiler identification is Clang 14.0.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
CMAKE_CXX_COMPILER_ID: Clang

 Unknown CMake command "rocm_package_setup_component"

**Comment by pfultz2** [comment]
MIOpen never calls `rocm_package_setup_component`. Most likely this comes from rocm-cmake.

**Comment by jinz2014** [comment]
Ok. I ran the command "cmake -P install_deps.cmake --minimum --prefix /root/MIOpen/install_dir".

**Comment by pfultz2** [comment]
That doesnt install rocm-cmake, so rocm-cmake is coming from somewhere else.

**Comment by atamazov** [comment]
@jinz2014 
> Another thing is that the script will build ROCm 5.5. Since an early version of ROCm has already been installed in the system, would this cause some conflicts ?

To avoid mess, I recommend keeping only the latest ROCm on your system. Use docker for experiments with other ROCm versions.

> Unknown CMake command "rocm_package_setup_component"

`rocm_package_setup_component` was added in rocm-cmake that comes with ROCm 5.3, https://github.com/RadeonOpenCompute/rocm-cmake/blob/026eb10b74bccc91f45c20fde1d9714e55f4bf3d/CHANGELOG.md#rocm-cmake-080-for-rocm-53.

It seems like CK build takes rocm-cmake from some older ROCm installed on your system.

Please note that you may need to set `CXX=/opt/rocm/llvm/bin/clang++` when building CK manually.

**Comment by atamazov** [comment]
@jinz2014 🙅  This ticket is off-topic here, please close it. If my recommendations do not work for you, then please open ticket at https://github.com/ROCmSoftwarePlatform/composable_kernel.

/CC @junliume

**Comment by jinz2014** [comment]
Okay.

**Comment by atamazov** [comment]
@jinz2014 Good. Come back if CK guys can't help you. But I hope my initial recommendation is enough.

**Comment by jinz2014** [comment]
Ok. Thanks.
