### ISSUE TITLE
Does MIOpen deconvolution support post_ops?

### ISSUE THREAD

**Issue by AryanKarumuri** [ROCmSoftwarePlatform/MIOpen#2032]
If MIOpen Deconvolution supports post_ops, what set of activation functions is currently supported by it?
Thank you.

**Comment by junliume** [comment]
@JehandadKhan Can you assign someone to the question?

**Comment by ppanchad-amd** [comment]
@AryanKarumuri Apologies for the lack of response. Do you still need assistance with this question? Thanks!

**Comment by ppanchad-amd** [comment]
@AryanKarumuri Closing ticket. Please re-open if you still need assistance with this ticket. Thanks!
