### ISSUE TITLE
Support HIP BE builds with CXX other than hip-clang or hcc.

### ISSUE THREAD

**Issue by atamazov** [ROCmSoftwarePlatform/MIOpen#207]
I've tried that locally and (after some hacks) was able build fully working library (including iGemm kernels, of course) and the driver. Benefits:
- Dramatic boost (~10X) of the build time of the library. The is very important for development.
- Less doubts about speed and correctness of the host code. This is especially important during transition from hcc to hip-clang.
- Correct debugging information (look at backtraces to see what I mean).

/cc @daniellowell @pfultz2 @DrizztDoUrden

**Comment by JehandadKhan** [comment]
I support this!
@atamazov what hacks ?

**Comment by atamazov** [comment]
Very dirty hacks, like editing generated makefiles.

It seems like hip-clang has much better performance than hcc (when compiling the host code). I think we do not need this anymore.
