### ISSUE TITLE
[CI] Use Navi21 nodes in AnyGPU stages

### ISSUE THREAD

**Issue by atamazov** [ROCmSoftwarePlatform/MIOpen#2076]
This
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/42c58c569f8b305105d9e380c828c3e416888fbc/Jenkinsfile#L579
should match to
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/42c58c569f8b305105d9e380c828c3e416888fbc/Jenkinsfile#L584

But Navi21 is missing. As a result, the Navi21 nodes are not used in the AnyGPU stages, which may lead to unnecessary delays.

There are several cases like this in "AnyGPU" stages throughout Jenkinsfile.

----
[Attribution] @junliume @johnny-keker https://github.com/ROCmSoftwarePlatform/MIOpen/labels/testing https://github.com/ROCmSoftwarePlatform/MIOpen/labels/performance https://github.com/ROCmSoftwarePlatform/MIOpen/labels/urgency_low, Proposed assignee: Any engineer who has some time and full CI access.

**Comment by junliume** [comment]
@atamazov actually this was intentional, we want to reserve Navi21 for Navi21-required stages and have relatively less nodes capable of it.

**Comment by atamazov** [comment]
I recommend adding an explanatory comment there (maybe referring to this ticket) and closing this.
