### ISSUE TITLE
[CI] All OCL backend tests are disabled - do we need OCL backend?

### ISSUE THREAD

**Issue by atamazov** [ROCmSoftwarePlatform/MIOpen#2077]
#1693 disables all OCL tests, including **_smoke tests_** (I've overlooked that when reviewing). Is it worth to keep a bunch of untested code in the library? Let's be consistent and:
- either remove the OCL backend totally
- or enable smoke tests for it (FP32 at least).

I think we need some decision ASAP.

----
[Attribution] @junliume @johnny-keker https://github.com/ROCmSoftwarePlatform/MIOpen/labels/urgency_high https://github.com/ROCmSoftwarePlatform/MIOpen/labels/value_unknown, Proposed assignee: @JehandadKhan

**Comment by JehandadKhan** [comment]
I suggest we remove it, it is an unnecessary complication of our library as well as our CI. I am not aware of anyone using it at the moment

**Comment by atamazov** [comment]
@DrizztDoUrden What do you think?

**Comment by DrizztDoUrden** [comment]
TBH removing it would ease a lot of headaches for me with serializing binaries, so I am kind of biased. (OCL can't get or load a binary without a stream handle afaik)

**Comment by atamazov** [comment]
@junliume The ticket is closed, but I am not aware of the final decision. Can you please remind me which one of these two alternatives was implemented and in which PR? 

> Let's be consistent and:
> * either remove the OCL backend totally
> * or enable smoke tests for it (FP32 at least).
