### ISSUE TITLE
[dependency] bzip2 not found on centOS

### ISSUE THREAD

**Issue by junliume** [ROCmSoftwarePlatform/MIOpen#2087]
**[Symptoms]**:
Since some DB files are growing out of GitHub limit, we introduced `bzip2` in #2037 
which works fine for Ubuntu and other Debian, but ... not RHEL or centOS since bzip2 is not pre-installed

**[Solution]**
Add `bzip2` as a dependency in `requirements.txt`:
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/develop/requirements.txt

Also since it is already in https://github.com/ROCmSoftwarePlatform/rocm-recipes/tree/master/miopen/bzip2
We may only need to add a line:
```
bzip2@1.0.8
```

**Comment by junliume** [comment]
_Copied from #2088:_

@pfultz2 and @JehandadKhan can confirm but this looks strange:
by this command:
`mkdir -p install_dir && cmake -P install_deps.cmake --minimum --prefix /root/MIOpen/install_dir`
then `bzip2` will be installed by default. **this PR should not be necessary**

But why release team is founding issues with #2087?

**Comment by atamazov** [comment]
> But why release team is founding issues with https://github.com/ROCmSoftwarePlatform/MIOpen/issues/2087?

And what is the answer? 😄

**Comment by pfultz2** [comment]
> then bzip2 will be installed by default. 

Yes bzip2 is installed as a dependency on boost, so should already be installed:

https://github.com/ROCmSoftwarePlatform/rocm-recipes/blob/master/recipes/boost/1.79/requirements.txt#L1

Its hard to say why this fails. Do you have the log of the build to check?

**Comment by junliume** [comment]
It seems to be a release team build issue, unrelated to any code changes.
