### ISSUE TITLE
Rework #152 to Invokers.

### ISSUE THREAD

**Issue by atamazov** [ROCmSoftwarePlatform/MIOpen#209]
~This is a blocker for #203 (and parallel tuning that depends on it) due to [this](https://github.com/ROCmSoftwarePlatform/MIOpen/pull/152#discussion_r422289511). Changes introduced by #152 must be reworked to invokers.~

~Since #145 we should NOT use `RunAndMeasure()` in the new Solvers. The only reason that #152 has passed the tests is that #203 is not yet merged.~

@daniellowell @DrizztDoUrden @alexandraBara @JehandadKhan @zjing14

_Originally posted by @atamazov in https://github.com/ROCmSoftwarePlatform/MIOpen/pull/152#issuecomment-625946518_

**Comment by zjing14** [comment]
@atamazov Do I need to remove the RunAndMeasure() now or after #203?

**Comment by atamazov** [comment]
Sorry, my bad. The issue is wrong :face_with_head_bandage:
