### ISSUE TITLE
when to add 7900xtx support?

### ISSUE THREAD

**Issue by PennyFranklin** [ROCmSoftwarePlatform/MIOpen#2097]
pay more money but not have the function to run stable diffusion  : (

**Comment by atamazov** [comment]
@PennyFranklin gfx1100 is supported, albeit unofficially. Please describe the problem (so we can reproduce it) or close the ticket.

**Comment by PennyFranklin** [comment]
> @PennyFranklin gfx1100 is supported, albeit unofficially. Please describe the problem (so we can reproduce it) or close the ticket.

oh, i just want a miopenkernel support so I may can try to run stable diffusion. if that is solved? or i should close the ticket and wait

**Comment by atamazov** [comment]
@PennyFranklin I am not fully aware of stable diffusion problems. There are several tickets that mention stable diffusion, all closed:
- #1606
- #1709 
- #1770
- #1996 

Please check.

**Comment by PennyFranklin** [comment]
i just wander when 'miopenkernel-gfx1100-96kdb' will   work

**Comment by atamazov** [comment]
@PennyFranklin 
> i just wander when 'miopenkernel-gfx1100-96kdb' will work

IIRC this is planned for the next release. @JehandadKhan Can you please clarify?

**Comment by PennyFranklin** [comment]
the next release came but I still couldn't use 'miopenkernel-gfx1100-96kdb'

**Comment by atamazov** [comment]
@PennyFranklin AFAIU this feature has missed the most recent release cycle and will be included into the next one. BTW we are going to make the binary cache independent of the number of compute units (so please do not expect "96" in the filename).

**Comment by PennyFranklin** [comment]
It doesn't matter, as long as it works. Looks like it's going to be a while before next release.
