### ISSUE TITLE
Unable to locate package miopenkernels-gfx90a-110kdb

### ISSUE THREAD

**Issue by rui-ren** [ROCmSoftwarePlatform/MIOpen#2136]
### Cannot install miopenkernels Packages

I am working some tasks using `ROCm55` and followed [here](https://rocmsoftwareplatform.github.io/MIOpen/doc/html/install.html#installing-miopen-kernels-package) to install the package, tried both name of `miopenkernels-gfx90a-110` and `miopenkernels-gfx90a-110kdb`, but got the same error below, 
```
#22 1421.7 ++ [[ rocm55 == \r\o\c\m\5\5 ]]
#22 1421.7 ++ apt install -y miopenkernels-gfx90a-110
#22 1421.7 
#22 1421.7 WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
#22 1421.7 
#22 1422.7 E: Unable to locate package miopenkernels-gfx90a-110
```

Can anyone let me know if there is any changes of installation?  

FYI, For `ROCm542`, `ROCm54` or `ROCm532`, `apt install -y miopenkernels-gfx90a-110kdb` is working properly. Thanks.

**Comment by rui-ren** [comment]
can anyone provide some insights? Thanks in advance. @junliume

**Comment by PeixuanZuo** [comment]
I think the name of `miopenkernels-xxx` change to `miopen-hip-xxx` on ROCm5,5, If we want to install `miopenkernels-gfx90a-110kdb`, we can try `miopen-hip-gfx90a-110kdb`. Can anyone confirm this change? Thanks.

**Comment by jithunnair-amd** [comment]
> I think the name of `miopenkernels-xxx` change to `miopen-hip-xxx` on ROCm5,5, If we want to install `miopenkernels-gfx90a-110kdb`, we can try `miopen-hip-gfx90a-110kdb`. Can anyone confirm this change? Thanks.

That's correct: https://repo.radeon.com/rocm/apt/5.5/pool/main/m/

**Comment by jithunnair-amd** [comment]
@junliume This documentation needs an update: https://docs.amd.com/bundle/MIOpen_gh-pages/page/install.html#installing-miopen-kernels-package

**Comment by rui-ren** [comment]
Hi, @jithunnair-amd  and @PeixuanZuo , thanks for the response. I can install `miopen-hip-gfx90a-110kdb` for ROCm55 now.

Do I need to keep `miopenkernels-gfx90a-110kdb` for ROCm542, or I can also use `miopen-hip-gfx90a-110kdb` ?

Thanks.

**Comment by rui-ren** [comment]
FYI for ROCm523, still need `miopenkernels-gfx90a-110kdb`  or `miopenkernels-gfx908-120kdb`, otherwise, can use `miopen-hip-gfx90a-110kdb`.
