### ISSUE TITLE
-ldl and -lpthread are missing when linking executables

### ISSUE THREAD

**Issue by junliume** [ROCmSoftwarePlatform/MIOpen#2178]
It is unknown what may have caused this issue but it is likely `cmake` related; hence there's no MIOpen code changes, but in the ( bad ) case below, the highlighted `-ldl -lpthread` is missing.

( good )

/opt/rocm/llvm/bin/clang++ -O3 -DNDEBUG -s -Wl,--enable-new-dtags,--rpath,$ORIGIN/../lib -pthread CMakeFiles/MIOpenDriver.dir/main.cpp.o CMakeFiles/MIOpenDriver.dir/InputFlags.cpp.o -o ../bin/MIOpenDriver  -Wl,-rpath,/long_pathname_so_that_rpms_can_package_the_debug_info/src/extlibs/MLOpen/build_hip/lib:/opt/rocm/lib: ../lib/libMIOpen.so.1.0.50700 -lpthread --hip-link --offload-arch=gfx900 --offload-arch=gfx906 --offload-arch=gfx908 --offload-arch=gfx90a --offload-arch=gfx1030 /opt/rocm/lib/libamd_comgr.so.2.5.50700 /opt/rocm/lib/librocblas.so.3.1.0.50700 /opt/rocm/lib/libamdhip64.so.5.6.50700 /opt/rocm/llvm/lib/clang/17.0.0/lib/linux/libclang_rt.builtins-x86_64.a ../../deps/lib/libboost_filesystem.a ../../deps/lib/libboost_atomic.a -L/long_pathname_so_that_rpms_can_package_the_debug_info/src/extlibs/MLOpen/deps/cget/pkg/sqlite3/install/lib -lsqlite3 **-ldl -lpthread** /usr/lib/x86_64-linux-gnu/librt.so

 ( bad )

/opt/rocm/llvm/bin/clang++ -O3 -DNDEBUG -s -Wl,--enable-new-dtags,--rpath,$ORIGIN/../lib -pthread CMakeFiles/MIOpenDriver.dir/main.cpp.o CMakeFiles/MIOpenDriver.dir/InputFlags.cpp.o -o ../bin/MIOpenDriver  -Wl,-rpath,/long_pathname_so_that_rpms_can_package_the_debug_info/src/extlibs/MLOpen/build_hip/lib:/opt/rocm/lib: ../lib/libMIOpen.so.1.0.50700 -lpthread --hip-link --offload-arch=gfx900 --offload-arch=gfx906 --offload-arch=gfx908 --offload-arch=gfx90a --offload-arch=gfx1030 /opt/rocm/lib/libamd_comgr.so.2.5.50700 /opt/rocm/lib/librocblas.so.3.1.0.50700 /opt/rocm/lib/libamdhip64.so.5.6.50700 /opt/rocm/llvm/lib/clang/17.0.0/lib/linux/libclang_rt.builtins-x86_64.a ../../deps/lib/libboost_filesystem.a ../../deps/lib/libboost_atomic.a -L/long_pathname_so_that_rpms_can_package_the_debug_info/src/extlibs/MLOpen/deps/cget/pkg/sqlite3/install/lib -lsqlite3 /usr/lib/x86_64-linux-gnu/librt.so

**Comment by junliume** [comment]
@atamazov could you also take a look?

**Comment by pfultz2** [comment]
So the sqlite3 recipe was updated to support windows and there was a bug in the pkgconfig where it was missing the -lpthread and -ldl flags. I have fixed this here: https://github.com/ROCmSoftwarePlatform/rocm-recipes/commit/7c09d33ac418c31cd5fe1f6e3c2605061dd367c6 so future builds should work.
