### ISSUE TITLE
Convolutions with alpha and beta = 1.0

### ISSUE THREAD

**Issue by Zsarl** [ROCmSoftwarePlatform/MIOpen#22]
As convolutions with alpha and beta = 1.0 is not implemnted in miopen yet, I was wondering if it is possible to acheive this with some kind of workaround?

I tried the miopenOpTensor but this doesn't work since the input and output tensors do not match.

I'm also a bit unsure about the blending of the computation using alpha and beta. The cuDNN documnetation it says the `dstValue = alpha[0]*computedValue + beta[0]*priorDstValue`. I don't see how this `yDesc = yDesc * alpha + xDesc * beta` operation would work if the dimensions are different.

Any suggestions are much apprechiated!

**Comment by daniellowell** [comment]
@Zsarl What do you mean that input and output tensors do not match in miopenOpTensor?

**Comment by Zsarl** [comment]
Well basically I get this:
`MIOpen Error: /data/repo/MIOpen/src/ocl/tensorocl.cpp:151: A and C Tensors do not match`.

Since the output dimension of the tensor depends on the number of filters in the convolution, I guess it's inevitable that the dimensions of the input and output tensors do not match?

**Comment by daniellowell** [comment]
You can do this perhaps:

Convolution to temp tensor
Dst = TensorOp(alpha*temp) + TensorOp(beta*priorDst)
Or using tensor scale:
Dst = TensorScale(alpha*temp) + TensorScale(beta*priorDst)

**Comment by Zsarl** [comment]
Thanks a lot for the reply!

I'm a bit rusty with this api, so I don't quite understand your suggestion. Would you mind translating your explaination to a specific example for the forward convolution case?

```
float alpha = 1.f, beta = 1.f;
miopenConvolutionForward(handle, alpha, xDesc, x, wDesc, w, convDesc, algo, beta, yDesc, y, workSpace, workSpaceSize);
```
Would the Data tensor y (output) here correspond to priorDst and need to be copied before being mixed with the new y tensor?

**Comment by dagamayank** [comment]
@Zsarl MIOpen currently supports `alpha=1`. So what you really want is a workaround for `beta=1`. MIOpen follows cuDNN's method of blending computations that you describe above. One way I can think of achieving this currently in MIOpen could be -

```
y_conv as the output of MIOpenConvolutionForward() // alpha=1, beta=0
y_scale as output of MIOpenScaleTensor() // scale with beta
y_add as the output of MIOpenOpTensor() // y_conv and y_scale as inputs to produce y_add as output.
```
`y_conv, y_scale and y_add` all have the same descriptor `yDesc`. If your `beta=1` then you can omit the `MIOpenScaleTensor` step above.

```
 miopenStatus_t miopenOpTensor(miopenHandle_t handle,
                                            miopenTensorOp_t tensorOp,
                                            const void* alpha1,
                                            const miopenTensorDescriptor_t aDesc,
                                            const void* A,
                                            const void* alpha2,
                                            const miopenTensorDescriptor_t bDesc,
                                            const void* B,
                                            const void* beta,
                                            const miopenTensorDescriptor_t cDesc,
                                            void* C);
```

Here `aDesc=bDesc=cDesc=yDesc`. `alpha1=1, alpha2=1, beta=0`. `A=y_conv, B=y_scale, C=y_add`

This is rather a contrived way of achieving this but we are working to add support for arbit `alpha, beta` soon. Hope this helps.

**Comment by Zsarl** [comment]
Thank you for the detailed explaination, managed to get it to work now.
(Seems like only the beta value for ConvolutionBackwardFilter affects classification performance).

Just wondering about what you said:

> If your `beta=1` then you can omit the MIOpenScaleTensor step above.

Wouldn't it be possible to to use the `alpha2` in the `MIOpenOpTensor` as the `beta` value directly instead of calling `MIOpenScaleTensor` prior to using `alpha2 = 1` - What is the difference?

**Comment by dagamayank** [comment]
`MIOpenOpTensor` implements the following equation:
`C = op ( alpha1[0] * A, alpha2[0] * B * ) + beta[0] * C`

So if B and C tensors are the same for you then yes, you can use `alpha2` to scale for `beta`.

**Comment by Zsarl** [comment]
OK, thanks a lot for the clarification!

**Comment by Zsarl** [comment]
Hi!

I see you have referenced this issue in your recent commit.

I just installed ROCm 1.7 and MIOpen 1.2, however I get the following error:

MIOpen Error: /data/repo/MIOpen/src/ocl/convolutionocl.cpp:537: Only alpha=1 and beta=0 is supported

Is it something wrong with my installation or is alpha and beta scaling still not supported in version 1.2 of MIOpen?
`uname -r` shows `4.4.0-104-generic` after installation of ROCm 1.7 and `sudo apt-get install miopen-hip` gives me `miopen-hip is already the newest version (1.2.0-a9949e3)`

**Comment by dagamayank** [comment]
@Zsarl Sorry for the delay in response. With v1.2 we enabled `alpha, beta` for a few select APIs like `TensorOps`. The other APIs would follow in subsequent releases, as needed.

I am closing this issue for now.
