### ISSUE TITLE
Support for GRU with ReLU activation function

### ISSUE THREAD

**Issue by Zadagu** [ROCmSoftwarePlatform/MIOpen#221]
Hi,

i'm looking for a method to accelerate training of RNNoise.
RNNoise uses 3 layers of GRUs with ReLU activation function.
I don't have any AMD Cards to test this myself. Does ROCm and MIOpen
support GRUs with ReLU activation function in Tensorflow? CuDNN doesn't.
For me this would be a reason to buy an AMD Card.

**Comment by daniellowell** [comment]
Our GRU implementation follows this mathematical formulation:
![image](https://user-images.githubusercontent.com/12801049/82152343-211dc600-9826-11ea-88df-d9df286868fe.png)

Luckily, AMD's implementation is entirely open source! 

Which means you can implement any activation function quite easily and build it for your own purposes, or submit a pull request as an additional feature to MIOpen. 

I think that is a great reason to buy an AMD GPU.
