### ISSUE TITLE
Remove MIOpenGEMM and MIOpenTensile code 

### ISSUE THREAD

**Issue by JehandadKhan** [ROCmSoftwarePlatform/MIOpen#2217]
Both of the above GEMM backends have been deprecated and their code sits in the library still. Perhaps its prudent to just remove it and simplify the gemm backend code.

cc @junliume @atamazov

**Comment by atamazov** [comment]
@JehandadKhan Sure! I think this is https://github.com/ROCmSoftwarePlatform/MIOpen/labels/quality https://github.com/ROCmSoftwarePlatform/MIOpen/labels/urgency_normal

**Comment by atamazov** [comment]
@JehandadKhan Please assign @averinevg @DrizztDoUrden and me as well. The one who first has free time or desire will take it into work.

**Comment by DrizztDoUrden** [comment]
I'd like to do this as it will reduce my headache from fixing bazillion corner-case code paths in [kernel binary serialization in solution](https://github.com/ROCmSoftwarePlatform/MIOpen/pull/2146)

**Comment by averinevg** [comment]
MIOpenGEMM and MIOpenTensile leftovers were removed in https://github.com/ROCm/MIOpen/pull/2499
