### ISSUE TITLE
[gfx940] instruction not supported on this GPU: v_mac_f32

### ISSUE THREAD

**Issue by junliume** [ROCmSoftwarePlatform/MIOpen#2228]
@Kirpich30000 could you check if this issue is winorgad related?
```
<instantiation>:12:13: error: instruction not supported on this GPU
            v_mac_f32 v[acc0 + gpr_in_line], s[f0], v[prev_input]
            ^
<instantiation>:5:5: note: while in macro instantiation
    .rept gprs_per_input_line
    ^
<instantiation>:10:25: note: while in macro instantiation
                        .convx3_line in0, acc0, filtersA, filtersA_part, fline, k
                        ^
<instantiation>:2:13: note: while in macro instantiation
            .rept acc_lines_per_wave // iterate over acc lines
            ^
<instantiation>:71:9: note: while in macro instantiation
        .rept filters_per_wave // iterate over output channels
        ^
<instantiation>:2:5: note: while in macro instantiation
    .rept input_lines_per_wave // iterate over input lines
    ^
/tmp/comgr-bfdfd1/input/conv3x3.s:1650:3: note: while in macro instantiation
  .conv3x3 linesA, filtersA, filtersA_part
```

**Comment by atamazov** [comment]
@junliume This solver is already disabled for gfx94x thanks to #2081. Therefore #2229 is not necessary in develop.

How exactly did you encounter this problem?

**Comment by junliume** [comment]
> @junliume This solver is already disabled for gfx94x thanks to #2081. Therefore #2229 is not necessary in develop.
> 
> How exactly did you encounter this problem?

MIGraphX, who is using MIOpen kernels in a strange way

**Comment by atamazov** [comment]
@junliume This simply can't happen unless MIGraphX uses MIOpen which does not have #2081 merged in OR it uses `MIOPEN_DEBUG_ENABLE_DEPRECATED_SOLVERS=1`. Anyway, this PR is correct, I am just curious.

@pfultz2 Can you please clarify?

**Comment by pfultz2** [comment]
We dont call MIOpen in a strange way, but we do use find 2.0 API and normal find mode.

**Comment by junliume** [comment]
@atamazov @DrizztDoUrden : FInd 2.0 does not bypass isApplicable(), right? Or the ctx refactoring is somehow missed in Find 2.0 pathes? Thanks.

**Comment by DrizztDoUrden** [comment]
Find 2.0 only bypasses `IsApplicable` when a solution is ran after deserialization. It is possible to save a solution in some old version and later run it when the solver has already been disabled for this config. I think immediate mode has the same kind of logic though.

On the second part: which refactoring are you talking of? A lot of stuff has changed since the first Find 2.0 PR. I can check if it is up to date, but 1.0 and 2.0 use mostly the same internals.
