### ISSUE TITLE
Share coding guidelines with Moreh team

### ISSUE THREAD

**Issue by TejashShah** [ROCmSoftwarePlatform/MIOpen#2242]

**Comment by atamazov** [comment]
@TejashShah Hello Tejash, welcome back ;) Are you asking us to write a kind of MIOpen coding guidelines document?

**Comment by TejashShah** [comment]
This is expected by EoW. The doc summarizing all steps and links to the wiki, github and commands to be provided to Moreh team.

**Comment by TejashShah** [comment]
> @TejashShah Hello Tejash, welcome back ;) Are you asking us to write a kind of MIOpen coding guidelines document?
Hello @atamazov, nice to see that you are very active in this project.

I am not asking any additional doc at this point from AMD/MIOpen team. I will be collating the existing guidelines to be shared with external contributors.
