### ISSUE TITLE
Demonstrate a single kernel OpenCL sample with perf #s

### ISSUE THREAD

**Issue by TejashShah** [ROCmSoftwarePlatform/MIOpen#2243]
The conservative estimate is 2 sprints but Moreh will try to figure out if it could be done in 1 sprint.

**Comment by atamazov** [comment]
@TejashShah Can you please elaborate a bit what does this ticket have to do with MIOpen?

**Comment by TejashShah** [comment]
Layernorm forward + backward  & all datatypes - fp16, fp32 and bfp16.

The performance comparison against rocm5.6.

**Comment by TejashShah** [comment]
This is going to be a reference kernel.

**Comment by TejashShah** [comment]
When PR is raised in HIP, we anticipate kernel code, the relevant host API and unit tests. The estimate-to be provided by @seungmanhan.

**Comment by TejashShah** [comment]
> @TejashShah Can you please elaborate a bit what does this ticket have to do with MIOpen?

We have external contributors who would like to include their kernels into MIOpen/CK. In the current format, those kernels are in OpenCL but soon it will be converted into HIP before it will be merged.

We are going to be super cautious, going forward, to ensure that only MIOpen-targeted issues show up in Issues tab.
