### ISSUE TITLE
Incorrectly setting gemm_k_global_splits in conv_asm_implicit_gemm_gtc_wrw_nhwc solver during database hit

### ISSUE THREAD

**Issue by Dmantri98** [ROCmSoftwarePlatform/MIOpen#2245]
For the conv_asm_implicit_gemm_gtc_wrw_nhwc solver, the configs that are within PerfDb are limited to the configs that are within the [kernel_param_list](https://github.com/ROCmSoftwarePlatform/MIOpen/blob/develop/src/solver/conv_asm_implicit_gemm_gtc_wrw_nhwc.cpp#L60), as this is a necessary condition to pass the [IsValidValue](https://github.com/ROCmSoftwarePlatform/MIOpen/blob/develop/src/solver/conv_asm_implicit_gemm_gtc_wrw_nhwc.cpp#L728) check.  Kernel configs within previous versions of the PerfDb had the the parameter "gemm_k_global_split" take any value between 0 and 10, which they would've been serialized with during tuning (through calls to find). But any config with "gemm_k_global_split" set to any value other than 0 or 1 would never have been valid since they would not have passed the [IsValidPerformanceConfig](https://github.com/ROCmSoftwarePlatform/MIOpen/blob/develop/src/solver/conv_asm_implicit_gemm_gtc_wrw_nhwc.cpp#L807) check as it calls IsValidValue() and that checks if a config is within the kernel_param_list and the parameter "gemm_k_global_split" takes on no other value then 0 or 1 within this list. This means that we currently only store configs that have "gemm_k_global_split" as set to either 0 or 1, which is suboptimal for performance. What should happen is what happens within [HeuristicInit](https://github.com/ROCmSoftwarePlatform/MIOpen/blob/develop/src/solver/conv_asm_implicit_gemm_gtc_wrw_nhwc.cpp#L636). The function "SetParamsForKSplit(problem, occupancy)" should be called with the correct occupancy gotten from the  GetImplicitGemmGtcDynamicWrwXdlopsNHWCKernel() function. Yet this code path does not take place when a PerfDb hit occurs and a config is loaded and [GetSolution](https://github.com/ROCmSoftwarePlatform/MIOpen/blob/develop/src/solver/conv_asm_implicit_gemm_gtc_wrw_nhwc.cpp#L977) is called. So the parameter "gemm_k_global_split", on perfdb hits, is never set to anything other than 0 or 1 which leads to suboptimal calculation in the [ComputeGemmKGlobalSplitsWith2DMerge](https://github.com/ROCmSoftwarePlatform/MIOpen/blob/develop/src/solver/conv_asm_implicit_gemm_gtc_wrw_nhwc.cpp#L1008) function call within GetSolution. I have ran an orthogonal (back to back) performance benchmarks of the optimal tuning configs against the default heuristic (HeuristicInit) on ~3.2k kernels and have gotten better average kernel runtimes for the default heuristic. Here are the runtimes:

Optimal Tuna: 0.74346 ms
Default Heuristic: 0.68656 ms

What I propose is to add the code path within HeuristicInit() that properly calculates occupancy within the GetSolution() function so that both default parameters and tuna parameters have the gemm_k_global_splits variable set correctly.

**Comment by carlushuang** [comment]
In this case I would suggest change the mechanism of `IsValidPerformanceConfig` function. We need to store the tuned `gemm_k_global_split` into db, because this is what we need. I think re-compute this `gemm_k_global_split` after load db is not what we want. 
What do you think
