### ISSUE TITLE
"-D__HIP_PLATFORM_HCC__=1" in V4R4GenXdlops iGemm Solutions

### ISSUE THREAD

**Issue by atamazov** [ROCmSoftwarePlatform/MIOpen#225]
Producing macros with reserved names may yield problems. These two lines can create problems with hip-clang (and comgr).

- https://github.com/ROCmSoftwarePlatform/MIOpen/blob/14d51c85df366e54de7329874dc23921eb2625c1/src/solver/conv_hip_implicit_gemm_v4r4_gen_xdlops_fwd_fp32.cpp#L532

- https://github.com/ROCmSoftwarePlatform/MIOpen/blob/b25e2e8120cecb5c3ce24303963a30362b85708d/src/solver/conv_hip_implicit_gemm_v4r4_gen_xdlops_wrw_fp32.cpp#L535

May become a blocker for the next release.

**Comment by JehandadKhan** [comment]
This is also part of the CMakeLists.txt [here](https://github.com/ROCmSoftwarePlatform/MIOpen/blob/1be0abd6c9e05d4b40c8ae1cd2b42f5aede65682/src/CMakeLists.txt#L532)

**Comment by aserio** [comment]
@zjing14, do you have any update on the resolution of this issue?

**Comment by zjing14** [comment]
__HIP_PLATFORM_HCC__ is mainly for low precision, i.e., float16 and bfloat16. For example, we use __float16 type in hip. I do not see the resolution currently. @TejashShah can give you more details.

**Comment by zjing14** [comment]
Currently, @TejashShah @asroy and me (@zjing14) are working on refactoring the solver and kernel. We can take care of it and change the macro name during refactoring.

**Comment by TejashShah** [comment]
We could change the name. But I need a flag that could tell whether I am building .cl vs hip kernel. It is required because HIP kernel compilation didn't support ushortx2 while opencl did. There are quite a few differences we encountered in OpenCL vs HIP backend. Thus this flag was used.

As far as I recall, this flag was not added by me. But I used the following CMakeLists.txt to learn that this is the flag that will be set during HIP backend and when HIP compiler is used.
> 
> 
> This is also part of the CMakeLists.txt [here](https://github.com/ROCmSoftwarePlatform/MIOpen/blob/1be0abd6c9e05d4b40c8ae1cd2b42f5aede65682/src/CMakeLists.txt#L532)

My question is that what flag do we have which could tell me whether this particular kernel file (.cl/.hpp/.h) is getting build by opencl compiler or hcc/hip-clang compiler? Just changing the name of this kernel at the location specified  by @atamazov  is not sufficient.

**Comment by TejashShah** [comment]
Few examples where opencl and hip compiler expected difference 

https://github.com/ROCmSoftwarePlatform/MIOpen/blob/fb0aa75c2d75d28d0b22ac0ad7f9c9057019da40/src/kernels/float_types.h#L84
half - opencl
_float16 - hcc/hipclang

https://github.com/ROCmSoftwarePlatform/MIOpen/blob/fb0aa75c2d75d28d0b22ac0ad7f9c9057019da40/src/kernels/float_types.h#L39

**Comment by atamazov** [comment]
WE SHOULD NOT PRODUCE MACROS WITH RESERVED NAMES

**Comment by zjing14** [comment]
@atamazov How we avoid using reserved names in the future? All reserved names have prefix "__".

**Comment by atamazov** [comment]
> My question is that what flag do we have which could tell me whether this particular kernel file (.cl/.hpp/.h) is getting build by opencl compiler or hcc/hip-clang compiler? 

You can use `#ifdef __OPENCL_VERSION__` to differentiate HIP compilation from OCL compilation. This macro is defined by the OCL compiler, https://www.khronos.org/registry/OpenCL/sdk/2.1/docs/man/xhtml/preprocessorDirectives.html

**Comment by atamazov** [comment]
> How we avoid using reserved names in the future? All reserved names have prefix "__".

Use can use these names (if name is documented), but we shouldn't define/declare these under any circumstances except P1 workarounds. Even single underscore in the beginning is usually prohibited, https://en.cppreference.com/w/cpp/language/identifiers

IIRC hip runtime headers use `__HIP_PLATFORM_HCC__` for its own purposes. It is the compiler and its library who are allowed to define (or not define) it. Right now I am experiencing HIP build problems with COMGR, and would like to avoid guessing if these problems relate to this issue or not.

**Comment by TejashShah** [comment]
> 
> 
> WE SHOULD NOT PRODUCE MACROS WITH RESERVED NAMES

We haven't produced this macro. This macro was introduced by someone (with HIP expert) in CMakeLists.txt. We simply reused the same macro at kernel level. So, it is correct to say that we shouldn't have reused the same macro.

**Comment by TejashShah** [comment]
@atamazov Your concern is that we should not define/redefine the variables with__. Point takend

My question: You don't have any objection if we use  HIP_PLATFORM_HCC  inside kernels, assuming the compiler have already defined it as part of passing those arguments just like we do

If I could use this variable, I wouldn't change it to __OPENCL_VERSION__. The problem is that what is the gaurantee that __OPENCL_VERSION__  will be set all the time. It shouldn't be the case where HIP_PLATFORM_HCC wasn't set by the compiler by default and we in MIOpen through workaround, set it on our own

**Comment by atamazov** [comment]
> We haven't produced this macro.

Please see the issue description, it denotes our C++ source code.

> Your concern is that we should not define/redefine the variables with __

Any entities (macros, functions, variables/objects, types) beginning with `_` or `__`.

> The problem is that...

The `__OPENCL_VERSION__` macro is defined by the OpenCL compiler within each translation unit from the beginning til the end of compilation. Otherwise there is a bug (and we'll file a ticket and apply workaround).

The `__OPENCL_VERSION__` macro must not be defined by the HIP compiler. If you do not want to count on it, I recommend the following:

```C++
#ifdef __HCC__
// Compiled with hcc

#ifdef __HIP__
// Compiled with hip-clang
```
Perhaps the `__HIPCC__` macro or `__HIP_PLATFORM_HCC__` is predefined by both hcc and hip-clang, but I am not sure. Please see https://rocmdocs.amd.com/en/latest/Programming_Guides/HIP-porting-guide.html#compiler-defines-summary for more info or ask compiler developers.

The advantage is that you do not need to pass extra options to compiler. This is how we write assembler kernels: these derive as much as possible from the predefined symbols (our assembler has similar machinery).

Or course you can pass `HIP_PLATFORM_HCC` without underscores or whatever you wish.

**Comment by TejashShah** [comment]
< We haven't produced this macro.
< Please see the issue description, it denotes our C++ source code.

Reference to the ticket which introduces this macro. Just to reiterate, we used it based on someone's recommendation

https://github.com/ROCmSoftwarePlatform/MIOpen/commit/75787c355be6639f3608662cd9a287f1421941e6

I will correct to use HIP_PLATFORM_HCC

**Comment by TejashShah** [comment]
I wouldn't want to change anything if I have option to do. I will try to remove the following code from all igemm solvers and check if it runs fine in hipclang and rocm3.3 and rocm3.5. if it works, implies that the compiler is setting this variable correctly (no need to set workaround), I would remove the following line.

std::string(" -D__HIP_PLATFORM_HCC__=1") + 

If I can't run the kernel correctly w/o the above line of code, I will introduce HIP_PLATFORM_HCC such as  
std::string(" -DHIP_PLATFORM_HCC=1") +

**Comment by atamazov** [comment]
I like conservatism ;) Please be aware that Jenkins uses something older than ROCm3.3. Good luck!

**Comment by TejashShah** [comment]
> 
> 
> I like conservatism ;) Please be aware that Jenkins uses something older than ROCm3.3. Good luck!

Surrendered! :wink: Changing my stance to avoid digging myself in the hole of older ROCm3.3 !! Will change to HIP_PLATFORM_HCC  in solver and kernels files.

**Comment by aserio** [comment]
@TejashShah, would you be able to provide an update on this issue?

**Comment by TejashShah** [comment]
@aserio Testing changes. Will have PR tomorrow, if not today.

**Comment by atamazov** [comment]
just in case -- I do not recommend using automatic closure of issues.
