### ISSUE TITLE
[Config Optimization] A few naive kernels are picked with no good alternatives

### ISSUE THREAD

**Issue by junliume** [ROCmSoftwarePlatform/MIOpen#2261]
It seems that these configs do not have a good alternative. We need to identify the gaps

```
./bin/MIOpenDriver conv -n 1 -c 128 --in_d 128 -H 128 -W 128 -k 1 --fil_d 3 -y 3 -x 3 --pad_d 1 -p 1 -q 1 --conv_stride_d 1 -u 1 -v 1 --dilation_d 1 -l 1 -j 1 --spatial_dim 3 -m conv -g 1 -F 1 -t 1
./bin/MIOpenDriver conv -n 1 -c 128 --in_d 128 -H 128 -W 128 -k 1 --fil_d 3 -y 3 -x 3 --pad_d 1 -p 1 -q 1 --conv_stride_d 1 -u 1 -v 1 --dilation_d 1 -l 1 -j 1 --spatial_dim 3 -m conv -g 1 -F 2 -t 1
./bin/MIOpenDriver conv -n 1 -c 128 --in_d 128 -H 128 -W 128 -k 1 --fil_d 3 -y 3 -x 3 --pad_d 1 -p 1 -q 1 --conv_stride_d 1 -u 1 -v 1 --dilation_d 1 -l 1 -j 1 --spatial_dim 3 -m conv -g 1 -F 4 -t 1
./bin/MIOpenDriver conv -n 1 -c 128 --in_d 64 -H 64 -W 64 -k 1 --fil_d 3 -y 3 -x 3 --pad_d 1 -p 1 -q 1 --conv_stride_d 1 -u 1 -v 1 --dilation_d 1 -l 1 -j 1 --spatial_dim 3 -m conv -g 1 -F 2 -t 1
```

**Comment by muralinr** [comment]
Hi @junliume All these above configs are related to 3D convolution.  We are currently supporting Naive convolution for 3D convolution.  When I change "--spatial_dim" to 2 instead of 3, ConvAsmImplicitGemmGTCDynamicWrwXdlopsNHWC kernel is pickedup. IGEMM kernel is picked up for 2D convolution for above configs.

**Comment by carlushuang** [comment]
asm igemm didn't implemented 3D conv, so should leverage CK kernels

**Comment by junliume** [comment]
@JehandadKhan @iq136boy Is 3D convolution integration into MIOpen still WIP?

**Comment by junliume** [comment]
Hi @iq136boy and @JehandadKhan when the integration is in progress, could we test performance of these configs?
