### ISSUE TITLE
Is there CU number requirements for MIOpen kernels?

### ISSUE THREAD

**Issue by xuantengh** [ROCmSoftwarePlatform/MIOpen#2285]
HIP provides the CU masking API to allow user to specify the number of CUs (WGPs) each HIP stream could use. But if I manually bind MIOpen handle to a stream with few active CUs (for example, only 3 CUs are active for this stream), the invoke to MIOpen APIs will hang. So I'm wondering if there is any CU number requirement for the MIOpen kernels? If so, where can I obtain these information?

**Comment by dmikushin** [comment]
First requirement is to make sure that your CU mask is valid. If the mask is not valid, it's already enough for the HIP runtime to hang. In this case it would not be an issue of MIOpen, in particular. Given that you are also an author of https://github.com/RadeonOpenCompute/ROCm/issues/2082 , you are sure that the CU mask is correct? Could you please share it?

**Comment by atamazov** [comment]
@Huangxt57 
>  So I'm wondering if there is any CU number requirement for the MIOpen kernels?

There is no such requirement.

> if I manually bind MIOpen handle to a stream with few active CUs (for example, only 3 CUs are active for this stream), the invoke to MIOpen APIs will hang.

MIOpen does not support non-uniform streams. Among other things, this means that all the streams MIOpen works with should have the same number of CUs. For example, if an instance of MIOpen uses a stream with 60 CUs and then you manually bind the same instance to a stream with 40 CUs, the behavior of the library will be undefined.

Please let us know if you need support for this feature and why. We'll consider this and, if the feature is well justified, include in our TODO list.

/cc @junliume

**Comment by xuantengh** [comment]
I use the MIOpen API on CU-masked HIP stream like this:
```c++
hipExtStreamCreateWithCUMask(&stream, cu_mask.size(), cu_mask.data());
miopenCreate(&handle);
miopenSetStream(handle, stream)
```
where `cu_mask` is the bit array indicating which CUs are active.

> this means that all the streams MIOpen works with should have the same number of CUs.

Note that there may be multiple MIOpen handlers bind with different streams with varied CU masks. Does this setting violate the mentioned restrictions?
