### ISSUE TITLE
Calling functions on `ExecutionContext` should not be required for proper initialization

### ISSUE THREAD

**Issue by JehandadKhan** [ROCmSoftwarePlatform/MIOpen#2289]
The `miopen::ExecutionContext` requires functions such as `DetectROCm` for correct initialization. This leads to hard to catch bugs such as #2288  and relies on the developer knowing the sequence of functions to call which has been addressed in various ways across the code ( temporary objects in lambdas ).

To my understanding such function calls which are required for the proper initialization of the object should be part of the ctor. I want to understand why did we not design it that way and rely on the developer calling these functions every time such an object is created.

**Comment by JehandadKhan** [comment]
cc @atamazov

**Comment by DrizztDoUrden** [comment]
If I remember correctly, it is not required in gwss, but a better way to do it would be to have  a second dedicated constructor like `ExecutionContext(FastInit{})` for when detect rocm is not needed.

**Comment by DrizztDoUrden** [comment]
I'll try to make a PR tomorrow. This is not really complicated. just a moderate number of lines.
In case you are more interested in historical perspective of how things became what they are: originally `DetectRocm` was only required in couple solvers and has been used sporadically, then it expanded to every part of library where it is not guaranteed to not be needed.
Nonetheless, I agree that this was poor planning and should be fixed.

P.S.: it is kind of used here and there practice to allow slow part of initialization to be delayed, but I don't think that this should be the case as the intermediate result is (or at least was) cached in a function static variable.

Also, I wonder if it is even MT-safe. I should check on that too.

**Comment by atamazov** [comment]
@JehandadKhan The reasons of functions like DetectRocm are historical. Usually we refactor such things during normal development. But **it happens from time to time, and even during refactoring.

**Comment by atamazov** [comment]
@DrizztDoUrden Please see https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1739#pullrequestreview-1557922866

**Comment by atamazov** [comment]
@DrizztDoUrden DetectRocm is thread-safe, and, after the 1st invocation, quite fast.

**Comment by atamazov** [comment]
@JehandadKhan Just to remind. In some old versions of the library we had to run the compiler in order to find out some necessary version information. That is one of the reasons of of introduction of DetectRocm. And at that time there was no abstraction representing the execution context. We had to call the function manually, when necessary.

Now the state of the library allows to get rid of it, as you properly noted in the topmost comment.

**Comment by DrizztDoUrden** [comment]
I also think that SetupFloats should be invoked from *::ProblemDescription constructor to force full setup there as it's fast as well and can be accidentally skipped. But I'd do that in a separate PR.

**Comment by JehandadKhan** [comment]
> Just to remind. In some old versions of the library we had to run the compiler in order to find out some necessary version information. That is one of the reasons of of introduction of DetectRocm. And at that time there was no abstraction representing the execution context. We had to call the function manually, when necessary.

@atamazov  Thanks for the context it does help. I suggest moving forward we move all such things to the handle creation time and maintain state there. This ensures that API call overhead time is consistent and the developer does not have to think about what functions they need to call and what is optional since all initializations are already done.

@DrizztDoUrden Please close this issue when the PR is merged
