### ISSUE TITLE
Remove iGEMM solvers 

### ISSUE THREAD

**Issue by JehandadKhan** [ROCmSoftwarePlatform/MIOpen#229]
The following solvers need to be removed from the library:

* ConvHipImplicitGemmV4_1x1
* ConvHipImplicitGemmV4Fwd

@asroy Please update the list if you believe some others can be removed as well

**Comment by aserio** [comment]
@JehandadKhan, has the work to remove these two solvers started? Who will be creating the PR?

**Comment by JehandadKhan** [comment]
If the iGEMM team does not object I can do it.

**Comment by aserio** [comment]
@daniellowell, please clarify who is assigned this task so that we can drive this high priority issue to completion.

**Comment by aserio** [comment]
@daniellowell, following up with my request.

**Comment by asroy** [comment]
@JehandadKhan please go ahead and remove these solvers, unless @zjing14, @Tejash object

I will remove the kernel part in separate PR.

**Comment by atamazov** [comment]
@asroy PR #274 how has some dead code in RunAndMeasureSolutionBase and GetSolutionBase. Maybe some invokers are never used.

Can we make all removals in a single PR?

**Comment by aserio** [comment]
@JehandadKhan has #274 addressed this issue or are there still aspects of this issue at large?

**Comment by JehandadKhan** [comment]
The PR has addressed the issue
