### ISSUE TITLE
conv_u1v1_wheel_alpha_v8_4_4_gfx803.so not working with ROCm-OpenCL-Runtime master branch

### ISSUE THREAD

**Issue by yxsamliu** [ROCmSoftwarePlatform/MIOpen#23]
conv_u1v1_wheel_alpha_v8_4_4_gfx803.so etc does not work with ROCm-OpenCL-Runtime master branch since the metadata format has changed. A 'SymbolName' metadata is required, which is usually the function_name@kd. Can those files be updated? Thanks.

**Comment by dagamayank** [comment]
@yxsamliu Can you please share the output of `uname -a` on your system? What is the version of ROCm installed on your system?

**Comment by yxsamliu** [comment]
4.11.0-kfd-compute-rocm-rel-1.6-180 #1 SMP Tue Oct 10 08:15:38 CDT 2017 x86_64 x86_64 x86_64 GNU/Linux

However to reproduce the issue, you need to build and install master branch of https://github.com/RadeonOpenCompute/ROCm-OpenCL-Runtime.

$ bin/test_main
Device Name: gfx803
Device Name: gfx803
Device Name: gfx803
runcl  -DMIOPEN_TYPE=float -DMIOPEN_ALPHA_TYPE=float src/Kernels/MIOpenTensorScaleKernel.cl -k SetTensor -dumpilisa -r 10 if#0: if#0: if#0: iv#0 204800,1,1/256,1,1
key: SetTensor,
Kernel filename: MIOpenTensorScaleKernel.cl
Info: Invoking kernel: SetTensor, work_dim = 3, global_work_offset = { 0, 0, 0 }, global_work_dim = { 204800, 1, 1 }, local_work_dim = { 256, 1, 1 }
runcl  -DMIOPEN_TYPE=float -DMIOPEN_ALPHA_TYPE=float src/Kernels/MIOpenTensorScaleKernel.cl -k ScaleTensor -dumpilisa -r 10 if#0: if#0: if#0: iv#0 204800,1,1/256,1,1
key: ScaleTensor,
Info: Invoking kernel: ScaleTensor, work_dim = 3, global_work_offset = { 0, 0, 0 }, global_work_dim = { 204800, 1, 1 }, local_work_dim = { 256, 1, 1 }
key: miopenConvolutionFwdAlgoWinograd,32x8x8x5x5x64x4x4x100xNCHWxFP32x1
Kernel filename: conv_u1v1_wheel_alpha_v8_4_4_gfx803.so
YAML:4:5: error: missing required key 'SymbolName'
  - Name:            sp3AsmConvRxSF
    ^
MIOpen Error: /home/yaxunl/h/git/MIOpen/MIOpen/src/ocl/clhelper.cpp:101: Error Building OpenCL Program in BuildProgram()
Error: failed to process metadata
 Build Program Failure
FAILED: (miopenFindConvolutionForwardAlgorithm( handle, inputTensor, in_dev, convFilter, wei_dev, convDesc, outputTensor, out_dev, 1, &ret_algo_count, &perf, fwd_workspace_dev, sz_fwd_workspace, 0)) == 0: /home/yaxunl/h/git/MIOpen/MIOpen/test/main.cpp:276
Aborted (core dumped)

**Comment by dagamayank** [comment]
What happens if you just install opencl from the ROCm supported package using `sudo apt-get install rocm-opencl-dev`, i.e., not build and install yourself from github.

**Comment by yxsamliu** [comment]
It passes with rocm-opencl-dev.

**Comment by dagamayank** [comment]
OK. In that case do you have a special need to build and install opencl yourself?

**Comment by yxsamliu** [comment]
right. is there a way to manually modify conv_u1v1_wheel_alpha_v8_4_4_gfx803.so to use the new metadata format?

**Comment by dagamayank** [comment]
>  In that case do you have a special need to build and install opencl yourself?

Can you please explain the reason why do you want to build and install OpenCL yourself?

**Comment by yxsamliu** [comment]
we want to test MIOpen with OpenCL development build to check if a change causes performance regression in MIOpen. In general, I think it is useful to include MIOpen in the regular OpenCL test runs.

**Comment by yxsamliu** [comment]
Is it possible to create an MIOpen branch that works with ROCm-OpenCL-Runtime master branch?

**Comment by dagamayank** [comment]
Moving this discussion internally.
