### ISSUE TITLE
Post-merge issues of #2125

### ISSUE THREAD

**Issue by atamazov** [ROCmSoftwarePlatform/MIOpen#2301]
- [x] 🔴 https://github.com/ROCmSoftwarePlatform/MIOpen/pull/2125#discussion_r1285961294 - the "deterministic" attribute is not observed.
- [x] 🟡 https://github.com/ROCmSoftwarePlatform/MIOpen/pull/2125#discussion_r1286284003 - computations that depend on problem should be moved from Invoker to InvokerFactory.

----
[Attribution] @junliume @JehandadKhan
- https://github.com/ROCmSoftwarePlatform/MIOpen/labels/correctness
- https://github.com/ROCmSoftwarePlatform/MIOpen/labels/urgency_high
- Proposed assignees: @iq136boy

**Comment by JehandadKhan** [comment]
@amberhassaan  Can you please take a look at this issue ? IIUC this should be a two liner fix.

Thanks @atamazov  for catching this.

**Comment by amberhassaan** [comment]
Will put out a fix later today.

**Comment by atamazov** [comment]
One more bullet (yellow) added.

**Comment by atamazov** [comment]
~The topmost comment updated with unresolved comments from #2305 and a new ticket.~

**Comment by atamazov** [comment]
via #2305
