### ISSUE TITLE
Building issues with clang14 and lld

### ISSUE THREAD

**Issue by mabdallah89** [ROCmSoftwarePlatform/MIOpen#2311]
When trying to build with clang-14 and lld, I have the following building error
```
$ make
[  0%] Built target sqlite_memvfs
[  2%] Built target addkernels
....
[  58%] Linking CXX shared library ../lib/libMIOpen.so
ld.lld: error: unable to find library -lsqlite3
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/CMakeFiles/MIOpen.dir/build.make:38142: lib/libMIOpen.so.1.0] Error 1
make[1]: *** [CMakeFiles/Makefile2:2632: src/CMakeFiles/MIOpen.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
```

```
~$ ldconfig -p | grep sqlite
        libsqlite3.so.0 (libc6,x86-64) => /lib/x86_64-linux-gnu/libsqlite3.so.0
        libsqlite.so.0 (libc6,x86-64) => /lib/x86_64-linux-gnu/libsqlite.so.0
```

```
$ echo $LD_LIBRARY_PATH
/home/mabdalla/openmi/opt/lib/:/lib/x86_64-linux-gnu/
```

**Comment by junliume** [comment]
@mabdallah89 May I ask did you build MIOpen dependencies first? i.e. 
`cmake -P install_deps.cmake --minimum`
or if you prefer separate directory:
`mkdir -p install_dir && cmake -P install_deps.cmake --minimum --prefix /root/MIOpen/install_dir`

**Comment by mabdallah89** [comment]
@junliume yes I did. However, I don't see "libsqlite3.so" found there downloaded, but I see the static library version "libsqlite3.a". Still, the dynamic library seems to be already installed by default in /lib/x86_64-linux-gnu/.

```
~$~/openmi/opt/cget/pkg/sqlite3/install/lib$ ls
       libsqlite3.a  pkgconfig
```

```
~$ ldconfig -p | grep sqlite
        libsqlite3.so.0 (libc6,x86-64) => /lib/x86_64-linux-gnu/libsqlite3.so.0
        libsqlite.so.0 (libc6,x86-64) => /lib/x86_64-linux-gnu/libsqlite.so.0
 ```

**Comment by junliume** [comment]
@mabdallah89 do you still encounter this issue?
> clang-14: error: linker command failed with exit code 1 (use -v to see invocation)

Could you let us know the invocation line (detailed log)?
