### ISSUE TITLE
Op2dTensorSquash doesn't fit into tensor operation paradigm and can't pass the tests.

### ISSUE THREAD

**Issue by CAHEK7** [ROCmSoftwarePlatform/MIOpen#2316]
@muralinr @zjing14 probably you may shed some light on it.
@junliume probably you know who else worked on this code and may answer the questions.

Should we move Op2dTensorSquash outside of 3d tensors operations and add separated tests and all the infrastructure for it? Combining different functionality under one API interface seems error prone for me.

Here is a detail description:

For 3d tensor operations there is a special `Squash` case where tensor B is not equal to A and C and is not properly squashed.
It supposed to be either equal to A and C A:2x3x4 and B:2x3x4 or some of the dimensions are squashed like B:1x3x4 or B:1x1x4 or B:2x3x1 but for that particular `squashed` case there is an exception https://github.com/ROCmSoftwarePlatform/MIOpen/blob/a0c73f544d3db86511f8a521a34198cba5939ac7/src/ocl/tensorocl.cpp#L1286 which explicitly breaks the rule and allows following combinations: A:1x1x3 and B:1x100x3.

The problem is `Op2dTensorSquash` does not pass tensor_ops tests but it is used in RNN tests and RNN relies on its behavior (when I force to use any non-squashed version which pass tensot_ops tests, it fails RNN tests):
<details>
<summary>Failed log</summary>
```
./bin/test_tensor_ops --float --a 1 1 3 --b 1 3 3 --offsets 0 0 0 --alpha-beta 1 1 1 --packed 1 --sa 1 1 1 --sb 1 1 1 --sc 1 1 1
...
MIOpen(HIP): Info2 [GetKernels] 0 kernels for key: Op2dTensorSquash "1-1-1-1x256x1"                                                              [2296/9067]MIOpen(HIP): Info2 [AddKernel] Key: Op2dTensorSquash "1-1-1-1x256x1"                                                                                        MIOpen(HIP): Info [PrintVersionImpl] COMgr v.2.5.0, USE_HIP_PCH: 1                                                                                          MIOpen(HIP): Info2 [SetIsaName] amdgcn-amd-amdhsa--gfx1030                                                                                                  MIOpen(HIP): Info2 [Log] Kernel MIOpenTensorKernels.cl Compile Time, ms: 223.932                                                                            MIOpen(HIP): Info2 [run] kernel_name = Op2dTensorSquash, global_work_dim = { 256, 1, 1 }, local_work_dim = { 256, 1, 1 }                                    GPU_C[0]: 57.000000                                                                                                                                         GPU_C[1]: 217.000000
GPU_C[2]: 286.000000
GPU_A[0]: 3.000000
GPU_A[1]: 7.000000
GPU_A[2]: 11.000000
GPU_B[0]: 3.000000
GPU_B[1]: 7.000000
GPU_B[2]: 11.000000
GPU_B[3]: 6.000000
GPU_B[4]: 10.000000
GPU_B[5]: 14.000000
GPU_B[6]: 9.000000
GPU_B[7]: 13.000000
GPU_B[8]: 0.000000
MIOpen(HIP): Info2 [default_deallocator] hipFree 36 at 0x7fc19fc02000 Ok
MIOpen(HIP): Info2 [default_deallocator] hipFree 12 at 0x7fc19fc01000 Ok
MIOpen(HIP): Info2 [default_deallocator] hipFree 12 at 0x7fc19fc00000 Ok
c[0](3.000000) = a[0](3.000000) * b[0](3.000000)
c[1](7.000000) = a[1](7.000000) * b[1](7.000000)
c[2](11.000000) = a[2](11.000000) * b[2](11.000000)
CPU_C[0]: 12.000000
CPU_C[1]: 56.000000
CPU_C[2]: 132.000000
./bin/test_tensor_ops --float --a 1 1 3 --b 1 3 3 --sa 1 1 1 --sb 1 1 1 --sc 1 1 1 --offsets 0 0 0 --alpha-beta 1 1 1 --packed 1
FAILED: 0.458838
Iteration: 0
TensorOp:
A tensor: 1, 1, 3
B tensor: 1, 3, 3
C tensor: 1, 1, 3
Offsets: 0,0,0
Max diff: 161
Mismatch at 0: 12 != 57
```
</details>

Currently to run such tests the check at https://github.com/ROCmSoftwarePlatform/MIOpen/blob/a0c73f544d3db86511f8a521a34198cba5939ac7/test/tensor_ops.cpp#L317 should be disabled, since it verifies normal tensor operations requirements and `squashed` version is out of this scope.

**Comment by muralinr** [comment]
@CAHEK7 Sure, if you want to add another test exclusively for 2D tensors, please feel free to add it.  However, we are not doing an active development for OpenCL kernels.

**Comment by CAHEK7** [comment]
I would like to remove the squashed version from the tensor operation at all. I'm not talking about the tests only. Move it to squashed tensor ops or something like this. (and keep ocl version as it is).

The rest of the tensor operations will be optimized and rewritten on hip. As about the optimizations - check pr #2262

**Comment by CAHEK7** [comment]
@muralinr 
The main concern is `Op2dTensorSquash` resides in 3d operations and moreover it does not behave like all the other operations and there are no direct tests for it. Somebody may wrongly call OpTensor3d expecting elementwise operations and got squashed version instead. There is no explicit difference between `Op2dTensorSquash`, `Op2dTensorLite` and `Op3dTensorGeneric`.
But the last two behaves identically, `Lite` version is just an optimized special case which can be verified by `Generic` version, while `Op2dTensorSquash` produces completely different results.

**Comment by muralinr** [comment]
@CAHEK7 Op2dTensorSquash kernel is used by RNNs (LSTM) currently.  I will run some of these RNN configs and provide you more info.

**Comment by muralinr** [comment]
@CAHEK7 The following RNN config will be using Op2dTensorSquash kernel.

./bin/MIOpenDriver rnnfp16 -n 224 -W 224 -H 1000 -l 8 -b 1 -m lstm -p 0 -r 0 -k 32 -F 4 -t 1 -w 1

**Comment by junliume** [comment]
@CAHEK7 please remind me if there is a fix WIP?

**Comment by muralinr** [comment]
@CAHEK7 Can you please run below tests which calls tensor operations?  

./bin/MIOpenDriver rnnfp16 -n 224 -W 224 -H 1000 -l 8 -b 1 -m lstm -p 0 -r 0 -k 32 -F 2 -t 1 -w 1
./bin/MIOpenDriver rnnfp16 -n 224 -W 224 -H 1000 -l 8 -b 1 -m lstm -p 0 -r 0 -k 32 -F 4 -t 1 -w 1
./bin/MIOpenDriver rnnfp16 -n 224 -W 224 -H 1000 -l 8 -b 1 -m lstm -p 0 -r 0 -k 32 -c 0 -F 1 -t 1 -w 1

**Comment by CAHEK7** [comment]
> @CAHEK7 please remind me if there is a fix WIP?

For this particular issue I don't know what should be fixed. The problem is that it passes RNN tests, but fails direct tensor_ops test and vice versa - if the kernel passes direct test it fails rnn. So 2d squashed operation is not the typical operation and can only be distinguished by specific 3d tensor configuration which also violates tensor ops paradigm.

My proposal is to move that squashed operation out of the tensors operations and add all of the required tests and infrastructure.

**Comment by atamazov** [comment]
Squash came from here: https://github.com/ROCmSoftwarePlatform/MIOpen/commit/df1cb2ac2a107ad9e7ffe88009fa7c19cb7588d0

**Comment by CAHEK7** [comment]
Since OpTensor is a part of external API, this squashed version must be removed from it as it violates the rules of tensor operations.

As for temporary solution, I suggest to introduce a flag which will be `false` by default and for all the external API calls and tests, but for direct call from RNN code it will be set to `true` to enable non-conformant behavior.

Later squashed version will be completely removed from OpTensor to some separated entity.
