### ISSUE TITLE
Cache CK convolution kernel objects as shared_ptr in Invoker lambda

### ISSUE THREAD

**Issue by amberhassaan** [ROCmSoftwarePlatform/MIOpen#2336]
`CK` has a `DeviceOpFactory::GetInstances()` API used by MIOpen Solvers that returns a `vector<unique_ptr<T>`, where `T` is an abstraction for a kernel. `unique_ptr<T>` makes it uncacheable inside MIOpen's `Invoker` lambda thus preventing reuse and forcing multiple calls to `GetInstances()` especially at the time of invoking a kernel. 

I will put up a PR that promotes `unique_ptr<T>` to `shared_ptr<T>` thus allowing us to cacheable inside MIOpen's `Invoker`.

**Comment by atamazov** [comment]
[Notice] IIUC this ticket is related to all CK solvers where this optimization is possible (see https://github.com/ROCmSoftwarePlatform/MIOpen/pull/2305#issuecomment-1693677130)
