### ISSUE TITLE
[pooling][average][FP16] PoolingBackwardNd: Correctness problems with big tensors

### ISSUE THREAD

**Issue by atamazov** [ROCmSoftwarePlatform/MIOpen#2344]
Tested on Navi21 and gfx906/60, ROCm 5.4 and 5.7 RC. The problem is inherent to averaging modes only, similar to #2109. Most likely, the reason is that computations are performed in FP16 domain which leads to overflow when the number of FP ops is big.

Examples:

```bash
./bin/test_pooling3d --half --index_type miopenIndexUint32 --mode miopenPoolingAverage --verify_indices 1 --input 1 64 1 410 400 --lens 1 409 399 --strides 1 1 1 --pads 0 0 0 --wsidx 0 -F 1 --disable-verification-cache -v
FAILED: 0.721753
Max diff: 0.0429382
Gpu data is all zeros
Mismatch at 0: 0.00105953 != 0
Backward Pooling: Average
Lengths: 1, 409, 399
Pads: 0, 0, 0
Strides: 1, 1, 1
Input tensor: 1, 64, 1, 410, 400
Output tensor: 1, 64, 1, 2, 2
```

```bash
./bin/test_pooling3d --half --index_type miopenIndexUint32 --mode miopenPoolingAverage --verify_indices 1 --input 1 64 11 41 400 --lens 10 40 399 --strides 1 1 1 --pads 0 0 0 --wsidx 0 -F 1 --disable-verification-cache -v
...
FAILED: 0.734635
Max diff: 0.0778198
Gpu data is all zeros
Mismatch at 0: 0.00108337 != 0
Backward Pooling: Average
Lengths: 10, 40, 399
Pads: 0, 0, 0
Strides: 1, 1, 1
Input tensor: 1, 64, 11, 41, 400
Output tensor: 1, 64, 2, 2, 2
```

```bash
./bin/test_pooling3d --half --index_type miopenIndexUint32 --mode miopenPoolingAverageInclusive --verify_indices 1 --wsidx 1 --input 1 3 1 256 256 --lens 1 180 180 --strides 1 1 1 --pads 0 0 0 --disable-verification-cache -v
...
FAILED: 0.255373
Max diff: 80.5
Mismatch at 0: 0.00533676 != 0.00534058
Backward Pooling: AverageInclusive
Lengths: 1, 180, 180
Pads: 0, 0, 0
Strides: 1, 1, 1
Input tensor: 1, 3, 1, 256, 256
Output tensor: 1, 3, 1, 77, 77
```

----
[Attribution] @junliume @JehandadKhan
- https://github.com/ROCmSoftwarePlatform/MIOpen/labels/bug
- https://github.com/ROCmSoftwarePlatform/MIOpen/labels/urgency_blocker
- Proposed assignees: @atamazov 
  - Actually I am fixing this altogether with implementing backward pooling support for big tensors, because this bug blocks my work.

**Comment by CAHEK7** [comment]
I guess it is called loss of precision problem when `100+0.001=100` but `1+0.001=1.001` (it's just an example for 4 digits).
I faced this problem on reduction kernels test and had to clamp input data range to avoid small or denormal numbers.

**Comment by atamazov** [comment]
The root reason is identified: the reference data on CPU is computed in fp16 domain.
