### ISSUE TITLE
Tuning set for 2.5

### ISSUE THREAD

**Issue by daniellowell** [ROCmSoftwarePlatform/MIOpen#237]
#### gfx900-56cu / gfx900-64cu
iGEMM, fp32 only -- all Recurrent
3D convolution iGEMM, fp32 -- all configs
All solvers, fp32 only -- batch size 1

#### gfx906-60cu / gfx906-60cu
iGEMM, fp32-fp16  -- all Recurrent
3D convolution iGEMM, fp32 -- all configs
All solvers, fp32-fp16              -- batch size 1

#### gfx908 
iGEMM, fp32, fp16, bfp16 -- ResNet50 and ResNext101

**Comment by daniellowell** [comment]
And anything missed from this ticket: https://github.com/ROCmSoftwarePlatform/MIOpen/issues/161

**Comment by alexandraBara** [comment]
> And anything missed from this ticket: #161

On this ticket, where are the Driver cmds? are they under "Test Cases to Replicate Issue"?

**Comment by alexandraBara** [comment]
configs tagged so far:
"recurrent"
"3d"
"obsolete" - taken from http://ontrack-internal.amd.com/browse/SWDEV-234450

**Comment by cderb** [comment]
[miopen_benchmark.zip](https://github.com/ROCmSoftwarePlatform/MIOpen/files/4747340/miopen_benchmark.zip)
performance comparison

**Comment by JehandadKhan** [comment]
### Performance Comparison

| Model         |  precision |  batchsize | This PR |  develop | Speed Up over develop |
|---------------|------------|------------|---------|----------|-----------------------|
| inception3    |  fp32      | 128        | 123.12  | 108.39   | 113.59%               |
| inception3    |  fp16      | 128        | 90.29   | 76.36    | 118.24%               |
| inception4    |  fp32      | 64         | 54.54   | 56.06    | 97.29%                |
| inception4    |  fp16      | 64         | 44.69   | 36.52    | 122.37%               |
| resnet101     |  fp32      | 64         | 113.71  | 110.63   | 102.78%               |
| resnet101     |  fp16      | 64         | 116.23  | 115.99   | 100.21%               |
| resnet50      |  fp32      | 128        | 197.46  | 197.55   | 99.95%                |
| resnet50      |  fp16      | 128        | 206.5   | 207.35   | 99.59%                |
| resnet50_v1.5 |  fp32      | 64         | 172.4   | 168.16   | 102.52%               |
| resnet50_v1.5 |  fp16      | 64         | 176.42  | 176.48   | 99.97%                |
