### ISSUE TITLE
Wrong workspace calculation/allocation disallows running xdlops bwd v1r1 kernels 

### ISSUE THREAD

**Issue by TejashShah** [ROCmSoftwarePlatform/MIOpen#238]
When running fp16 configs through MIOpenDriver with all fwd/wrw/bwd directions (default behavior), often backward v1r1 xdlops kernels are not running due to workspace check.

Steps to reproduce:

1. Fetch the tip of develop (ef1c1925fcd3d76c31769272da175947923b9ae2)

2. 
export MIOPEN_DEBUG_AMD_WINOGRAD_RXS_WRW=0
export MIOPEN_DEBUG_AMD_ROCM_PRECOMPILED_BINARIES=0
export MIOPEN_DEBUG_GCN_ASM_KERNELS=0
export MIOPEN_DEBUG_CONV_FFT=0
export MIOPEN_DEBUG_CONV_DIRECT=0
export MIOPEN_GEMM_ENFORCE_BACKEND=3
export MIOPEN_LOG_LEVEL=6
export MIOPEN_ENABLE_LOGGING=1
export MIOPEN_DEBUG_IMPLICIT_GEMM_XDLOPS_INLINE_ASM=1
export MIOPEN_DEBUG_CONV_IMPLICIT_GEMM_XDLOPS=1
export MIOPEN_FIND_ENFORCE=1

3. 
MIOpenDriver convfp16 -V 0 -n 128 -c 1024 -H 14 -W 14 -k 1024 -y 1 -x 1 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -g 1 -t 1 

MIOpen Forward Conv. Algorithm: 5, Solution: 51/ConvHipImplicitGemmV4R4GenFwdXdlops
GPU Kernel Time Forward Conv. Elapsed: 2.269941 ms (average)
**MIOpen(HIP): Info [EvaluateInvokers] Skipping solver <ConvHipImplicitGemmBwdDataV1R1Xdlops> due to insufficient workspace (102760448 < 102760448)
MIOpen Error: /PublicMIOpen/src/ocl/convolutionocl.cpp:2633: Backward Data Algo cannot be executed**
MIOpen Backward Weights Conv. Algorithm: 5, Solution: 50/ConvHipImplicitGemmV4R4WrWXdlops
GPU Kernel Time Backward Weights Conv. Elapsed: 13.954194 ms (average)
**RunBackwardGPU() failed, rc = 0x7**

When I run the same config with '-F 2' option i.e. run only backward data, it passes.

MIOpenDriver convfp16 -V 0 -n 128 -c 1024 -H 14 -W 14 -k 1024 -y 1 -x 1 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -g 1 -t 1 -F 2

The same problem exists for convbfp16 as the underlying solver is the same for fp16 and bfp16.  The problem is generic enough regardless of config.

This problem wasn't present in this commit: 41a9a4712bdad7a87d8c596db3515c58b1f0a379

**Comment by atamazov** [comment]
We'll look into this. However we can't reproduce this as we do not have access to the necessary HW.

@dagamayank @daniellowell

**Comment by atamazov** [comment]
We'll look into this. However we can't reproduce this as we do not have access to the necessary HW. Please assign somebody else.

@dagamayank @daniellowell

**Comment by atamazov** [comment]
We'll be able to help better if the following steps done:
1. Identifying the failing commit in the range [41a9a47, ef1c192]
1. Collecting logs with level 6 from the failing commit and the one that immediately precedes it.
1. Attaching these logs here.

**Comment by TejashShah** [comment]
> 
> 
> We'll be able to help better if the following steps done:
> 
>     1. Identifying the failing commit in the range [[41a9a47](https://github.com/ROCmSoftwarePlatform/MIOpen/commit/41a9a4712bdad7a87d8c596db3515c58b1f0a379), [ef1c192](https://github.com/ROCmSoftwarePlatform/MIOpen/commit/ef1c1925fcd3d76c31769272da175947923b9ae2)]

commit ec00901b745ee38002120ae5e1d178829584e650 
> 
>     2. Collecting logs with level 6 from the failing commit and the one that immediately precedes it.
> 
>     3. Attaching these logs here.

Shared debug.log at 
https://amdcloud-my.sharepoint.com/:u:/g/personal/teshah_amd_com/EVdaXsFzdKVDn0KAooXIgR0BrDMlee8B0bjnd1ej4QzxcA

Please let me know if you could access the file as it's first attempt.

**Comment by atamazov** [comment]
Oops, wait...

**Comment by atamazov** [comment]
This is either driver or library problem... Does test_conv2d succeed when run with this config?

**Comment by TejashShah** [comment]
> 
> 
> This is either driver or library problem... Does test_conv2d succeed when run with this config?

As I mentioned earlier, it works fine when you run MIOpenDriver command "-F 2". Only when all directions are run one after another it misbehaves.

**Comment by atamazov** [comment]
`test_conv2d` is not a driver.

**Comment by atamazov** [comment]
> Shared debug.log at https://amdcloud-my.sharepoint.com/:u:/g/personal/teshah_amd_com/EVdaXsFzdKVDn0KAooXIgR0BrDMlee8B0bjnd1ej4QzxcA

I do not have access to amdcloud.

**Comment by atamazov** [comment]
> `test_conv2d` is not a driver.

@TejashShah please run Bwd-only with `test_conv2d`:
```
./bin/test_conv2d --half --cmode conv --pmode default --group-count 1 \
--input 128 1024 14 14 --weights 1024 1024 1 1 \
--pads_strides_dilations 0 0 1 1 1 1 \
--disable-forward \
--disable-backward-weights \
--disable-validation \
--verbose
```
and all directions:
```
./bin/test_conv2d --half --cmode conv --pmode default --group-count 1 \
--input 128 1024 14 14 --weights 1024 1024 1 1 \
--pads_strides_dilations 0 0 1 1 1 1 \
--disable-validation \
--verbose
```
This would tell us if the problem is in the driver of in the library. Thanks!

**Comment by TejashShah** [comment]
It looks good. So, no problem in the library. Just a driver, perhaps.

root@rocm-framework-7:/PublicMIOpen/pr-hip-build-33# ./bin/test_conv2d --half --cmode conv --pmode default --group-count 1 \
> --input 128 1024 14 14 --weights 1024 1024 1 1 \
> --pads_strides_dilations 0 0 1 1 1 1 \
> --disable-validation \
> --verbose
./bin/test_conv2d --half --cmode conv --pmode default --group-count 1 --input 128, 1024, 14, 14 --weights 1024, 1024, 1, 1 --pads_strides_dilations 0 0 1 1 1 1 --trans_output_pads 0 0
MIOpen(HIP): Warning [Prefetch] File is unreadable: /PublicMIOpen/src/kernels/gfx90878.HIP.fdb.txt
Forward convolution: ConvHipImplicitGemmV4R4GenFwdXdlops
Input tensor: 128, 1024, 14, 14
Weights tensor: 1024, 1024, 1, 1
Output tensor:
Filter: conv2d, miopenConvolution, miopenPaddingDefault, {0, 0}, {1, 1}, {1, 1},
./bin/test_conv2d --half --cmode conv --pmode default --group-count 1 --input 128, 1024, 14, 14 --weights 1024, 1024, 1, 1 --pads_strides_dilations 0 0 1 1 1 1 --trans_output_pads 0 0
Backward convolution: ConvHipImplicitGemmBwdDataV1R1Xdlops
Input tensor: 128, 1024, 14, 14
Weights tensor: 1024, 1024, 1, 1
Output tensor: 128, 1024, 14, 14
Filter: conv2d, miopenConvolution, miopenPaddingDefault, {0, 0}, {1, 1}, {1, 1},
./bin/test_conv2d --half --cmode conv --pmode default --group-count 1 --input 128, 1024, 14, 14 --weights 1024, 1024, 1, 1 --pads_strides_dilations 0 0 1 1 1 1 --trans_output_pads 0 0
Backward weights convolution: ConvAsmBwdWrW1x1
Input tensor: 128, 1024, 14, 14
Weights tensor: 1024, 1024, 1, 1
Output tensor: 128, 1024, 14, 14
Filter: conv2d, miopenConvolution, miopenPaddingDefault, {0, 0}, {1, 1}, {1, 1},

**Comment by atamazov** [comment]
> MIOpen(HIP): Info [EvaluateInvokers] Skipping solver due to insufficient workspace (102760448 < 102760448)

This weird message means that nullptr is passed. Most likely this is a driver bug, introduced recently.

**Comment by atamazov** [comment]
This should be fixed by #296

**Comment by atamazov** [comment]
Let's check if the current driver has this problem (and hopefully close).

**Comment by daniellowell** [comment]
@TejashShah please verifiy

**Comment by TejashShah** [comment]
The test passed. I no longer see 
"
MIOpen(HIP): Info [EvaluateInvokers] Skipping solver due to insufficient workspace (102760448 < 102760448)
MIOpen Error: /PublicMIOpen/src/ocl/convolutionocl.cpp:2633: Backward Data Algo cannot be executed
MIOpen Backward Weights Conv. Algorithm: 5, Solution: 50/ConvHipImplicitGemmV4R4WrWXdlops
GPU Kernel Time Backward Weights Conv. Elapsed: 13.954194 ms (average)
RunBackwardGPU() failed, rc = 0x7
"

It was able to run all passes with a single command.
root@rocm-framework-7:/devMIOpen/dev-hipclang-build# MIOpenDriver convfp16 -V 1 -n 128 -c 1024 -H 14 -W 14 -k 1024 -y 1 -x 1 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -g 1 -t 1 2>&1 | tee issue238_ver.log
root@rocm-framework-7:/devMIOpen/dev-hipclang-build# egrep "GPU Kernel Time|Solution:" issue238.log
MIOpen Forward Conv. Algorithm: 5, Solution: 64/ConvHipImplicitGemmForwardV4R4Xdlops
GPU Kernel Time Forward Conv. Elapsed: 0.722718 ms (average)
MIOpen Backward Data Conv. Algorithm: 5, Solution: 60/ConvHipImplicitGemmBwdDataV4R1Xdlops
GPU Kernel Time Backward Data Conv. Elapsed: 0.745367 ms (average)
MIOpen Backward Weights Conv. Algorithm: 5, Solution: 52/ConvHipImplicitGemmV4R4GenWrWXdlops
GPU Kernel Time Backward Weights Conv. Elapsed: 8.207568 ms (average)
