### ISSUE TITLE
Error  in db_path.cpp on Windows

### ISSUE THREAD

**Issue by scarsty** [ROCmSoftwarePlatform/MIOpen#2415]
I have built miopen.dll on Windows (with many many tricks) with HIP backend.
But when I tried to run a simple active, I got:
```
MIOpen Error: D:/project/MIOpen/build-msvc/db_path.cpp:62:
```
Is there any suggestion or currently it cannot work on Windows? The card is 7900xtx.

**Comment by junliume** [comment]
@apwojcik do you observe similar issues?
currently it is expected that
```
#ifdef __linux__
...
#else
MIOPEN_THROW(miopenStatusNotImplemented);
#endif
```

**Comment by scarsty** [comment]
> @apwojcik do you observe similar issues? currently it is expected that
> 
> ```
> #ifdef __linux__
> ...
> #else
> MIOPEN_THROW(miopenStatusNotImplemented);
> #endif
> ```

I think db_path prevent the running is a bad idea.

**Comment by apwojcik** [comment]
There is a patch coming that implements that part on Windows. It still needs to be submitted. It depends on PRs already pending review, so I will submit it as soon as they merge.
@scarsty After merging all Windows PRs, the MinGW32 and cross-compilation will not be possible. We do not plan to keep support for MinGW32 and cross-compilation on Linux. Only native Windows compilation will be possible.

**Comment by scarsty** [comment]
> There is a patch coming that implements that part on Windows. It still needs to be submitted. It depends on PRs already pending review, so I will submit it as soon as they merge. @scarsty After merging all Windows PRs, the MinGW32 and cross-compilation will not be possible. We do not plan to keep support for MinGW32 and cross-compilation on Linux. Only native Windows compilation will be possible.

Is there any way to patch it myself?

I think to drop the supporting MINGW32 is good, as the clang++ released with rocm cannot support target of mingw32-gnu. And I have found some probable problems to share.

There are many assert in `amd_warp_functions.h`, like:
```c++
    #ifndef _MSC_VER
    static_assert(sizeof(long) == 2 * sizeof(int), "");
    static_assert(sizeof(long) == sizeof(uint64_t), "");
    ...
    #else
    static_assert(sizeof(long) == sizeof(int), "");
    ...
    #endif
```
`_MSC_VER` should be replaced with `_WIN32`, or clang with gnu libraries will fail here.

The long and int types is mixed used in boost, after checking the code of boost, I cannot understand why it happened. 

In `type_names.hpp`, typeid().name() is const char*.

Some head files are lost on Windows.

Link to hiprtc is lost.

**Comment by scarsty** [comment]
I found the hip-clang++ has a definition of __LP64__, which should not exist on Windows, and triggered a series of errors in boost.
So I advise to use MSVC, if the macro is hard to removed.

**Comment by scarsty** [comment]
These problems are solved in branch uif2-initial so we can close it.
