### ISSUE TITLE
Do not crash on malformed perf configs for CK kernels.

### ISSUE THREAD

**Issue by CAHEK7** [ROCmSoftwarePlatform/MIOpen#2426]
Based on https://github.com/ROCmSoftwarePlatform/MIOpen/pull/2379#discussion_r1323604344

Instead of throwing an exception for bad perf config it's better to return an error and handle it gracefully.

> When CK cannot find a good solution, instead of throwing an exception, we should return ConvSolution(miopenStatusInvalidValue). Why: This won't break Find operation, i.e. would improve stability of releases at the users' sites. In all other cases (i.e. attempt to run a convolution) returning a solution with error code would lead to MIOPEN_THROW somewhere in the upper layers of the library.
> 
> Implementation: Maybe the most robust approach is throwing a custom exception and catching it in GetSolution (and then MIOPEN_LOG_E there). You can find example in comgr.cpp (which handles compilation errors).

**Comment by JehandadKhan** [comment]
I prefer the invalid solution approach, more importantly I think we should ensure that we filter this in `IsApplicable` so we dont get to that point at all.

**Comment by CAHEK7** [comment]
It's not about `IsApplicable` function, the situation may happen for various reasons like malformed perfdb or significant changes in CK internals.
