### ISSUE TITLE
Unable to locate package miopen-hip-gfx90a-110kdb for ROCm57

### ISSUE THREAD

**Issue by rui-ren** [ROCmSoftwarePlatform/MIOpen#2433]
### Unable to locate package miopen-hip-gfx90a-110kdb

Cannot find `miopen-hip-gfx90a-110kdb`  from the website: https://repo.radeon.com/rocm/apt/5.7/pool/main/m/

```diff
++ apt install -y miopen-hip-gfx90a-110kdb
Unable to locate package miopen-hip-gfx90a-110kdb
[install_precompiled_kernels.sh] Reading package lists...
[install_precompiled_kernels.sh] Building dependency tree...
[install_precompiled_kernels.sh] Reading state information...
```

If the package name changed again?  

Thanks.

**Comment by rui-ren** [comment]
@jithunnair-amd @junliume  FYI

**Comment by junliume** [comment]
Include @cderb for more clarifications.

I believe we use the same package for all gfx90a now, @cderb  could you check what should be the installation command?
