### ISSUE TITLE
ssh breaks when ctest is run

### ISSUE THREAD

**Issue by JiaJiDuan** [ROCmSoftwarePlatform/MIOpen#2442]
I have successfully built MIOpen-rocm-5.6.0 from source code.  

I use ssh to connect to the remote developer, but whenever I run make check, the ssh connection breaks. I have no idea what the reason is.   

Can someone help me solve this problem?If there is any information I need to provide, please let me know.

**Comment by junliume** [comment]
@JiaJiDuan could you please provide a reproduce procedure? If the remote node offline when you try to run "check" since it will run all unit tests? Or it could be the high CPU/GPU utilization is causing ssh connection to break? Hard to tell from others' side without a minimal reproducible example.

**Comment by JiaJiDuan** [comment]
Sorry, I think this may be a system driven issue, not related to miopen, I will close this issue first.
If a new problem is encountered, I will describe the phenomenon in more detail and open a new issue.
