### ISSUE TITLE
[bug] cmake error at find_program(UNZIPPER lbunzip2 bunzip2)

### ISSUE THREAD

**Issue by JiaJiDuan** [ROCmSoftwarePlatform/MIOpen#2455]
When I try to build projects from source code with tag rocm-5.7.0, cmake reports the following error：
```
-- UNZIPPER-NOTFOUND -k -f /home/marco/workspace/MIOpen/src/kernels/gfx1030_36.db.bz2
CMake Error at CMakeLists.txt:485 (message):
  /home/marco/workspace/MIOpen/src/kernels/gfx1030_36.db could not be
  extracted, file is empty!
Call Stack (most recent call first):
  CMakeLists.txt:496 (unpack_db)
```
I have bunzip2 on my system and I don't have lbunzip2，but that should work too.  
So I think `find_program(UNZIPPER lbunzip2 bunzip2)` should be changed to `find_program(UNZIPPER NAMES lbunzip2 bunzip2)`  on CMakeLists.txt line 473

**Comment by junliume** [comment]
Hi @JiaJiDuan `lbzip2` is recommended since it is parallel. However, indeed if you have `bzip2` it should still work. You are welcome to raise a PR, or we can fix it together with some later PRs.

One other thing I have noticed is whether you have pulled the `git-lfs` files?

**Comment by junliume** [comment]
I see that it has already been fixed with https://github.com/ROCmSoftwarePlatform/MIOpen/pull/2276/files and will be included in our next non-patch release.

**Comment by JiaJiDuan** [comment]
Hi, @junliume .Thank you for your reply.  


> I see that it has already been fixed with https://github.com/ROCmSoftwarePlatform/MIOpen/pull/2276/files and will be included in our next non-patch release.  

Great! Looking forward to the next version.  
  
  
   

> `lbzip2` is recommended since it is parallel. However, indeed if you have `bzip2` it should still work.  

The bunzip2 I used was obtained through install_deps.cmake. It does not contain lbunzip2 as a boost dependency.  
I am now using lbunzip2 through `apt install lbzip2`


> One other thing I have noticed is whether you have pulled the `git-lfs` files?

I haven't. I have git-lfs installed, but don't know how to use it.  
Compiled a warning：
```
CMake Warning at CMakeLists.txt:548 (message):
  GIT LFS Files not pulled down, skipped: gfx90a.kdb.bz2; gfx1030.kdb.bz2;
  gfx908.kdb.bz2; gfx906.kdb.bz2; gfx900.kdb.bz2
```
This probably doesn't matter to me because my `AMDGPU` is gfx1102. But I still want to know how to use git-lfs in this project.  
>
>
Looking forward to your reply.

**Comment by junliume** [comment]
Hi @JiaJiDuan here is the script I usually use, and you can modify based on your need:
```
export LC_ALL=C.UTF-8 && \
export LANG=C.UTF-8 && \
apt-get update -y && \
apt-get install -y sudo && \
sudo apt-get -y install git git-lfs unzip lbzip2 python3.9-venv pkg-config vim ninja-build half && \
sudo apt update && \
cd /root && git clone -b develop https://github.com/ROCmSoftwarePlatform/MIOpen && cd MIOpen && \
git-lfs pull --exclude= && \
mkdir -p install_dir && cmake -P install_deps.cmake --minimum --prefix /root/MIOpen/install_dir && \
mkdir -p build && \
cd build && \
CXX=/opt/rocm/llvm/bin/clang++ CC=/opt/rocm/llvm/bin/clang cmake -DMIOPEN_BACKEND=HIP -DCMAKE_PREFIX_PATH="/root/MIOpen/install_dir;/opt/rocm" \
-DMIOPEN_TEST_ALL=On -DMIOPEN_TEST_HALF=On .. && \
make -j$(nproc) install
```
The KDB files are for pre-compiled kernel caches, which for `gfx1102` is not yet available.

**Comment by JiaJiDuan** [comment]
Hi, @junliume .Thank you for your reply. I'll look at your script carefully.  
I will close this issue.   
In the future, if I have new doubts, I will open a new issue.

**Comment by JiaJiDuan** [comment]
Hi,@junliume. Thank you for your reply. I'll look at your script carefully.
I will close this issue.
In the future, if I have new doubts, I will open a new issue.
