### ISSUE TITLE
MIGraphX tuning 

### ISSUE THREAD

**Issue by JehandadKhan** [ROCmSoftwarePlatform/MIOpen#247]
[Link to file](https://github.com/mvermeulen/rocm-migraphx/blob/7c249f732cff60e2eba77826b390afb3169382ea/dockerfiles/miopen/gfx906_60.HIP.2_3_0.ufdb.txt#L1)

The above file is a find db with the configs needed to be tuned.

**Comment by alexandraBara** [comment]
these need to be tuned this tuning session?

**Comment by JehandadKhan** [comment]
I believe no, @daniellowell  would you agree ?

**Comment by alexandraBara** [comment]
OK, regardless I tagged them with "issue247"
