### ISSUE TITLE
Create Project to track status of Windows impementation

### ISSUE THREAD

**Issue by Joly0** [ROCmSoftwarePlatform/MIOpen#2475]
Hey, it would be great, if there was a project here https://github.com/ROCmSoftwarePlatform/MIOpen/projects?type=classic for windows support aswell. I can assume some are waiting to use it and it would be great to know, how much work still needs to be done and how much has already been done to implement it.

**Comment by junliume** [comment]
Done. Next step is to associate all Windows Enablement related PRs to that project :)

**Comment by Joly0** [comment]
> Done. Next step is to associate all Windows Enablement related PRs to that project :)

Thanks for that :D It´ll definitely help people, once all the related PRs are associated

**Comment by Joly0** [comment]
@junliume Will (or better when will) the PRs get associated with the Project?
