### ISSUE TITLE
Adopt Google Style Guide for C++ in order to improve consistency in coding style

### ISSUE THREAD

**Issue by amberhassaan** [ROCmSoftwarePlatform/MIOpen#2482]
As the title says [Google Style Guide for C++](https://google.github.io/styleguide/cppguide.html) is fairly detailed down to how to name methods and class members. I personally don't agree with everything it has to offer but I'm hoping that we can all agree to use it so that we don't need to have any code style discussions. 
Another goal is to improve the quality of the code (in addition to style) in terms of abstraction, robustness and performance (The style guide has a small number of recommendations on  that front). 

We can also make agreed upon deviations from the style guide when necessary as long as we document it here or some other document. 

@junliume @JehandadKhan @CAHEK7 @DrizztDoUrden @averinevg @atamazov @cderb @iq136boy @bghimireamd : please share your opinion. CC: @ROCmSoftwarePlatform/miopen-devs

**Comment by junliume** [comment]
@amberhassaan we may convert this issue into discussion.

**Comment by amberhassaan** [comment]
oh, sorry, didn't know github has that feature. Let me move this to a discussion: https://github.com/ROCmSoftwarePlatform/MIOpen/discussions/2483

Closing this issue.
