### ISSUE TITLE
local memory limit exceeded 

### ISSUE THREAD

**Issue by reger-men** [ROCmSoftwarePlatform/MIOpen#25]
Input shape    = [1,3,800,1280]
output shape  = [1,3,50,80]
`miopenPoolingForward` return `error: local memory limit exceeded (72900) in mloPooling`
even if increase the shape output to [1,3,100,160], still get this error.

`miopenPoolingForward` work only if i want to halve the input shape.

Any idea, how to fix this? thanks.

**Comment by dagamayank** [comment]
@reger-men Thanks for reporting the issue and apologies for the delay in my relay. We have fixed this bug and it will available in the next release.

**Comment by reger-men** [comment]
@dagamayank Thank you for your reply. Could you please tell me on which branch did you fix this issue? I would like to use it.

**Comment by dagamayank** [comment]
@reger-men Try on the master branch now.
