### ISSUE TITLE
[test_handle_test][ROCm 3.3] test_multithreads() failure

### ISSUE THREAD

**Issue by atamazov** [ROCmSoftwarePlatform/MIOpen#254]
Test fails with 
```
FAILED: data_out == data_in: /home/atamazov/github/MLOpen1/test/handle_test.cpp: 80
FAILED: data_out == data_in: /home/atamazov/github/MLOpen1/test/handle_test.cpp: 80
```
~The reason is sharing MIOpen handle between threads. Setting `MIOPEN_TEST_USE_GLOBAL_HANDLE` to 0 in `...test/get_handle.hpp` resolves the issue.~

Note that the issue is not reproducible with ROCm 3.5.

I am wondering if ROCm 3.3 and its predecessors have problems with this, and if this affects the stability of our tests on Jenkins.

**Comment by pfultz2** [comment]
The handle is used across multiple threads but not at the same time. The test is there to ensure that this can be safely done. In addition, switching `MIOPEN_TEST_USE_GLOBAL_HANDLE` wouldn't make a difference since it calls `get_handle()` once and reuses that handle multiple times across the different threads.

**Comment by atamazov** [comment]
@pfultz2 Sorry for confusion, the description was incomplete.

The patch that workarounds the issue is attached. In short:
```C++
void test_multithreads(kernel_type_t kern_type)
{
    auto&& h = get_handle();
    auto&& h1 = get_handle();
    auto&& h2 = get_handle();
    auto&& h3 = get_handle();
    std::thread([&] { run2s(h1, 16, kern_type); }).join();
    std::thread([&] { run2s(h2, 32, kern_type); }).join();
    std::thread([&] { std::thread([&] { run2s(h3, 64, kern_type); }).join(); }).join();
    run2s(h, 4, kern_type);
}
```
Both unmodified test and this test fail. With `MIOPEN_TEST_USE_GLOBAL_HANDLE` to 0, modified test is passing.

**Comment by atamazov** [comment]
Note that the issue is not reproducible with ROCm 3.5, so lowering the priority.

I am wondering if ROCm 3.3 and its predecessors have problems with this, and if this affects the stability of our tests on Jenkins.

**Comment by atamazov** [comment]
I think this is ROCm 3.3 specific problem unrelated to the MIOpen.
