### ISSUE TITLE
[Issue]: [Tests] test_handle_test will fail under DEV builds

### ISSUE THREAD

**Issue by junliume** [ROCmSoftwarePlatform/MIOpen#2600]
### Problem Description

`test_handle_test` is a reverse test, however it checks for `failed` keyword, and in the following code, MIOpen will emit error under DEV configuration.

https://github.com/ROCm/MIOpen/blob/a64e600360eccab11d2e9423f362bbd839f1e9e7/test/handle_test.cpp#L234-L261

```
1 error generated when compiling for gfx1100.
MIOpen(HIP): Info2 [AddKernel] Key: NoAlgo ""
MIOpen(HIP): Info2 [Log] Kernel nop_hip.cpp Compile Time, ms: 215.881
MIOpen(HIP): Error [auto test_warnings] FAILED: Build of the HIP kernel 'nop_hip.cpp' should produce warnings
CMake Error at test_test_handle_test.cmake:7 (message):
  Test failed
```

ref: https://github.com/ROCm/MIOpen/pull/1729#discussion_r961254193

### Operating System

Ubuntu 22.04.3 LTS

### CPU

AMD Ryzen Threadripper 3960X

### GPU

AMD Radeon RX 7900 XT

### ROCm Version

ROCm 5.7.1

**Comment by junliume** [comment]
@atamazov it seems that "Build of the HIP kernel 'nop_hip.cpp' should produce warnings" now fails, probably due to hipRTC changes?

**Comment by pfultz2** [comment]
> it seems that "Build of the HIP kernel 'nop_hip.cpp' should produce warnings" now fails, probably due to hipRTC changes?

Yes, we've seen the same issue with migraphx. I believe hiprtc team has a fix.

**Comment by junliume** [comment]
Confirmed that hipRTC is working on a fix and PR ready.

**Comment by atamazov** [comment]
@junliume 
> @junliume closed this as completed...

...via #2519
