### ISSUE TITLE
[ROCm3.5][Driver] miopenGcnAsmWinogradXformData_7_7_2_2: Memory access fault by GPU node-2

### ISSUE THREAD

**Issue by atamazov** [ROCmSoftwarePlatform/MIOpen#264]
ROCm3.5, Radeon VII, develop at e65e04ac1df4f. CMake command line:
```bash
CXX=/opt/rocm/llvm/bin/clang++ \
CXXFLAGS=-O0 \
cmake \
-DBUILD_DEV=On \
-DCMAKE_BUILD_TYPE=debug \
-DMIOPEN_GPU_SYNC=On \
-DCMAKE_CXX_FLAGS_DEBUG=-g \
-fno-omit-frame-pointer \
-fsanitize=undefined \
-fno-sanitize-recover=undefined \
-DMIOPEN_TEST_FLAGS=--disable-verification-cache ../..
```
Failing config:
```
$ ./bin/MIOpenDriver conv -n 1 -c 3 -H 32 -W 32 -k 1 -c 3 -y 7 -x 7 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -V 0 -F 0
...
Memory access fault by GPU node-2 (Agent handle: 0x247cb00) on address (nil). Reason: Page not present or supervisor privilege.
```

## Triaging

- The issue disappears with `-F 4` (WrW only):
```
MIOpen(HIP): Info [FindConvBwdWeightsAlgorithm] ConvBinWinogradRxS: miopenSp3AsmConvRxSf3x2: 0.11072 < 3.40282e+38
MIOpen(HIP): Info [FindConvBwdWeightsAlgorithm] ConvBinWinogradRxSf2x3: miopenSp3AsmConv_group_20_5_23_M_stride1: 0.06672 < 0.11072
MIOpen(HIP): Info [FindConvBwdWeightsAlgorithm] ConvWinograd3x3MultipassWrW<7-2>: miopenGcnAsmWinogradXformData_7_7_2_2/miopenGcnAsmWinogradXformFilter_7_7_2_2/miopenGcnAsmWinogradXformOut_7_7_2_2: 0.09536 >= 0.06672
MIOpen(HIP): Info [FindConvBwdWeightsAlgorithm] ConvWinograd3x3MultipassWrW<7-3>: miopenGcnAsmWinogradXformData_7_7_3_3/miopenGcnAsmWinogradXformFilter_7_7_3_3/miopenGcnAsmWinogradXformOut_7_7_3_3: 0.0712 >= 0.06672
MIOpen(HIP): Info [FindConvBwdWeightsAlgorithm] Selected: ConvBinWinogradRxSf2x3: miopenSp3AsmConv_group_20_5_23_M_stride1: 0.06672, workspce_sz = 0
```
[pass.log](https://github.com/ROCmSoftwarePlatform/MIOpen/files/4733293/pass.log)
[fail.log](https://github.com/ROCmSoftwarePlatform/MIOpen/files/4733294/fail.log)

- Disabling all algos except Winograd doesn't help. I.e. when run with `-F 0`, driver fails at WrW Find phase, after evaluating `ConvBinWinogradRxS` and `ConvBinWinogradRxSf2x3` (during evaluation of `ConvWinograd3x3MultipassWrW<7-2>`). Of course, the problem disappears with `-F 4`. Settings:
```
export MIOPEN_DEBUG_CONV_GEMM=0
export MIOPEN_DEBUG_CONV_DIRECT=0
export MIOPEN_DEBUG_CONV_FFT=0
export MIOPEN_DEBUG_CONV_IMPLICIT_GEMM=0
```

Then I played with enabling/disabling individual Winograd Solvers and stopped with the following settings:
```
MIOPEN_DEBUG_AMD_WINOGRAD_RXS=0
MIOPEN_DEBUG_AMD_WINOGRAD_RXS_F2X3=0
MIOPEN_DEBUG_AMD_WINOGRAD_RXS_F3X2=0
MIOPEN_DEBUG_CONV_DIRECT=0
MIOPEN_DEBUG_CONV_GEMM=1
MIOPEN_DEBUG_CONV_IMPLICIT_GEMM=0
````
and got the following (no failure):
```
...Info [FindConvFwdAlgorithm] FW Chosen Algorithm: gemm , 397488, 0.05904...
...Info [FindConvBwdDataAlgorithm] BWD Chosen Algorithm: gemm , 397488, 0.06784...
...Info [FindConvBwdWeightsAlgorithm] BWrW Chosen Algorithm: ConvWinograd3x3MultipassWrW<7-3> , 158268, 0.06304...
```

- At this point enabling either of Winograd RxS solvers brings the `Memory access fault by GPU node-2` failure back.
- Weird effect: enabling `MIOPEN_DEBUG_AMD_WINOGRAD_RXS` or `MIOPEN_DEBUG_AMD_WINOGRAD_RXS_F2X3` also leads to ___very strange failure, as if this somehow disables GEMM___:
```
...Info [FindConvFwdAlgorithm] FW Chosen Algorithm: ConvBinWinogradRxS , 0, 0.04016...
!!! MIOpen Error: /home/atamazov/github/MLOpen1/src/ocl/convolutionocl.cpp:2632: Backward Data Algo cannot be executed !!! ...
```
:red_circle: All the above suggests that the library is somehow messed up.

**Comment by shurale-nkn** [comment]
workspace_dev ptr was corrupted in PR #172 .
workspace_dev was initialized at AllocateBuffersAndCopy().
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/f10b50b844611ab444695b286c06db24deeb7d0e/driver/conv_driver.hpp#L1035-L1040

And corrupted after FindForward(),
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/f10b50b844611ab444695b286c06db24deeb7d0e/driver/conv_driver.hpp#L1657-L1659

FindBackwardData(),
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/f10b50b844611ab444695b286c06db24deeb7d0e/driver/conv_driver.hpp#L2059-L2061

and RunBackwardWrwGpuFind() calls
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/f10b50b844611ab444695b286c06db24deeb7d0e/driver/conv_driver.hpp#L2267-L2269

And it was never restored in Driver. Therefore, each subsequent search was executed with a corrupted pointer. In most cases, workspace_dev = nullptr.

**Comment by atamazov** [comment]
Thank you for detailed analysis, Kamil.

**Comment by atamazov** [comment]
However the code you are pointing to looks valid. Initially, workspace_dev is set up to suit Find() needs. After Find(), the library often needs less workspace. If we give more, then we can miss a bug in the Solver (if it reports less workspace than is actually needs).

The idea is to resize workspace to match the size required for the found algorithm. This has been implemented in #171.

@zjing14, what could be wrong there, any ideas?

**Comment by shurale-nkn** [comment]
@atamazov 
> However the code you are pointing to looks valid. Initially, workspace_dev is set up to suit Find() needs. After Find(), the library often needs less workspace. If we give more, then we can miss a bug in the Solver (if it reports less workspace than is actually needs).

 1)This code cannot guarantee that an error will be found. Buffer reallocation leads only to undefined behavior. Your new small buffer can be located in a previously released one.
Pleas check branch **WSPC_problems**. Here I reduced the size of the reallocated buffer by 2 times, and no errors related to workspace occurred. 


 2)Lets do not mix _Unit testing_ with _Integration testing_.
Unit testing should catch kernel segfaults. MIOpenDriver is not a part of unit testing. It checks the joint functioning of all parts of the system and checking only the fastest solution will not replace unit testing.
For unit testing, you need to check each kernel\solver separately

**Comment by atamazov** [comment]
@shurale-nkn Thanks for feedback.

> This code cannot guarantee that an error will be found.

Of course. However we would like to raise probability that error will be caught.

> Buffer reallocation leads only to undefined behavior. 

OCL/HIP runtime can give bigger buffers than asked (but never smaller). This is not an UB. But we are getting NULL, and the most interesting question is why this happens?

> Here I reduced the size of the reallocated buffer by 2 times, and no errors related to workspace occurred.

This is normal. If you provide smaller buffer than needed, then you definitely step into UB. Errors are not guaranteed.

> Lets do not mix Unit testing with Integration testing.
> Unit testing should catch kernel segfaults....

Unfortunately it seems like you are mixing testing levels and testing types (see https://en.wikipedia.org/wiki/Software_testing). "..._unit testing is a software testing method by which individual units of source code... are tested to determine whether they are fit for use._" The criteria of "_fit for use_" could be correctness, performance, consumed resources and so on.

There could be very rigorous integration tests (when the test tries all possible combinations of inputs and environments and carefully checks for correctness, performance, error handling etc) and very superficial unit tests (like "it passes if compiles without warnings").

> For unit testing, you need to check each kernel\solver separately

I think that we all want to create such tests, but always have more important work to do ;)

> Pleas check branch WSPC_problems. 

___Thanks for providing it. I guess it should somehow help me. Does it fix any issue? Do you recommend using it and looking what happens?___

**Comment by shurale-nkn** [comment]
@atamazov 
>OCL/HIP runtime can give bigger buffers than asked (but never smaller). This is not an UB. But we are getting NULL, and the most interesting question is why this happens?

UB here is result of the testing. In one case buffer reallocated in new place with protected pages on both sides, and we have a segfault. In the other case it is the same place with a large unprotected area and no segfault  will occur. 
And you can't predict which one of them will be now, because new size same or smaller. Plus memory protection works only on page size, there is no guarantee that the buffer size is sufficient. (in this code)

>Unfortunately it seems like you are mixing testing levels and testing types (see https://en.wikipedia.org/wiki/Software_testing). "...unit testing is a software testing method by which individual units of source code... are tested to determine whether they are fit for use." The criteria of "fit for use" could be correctness, performance, consumed resources and so on. 

From your link:
_Unit testing refers to tests that verify the functionality of a specific section of code, usually at the function level. In an object-oriented environment, this is usually at the class level, and the minimal unit tests include the constructors and destructors_
Forward Find, Backward Find, BackwardWeights Find includes too many different parts of the library.
There are too many reasons why we have errors in the tests, so this is not a modal(unit) testing. 
We can test only search or db, but with using stub solvers. Or this is Integration testing where we test all at once.

>There could be very rigorous integration tests (when the test tries all possible combinations of inputs and environments and carefully checks for correctness, performance, error handling etc) and very superficial unit tests (like "it passes if compiles without warnings").

And?...
We speak about kernel correctness. Or what do we want to check by changing workspace size

>I think that we all want to create such tests, but always have more important work to do ;)

Somehow  it should be done. Before merge by self testing or as jenkins targeted testing for each new or updated kernel, but not as result of integration testing. Errors in high-level modules can mask errors in kernels.

>Of course. However we would like to raise probability that error will be caught.
>Thanks for providing it. I guess it should somehow help me. Does it fix any issue? Do you recommend using it and looking what happens?

I recommend not imagining that this code increases the reliability of testing. Only increases the complexity.
This branch shows how this technique with buffer reallocation can't detect "out of the bounds" access.  Can you show me an example where it finds an error with access outside of the buffer?

**Comment by atamazov** [comment]
> We speak about kernel correctness. Or what do we want to check by changing workspace size

I don't. In this ticket I am trying to resolve the specific problem. The code in the driver looks good, but it gives nullptr instead of workspace. There is an issue somewhere. We need to identify the reason of it. Or, at least, make sure that our library is NOT the reason. Revering #172 is easy, but this is not a solution.

Other discussions are basically off-topic here.

> Can you show me an example where it finds an error with access outside of the buffer?

You can find relevant info at https://github.com/AMDComputeLibraries/MLOpen/pull/2341#issuecomment-570713697. If you need specific examples, I recommend asking @zjing14, perhaps he has something on hand.

**Comment by shurale-nkn** [comment]
@atamazov 
```
int ConvDriver<Tgpu, Tref>::RunForwardGpuFind(const bool is_transform)
{
#if MIOPEN_BACKEND_OPENCL
    cl_context ctx;
    clGetCommandQueueInfo(q, CL_QUEUE_CONTEXT, sizeof(cl_context), &ctx, nullptr);
#elif MIOPEN_BACKEND_HIP
    uint32_t ctx = 0;
#endif
    workspace_dev.reset();
    workspace_dev = std::unique_ptr<GPUMem>(new GPUMem(ctx, ws_sizeof_find_fwd, 1));
 int ret_algo_count;
    int request_algo_count = 2;
    // The library returns `request_algo_count` algorithms to the caller. However this does
    // not affect auto-tuning and find-db updates. Internally, the library searches for
    // *all* available algorithms during Find(), -- regardless of how many algorithms
    // requested, -- so perf-db and find-db are fully updated.
    std::vector<miopenConvAlgoPerf_t> perf_results(request_algo_count);

    auto rc = FindForward(ret_algo_count, request_algo_count, perf_results);
...
```
```
int ConvDriver<Tgpu, Tref>::RunBackwardDataGpuFind(){
...
workspace_dev = std::unique_ptr<GPUMem>(new GPUMem(ctx, ws_sizeof_find_bwd, 1));
...
```
```
int ConvDriver<Tgpu, Tref>::RunBackwardWrwGpuFind(){
...
workspace_dev = std::unique_ptr<GPUMem>(new GPUMem(ctx, ws_sizeof_find_wrw, 1));
```

Adding reallocation at the beginning of each Run____GpuFind() function, before Find__() call, will fix the problem.

Then you will get 3 separated  WS for each direction.
https://github.com/AMDComputeLibraries/MLOpen/pull/2341#issuecomment-570716517
>Call GWSS, allocate, call Find, free WS and then allocate the amount returned by Find, then invoke convolution etc.

But you still can't check WS calculation. Because this about segfaults, and you can't guarantee exactly where the buffer will be after reallocation.
https://github.com/AMDComputeLibraries/MLOpen/pull/2341#issuecomment-570713697
>When workspace is queried before find we get one value, then Find is run and it returns a second value. The problem is that second value was wrongly calculated.

**Comment by atamazov** [comment]
Thanks Kamil, not I see the bug in the driver. Wondering how it works now.

**Comment by atamazov** [comment]
@shurale-nkn Thanks Kamil, now I see the bug in the driver. Wondering how it works...

**Comment by atamazov** [comment]
by #296
