### ISSUE TITLE
conv::ProblemDescription vs miopen::ProblemDescription

### ISSUE THREAD

**Issue by JehandadKhan** [ROCmSoftwarePlatform/MIOpen#266]
The following lines of code in `miopen::conv::ProblemDescription` appear to be for the consumption of SQLite Perf DB

https://github.com/ROCmSoftwarePlatform/MIOpen/blob/e65e04ac1df4fa1381cf6ea439ad22b29998df42/src/include/miopen/conv/problem_description.hpp#L285

However, AFAIU only the Visit methods in `miopen::ProblemDescription` are used there. Furthermore, `miopen::conv::ProblemDescription` has a `table_name()` method, which is not used either. 

Should we get rid of one of these code blocks, whichever is redundant. Can someone help me understand the design here?

@atamazov @DrizztDoUrden

**Comment by atamazov** [comment]
[Off-topic] [Tip] :bulb: @JehandadKhan click on the source code link you've provided,

> https://github.com/ROCmSoftwarePlatform/MIOpen/blob/e65e04ac1df4fa1381cf6ea439ad22b29998df42/src/include/miopen/conv/problem_description.hpp#L285

then scroll to the top of the page and click `[Blame]` to see where this line of code came from.

**Comment by DrizztDoUrden** [comment]
We should update all solvers to the new struct and get rid of miopen::ProblemDescription. That would eliminate unrequited copies of tensor descriptors data an all the mess around it.

**Comment by JehandadKhan** [comment]
> We should update all solvers to the new struct and get rid of miopen::ProblemDescription. That would eliminate unrequited copies of tensor descriptors data an all the mess around it.

I will update the perf db infra to use the new struct.

**Comment by atamazov** [comment]
@DrizztDoUrden It is so that all new solvers should use `miopen::conv::ProblemDescription`?

**Comment by DrizztDoUrden** [comment]
My idea was to smooth transition by making them have 2 `GetSolution()`, one with old struct and one with `ExectutionContext` and `conv::ProblemDescription`. Old API method just transforming params. And later just remove all old methods.

**Comment by DrizztDoUrden** [comment]
@aserio Do you have in mind any specific topic you expect comments on?

**Comment by aserio** [comment]
@DrizztDoUrden, I was just adding the label  to clarify the purpose of the ticket :)

**Comment by atamazov** [comment]
@aserio Basically there is nothing to discuss. This is a quality issue that will be gradually resolved.

**Comment by DrizztDoUrden** [comment]
To clarify the intent. My idea was to show how to do it in GEMM solver PRs, as I would have to make solvers there. But it's got postponed.

**Comment by JehandadKhan** [comment]
@DrizztDoUrden we should add all the members of the `miopen::ProblemDescription` Visitor to the `miopen::conv::ProblemDescription` before we make the transition.

**Comment by atamazov** [comment]
@DrizztDoUrden Is it so that currently we need `Serialize` and `mloBuildConf_Key` methods from both ProblemDescriptions?

**Comment by DrizztDoUrden** [comment]
I don't think there should be any point in time when the methods should be used from both simultaneously.

**Comment by aserio** [comment]
@DrizztDoUrden, would you be able to provide an update on the status of this ticket?

**Comment by DrizztDoUrden** [comment]
What do you mean?

**Comment by aserio** [comment]
@DrizztDoUrden I have two primary concerns as this is a high-priority ticket: 
1. What are the steps to resolve this issue? (Especially what the the remaining steps to resolve the issue.) 
2. What is the current timeline for completion?

**Comment by DrizztDoUrden** [comment]
Steps to resolve as I see them:
1. Move every solver to the conv::ProblemDescription.
2. Remove the miopen::ConvolutionContext.

Timeline: I am not sure, kind of every other ticket I get lately is a high priority. But I'd like to get into this after Run and Measure elimination. It shouldn't require a lot of time though and the first step may be paralleled.
This is kind of blocker for a sane way of implementing gemm invokers btw, as gemm functions have tensor descriptors as parameters If I remember that correctly.

**Comment by aserio** [comment]
@DrizztDoUrden have you been able to return to this issue?
