### ISSUE TITLE
Location of half.hpp

### ISSUE THREAD

**Issue by trixirt** [ROCmSoftwarePlatform/MIOpen#2672]
On the rocm-6.0.0 tag on Fedora Rawhide and gfx90a

There are many build errors similar to
MIOpen/test/serialize.hpp:33:10: fatal error: 'half/half.hpp' file not found
   33 | #include <half/half.hpp>
      |          ^~~~~~~~~~~~~~~

On Fedora half.hpp is part of the system supplied headers and is installed to the system's /usr/include
Adding the half/ to the path makes it impossible to correct.
The location of half.hpp should be determined in the cmake infra and added as a -I<include-path-to-half> 
and just include <half.hpp>

**Comment by atamazov** [comment]
@trixirt Have you successfully installed the dependencies as specified at https://github.com/ROCm/MIOpen#installing-the-dependencies?

Do you use `CMAKE_PREFIX_PATH` as shown at https://github.com/ROCm/MIOpen#for-the-hip-backend-rocm-35-and-later-run?

**Comment by trixirt** [comment]
I am packaging MIOpen with the Fedora dependencies for Fedora.
The ROCm packages in Fedora are tracked here [Fedora Heterogeneous Compute Sig 
](https://fedoraproject.org/wiki/SIGs/HC)

To be packaged in Fedora MIOpen must be packaged with the Fedora dependencies.

**Comment by ppanchad-amd** [comment]
@trixirt Were you able to resolve your issue? Thanks!
