### ISSUE TITLE
[DOCS][APT] `miopenkernels-<arch>-<num cu>` package not found - docs might need updating

### ISSUE THREAD

**Issue by danpetreamd** [ROCmSoftwarePlatform/MIOpen#2679]
In the [Installing MIOpen kernels package](https://github.com/ROCm/MIOpen/blob/develop/README.md#installing-miopen-kernels-package) section, the documentation says:

```
To install the kernels package for your GPU architecture, use the following command:
``` 
https://github.com/ROCm/MIOpen/blob/3a33fe7a1a2d2d30c6b0d6fe64efbca94d69ba2a/docs/install.md?plain=1#L40

I've been using the Docker image `rocm/pytorch:rocm6.0_ubuntu20.04_py3.9_pytorch_2.1.1` and I can't find any `apt` packages following this pattern: `miopenkernels-<arch>-<num cu>`.

Instead I found this:

```shell
$ apt show miopen-hip-gfx9* | grep Package:
Package: miopen-hip-gfx900kdb
Package: miopen-hip-gfx900kdb6.0.0
Package: miopen-hip-gfx906kdb
Package: miopen-hip-gfx906kdb6.0.0
Package: miopen-hip-gfx908kdb
Package: miopen-hip-gfx908kdb6.0.0
Package: miopen-hip-gfx90akdb
Package: miopen-hip-gfx90akdb6.0.0
```

which aligns with:
https://github.com/ROCm/MIOpen/blob/3a33fe7a1a2d2d30c6b0d6fe64efbca94d69ba2a/utils/install_precompiled_kernels.sh#L34

**Comment by ppanchad-amd** [comment]
@danpetreamd Can we close this ticket now? Thanks!
