### ISSUE TITLE
Dead links inside of Docs

### ISSUE THREAD

**Issue by YellowRoseCx** [ROCmSoftwarePlatform/MIOpen#2682]
Inside the Performance Database documentation, there is a link to 

> "User PerfDb resides in the user’s home directory. See [Setting up locations](https://rocmsoftwareplatform.github.io/MIOpen/doc/html/install.html#setting-up-locations) for more information."

 but the link itself, ``https://rocmsoftwareplatform.github.io/MIOpen/doc/html/install.html#setting-up-locations`` is dead

https://github.com/ROCm/MIOpen/blob/docs/6.0.0/docs/perfdatabase.md?plain=1#L14

I've also come a dead link here in the docs: https://rocm.docs.amd.com/projects/MIOpen/en/latest/driver.html 
where it says "Documentation on how to run the driver is [here](https://rocmsoftwareplatform.github.io/MIOpen/doc/html/driver.html)."

**Comment by bghimireamd** [comment]
#2696 should fix this issue

**Comment by JehandadKhan** [comment]
#2696  has been merged, please reopen if there are still issues.
