### ISSUE TITLE
build is incomplete (HIP 6.0)

### ISSUE THREAD

**Issue by jinz2014** [ROCmSoftwarePlatform/MIOpen#2700]
I tried to build MIOpen, and got the following issues

-- Build with HIP 6.0.23494
-- Enable Composable Kernels: ON
-- Hip compiler flags:  -mllvm -amdgpu-early-inline-all=true -mllvm -amdgpu-function-calls=false -x hip -isystem /opt/rocm/include  -D__HIP_PLATFORM_AMD__=1  -DUSE_PROF_API=1 -isystem /opt/rocm/include --hip-link  -fno-offload-uniform-block
CMake Error at /opt/rocm/lib/cmake/composable_kernel/composable_kernelConfig.cmake:24 (include):
  include could not find requested file:

    /opt/rocm/lib/cmake/composable_kernel/composable_kerneldevice_other_operationsTargets.cmake
Call Stack (most recent call first):
  CMakeLists.txt:277 (find_package)

CMake Error at /opt/rocm/lib/cmake/composable_kernel/composable_kernelConfig.cmake:24 (include):
  include could not find requested file:

    /opt/rocm/lib/cmake/composable_kernel/composable_kerneldevice_gemm_operationsTargets.cmake
Call Stack (most recent call first):
  CMakeLists.txt:277 (find_package)

CMake Error at /opt/rocm/lib/cmake/composable_kernel/composable_kernelConfig.cmake:24 (include):
  include could not find requested file:

    /opt/rocm/lib/cmake/composable_kernel/composable_kerneldevice_conv_operationsTargets.cmake
Call Stack (most recent call first):
  CMakeLists.txt:277 (find_package)

CMake Error at /opt/rocm/lib/cmake/composable_kernel/composable_kernelConfig.cmake:24 (include):
  include could not find requested file:

    /opt/rocm/lib/cmake/composable_kernel/composable_kerneldevice_contraction_operationsTargets.cmake
Call Stack (most recent call first):
  CMakeLists.txt:277 (find_package)

CMake Error at /opt/rocm/lib/cmake/composable_kernel/composable_kernelConfig.cmake:24 (include):
  include could not find requested file:

    /opt/rocm/lib/cmake/composable_kernel/composable_kerneldevice_reduction_operationsTargets.cmake
Call Stack (most recent call first):
  CMakeLists.txt:277 (find_package)

CMake Warning at CMakeLists.txt:277 (find_package):
  Found package configuration file:

    /opt/rocm/lib/cmake/composable_kernel/composable_kernelConfig.cmake

  but it set composable_kernel_FOUND to FALSE so package "composable_kernel"
  is considered to be NOT FOUND.  Reason given by package:

  Unsupported component: device_reduction_operations

**Comment by junliume** [comment]
@jinz2014 have you built Composable Kernel as part of MIOpen dependency yet? It is listed in the `requirements.txt`

**Comment by bghimireamd** [comment]
you could also use pre-built docker https://hub.docker.com/r/rocm/miopen/tags if you don't want to build all the third party libraries from scratch.

**Comment by jinz2014** [comment]
Could you please suggest the build instruction when the composable kernel is not installed at the default location (/opt/rocm) ?

CMAKE_PRFEFIX_PATH does not seem to find them:

-DCMAKE_PREFIX_PATH="/path/to/composable_kernel/install/lib/cmake/composable_kernel"

**Comment by bghimireamd** [comment]
did you have `-DMIOPEN_USE_COMPOSABLEKERNEL=ON` on your cmake configuration?

**Comment by jinz2014** [comment]
Please update your instructions for build from source if needed ! 

In addition, the "requirements.txt" include installation of libraries that are not latest (e.g. rocMLIR 5.5.0). If there is no conflict or other issue, is it good to specify the latest versions for ROCm components (rocMLIR 6.0.0) ?

Our admin installed composable kernel in /opt/rocm. 

Thanks.
