### ISSUE TITLE
apt install conflicts with rocm

### ISSUE THREAD

**Issue by jinz2014** [ROCmSoftwarePlatform/MIOpen#2706]
Installing the library shows the following issue:

```
dpkg: error processing archive /tmp/apt-dpkg-install-sZnI2A/13-rocblas-dev_4.0.0.60000-91~22.04_amd64.deb (--unpack):
trying to overwrite '/opt/rocm-6.0.0/include/rocblas/internal/rocblas-auxiliary.h', which is also in package rocblas-dev6.0.0 4.0.0.60000-91~22.04
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
```
 
Installation conflicts with rocm.

**Comment by ppanchad-amd** [comment]
@jinz2014 Internal ticket has been created to investigate this issue. Thanks!

**Comment by jamesxu2** [comment]
Hello @jinz2014 , can you provide more information on how you installed ROCm?

I'm not able to reproduce this issue with the following two steps:
1. Installing ROCm using the [amdgpu-installer](https://rocm.docs.amd.com/projects/install-on-linux/en/latest/how-to/amdgpu-install.html). i.e. Downloading the installer, running ```sudo amdgpu-install --usecase=rocm```
2. ```miopen-hip``` and ```miopen-hip-dev``` are installed by the previous command so it's not necessary to install separately through apt. (I assume you're following the [Installing MIOpen ](https://rocm.docs.amd.com/projects/MIOpen/en/latest/install/install.html)instructions)

If you can provide a more detailed description of how you installed ROCm and MIOpen, I may be able to investigate further.

**Comment by jinz2014** [comment]
I will close the issue. Thank you for your investigation!
