### ISSUE TITLE
Is it possible to use rocm for macOS?

### ISSUE THREAD

**Issue by johnnynunez** [ROCmSoftwarePlatform/MIOpen#2721]
https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available/ 

<img width="744" alt="image" src="https://github.com/ROCm/MIOpen/assets/22727137/9d177170-280c-46ed-923b-6e87187d6303">

**Comment by amberhassaan** [comment]
@junliume : don't we require AMD hardware and driver to be able to run a docker container?

**Comment by ppanchad-amd** [comment]
@johnnynunez MacOS is not supported on rocm. Thanks!
