### ISSUE TITLE
Pre-compiled kernels package for gfx1100?

### ISSUE THREAD

**Issue by Looong01** [ROCmSoftwarePlatform/MIOpen#2740]
I have 7900XTX, the gfx1100 one. I have wait for the pre-compiled kernels package for months, but there is still no pre-compiled kernels package.

Would u like to provide one for gfx1100?

**Comment by atamazov** [comment]
@JehandadKhan @junliume Can you please have a look?

**Comment by ppanchad-amd** [comment]
@Looong01 I will follow up with the internal team and let you know. Thanks!

**Comment by Beinsezii** [comment]
Was this ever followed up? With MIOpen 3.2.0 the measurement times have become insane, >4 minutes of extra time for the first run of a diffusers model for every shape. `apt search miopen` still only shows gfx9 and gfx10

**Comment by jamesxu2** [comment]
Hi @Looong01 and @Beinsezii, 

MIOpen is actually moving away from precompiled kernels altogether. As a result, a gfx1100 precompiled kernel package is not planned.  We hear your frustration about the wait time for the first run of a model, and we're working on an alternative heuristics-based strategy to reduce kernel compilation time which will be provided in a future release.
