### ISSUE TITLE
[hipRTC] MIOpen Custom Limits missing members such as lowest()

### ISSUE THREAD

**Issue by junliume** [ROCmSoftwarePlatform/MIOpen#2752]
**[Observation]**:
Several ONNX UT has failed with the message
```
/tmp/comgr-01aacb/include/data_type.hpp:1025:86: error: no member named 'lowest' in 'std::numeric_limits<float>'
 1025 |     __host__ __device__ static constexpr T Lowest() { return std::numeric_limits<T>::lowest(); }
      |                                                              ~~~~~~~~~~~~~~~~~~~~~~~~^
/tmp/comgr-01aacb/include/reduction_operator.hpp:87:84: note: in instantiation of member function 'ck::NumericLimits<float>::Lowest' requested here
   87 |     __device__ static constexpr T GetReductionZeroVal() { return NumericLimits<T>::Lowest(); };
      |                                                                                    ^
/tmp/comgr-01aacb/include/gridwise_generic_2d_reduction_direct_threadwise.hpp:85:40: note: in instantiation of member function 'ck::reduce::Max<float>::GetReductionZeroVal' requested here
   85 |         const auto zeroVal = opReduce::GetReductionZeroVal();
      |                                        ^
```
It is requested here:
https://github.com/ROCm/MIOpen/blob/b44f182b731532b5c32eb37a2df16b18efe4d94f/src/composable_kernel/composable_kernel/include/utility/data_type.hpp#L1025

**[More Discussion]**:
@atamazov @JehandadKhan  we cannot just re-invent all variations of member functions for all variations of datatypes on our own, right? 
https://en.cppreference.com/w/cpp/types/numeric_limits

**[Related PRs]**:
https://github.com/ROCm/MIOpen/pull/2637
https://github.com/ROCm/MIOpen/pull/2705

here is just a few examples (not a complete list)
- https://github.com/ROCm/MIOpen/blob/b44f182b731532b5c32eb37a2df16b18efe4d94f/test/check_numerics_test.cpp#L146
- https://github.com/ROCm/MIOpen/blob/b44f182b731532b5c32eb37a2df16b18efe4d94f/test/check_numerics_test.cpp#L152
- https://github.com/ROCm/MIOpen/blob/b44f182b731532b5c32eb37a2df16b18efe4d94f/test/rnn_seq_api.hpp#L1472
- https://github.com/ROCm/MIOpen/blob/b44f182b731532b5c32eb37a2df16b18efe4d94f/test/soft_max.cpp#L116
- https://github.com/ROCm/MIOpen/blob/b44f182b731532b5c32eb37a2df16b18efe4d94f/test/gtest/cat.hpp#L136

**Comment by junliume** [comment]
The "good" news:
```
# grep "error:" ONNXUT_206_54.log | awk -F":" '{for(i=0;i++<3;){$i=""} print $0}' | awk '!seen[$0]++'
    error  no member named 'lowest' in 'std  numeric_limits<float>'
    error  implicit instantiation of undefined template 'std  numeric_limits<int>'
```
So there is only one problem to resolve so far in this ticket (the other one is fixed by #2705), which is
```
 'lowest' in 'std  numeric_limits<float>'
```
What I am afraid of is that there might be issues not discovered by tests yet (just like this one)

**Comment by atamazov** [comment]
@junliume 
> we cannot just re-invent all variations of member functions for all variations of datatypes on our own, right?

We can, but this would be a serious waste of time. The current approach is to implement only necessary stuff.

**Comment by atamazov** [comment]
@junliume 
- ❓ Is it possible to find out the failing config and failing solver (and target GPU)? This is necessary to create a regression test.
- ❓ What version of ROCm is used on the system where the error occurred?

**Comment by atamazov** [comment]
@junliume 
> we cannot just re-invent all variations of member functions for all variations of datatypes on our own, right?

~We can, but this would be a serious waste of time. The current approach is to implement only necessary stuff.~

[Correction] We should only define things that are missing in the PCH. Otherwise an error like "duplicate definition" would occur.
