### ISSUE TITLE
Embedded builds are broken

### ISSUE THREAD

**Issue by atamazov** [ROCmSoftwarePlatform/MIOpen#2763]
```bash
$ cmake ... -DMIOPEN_EMBED_DB='gfx906_60' ...
...
-- Embedding files
ERROR Unable to locate file /root/github/MLOpen1/build/embedded/share/miopen/db/gfx906_60.HIP.fdb.txt to embed
ERROR Unable to locate file /root/github/MLOpen1/build/embedded/share/miopen/db/gfx906_60.db to embed
-- Generating embedding library miopen_data
CMake Error at cmake/embed.cmake:64 (message):
  Symbols and objects dont match: 0 != 2
Call Stack (most recent call first):
  cmake/embed.cmake:148 (generate_embed_source)
  src/CMakeLists.txt:920 (add_embed_library)
...
```
❗ The implicit reason of the issue is that `Fp32 Hip Debug Embedded Vega20` CI stage is disabled for 5 months due to https://github.com/ROCm/MIOpen/pull/2395#discussion_r1494944445.

----
[Attribution] @junliume @JehandadKhan
- https://github.com/ROCm/MIOpen/labels/bug
- https://github.com/ROCm/MIOpen/labels/urgency_unknown
- Proposed assignees:
  - @junliume 
  - @JehandadKhan 
  - @atamazov  (to be informed only)
  - @DrizztDoUrden (to be informed only)

**Comment by atamazov** [comment]
Faulty commit is b9f6ef2255e40db3ccd5e58692a42a1c4f9dddae, `[HotFix] Fix DB install after #2347` (#2702).

**Comment by atamazov** [comment]
The fix should include enabling at least one Embedded Smoke stage on CI (MI200 is fine).

**Comment by junliume** [comment]
Observed issues that the DB files under `build/share/miopen/db/` are not generated without making a target. So with or without embedded config included in cmake line, the folder `build/share/miopen/db/` does not contain findDB or perfDB, kDB.

https://github.com/ROCm/MIOpen/blob/6435d6248dd9315deb74da2bd4aaba32ae664035/CMakeLists.txt#L529

**Comment by atamazov** [comment]
@junliume @JehandadKhan @apwojcik I still recommend either fixing this or getting rid of the Embedded Build feature (but the latter does not make sense to me as we put substantial efforts into this feature).

**Comment by apwojcik** [comment]
@atamazov @JehandadKhan @junliume @tperry-amd It is on my list, but it has to wait until I finish with PRs fixing MIOpen runtime bugs on Windows. Next, I will fix the embed build and submit PR for building dependencies directly from CMake.
The plan is to replace the content of `embed.cmake` from MIOpen with `Embed.cmake` from MIGraphX (as much as possible), which had been ported to support Windows resource files - the native technology for embedding data into binary files on Windows (i.e., executables, DLLs, data only libraries, etc.).

**Comment by apwojcik** [comment]
Unless it is urgent, let someone else take over the task and fix the embed build, and I will help.

**Comment by atamazov** [comment]
@apwojcik It's Ok, I do not think this is urgent. Just want to make sure that eventually this issue will be fixed.
