### ISSUE TITLE
MIOpen for MI300 machine. 

### ISSUE THREAD

**Issue by rui-ren** [ROCmSoftwarePlatform/MIOpen#2797]
Hi there, 

I am about to install `miopen` packages for `MI300`,

### Questions: 

1. Is `miopen-hip-gfx1030kdb` the correct package for `ROCm6.0` + `MI300` ?

2. If `gfx1030kdb` is for MI300, is it backward compatible for MI200 and MI100?

Thank you in advance.
  @junliume

**Comment by junliume** [comment]
Hi @rui-ren 

`gfx1030` is for Navi21 (6800 XT), and for MI300 we should use `src/kernels/gfx942.kdb.bz2` for kernel cache.
From MI300, we are using heuristics more than precision tuning: `src/kernels/gfx942.tn.model`

**Comment by rui-ren** [comment]
Hi @junliume , Thanks for your response. Where can I find the package for MI300 ?  

I can not find it from [Here](https://repo.radeon.com/rocm/apt/6.0/pool/main/m/). Thanks. 

FYI @PeixuanZuo

**Comment by ghost** [comment]
Hi there, I have also faced same issue. I am not able to find MIOpen for MI300 (gfx942). Could anyone know where to find one? Thanks.

**Comment by rui-ren** [comment]
Hi @taka-nscc, I cannot find the package as well. As MI300 was out for quite a while, MIOpen should release the package for MI300 support soon. +cc @junliume

**Comment by JehandadKhan** [comment]
@cderb  Can you please investigate this? I see the kdb file in the repo so it is strange that the package is not there.

**Comment by atamazov** [comment]
@junliume @JehandadKhan It might be worth assigning this to @cderb and setting the appropriate lables so Chris can easily find this task among others and prioritize his work.

**Comment by rui-ren** [comment]
Any updates on this?

**Comment by ghost** [comment]
I think MIOpen for MI300 (gfx942) is available finally.
https://repo.radeon.com/rocm/apt/6.1/pool/main/m/

**Comment by rui-ren** [comment]
Great! Thank you all for the fix.
