### ISSUE TITLE
MLIR kernel perf regression after #2722

### ISSUE THREAD

**Issue by junliume** [ROCmSoftwarePlatform/MIOpen#2799]
**[Observations]**:
After #2722 we observed that some benchmarks have regression in performance, for example:
[Case1_MIOPEN_USE_SQLITE_PERFDB_on.log](https://github.com/ROCm/MIOpen/files/14565644/Case1_MIOPEN_USE_SQLITE_PERFDB_on.log)
[Case2_MIOPEN_USE_SQLITE_PERFDB_off.log](https://github.com/ROCm/MIOpen/files/14565645/Case1_MIOPEN_USE_SQLITE_PERFDB_off.log)

(**update**: the name of the logs might be misleading, the `Case1_MIOPEN_USE_SQLITE_PERFDB_on` is actually generated by reverting #2722 and #2769)

A typical example:
with #2722 
```
./bin/MIOpenDriver convfp16 -n 128 -c 256 -H 56 -W 56 -k 256 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -m conv -g 32 -F 4 -t 1
MIOpenDriver convfp16 -n 128 -c 256 -H 56 -W 56 -k 256 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -m conv -g 32 -F 4 -t 1 -V 0
PRNG seed: 12345678
MIOpen Backward Weights Conv. Algorithm: 5, Solution: 105/ConvMlirIgemmWrWXdlops
GPU Kernel Time Backward Weights Conv. Elapsed: 55.784523 ms (average)
stats: name, n, c, ho, wo, x, y, k, flopCnt, bytesRead, bytesWritten, GFLOPs, GB/s, timeMs
stats: bwdw-conv3x3u1, 128, 256, 56, 56, 3, 3, 256,  14797504512, 0, 0, 265, 0, 55.784523
```
before #2722
```
./bin/MIOpenDriver convfp16 -n 128 -c 256 -H 56 -W 56 -k 256 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -m conv -g 32 -F 4 -t 1
MIOpenDriver convfp16 -n 128 -c 256 -H 56 -W 56 -k 256 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -m conv -g 32 -F 4 -t 1 -V 0
PRNG seed: 12345678
MIOpen Backward Weights Conv. Algorithm: 5, Solution: 105/ConvMlirIgemmWrWXdlops
GPU Kernel Time Backward Weights Conv. Elapsed: 5.149903 ms (average)
stats: name, n, c, ho, wo, x, y, k, flopCnt, bytesRead, bytesWritten, GFLOPs, GB/s, timeMs
stats: bwdw-conv3x3u1, 128, 256, 56, 56, 3, 3, 256,  14797504512, 0, 0, 2873, 0, 5.149903
```

Docker A: compute-artifactory.amd.com:5000/rocm-plus-docker/framework/compute-rocm-dkms-component-staging-miopen:462_ubuntu20.04_py3.9_pytorch_release-2.1_8a19b44
Docker B: compute-artifactory.amd.com:5000/rocm-plus-docker/framework/compute-rocm-dkms-no-npi-hipclang:13604_ubuntu20.04_py3.9_pytorch_release-2.1_8a19b44

https://github.com/ROCm/MIOpen/pull/2798 is created as a temporal workaround to patch this issue

**Comment by atamazov** [comment]
GPU: MI200

**Comment by DrizztDoUrden** [comment]
Can you send me log with MIOPEN_LOG_LEVEL=6? At least for the 55 ms case. I don't have access to that GPU and debugging locally with matching file finds perf-db record just fine, but I am not sure what happens next as the solver is not applicable on the PCs I have access to.

**Comment by DrizztDoUrden** [comment]
https://github.com/ROCm/MIOpen/blob/7335c4501e71c5321f8a8a3951baa5a34d188945/CMakeLists.txt#L551

It looks like sqlite db files are always installed, that could lead to regression due to complete lack of compatible system db in the installed package

**Comment by DrizztDoUrden** [comment]
https://github.com/ROCm/MIOpen/pull/2800 should probably fix it

**Comment by cderb** [comment]
I installed #2800 on top of Docker A: compute-artifactory.amd.com:5000/rocm-plus-docker/framework/compute-rocm-dkms-component-staging-miopen:462_ubuntu20.04_py3.9_pytorch_release-2.1_8a19b44
``` 
MIOpenDriver convfp16 -n 128 -c 256 -H 56 -W 56 -k 256 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -m conv -g 32 -F 4 -t 1
MIOpenDriver convfp16 -n 128 -c 256 -H 56 -W 56 -k 256 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -m conv -g 32 -F 4 -t 1
PRNG seed: 12345678
MIOpen Backward Weights Conv. Algorithm: 0, Solution: 102/GemmWrwUniversal
GPU Kernel Time Backward Weights Conv. Elapsed: 10.956957 ms (average)
stats: name, n, c, ho, wo, x, y, k, flopCnt, bytesRead, bytesWritten, GFLOPs, GB/s, timeMs
stats: bwdw-conv3x3u1, 128, 256, 56, 56, 3, 3, 256,  14797504512, 0, 0, 1351, 0, 10.956957
Backward Convolution Weights Verifies OK on GPU reference (0.00304126 < 0.0164)
```

**Comment by DrizztDoUrden** [comment]
I wonder, why it's still 10.9 ms vs 5.1 ms

**Comment by junliume** [comment]
@cderb and @DrizztDoUrden I tested on MI250X system and here is what I got after installing #2800 in Docker A:

Maybe @cderb  we should clean the install destination for the DB files, they should not be installed as according to #2800 .
```
###:/var/lib/jenkins/pytorch-micro-benchmarking# /opt/rocm/bin/MIOpenDriver convfp16 -n 128 -c 256 -H 56 -W 56 -k 256 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -m conv -g 32 -F 4 -t 1
MIOpenDriver convfp16 -n 128 -c 256 -H 56 -W 56 -k 256 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -m conv -g 32 -F 4 -t 1
PRNG seed: 12345678
MIOpen Backward Weights Conv. Algorithm: 5, Solution: 105/ConvMlirIgemmWrWXdlops
GPU Kernel Time Backward Weights Conv. Elapsed: 5.123152 ms (average)
stats: name, n, c, ho, wo, x, y, k, flopCnt, bytesRead, bytesWritten, GFLOPs, GB/s, timeMs
stats: bwdw-conv3x3u1, 128, 256, 56, 56, 3, 3, 256,  14797504512, 0, 0, 2888, 0, 5.123152
```
