### ISSUE TITLE
Problem building MIOpenDriver

### ISSUE THREAD

**Issue by kcperry** [ROCmSoftwarePlatform/MIOpen#28]
I'm running into a problem building MIOpenDriver after a successful HIP build of MIOpen...

 make MIOpenDriver
[  5%] Built target addkernels
[ 97%] Built target MIOpen
[ 97%] Linking CXX executable ../bin/MIOpenDriver
ld: /tmp/tmp.FuopL936mR/main.cpp.host.o: undefined reference to symbol '_ZN5boost6system15system_categoryEv'
//usr/lib/x86_64-linux-gnu/libboost_system.so.1.58.0: error adding symbols: DSO missing from command line
clang-6.0: error: linker command failed with exit code 1 (use -v to see invocation)
driver/CMakeFiles/MIOpenDriver.dir/build.make:128: recipe for target 'bin/MIOpenDriver' failed
make[3]: *** [bin/MIOpenDriver] Error 1
CMakeFiles/Makefile2:3144: recipe for target 'driver/CMakeFiles/MIOpenDriver.dir/all' failed
make[2]: *** [driver/CMakeFiles/MIOpenDriver.dir/all] Error 2
CMakeFiles/Makefile2:3151: recipe for target 'driver/CMakeFiles/MIOpenDriver.dir/rule' failed
make[1]: *** [driver/CMakeFiles/MIOpenDriver.dir/rule] Error 2
Makefile:1313: recipe for target 'MIOpenDriver' failed
make: *** [MIOpenDriver] Error 2

**Comment by dagamayank** [comment]
Trying adding `-DMIOPEN_MAKE_BOOST_PUBLIC=ON` as outlined at the link below.

https://github.com/ROCmSoftwarePlatform/MIOpen#building-the-driver

**Comment by kcperry** [comment]
Ahhh, I missed that and it was indeed the issue. As expected the "Running the tests" section was successful now as well.

Thanks!
