### ISSUE TITLE
[MHA] Implement point-wise operation descriptor in Graph API

### ISSUE THREAD

**Issue by scerzh** [ROCmSoftwarePlatform/MIOpen#2839]
The following descriptors are to be implemented.

MIOPEN_BACKEND_POINTWISE_DESCRIPTOR
- [x] Builder and tests
- [x] C functions and tests

MIOPEN_BACKEND_OPERATION_POINTWISE_DESCRIPTOR
- [x] Builder and tests
- [x] C functions and tests

**Comment by atamazov** [comment]
@scerzh I guess either the topmost comment should be beefed up with more checkboxes or this ticket should be closed, right?

**Comment by scerzh** [comment]
> @scerzh I guess either the topmost comment should be beefed up with more checkboxes or this ticket should be closed, right?

The last checkbox is still not merged #2886. The PR is linked to this issue and will close it automatically after merging.
