### ISSUE TITLE
Compile on GPUless machines 

### ISSUE THREAD

**Issue by alexandraBara** [ROCmSoftwarePlatform/MIOpen#284]
I'm looking for input on this new feature.

We want to be able to:
1. use generic_search loop to only compile(and not run) kernels on machines with no GPU.
1. use custom cache directory (something other than .cache/miopen/ ) --> through env var to specify custom cache (so we can run once per arch and specify different location so we can distinguish between architectures)
1. use env var to specify which arch we want to compile for. We do not need the same for CU since we don't use CUs to compile (create hash)

So far I have:
- custom cache dir through env var and another env var to spoof arch
- calling PrecompileKernels in generic_search to compile to custom cache.
The struggle lies in not loading kernels in the hip runtime. 
I have observed that EvaluateInvokers (through for instance FindConvolutionForwardAlgo)
calls EvaluateInvokers -> handle.PrepareInvoker --> cache.AddKernel .... -> hipModuleGetFunction()! 

@atamazov  @DrizztDoUrden  any suggestions how to..get around this?

**Comment by atamazov** [comment]
> use custom cache directory (something other than .cache/miopen/ ) --> ... so we can run once per arch and specify different location so we can distinguish between architectures

Is it the only reason for customizing binary cache directory?

**Comment by alexandraBara** [comment]
> > use custom cache directory (something other than .cache/miopen/ ) --> ... so we can run once per arch and specify different location so we can distinguish between architectures
> 
> Is it the only reason for customizing binary cache directory?

I believe so, but we can just not implement it and leave the regular cache location unless someone thinks of a better reason to keep both.

**Comment by atamazov** [comment]
IIRC gfx arch and num of CUs are associated with each binary-db (kern_db) record. There should be some other reason, otherwise we simply do not need this feature.

**Comment by alexandraBara** [comment]
> IIRC gfx arch and num of CUs are associated with each binary-db (kern_db) record. There should be some other reason, otherwise we simply do not need this feature.

I'm not sure which feature you are referring to when you say "we simply do not need this feature"! If you are referring to the extra custom cache location, yeah we dont really need another one, we can use the default cache location as well.
If you are referring to this entire feature of GPUless compilation - we do in fact need this feature. 
But i need help with the invoker stuff here - specifically it trying to add kernels to mem cache.
How do we avoid adding these to mem cache?

**Comment by atamazov** [comment]
Of course I mean the "use custom cache directory". If it is not needed, then could you please remove this feature from the list. I really would like to help you, but I need to understand the task first.

**Comment by atamazov** [comment]
> use env var to specify which arch we want to compile for. We do not need the same for CU since we don't use CUs to compile (create hash)

Unfortunately, this is incorrect. The library needs to know the number of CUs in order to prepare Solutions (that contain build options, that depend on num of CUs)
