### ISSUE TITLE
[MHA] Implement random number generator descriptor in Graph API

### ISSUE THREAD

**Issue by scerzh** [ROCmSoftwarePlatform/MIOpen#2842]
The following descriptors are to be implemented.

MIOPEN_BACKEND_RNG_DESCRIPTOR
- [x] Builder and tests
- [x] C functions and tests

MIOPEN_BACKEND_OPERATION_RNG_DESCRIPTOR
- [x] Builder and tests
- [x] C functions and tests

**Comment by atamazov** [comment]
@scerzh I guess either the topmost comment should be beefed up with more checkboxes or this ticket should be closed, right?

**Comment by scerzh** [comment]
The last 2 checkboxes are still not merged #2873
The PR is linked to this issue and close it automatically after merging.
