### ISSUE TITLE
MIOPEN_USER_DB_PATH=. no longer works as it should after #2823

### ISSUE THREAD

**Issue by averinevg** [ROCmSoftwarePlatform/MIOpen#2881]
With `MIOPEN_USER_DB_PATH=.` MIOpen creates a new directory (`'"."'`) in the current directory and puts db files into that directory instead of the current directory. Probably caused by https://github.com/ROCm/MIOpen/pull/2823

CC @junliume @atamazov

**Comment by junliume** [comment]
Thanks! @averinevg 

@apwojcik @atamazov and @JehandadKhan could we assign to fix this issue asap?

**Comment by atamazov** [comment]
@junliume If the reason is 2823 then I would ask @apwojcik to fix it.

BTW can you please clarify what this issue is blocking?

**Comment by junliume** [comment]
@apwojcik is OoO for the next a few days, this issue is blocking our next staging since HPC customers are using this feature.

**Comment by CAHEK7** [comment]
That's not the only problem. Right now for my dev build it creates `"` directory with following subdirectories `home`/`user`/`src`/`kernels"`, so it means that it wrongly interprets `"/home/user/src/kernels"` string.

Somewhere `fp::path` has been directly fed into string stream and it introduced extra quotes.
Like
```C++
std::cout << fspath << "\n";
std::cout << fspath.string() << "\n";
```
prints
```
"/home/user/kernels"
/home/user/kernels
```

Upd: https://github.com/ROCm/MIOpen/blob/78c1a7e2ad45ed85899afc8150195e7f229851d4/src/find_db.cpp#L222
#2823 indeed.
