### ISSUE TITLE
Building from source prefers ROCm version of CK

### ISSUE THREAD

**Issue by tbennun** [ROCmSoftwarePlatform/MIOpen#2885]
Since Composable Kernel is now a part of the ROCm release, building MIOpen from source uses the headers of the pre-installed version rather than the latest version built from source.

To mitigate CMake configuration issues, I had to swap the order of CMAKE_PREFIX_PATHs, i.e., instead of the instructions in the README:
```sh
cmake -DMIOPEN_BACKEND=HIP -DCMAKE_PREFIX_PATH="<hip-installed-path>;<rocm-installed-path>;<miopen-dependency-path>" ..
```

I used:
```sh
cmake -DMIOPEN_BACKEND=HIP -DCMAKE_PREFIX_PATH="<miopen-dependency-path>;<rocm-installed-path>" ..
```

However, that does not resolve the issue where the compiler uses the `/opt/rocm-version` as the first include directory, which takes precedence over the dependency path. The only way I could resolve this was to remove the `ck` folder from `/opt/rocm-version/include`.

**Comment by ppanchad-amd** [comment]
Hi @tbennun, an internal ticket has been created to assist with your issue. Thanks!

**Comment by darren-amd** [comment]
Hi @tbennun,

Just wanted to confirm, are you trying to build MIOpen with your own built version of CK? If so, could you please provide me with the version you have built, as well as the full cmake command you are running? Thanks!

**Comment by tbennun** [comment]
@darren-amd I am not trying to build with my own version of CK, but to reuse the one built/installed with `install_deps`, which was a newer revision than the ROCm release of CK at the time. It was the latest development git revision of MIOpen at the time (April 10).

The CMake command I used was exactly as in my original message.

**Comment by darren-amd** [comment]
Hi @tbennun,

I'm currently in contact with the internal team about why the default behavior of cmake is not targeting the CK version installed with `install_deps`.

However, a solution is to add the path directly within the cmake file when it is trying to find the composable_kernel package: [Find CK Package](https://github.com/ROCm/MIOpen/blob/9591b7a285d4ef89f96a89af498599c77d74207d/CMakeLists.txt#L330)

You would add something like:
`find_package(composable_kernel 1.0.0 PATHS /path/to/CK COMPONENTS device_other_operations device_gemm_operations device_conv_operations device_reduction_operations)`

Please give that a try and let me know if you run into any issues. Thanks!
