### ISSUE TITLE
slight correction to build instructions

### ISSUE THREAD

**Issue by kcperry** [ROCmSoftwarePlatform/MIOpen#29]
Not sure if this is the best place to put this but in building MIOpen it should be mentioned in the "Configuring with cmake" section that after you create the "build" path and descend into it, "rm ../CMakeCache.txt" should be done otherwise the subsequent configuration step will fail but it will not look like it fails because the generated objects will be placed in path above instead in the current working directory (i.e. "build") which you created to keep your build separate from the source.

It took me awhile to track that down so I'm sure someone else might come across it unless they are intimately familiar with using cmake.

**Comment by pfultz2** [comment]
>  descend into it, "rm ../CMakeCache.txt" should be done

There is no need for this step because this file does not exist. Most likely this file is leftover from invoking cmake at the top-level, which is not part of the build instructions.
