### ISSUE TITLE
hipErrorSharedObjectInitFailed during tuning in Pytorch

### ISSUE THREAD

**Issue by zjing14** [ROCmSoftwarePlatform/MIOpen#290]
- hipErrorSharedObjectInitFailed during tuning in Pytorch
- Reported by http://ontrack-internal.amd.com/browse/SWDEV-240233
- Similar failure (hipErrorSharedObjectSymbolNotFound) found with resnext101
- Based on current logs, failure happens with tuning Asm kernels (both DirectConv and Winograd Asm kernels) on gfx908 in Pytorch. Cannot reproduce the failure with tuning individual config with MIOpenDriver

**Comment by atamazov** [comment]
Similar error happens in our CI from time to time. Not reproducible too.
