### ISSUE TITLE
MIOpen abort when there's no /tmp folder

### ISSUE THREAD

**Issue by sunway513** [ROCmSoftwarePlatform/MIOpen#291]
I see the following crash reported when there's no "/tmp" folder in the docker container.
```
2020-06-15 01:59:24.750820: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library librocblas.so
2020-06-15 01:59:25.070385: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libMIOpen.so
MIOpen(HIP): Error [LockFilePath] File system operation error in LockFile. Error code: system:20. Description: 'boost::filesystem::temp_directory_path: Not a directory: "/tmp"'
MIOpen(HIP): Error [LockFilePath] File system operation error in LockFile. Error code: system:20. Description: 'boost::filesystem::temp_directory_path: Not a directory: "/tmp"'
MIOpen Error: boost::filesystem::temp_directory_path: Not a directory: "/tmp"
MIOpen Error: boost::filesystem::temp_directory_path: Not a directory: "/tmp"
2020-06-15 01:59:25.802308: F tensorflow/stream_executor/rocm/rocm_dnn.cc:3564] call to miopenFindConvolutionForwardAlgorithm failed: miopenStatusUnknownError
2020-06-15 01:59:25.802327: F tensorflow/stream_executor/rocm/rocm_dnn.cc:3564] call to miopenFindConvolutionForwardAlgorithm failed: miopenStatusUnknownError
Fatal Python error: Aborted
```

**Comment by aserio** [comment]
@sunway513, would you be able to assign a priority to this issue?

**Comment by daniellowell** [comment]
@DrizztDoUrden please take a look. We should have a environment variable to be able to specify the /tmp directory to be used. 
@sunway513 how are other components handling no /tmp directory? Or is it only MIOpen that uses it?

**Comment by sunway513** [comment]
@daniellowell This is just a corner case, by default the OS will have /tmp folders available. 
I manually delete that folder (60GB+) after hours of re-tuning to free some space. I've only seen complains from MIOpen end when the /tmp folder is missing.

**Comment by atamazov** [comment]
> We should have a environment variable to be able to specify the /tmp directory to be used.

We already have it:
```
ISO/IEC 9945: The path supplied by the first environment variable
found in the list TMPDIR, TMP, TEMP, TEMPDIR. If none of these
are found, "/tmp", or, if macro __ANDROID__ is defined, "/data/local/tmp".
```
See https://www.boost.org/doc/libs/1_73_0/libs/filesystem/doc/reference.html#temp_directory_path

**Comment by atamazov** [comment]
comgr uses `llvm::sys::path::system_temp_directory()`, see
https://github.com/llvm/llvm-project/blob/dab859d1bf250c4d0299ac505e2a6773c56b6503/llvm/lib/Suppor/Unix/Path.inc#L1205
It tries the following temp vars, in order: `TMPDIR`, `TMP`, `TEMP`, `TEMPDIR`. If none variables defined, `/tmp` is returned. This matches the logic of `boost::temp_directory()`, under linux at least.

**Comment by atamazov** [comment]
Quick test shows that both comgr and MIOpen follow the TMPDIR env var.

**Comment by daniellowell** [comment]
@sunway513 is this still an issue?

**Comment by sunway513** [comment]
@daniellowell , should I try the tip of develop to test again?

**Comment by atamazov** [comment]
@sunway513 The environment that does not have nether one of {`TMPDIR`, `TMP`, `TEMP`, `TEMPDIR`} variables set nor `/tmp` directory does not comply the POSIX base specification.

In other words, any, er, "normal" system should have temp directory created and it should provide apps with information where it resides.

**Comment by sunway513** [comment]
@atamazov , thanks for the info, that's fair enough. I'll close this issue then.
