### ISSUE TITLE
Build failure Unable to found boost_filesystem

### ISSUE THREAD

**Issue by RandUser123sa** [ROCmSoftwarePlatform/MIOpen#2954]
Hi all,

I'm trying to compile the version 6.1.0 with follow parameters:

CXX=/opt/rocm/llvm/bin/clang++ cmake \
    -Wno-dev \
    -G Ninja \
    -D CMAKE_CXX_FLAGS="${CXXFLAGS} -fcf-protection=none -DNDEBUG" \
    -D CMAKE_INSTALL_PREFIX=/opt/rocm \
    -D CMAKE_BUILD_TYPE=None \
    -D MIOPEN_BACKEND=HIP \
    -D HALF_INCLUDE_DIR=/usr/include/half \
    ..

and receive error:

-- Build with HIPRTC 6.1.40091
CMake Error at /usr/lib64/cmake/Boost-1.85.0/BoostConfig.cmake:141 (find_package):
  Found package configuration file:

    /usr/lib64/cmake/boost_filesystem-1.85.0/boost_filesystem-config.cmake

  but it set boost_filesystem_FOUND to FALSE so package "boost_filesystem" is
  considered to be NOT FOUND.  Reason given by package:

  No suitable build variant has been found.

  The following variants have been tried and rejected:

  * libboost_filesystem.so.1.85.0 (shared, Boost_USE_STATIC_LIBS=ON)

Call Stack (most recent call first):
  /usr/lib64/cmake/Boost-1.85.0/BoostConfig.cmake:262 (boost_find_component)
  /usr/share/cmake-3.29/Modules/FindBoost.cmake:594 (find_package)
  CMakeLists.txt:397 (find_package)

I have:
$ ls -la /usr/lib64/libboost_filesystem.so*
lrwxrwxrwx 1 root root     29 Apr 29 15:21 /usr/lib64/libboost_filesystem.so -> libboost_filesystem.so.1.85.0*
-rwxr-xr-x 1 root root 138792 Mar 30 19:05 /usr/lib64/libboost_filesystem.so.1.84.0*
-rwxr-xr-x 1 root root 146984 Apr 16 23:54 /usr/lib64/libboost_filesystem.so.1.85.0

Any solutions ?

**Comment by junliume** [comment]
@RandUser123sa could you please try the following steps?
```
cd /root && git clone -b develop https://github.com/ROCmSoftwarePlatform/MIOpen && cd MIOpen && \
mkdir -p install_dir && cmake -P install_deps.cmake --minimum --prefix /root/MIOpen/install_dir && \
mkdir -p build && \
cd build && \
CXX=/opt/rocm/bin/amdclang++ CC=/opt/rocm/bin/amdclang cmake -DMIOPEN_BACKEND=HIP -DCMAKE_PREFIX_PATH="/root/MIOpen/install_dir;/opt/rocm" \
-DMIOPEN_TEST_ALL=On -DMIOPEN_TEST_HALF=On .. && \
make -j$(nproc) install

**Comment by RandUser123sa** [comment]
I was able to compile it when added Boost_USE_STATIC_LIBS=NO . It's seems my disto does not have static boost_filesystem :

CXX=$ROCM_INSTALL_DIR/llvm/bin/clang++ cmake \
    -Wno-dev \
    -G Ninja \
    -D CMAKE_CXX_FLAGS="${CXXFLAGS} -fcf-protection=none -DNDEBUG" \
    -D CMAKE_INSTALL_PREFIX=/opt/rocm \
    -D CMAKE_BUILD_TYPE=Release \
    -D MIOPEN_BACKEND=HIP \
    -D HALF_INCLUDE_DIR=/usr/include/half \
    -D BUILD_TESTING=NO \
    -D Boost_USE_STATIC_LIBS=NO \
..
