### ISSUE TITLE
Reproduce kernel cache binary files in MIOpen

### ISSUE THREAD

**Issue by xuantengh** [ROCmSoftwarePlatform/MIOpen#2955]
Hi MIOpen developers,

There is a [team](https://salsa.debian.org/rocm-team/) intended to ship MIOpen to Debian's official repository and has made some [progress](https://salsa.debian.org/rocm-team/miopen). We notice that there exist some binary files like `src/kernels/*.kdb.bz2` used as the kernel cache to [avoid runtime JIT when the kernel is first invoked](https://github.com/ROCm/MIOpen/issues/2255#issuecomment-1637242203), tracked as either normal Git files or LFS refs based on their sizes. However, it seems that these files are maintained in an opaque way, where the engineers upload without extra explanation #2859, which is not compatible with [DFSG](https://wiki.debian.org/DebianFreeSoftwareGuidelines) requiring source code when distributing the package.

So our question is: can we rebuild/reproduce these binary files locally when compiling MIOpen? This allows us to bring MIOpen in the [`main` archive](https://www.debian.org/doc/debian-policy/ch-archive#archive-areas) is the package repository. Otherwise, we may choose to exclude all the binary files at the expense of user performance.

Same problem comes for the `src/kernels/*.inc` assembly codes, which are uploaded likewisely #2778, #1968. As they're thousands of lines, are they disassembled from some other artifacts?

Looking forward to your replay. Thanks!

**Comment by atamazov** [comment]
@Huangxt57 
> Same problem comes for the `src/kernels/*.inc` assembly codes

FYI The most of those have been generated by an open-source generator, https://github.com/ROCm/MISA.

**Comment by huanrwan-amd** [comment]
@xuantengh 
If the kernel objects can't be retieved by lfs then there are 2 more options.
1 - install from apt
https://github.com/ROCm/MIOpen/blob/develop/docs/install/install.rst
apt-get install miopen-hip-<arch>kdb

2 - Rebuild using /test/gtest/db_sync.cpp
```
The db_sync test from the test/gtest directory can be used to regenerate the *.kdb files in addition to verifying their accuracy.

Steps for generating kdb files:

1. KDB files must be generated on their target architecture. Eg gfx942.kdb must be generated on a MI300 machine.
2. Load a docker image on the machine with the desired software environment.
3. Clone MIOpen and change to the desired branch. Also use git-lfs to pull the kdb files
        git-lfs pull --exclude= 
4. Install MIOpen dependencies if they are not already available on the image.
        cd MIOpen; CXX=/opt/rocm/llvm/bin/clang++ cget install -f ./dev-requirements.txt --prefix ~/MIOpen/deps
5. Build MIOpen with COMGR and HIPRTC disabled so that kernel objects are generated without target id.
        mkdir build; cd build; CXX=/opt/rocm/llvm/bin/clang++ cmake -DMIOPEN_TEST_DBSYNC=1 - 
        DCMAKE_INSTALL_PREFIX=~/MIOpen/install -DCMAKE_PREFIX_PATH=~/MIOpen/deps -DMIOPEN_USE_COMGR=Off -DMIOPEN_USE_HIPRTC=Off  ..
        LLVM_PATH=/opt/rocm/llvm make -j$(nproc) install test_db_sync 
6. Current copies of the MIOpen dbs will be in ~/MIOpen/build/share/miopen/db after building MIOpen. To do a full regeneration of the kdb, the target kdb will need to be emptied here.
        sqlite3 ~/MIOpen/build/share/miopen/db/gfx942.kdb "delete from kern_db" 
7. Now test_db_sync can be run to generate the full kdb in the user directory.
        MIOPEN_USER_DB_PATH=~/.cache/miopen MIOPEN_SYSTEM_DB_PATH=~/MIOpen/build/share/miopen/db  MIOPEN_TEST_DBSYNC=1 ./bin/test_db_sync 
8. The complete *.ukdb file will be at MIOPEN_USER_DB_PATH, copy this file to the target kdb name eg gfx942.kdb.
9. Disable journaling for the new kdb file
        sqlite3 gfx942.kdb "pragma journal_mode=delete" 
10. Replace the kdb.bz2 file in MIOpen/src/kernels/
        lbzip2 -kf gfx942.kdb 
11. The .gitattributes file marks this filetype as a lfs file. git add/commit/push can be called on the kdb.bz2 file the same as a usual git file.

```
Thanks @cderb for providing the comments.
