### ISSUE TITLE
[GEMM group conv] Incorrect GPU time when GemmBwd1x1_stride1 and GemmFwd1x1_0_1 are invoked in "Run" mode.

### ISSUE THREAD

**Issue by atamazov** [ROCmSoftwarePlatform/MIOpen#2967]
The issue affects only performance testing, when GPU time is collected via MIOpenDriver etc. Internal benchmarking of kernels (during Find calls) is fine. I am going to fix this soon, as a by-product of some other work.

### Incorrect (too high) GPU time when GemmBwd1x1_0_1 is invoked in "Run" mode for group convolutions

https://github.com/ROCm/MIOpen/blob/fc5bac7a1bfa4690bc6df7221574fddfedc3cba5/src/solver/gemm_bwd.cpp#L573-L579

It should contain:
```C++
if(group_count > 1 && conv_params.type != InvokeType::Run)
    time_gemm *= in_n;
```

### Incorrect (too small) GPU time when GemmFwd1x1_0_1 is invoked in "Run" mode for group convolutions

https://github.com/ROCm/MIOpen/blob/fc5bac7a1bfa4690bc6df7221574fddfedc3cba5/src/solver/gemm.cpp#L828-L832

It should contain:
```C++
if(conv_params.type != InvokeType::Run)
    time_gemm += time * in_n;
else
    time_gemm += time;
```
[Notice] `group_count > 1` should be removed because it is always true there.

----
[Attribution] @junliume @JehandadKhan @DrizztDoUrden 
- https://github.com/ROCm/MIOpen/labels/bug
- https://github.com/ROCm/MIOpen/labels/testing
- https://github.com/ROCm/MIOpen/labels/urgency_normal
- Proposed assignees: @atamazov

**Comment by averinevg** [comment]
Should we close the issue?
