### ISSUE TITLE
Hybrid mode with iGEMM hit detection

### ISSUE THREAD

**Issue by daniellowell** [ROCmSoftwarePlatform/MIOpen#299]
Currently we have PR #178. Which has this "hybrid" behavior:
1. When running Find() MIOpen will first check the Find-Db
2. If there is a hit, then that solver will be selected for compilation and execution
3. If there is a miss, then the "normal" Find() behavior kicks in.

In order to reduce compilation time down further, we propose this tweak in the "hybrid" mode:
1. When running Find() MIOpen will first check the Find-Db
2. If there is a hit, then that solver will be selected for compilation and execution even if the kernel is a iGEMM HIP source kernel
3. If there is a miss, then the "normal" Find() mode kicks in with the HIP source iGEMM kernels bypassed.

This would imply we can distinguish ASM versions of iGEMM from HIP versions and that we have a complement of ASM iGEMM solvers so there is no significant performance decrease. However, since a miss in the Find-Db implies a miss in the performance database, I do not think there will be a performance drop.

**Comment by atamazov** [comment]
> If there is a miss, then the "normal" Find() mode kicks in with the HIP source iGEMM kernels bypassed.

That would bypass also "dynamic" HIP kernels. Do we want this?

**Comment by atamazov** [comment]
Shall we see how much can we get from existing measures, -- Hybrid Find, precompiled kernels, hip-clang (which seems way faster than hcc) -- and then decide about importance of this.

**Comment by daniellowell** [comment]
> That would bypass also "dynamic" HIP kernels. Do we want this?

No, what I meant was that asm iGEMM “dynamic” kernels would run, but HIP source kernels would not be.

**Comment by atamazov** [comment]
...So this would implicitly depend on how "dynamic" kernels are written. I think it is better to explicitly specify which Solutions should be skipped during Hybrid Find fallback (that leverages normal Find). This is clear design (and easy to implement).

**Comment by atamazov** [comment]
[Minor side effect] This (skipping solvers during Hybrid Find fallback) may affect _potential_ Immediate mode performance. I am saying "potential" because this happens when find-db does NOT contain relevant record, so Immediate mode would by default hit its fallback (now GEMM). However Immediate mode may reveal better performance after normal Find (and after Hybrid mode) than after this modified Hybrid. Although the side effect is negligible, it indicates a quirky design.

**Comment by carlushuang** [comment]
This mode seems also imply a **db-record-first** strategy. I think it is OK and easy to understand. If there is some _potential_ performance drop, just add them into DB?

**Comment by JehandadKhan** [comment]
This might be simplified if we add dynamic iGEMM as a separate algorithm

**Comment by daniellowell** [comment]
@carlushuang @JehandadKhan It might be easier if dynamic iGEMM asm kernels were a different algorithm. I'm not sure it matters if we an just filter on solvers, but perhaps it would be cleaner.

**Comment by atamazov** [comment]
The notion of "algorithm" is intended for other purposes. See https://github.com/AMDComputeLibraries/MLOpen/issues/1753

**Comment by atamazov** [comment]
https://github.com/ROCmSoftwarePlatform/MIOpen/issues/299#issuecomment-645692843 is updated with more or less clear proposal.

### Motivation

Q: Why we are not simply disabling the Solvers that delay the inital startup time, i.e. those that slow to build AND have narrow coverage? Why we want this "tweak"? Tweaks are not good!

A: We are delivering a package with pre-compiled kernels for the best Solvers. These include the "delaying" Solvers, but these do not introduce any delay because kernels are pre-compiled. The system-find-db contains relevant information.

If we disable the "delaying" Solvers then:
- We need to build a dediated package with pre-compiled kernels.
- We need to prepare another "version"  of the system-find-db.
- And this would lead to GPU performance drop.

The tweak allows us to:
- Re-use exising pre-compiled kernels package
- Re-use existing system-find-db
- Keep GPU performance on known configs.

:arrow_right: The same effect on the initial startup time, but better GPU performance and less work.

**Comment by JehandadKhan** [comment]
I would be against anything that creates versions of any db for any purpose. This adds considerable overhead and strains procedures in place.

**Comment by atamazov** [comment]
Of course :wink:

**Comment by daniellowell** [comment]
@carlushuang @zjing14 What is the status of this feature?

**Comment by zjing14** [comment]
@daniellowell I did not get a chance to take care of this PR. I will work on this PR this week. Is it urgent?

**Comment by daniellowell** [comment]
Not urgent per-say, I would just like to make progress on it.

**Comment by zjing14** [comment]
At the first stage, we should separate the dynamic igemm solvers (i.e., ConvAsmImplicitGemmV4R1DynamicFwd_1x1 and ConvAsmImplicitGemmV4R1DynamicFwd) out of the regular implicit gemm algorithm into a new algorithm, called dynamicImplicitGemm.

**Comment by zjing14** [comment]
> ...So this would implicitly depend on how "dynamic" kernels are written.
> 
> ## Proposal
> Add an explicit attribute to all Solutions. The attribute says whether a solution should be skipped during fallback. Default value is "false" (do not skip). Should be explicitly set to "true" in the selected (slow to build AND having narrow coverage) Solvers.
> 
> Implement the new optimized Find mode ("Optimized Hybrid Find"?) that reads and uses the new attribute during fallback. Make it the default, keeping in mind the following side effect.

 @atamazov @daniellowell Since all igemm solvers except dynamic igemm are hip-based. After splitting all dynamic igemm into a dedicated algorithm, we skip the entire igemm algorithm instead of adding an explicit attribute to all solvers.

**Comment by atamazov** [comment]
> At the first stage, we should separate the dynamic igemm solvers (i.e., ConvAsmImplicitGemmV4R1DynamicFwd_1x1 and ConvAsmImplicitGemmV4R1DynamicFwd) out of the regular implicit gemm algorithm into a new algorithm, called dynamicImplicitGemm. I will create a PR for this.

Please don't. This would affect all databases.

**Comment by atamazov** [comment]
Let's reach consensus prior going for implementation.

**Comment by zjing14** [comment]
Purpose a prototype with FallBackSolversContainer (PR #326). @atamazov @pfultz2 @JehandadKhan Please check if the method is OK for the "hybrid" mode

**Comment by atamazov** [comment]
@zjing14 Thanks! Some [feedback](https://github.com/ROCmSoftwarePlatform/MIOpen/pull/326#issuecomment-654483612).

**Comment by atamazov** [comment]
@daniellowell I believe we need a name for this new Find mode. This is very like the Hybrid mode, but with an _optimized version of Find machinery_ -- where "inefficient" kernels are excluded, -- instead of the normal Find on the fallback path. What about ___OptimizedHybrid Find mode___?

**Comment by JehandadKhan** [comment]
@atamazov I would prefer the implementation that @zjing14 has created as opposed to touching each solver to add a new attribute. Having a container as a heuristic, I believe is much simpler to maintain. @pfultz2 do you care to weigh in ?

**Comment by atamazov** [comment]
@JehandadKhan 
> (C) Each Solver that takes long time to build and has narrow coverage should be modified: its IsApplicable() should return false when skip_solutions_that_take_long_time_to_build_and_have_narrow_coverage is true. 
>
> ## Other solvers do not require modifications.

**Comment by JehandadKhan** [comment]
@atamazov Fair enough, however, having a single container to change if we add new solver or remove one from the mix seems like a better design to me. This gives one source location with all the information.

**Comment by atamazov** [comment]
> having a single container to change if we add new solver or remove one from the mix seems like a better design to me

Having zero containers to change is even better, right? No need to change anything when we add or remove the Solver. It is the Solver who contains all the info.

**Comment by JehandadKhan** [comment]
> > having a single container to change if we add new solver or remove one from the mix seems like a better design to me
> 
> Having zero containers to change is even better, right? No need to change anything when we add or remove the Solver. It is the Solver who contains all the info.

Indeed, and finding out which container would and would not be called requires looking at all solvers.

**Comment by atamazov** [comment]
> Indeed, and finding out which container would and would not be called requires looking at all solvers.

Do you have performance optimization in mind?

**Comment by JehandadKhan** [comment]
> Do you have performance optimization in mind?

I don't believe either approach would differ much in performance.

**Comment by atamazov** [comment]
FAST_HYBRID mode implemented in #326
