### ISSUE TITLE
Error: There is no device can be used to do the computation on HIP/CUDA path

### ISSUE THREAD

**Issue by sriharikarnam** [ROCmSoftwarePlatform/MIOpen#30]
We get "Error: There is no device can be used to do the computation" on HIP/CUDA path, while exercising test cases after integrating MiOpen for MXNet HIP Port.
Pre-built MiOpen package is taken from ROCm.($ sudo apt-get install miopen-hip)

Query: 
Does pre-built package of MiOpen  supports both  HIP/CUDA and HIP/ROCm Platforms.

**Comment by dagamayank** [comment]
Please clarify what do you mean by HIP/CUDA path?

**Comment by sriharikarnam** [comment]
@dagamayank : We have done porting of MXNet to HIP, and this port is expected to work on NVCC platform and HCC platform as a common code. We have integrated MiOpen in place of cuDNN. After integration , while testing the port on NVCC platform with MiOpen, we get error as above.

**Comment by dagamayank** [comment]
@sriharikarnam MIOpen is not meant to work on any other platform apart from ROCm. Therefore, it will not work with `nvcc`. If you want your HIP port to work with `nvcc` please use cuDNN.
