### ISSUE TITLE
[SLES][RHEL8] error: no member named 'exclusive_scan' in namespace 'std

### ISSUE THREAD

**Issue by junliume** [ROCmSoftwarePlatform/MIOpen#3048]
https://github.com/ROCm/MIOpen/blob/upgrade_environ/src/include/miopen/graphapi/util.hpp#L70

sles and rhel8 build failed, 
```
2024-06-11T10:13:11.549602605Z In file included from /long_pathname_so_that_rpms_can_package_the_debug_info/src/extlibs/MLOpen/src/graphapi/find_engine.cpp:36:
2024-06-11T10:13:11.549641496Z /long_pathname_so_that_rpms_can_package_the_debug_info/src/extlibs/MLOpen/src/include/miopen/graphapi/util.hpp:70:10: error: no member named 'exclusive_scan' in namespace 'std'
2024-06-11T10:13:11.549648076Z    70 |     std::exclusive_scan(dims.begin(), dims.end(), strides.begin(), T{1LL}, std::multiplies<T>{});
2024-06-11T10:13:11.549658586Z   
```

**Comment by amberhassaan** [comment]
Are the RHEL8 systems not using `c++17`? `std::exclusive_scan` is part of the `c++-17` standard library.

**Comment by CAHEK7** [comment]
> Are the RHEL8 systems not using `c++17`? `std::exclusive_scan` is part of the `c++-17` standard library.

It may not be fully supported.

**Comment by junliume** [comment]
@CAHEK7 @amberhassaan since we have `boost` can we use `boost::compute::exclusive_scan` instead?

**Comment by JehandadKhan** [comment]
I would suggest not using boost, since we wish to retire it as a dependency. I am curious as to why this is an issue to begin with, since we use amd-clang to build it. Which would support stuff across the board ?

**Comment by CAHEK7** [comment]
> I would suggest not using boost, since we wish to retire it as a dependency. I am curious as to why this is an issue to begin with, since we use amd-clang to build it. Which would support stuff across the board ?

We are using a system-installed standard library. We can ship and use our own, but that can be a problem.

**Comment by junliume** [comment]
> e we have `boost` can we use `boost::compute::exclusive_scan` instead?

IIUC, HIP `amdclang++` still (by default) depends/links on/against `libstdc++` shipped with native GNU in these Linux distributions? I am wondering if we can link to LLVM `libc++` but the support of the latter might not be well covered either.

**Comment by amberhassaan** [comment]
That means these systems are not using a `C++-17` compliant `libstdc++` and that is not acceptable to begin with. Otherwise, we are saying that we will use `c++-17` language features but not library features, so that's like supporting half the standard, not complete standard.

**Comment by CAHEK7** [comment]
> That means these systems are not using a `C++-17` compliant `libstdc++` and that is not acceptable to begin with. Otherwise, we are saying that we will use `c++-17` language features but not library features, so that's like supporting half the standard, not complete standard.

No, it does not mean. There are no linux-based libraries which fully support the whole C++17 standard. For example, parallel algorithms are still badly supported. Moreover `std::exclusive_scan` is not even separately tracked as a special feature.
This particular algorithm has been supported in clang 16, which is released... in 2023! So we must drop everything 1 year old.
It's a bit better for gcc - the first support released in gcc 11, which is 2021, but still.
