### ISSUE TITLE
Remove deprecated Comgr actions

### ISSUE THREAD

**Issue by lamb-j** [ROCmSoftwarePlatform/MIOpen#3075]
The AMD_COMGR_ACTION_COMPILE_SOURCE_TO_FATBIN and AMD_COMGR_ACTION_ADD_DEVICE_LIBRARIES actions have been deprecated, and will be removed with the upcoming Comgr 3.0 release.

We should be able to replace them with one of the following:

AMD_COMGR_ACTION_COMPILE_SOURCE_WITH_DEVICE_LIBS_TO_BC

or 

AMD_COMGR_ACTION_COMPILE_SOURCE_TO_RELOCATABLE
AMD_COMGR_ACTION_COMPILE_SOURCE_TO_EXECUTABLE
 
(Although not in the action name, the last two also add the device libraries)

**Comment by JehandadKhan** [comment]
@atamazov  Can you please take a look when you get a chance ?

**Comment by atamazov** [comment]
[Notice]
> The AMD_COMGR_COMPILE_SOURCE_TO_FATBIN

Typo, it should be AMD_COMGR_`ACTION_`COMPILE_SOURCE_TO_FATBIN

**Comment by atamazov** [comment]
@lamb-j 
> The AMD_COMGR_COMPILE_SOURCE_TO_FATBIN and AMD_COMGR_ACTION_ADD_DEVICE_LIBRARIES actions have been deprecated, and will be removed with the upcoming Comgr 3.0 release.

Are you going to remove these from the `amd_comgr_action_kind_t` enum or just make them not working?

**Comment by atamazov** [comment]
@JehandadKhan 

> The AMD_COMGR_COMPILE_SOURCE_TO_FATBIN

This is only used in `comgr::BuildHip()`, which is deprecated and not used anymore (we use HIPRTC instead). I am going to remove it anyway.

> AMD_COMGR_ACTION_ADD_DEVICE_LIBRARIES 

This one is used in two places
- `comgr::BuildHip()`, which we do not care of anymore (see above)
- `comgr::BuildOcl()`, but only if COMgr version is < 1.7

So it seems like we do not need to make any changes in the library provided that the upcoming changes in COMgr won't break the `amd_comgr_action_kind_t` enum (see https://github.com/ROCm/MIOpen/issues/3075#issuecomment-2192617063).

**Comment by lamb-j** [comment]
We are planning to remove the following from the enums:

Actions:
AMD_COMGR_ACTION_OPTIMIZE_BC_TO_BC
AMD_COMGR_ACTION_COMPILE_SOURCE_TO_FATBIN
AMD_COMGR_ACTION_ADD_DEVICE_LIBRARIES

Languages:
AMD_COMGR_LANGUAGE_HC

As we're incrementing the major version, our goal is to remove all the functionality previously marked as deprecated

**Comment by lamb-j** [comment]
@atamazov Any updates?

**Comment by atamazov** [comment]
@lamb-j Sorry I was busy with other stuff. The changes described at https://github.com/ROCm/MIOpen/issues/3075#issuecomment-2192739434 look good to me. I'll make the necessary adaptations in MIOpen ASAP and let you know.

**Comment by atamazov** [comment]
@lamb-j #3107 contains necessary fixes. Thanks for heads-up.

**Comment by atamazov** [comment]
[Informative] COMgr 3.0 changes: https://github.com/ROCm/llvm-project/blob/amd-staging/amd/comgr/docs/ReleaseNotes.md#comgr-v30-release-notes

**Comment by lamb-j** [comment]
Need changes in amd-master branch

**Comment by atamazov** [comment]
@junliume FYI

> Need changes in amd-master branch

**Comment by junliume** [comment]
@atamazov @lamb-j is there a pending PR? We need to make changes to `develop` branch regardless.

**Comment by lamb-j** [comment]
https://github.com/ROCm/MIOpen/pull/3107

We had the above PR against the "develop" branch. Do I need to create similar PRs for the "amd-develop" and "amd-master" branches?

**Comment by junliume** [comment]
> #3107
> 
> We had the above PR against the "develop" branch. Do I need to create similar PRs for the "amd-develop" and "amd-master" branches?

#3107 is already under mainline staging (currently in `amd-develop` branch), if staging passes it will be merged into mainline `amd-master`

**Comment by lamb-j** [comment]
Looks like the patch was promoted to mainline. Thanks!
