### ISSUE TITLE
CopyTensor in c-api

### ISSUE THREAD

**Issue by ashmanov** [ROCmSoftwarePlatform/MIOpen#31]
Hello! Why not wrap [CopyTensor from C++ api](https://github.com/ROCmSoftwarePlatform/MIOpen/blob/master/src/include/miopen/tensor_ops.hpp#L57) as miopenTransformTensor in c-api?

**Comment by ashmanov** [comment]
It looks like it is easy to add it and developers just forgot to add it to C-API.

**Comment by daniellowell** [comment]
As I understand it, transfer tensor isn't a simple copy over, but changing the data layout. In that case wrapping copyTensor would not be sufficient. Also, MIOpen currently only supports NCHW as our 4D tensor layout.
