### ISSUE TITLE
CMake flag for embedded builds

### ISSUE THREAD

**Issue by daniellowell** [ROCmSoftwarePlatform/MIOpen#321]
### Required:
Changes to make user-db optional. 
CMake variable `-DMIOPEN_DISABLE_USERDB=1`
Reference PR #251

Changes to disable system-db:
CMake variable `-DMIOPEN_DISABLE_SYSDB`
Reference PR #329 

Build statically.
CMake variable `-DBUILD_SHARED_LIBS=Off`
Reference PR #137 

Disable HIP kernels.
CMake variable `-DMIOPEN_USE_HIP_KERNELS=Off`
Reference PR #283 

Enable builds via COMgr.
CMake variable `-DMIOPEN_USE_COMGR=On`
Reference PRs #177 #257 #293 #315

_Edit: Should be fixed by the HIP team_
~~HIP static library: `-lamdhip64_static`~~

### Conditional:
 (depending on PR merging)

Embed databases
CMake variable `-DMIOPEN_EMBED_DB=1`
Reference PR #313 

-------------------------
Feature PR: #327

**Comment by atamazov** [comment]
Added COMgr specific flags.

**Comment by pfultz2** [comment]
> HIP static library: -lamdhip64_static

This should be fixed in HIP(as its an usage requirement for HIP static lib), MIOpen should not be adding this flag.

**Comment by aserio** [comment]
@daniellowell can this issue now be closed or should we expect further PRs to address this issue?

**Comment by daniellowell** [comment]
I still need to integrate rocBLAS, leaving this open in case there are any additional issues.

**Comment by aserio** [comment]
@daniellowell, have you had the opportunity to integrate rocBLAS?

**Comment by aserio** [comment]
Daniel reports that the rocBLAS library has been integrated.
