### ISSUE TITLE
Which version of hcc should I use to build MIOpen

### ISSUE THREAD

**Issue by tstellar** [ROCmSoftwarePlatform/MIOpen#33]
I've been using the rocm-1.6.0 release of hcc to build MIOpen, but I'm getting the error below.  I'm seeing this error with  v1.2.0 and 1.1.4.  Which versions of hcc are supported?

hcc: /builddir/build/BUILD/llvm-rocm-1.6.0/tools/clang/lib/Sema/SemaChecking.cpp:9826: void clang::Sema::DiagnoseAlwaysNonNullPointer(clang::Expr*, clang::Expr::NullPointerConstantKind, bool, clang::SourceRange): Assertion `ParamIter != FD->param_end()' failed.

**Comment by tstellar** [comment]
This is working for me now with hcc from the rocm-1.7.0 release.

**Comment by dagamayank** [comment]
@tstellar Thanks. Closing this issue then.
