### ISSUE TITLE
Compatiblity with MIGraph Python API?

### ISSUE THREAD

**Issue by EXJUSTICE** [ROCmSoftwarePlatform/MIOpen#3345]
Hi

I understand that it is possible to run MIOpen together with the MIGraph driver on the command line, by adding prefixes for `MIOPEN_FIND_ENFORCE` and `MIOPEN_FIND_MODE`.
MIGraph also has a Python API - is there support for MIOpen in this approach? For example, through the use of env variables as [shown in the documentation](https://rocm.docs.amd.com/projects/MIOpen/en/docs-5.3.3/find_and_immediate.html)

**Comment by ppanchad-amd** [comment]
Hi @EXJUSTICE. Internal ticket has been created to assist with your question. Thanks!

**Comment by huanrwan-amd** [comment]
Hi @EXJUSTICE , thank you for your message. Just want to understand your question clearly: do you want a set of python API for MIOpen API? Currently MIOpen only support C++ APIs: https://rocm.docs.amd.com/projects/MIOpen/en/latest/reference/index.html

**Comment by huanrwan-amd** [comment]
Hi @EXJUSTICE, close the issue for now. If you need further help, please let us know.
