### ISSUE TITLE
Ship MIOpenDriver by default

### ISSUE THREAD

**Issue by whchung** [ROCmSoftwarePlatform/MIOpen#34]
Please consider ship `MIOpenDriver` in the release package so it's easier for framework developers to diagnose issues.

**Comment by whchung** [comment]
`MIOpenDriver` at tip of MIOpen won't link (commit # 08114baa029a519ea12b52c5274c0bd8f4ad0d26)

Error log:
```
[100%] Linking CXX executable ../bin/MIOpenDriver
ld: /tmp/tmp.UgTm62Ysql/main.cpp.host.o: undefined reference to symbol '_ZN5boost6system15system_categoryEv'
//usr/lib/x86_64-linux-gnu/libboost_system.so.1.58.0: error adding symbols: DSO missing from command line
clang-6.0: error: linker command failed with exit code 1 (use -v to see invocation)
driver/CMakeFiles/MIOpenDriver.dir/build.make:129: recipe for target 'bin/MIOpenDriver' failed
make[3]: *** [bin/MIOpenDriver] Error 1
CMakeFiles/Makefile2:3322: recipe for target 'driver/CMakeFiles/MIOpenDriver.dir/all' failed
make[2]: *** [driver/CMakeFiles/MIOpenDriver.dir/all] Error 2
CMakeFiles/Makefile2:3329: recipe for target 'driver/CMakeFiles/MIOpenDriver.dir/rule' failed
make[1]: *** [driver/CMakeFiles/MIOpenDriver.dir/rule] Error 2
Makefile:1378: recipe for target 'MIOpenDriver' failed
make: *** [MIOpenDriver] Error 2
```

**Comment by whchung** [comment]
Have to manually edit `build/driver/CMakeFiles/MIOpenDriver.dir/link.txt` and add `-lboost_system` to make `MIOpenDriver` link.

Relevant stackoverflow post: https://stackoverflow.com/questions/38650981/undefined-reference-to-symbol-zn5boost6system15system-categoryev-error

**Comment by pfultz2** [comment]
I would prefer not to ship the driver. Its only for miopen developers, its not tested, and has issues. We could ship the tests, but those should go in a separate package.

**Comment by whchung** [comment]
we need help from users of DNN frameworks, and `MIOpenDriver` would be a first step to help users provide more information. I'm okay to have it shipped in a different package.

**Comment by whchung** [comment]
Please consider ship MIOpenDriver in the release package so it's easier for framework developers to diagnose issues.

**Comment by bensander** [comment]
Agree this would be very useful.  Could help with power and perf analysis , end user issues, and more

**Comment by daniellowell** [comment]
Added to MIOpen 2.0.0
