### ISSUE TITLE
miopen 6.3.0 fails to build due to missing `#include <cmath>`

### ISSUE THREAD

**Issue by AngryLoki** [ROCmSoftwarePlatform/MIOpen#3441]
On system with unmodified clang-19 with libstdc++-14 miopen-6.3.0 fails to build with:

```
In file included from /var/tmp/portage/sci-libs/miopen-6.3.0/work/MIOpen-rocm-6.3.0/driver/dm_reducecalculation.cpp:26:
/var/tmp/portage/sci-libs/miopen-6.3.0/work/MIOpen-rocm-6.3.0/driver/reducecalculation_driver.hpp:80:34: error: no matching function for call to 'isnan'
   80 |             if(nanPropagation && isnan(val))
      |                                  ^~~~~
```

Note, that on some other systems it compiles for various reasons. For example, on libc++ systems it works fine, as `math.h` is indirectly included in `<algorithm>`
```
#include <algorithm>
// #include <math.h>

auto x = isnan(1);
```
Conformance viewer: https://godbolt.org/z/qvG61vE8W

Could you apply this fix? Thanks!

```diff
--- a/driver/reducecalculation_driver.hpp
+++ b/driver/reducecalculation_driver.hpp
@@ -34,6 +34,7 @@
 #include <algorithm>
 #include <cfloat>
 #include <cstdlib>
+#include <cmath>
 #include <memory>
 #include <miopen/miopen.h>
 #include <miopen/tensor.hpp>
@@ -77,7 +78,7 @@ int32_t mloReduceCalculationForwardRunHost(miopenTensorDescriptor_t inputDesc,
         for(size_t i = 0; i < reduce_size; ++i)
         {
             Tcheck val = static_cast<Tcheck>(input[input_idx]);
-            if(nanPropagation && isnan(val))
+            if(nanPropagation && std::isnan(val))
             {
                 val = 0.0f;
             }

```

**Comment by johnnynunez** [comment]
https://github.com/Rinzii/ccmath ?

**Comment by lucbruni-amd** [comment]
Hi @AngryLoki, an internal ticket has been created and we are looking into the matter. Thanks for your patience.

**Comment by CAHEK7** [comment]
@AngryLoki, I'm afraid that going through the internal bug tracker, planning, discussing, implementing, reviewing, etc will take eternity for this trivial thing.

**Comment by AngryLoki** [comment]
@CAHEK7 , from what I see, making pull-requests to ROCm repositories does not help, as they are also need to be imported into internal fork first. Correct me if I'm wrong.

Regarding time - for me it does not matter, I applied patch and just want to remove this patch in some future version.

**Comment by CAHEK7** [comment]
@AngryLoki
All the development happens right inside this repository, and this repo is used for the release process. All the PRs should land here, and even if this repo is used somewhere internally, it's a submodule or direct git hash pointing on  the particular release branch (or just fixed revision).
