### ISSUE TITLE
Segfault in miopenFindConvolutionForwardAlgorithm

### ISSUE THREAD

**Issue by AdemSchen** [ROCmSoftwarePlatform/MIOpen#36]
When using miopenFindConvolutionForwardAlgorithm me and my group get segfault! We been wondering if it is because of using Malloc and not allocating with opencl is this possible ?

**Comment by dagamayank** [comment]
@AdemSchen If you are using OpenCL then yes, the buffers need to allocated using the OpenCL buffer creation APIs. On the other hand, if you are using HIP then the buffers need to allocated using the HIP buffer creation APIs. Just C `malloc` will not work. Hope this addresses the issue.
