### ISSUE TITLE
Move databases to precompiled kernels

### ISSUE THREAD

**Issue by daniellowell** [ROCmSoftwarePlatform/MIOpen#376]
The current performance database is in binary format, and it is now approaching 80MB.
There is a max limit of 100MB on GitHub, so we will need to do tricks to support it if we are to continue.
I propose moving all databases to precompiled kernels packages.

The alternative is to break up all databases along architectures to reduce individual database file sizes.

**Comment by JehandadKhan** [comment]
In theory Git LFS as suggested by @ce1adon is an ideal solution, since it would allow us to bring back the pre-compiled kernels package in the repo as well (no more separate package and simpler embedded package as well). However, when we tested it for a separate repo, it needs installation of the separate package ( the git lfs package) and it would not pull down the db file automatically and you need additional steps to be able to get the binary files. 

@ce1adon do you agree, or do you think its doable ?

**Comment by pfultz2** [comment]
When using git lfs, will we still be able to download the source tarballs from GH?

> I propose moving all databases to precompiled kernels packages.

This makes it difficult to use MIOpen when building and installing from source as the kernels package and webserver is not publicly available nor is it easily installable.

> The alternative is to break up all databases along architectures to reduce individual database file sizes.

I thought we already do that?

**Comment by JehandadKhan** [comment]
> > The alternative is to break up all databases along architectures to reduce individual database file sizes.
> 
> I thought we already do that?
For everything except perf db

**Comment by daniellowell** [comment]
>For everything except perf db

Bingo.

But really I think it may be better to kick the can down there road and split up the performance database across separate architectures.

**Comment by JehandadKhan** [comment]
> I think it may be better to kick the can down there road and split up the performance database across separate architectures.

Can you please clarify a bit? 

Do we want to split the DBs now and avoid storing these files separately ? 
Or 
Do we want to just move the file away now and not have to deal with this again and again? 
Or
Both ?

**Comment by daniellowell** [comment]
Split the performance database miopen.db across architectures.
We will have to revisit this again, but the complexity of moving the db to the precompiled kernels seems not fantastic....

**Comment by aserio** [comment]
@daniellowell shall I mark this as on hold?

**Comment by aserio** [comment]
@daniellowell shall I mark this as on hold?

**Comment by aserio** [comment]
Will create a ticket to split the perf-db into arch. specific files.
