### ISSUE TITLE
FP16 xdlops regression after PR #323

### ISSUE THREAD

**Issue by asroy** [ROCmSoftwarePlatform/MIOpen#377]
@zjing14 Somehow this PR is creating some regression in some cases (using rocm 3.5)

commit: 089f10fe8977ce90684f839fb1af17439590a8a9
```
MIOpenDriver convfp16 -F 1 -n 128 -g 1 -k 1024 -c 1024 -H 73 -W 73 -y 3 -x 3 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -V 0 -w 1 -t 1 -i 1
MIOpen Forward Conv. Algorithm: 5, Solution: 64/ConvHipImplicitGemmForwardV4R4Xdlops
GPU Kernel Time Forward Conv. Elapsed: 119.610374 ms (average)
stats: name, n, c, ho, wo, x, y, k, flopCnt, bytesRead, bytesWritten, GFLOPs, GB/s, timeMs
stats: fwd-conv3x3u1, 128, 1024, 71, 71, 3, 3, 1024,  12178648203264, 1415839744, 1321467904, 101819, 23, 119.610374
```

commit: 14064f08046b926459ff19295e741eb222a0b553
```
MIOpen Forward Conv. Algorithm: 5, Solution: 64/ConvHipImplicitGemmForwardV4R4Xdlops
GPU Kernel Time Forward Conv. Elapsed: 156.308685 ms (average)
stats: name, n, c, ho, wo, x, y, k, flopCnt, bytesRead, bytesWritten, GFLOPs, GB/s, timeMs
stats: fwd-conv3x3u1, 128, 1024, 71, 71, 3, 3, 1024,  12178648203264, 1415839744, 1321467904, 77914, 18, 156.308685
```

_Originally posted by @asroy in https://github.com/ROCmSoftwarePlatform/MIOpen/pull/323#issuecomment-672575177_

**Comment by asroy** [comment]
This maybe a compiler issue (related to AccVGPR), @zjing14 please look into it and create a compiler JIRA if necessary.

**Comment by zjing14** [comment]
Yes. The regression is caused by AccVGPR allocation issue. Using M/N repeats will trigger that. Let me investigate if it is due to moving repeats from blockwise-gemm to xdlops-gemm. If yes, we can temporally keep repeats in blockwise-gemm.

**Comment by atamazov** [comment]
[Side note] @asroy As the main product of the library (after correctness) is _performance_, I would say that any performance regression this is a bug. Of course, correctness bugs usually should have higher priority assigned (than performance bugs), and we have a set of `priority` labels for that.

However the term `bug` usually understood as a correctness problem. Perhaps that if why you've used the `performance` label. I think it is worth to rename the `bug` label to `defect` and introduce two more categories: `correctness` and `performance` for the cases when we want (and can) be specific. For example, `enhancement` can be additionally marked with `performance`. And we already have `quality` (which I usually understand as code quality). What do you think?

/cc @daniellowell

**Comment by atamazov** [comment]
@asroy @zjing14 Let's track SWDEV-241664. If it is decided that the problem is in the compiler, then we'll need to rework the code introduced in #379. We'll need to use version detection machinery to disable the workaround as soon as fixed compiler arrives. Am I correct?

**Comment by asroy** [comment]
@atamazov I believe this issue will be fixed by #403. @zjing14 Can you confirm?

**Comment by zjing14** [comment]
This should be already workaround in develop. Of course #403 can resolve
the problem fundamentally.

**Comment by atamazov** [comment]
Good news, thanks.
