### ISSUE TITLE
Heuristic mapping feature

### ISSUE THREAD

**Issue by daniellowell** [ROCmSoftwarePlatform/MIOpen#378]
@carlushuang @atamazov I merged this PR #368, but I am thinking that we should discuss adding a type of tuning in these ASM-iGEMM. However, this feature would not be "tuning" as we know it, but rather a means to extract a heuristic based on how each of the ASM kernels perform when given an input.

In this scenario RunAndMeasure would just run through all the ASM kernels, overriding the existing heuristic and produce a tuning configuration. That tuning config would simply be the kernel selected and THAT could be placed into the perf db.

When rerunning MIOpen with this new entry in the perf db in production mode, the entry in the perf db would override the internal hardcoded heuristic.

This can initially be used for ASM-iGEMM, but we can expand it for MIOpen-Tensile when that comes on line.

**Comment by carlushuang** [comment]
Hi @daniellowell . From current solver design it seems we can't have both:

1. Purely Heuristic, no RunAndMeasure
2. Heuristic mapping, need tuning

https://github.com/ROCmSoftwarePlatform/MIOpen/blob/develop/src/include/miopen/find_solution.hpp#L118 here by `rank<>` statically, we may go either RunAndMeasure, or just GetSolution without run.

**Comment by atamazov** [comment]
@daniellowell 
> RunAndMeasure would just run through all the ASM kernels

Hmm... Do you mean exhaustive search under "RunAndMeasure"?

> ...When rerunning MIOpen with this new entry in the perf db in production mode...

What is "production mode"?

I _feel_ I know the answers, but would not like to guess ;)))

**Comment by atamazov** [comment]
@carlushuang 
>  From current solver design it seems we can't have both:
> 1. Purely Heuristic, no RunAndMeasure
> 2. Heuristic mapping, need tuning

When perf-db has relevant record, the library works as if:
```C++
perfConfig= db.Load(problem, SolverDbId(solver));
solution = solver.GetSolution(problem, perfConfig);
```
Otherwise, the library takes Solution from:
```C++
perfConfig = solver.GetPerformanceConfig(problem);
solution = solver.GetSolution(problem, perfConfig);
```
In other words, the solver builds the "default" performance-config from the problem-config. It is the `GetPerformanceConfig(ProblemDescription&)` method that does this. ___It may perform whatever heuristic we want.___

See `FindSolutionImpl(rank<1>...)` at line 42 and below.

**Comment by daniellowell** [comment]
Production mode would be MIOpen that is tuned up and being run in a regular training session.

**Comment by atamazov** [comment]
@daniellowell It seems like I've understood the idea.

We have some Solvers that can perform auto-tuning very quicky (in 1-3 seconds). Basically, those that are written in assembly language and have a small number of possible PerformanceConfigs. If auto-tuning is expected to provide significant performance gain, then it may be worth running auto-tuning automatically, when Normal Find is performed for the first time. Subsequent Finds will simply reuse the found PerformanceConfig.

Is it what you have in mind?

**Comment by atamazov** [comment]
It seems like we do not really need this.
