### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by ankan-ban** [ROCmSoftwarePlatform/MIOpen#38]
Any plans to support MIOpen on Windows platform?
Maybe provide a visual studio solution to make it easier/possible to build on Windows.

**Comment by pfultz2** [comment]
> Any plans to support MIOpen on Windows platform?

We used to build windows binaries, but we never disturbed them AFAIK. The dockerfile still sets up the compiler for windows, but its missing a proper opencl runtime.

> Maybe provide a visual studio solution to make it easier/possible to build on Windows.

CMake already can create a visual studio project.

**Comment by dagamayank** [comment]
Windows support is not planned at the moment.

**Comment by TByte007** [comment]
So at the end you only support Linux ? No BSDs like FreeBSD, OpenBSD, NetBSD or any other Unix ?

**Comment by atamazov** [comment]
I recommend opening another ticket for *NIX support discussions.
