### ISSUE TITLE
Post-merge review(s) of PR #347

### ISSUE THREAD

**Issue by atamazov** [ROCmSoftwarePlatform/MIOpen#387]
This is to be closed once all comments mentioned below are resolved.

- [x] https://github.com/ROCmSoftwarePlatform/MIOpen/pull/347#pullrequestreview-469461853

/cc reviewers of #347 -- @daniellowell @asroy @zjing14 @carlushuang @TejashShah

**Comment by aserio** [comment]
@atamazov, should we close this issue as #347 has been merged?

**Comment by atamazov** [comment]
@aserio Just the opposite.

**Comment by aserio** [comment]
@atamazov, Ah! Skimmed through to fast!

**Comment by aserio** [comment]
@jane-zxy What is the status of these post-merge reviews?

**Comment by aserio** [comment]
@jane-zxy What is the status of these post-merge reviews?

**Comment by asroy** [comment]
After double checking the comments of, I think there are not issues with original PR

https://github.com/ROCmSoftwarePlatform/MIOpen/pull/347#issuecomment-713729502

@atamazov @jane-zxy

**Comment by atamazov** [comment]
I just resolved all review comments but one, -- `NextFlag<false, false>` is not good.
