### ISSUE TITLE
Documentation Unclear: Is ROCm required even for OpenCL?

### ISSUE THREAD

**Issue by cathalgarvey** [ROCmSoftwarePlatform/MIOpen#39]
I think the answer is "No", because that's part of the selling point of MIOpen, right? :)

But, the Readme and docs seem to suggest that whichever you choose from HIP/OpenCL, you need a ROCm stack to use MIOpen. If that's not true, it should be made a bit clearer..

**Comment by dagamayank** [comment]
@cathalgarvey ROCm is the platform we *support*.  If you encounter issues on the non-supported platform then you are "on your known". Most of the performance enhancements are available only on a ROCm platform.

I am closing this issue for now.
