### ISSUE TITLE
Precompiled Headers Embedded into MIOpen static build

### ISSUE THREAD

**Issue by daniellowell** [ROCmSoftwarePlatform/MIOpen#399]
Requirements:
- Cmake flag to allow developers to precompile hip headers @shaojiewang 
- Precompile hip headers (PCH) @shaojiewang 
- Embed PCH @JehandadKhan 
- Have COMgr use PCH to compile hip kernels @atamazov 

This one requires a bit of a team effort.

**Comment by aserio** [comment]
@shaojiewang, @JehandadKhan, @atamazov, @anghostcici: What is the status of each of your contributions?
cc: @sabreshao

**Comment by JehandadKhan** [comment]
This is completed

**Comment by sabreshao** [comment]
@aserio Gupta Maneesh's team is working on implement the hip_embed_pch.sh for generating PCH object file and embed it. See SWDEV-249870 for more information.

**Comment by aserio** [comment]
Still waiting for pre-compiled header resolution. #452 should solve the issue.

**Comment by atamazov** [comment]
The design described in the topmost comment is no longer relevant. Let's not confuse ourselves. I highly recommend updating the description, or closing this ticket as invalid.
