### ISSUE TITLE
Implement workaround for correctness problems in ConvHipImplicitGemmV4R4GenWrWXdlops

### ISSUE THREAD

**Issue by atamazov** [ROCmSoftwarePlatform/MIOpen#406]
The workaround should make the solver non-applicable for the cases described at https://github.com/AMDComputeLibraries/MLOpen/issues/2532#issuecomment-682304119. This could be done quickly and would ensure correctness in case of delaying the delivery of the new bwd-wrw xdlops kernel mentioned at https://github.com/AMDComputeLibraries/MLOpen/issues/2532#issuecomment-683137628.

**Comment by asroy** [comment]
@ltqin has test new bwd-wrw on these cases and they passed.

@zjing14 Please create workaround to disable the configs for ConvHipImplicitGemmV4R4GenWrWXdlops for now. The workaround doesn't need to be very accurate because ConvHipImplicitGemmV4R4GenWrWXdlops will be deprecated once new kernel is merged in.

**Comment by zjing14** [comment]
@asroy Based on the investigation from @ekuznetsov139, the issue is related to BBlockCopySrcDataPerRead > 1. As the kernel will be deprecated, we can force BBlockCopySrcDataPerRead = 1, though it degrades performance.

**Comment by atamazov** [comment]
This looks acceptable, but may lead to worse perf pregressions than if we make the solver non-applicable.

**Comment by zjing14** [comment]
Yes. But other kernels without xdlops and atomic support won't perform well anyway.

**Comment by atamazov** [comment]
> Yes. But...

If `ConvHipImplicitGemmV4R4GenWrWXdlops` may win over all other kernels even with enforced `BBlockCopySrcDataPerRead = 1`, then I was wrong, and narrowing applicability is not the best choice for the workaround ;)

**Comment by zjing14** [comment]
I can do tests after enforcing BBlockCopySrcDataPerRead = 1 to see if ConvHipImplicitGemmV4R4GenWrWXdlops still outperform other kernels.

**Comment by aserio** [comment]
@zjing14, can this issue be closed as your PR has been merged?

**Comment by zjing14** [comment]
@aserio My PR does not fix this issue. We are waiting for this PR https://github.com/ROCmSoftwarePlatform/MIOpen/pull/413.

**Comment by atamazov** [comment]
@zjing14 This blocker issue is dedicated to the workaround and now should be closed. It is the https://github.com/AMDComputeLibraries/MLOpen/issues/2532 issue that is of high priority and needs #413.
