### ISSUE TITLE
Failure in ConvOclBwdWrW2<1>

### ISSUE THREAD

**Issue by ce1adon** [ROCmSoftwarePlatform/MIOpen#407]
A replicable failure has been observed in kernel ConvOclBwdWrW2<1>.

See:
https://github.com/ROCmSoftwarePlatform/MIOpen/pull/139#issuecomment-678445039

Please evaluate it.

**Comment by atamazov** [comment]
Thanks for opening the issue. But it works for me on Radeon VII, ROCm 3.5. How can I reproduce it? Should I use different ROCm or GPU?

**Comment by ce1adon** [comment]
> Thanks for opening the issue. But it works for me on Radeon VII, ROCm 3.5. How can I reproduce it? Should I use different ROCm or GPU?

Sure. Details sent.

**Comment by atamazov** [comment]
Moved to https://github.com/AMDComputeLibraries/MLOpen/issues/2534
