### ISSUE TITLE
[gemm_v2.cpp] dummy_memset may corrupt input data

### ISSUE THREAD

**Issue by shurale-nkn** [ROCmSoftwarePlatform/MIOpen#418]
In some cases, GEMM may corrupt input data.

This happens if one of the matrices A or B has the same pointer with matrix C. (in some cases the matrixes is located in the same buffer but with different offsets)
But the dummy_memset function does not contain an offset variable in the arguments. And it fills the memory, starting with mem, with zeros.
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/c7428da0c7bed941007e9239d4c3d3467188fb85/src/gemm_v2.cpp#L108

Therefore, in all three cases, if c_offset not zero, some input data will be corrupted

https://github.com/ROCmSoftwarePlatform/MIOpen/blob/c7428da0c7bed941007e9239d4c3d3467188fb85/src/gemm_v2.cpp#L357-L363
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/c7428da0c7bed941007e9239d4c3d3467188fb85/src/gemm_v2.cpp#L664-L670
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/c7428da0c7bed941007e9239d4c3d3467188fb85/src/gemm_v2.cpp#L927-L933

**Comment by atamazov** [comment]
@shurale-nkn We need to evaluate importance of this. Does it lead to any harm (correctness problems)? In which cases?

**Comment by daniellowell** [comment]
@shurale-nkn Updates?

**Comment by shurale-nkn** [comment]
@daniellowell 
The problem is still relevant.

In develop branch we are calling gemm with dummy_memset only in Find mode, therefore, there are no verification errors.
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/6fd907bb51fd974c083cf01aeaf52aa7d6b707f4/src/ocl/convolutionocl.cpp#L435-L445

where ``time_precision`` is responsible for using dummy_memset, 
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/6fd907bb51fd974c083cf01aeaf52aa7d6b707f4/src/ocl/convolutionocl.cpp#L363

In other cases, when correct calculations are required, we are using ``false`` instead of ``time_precision`` and any other function instead CallGemmTimeMeasure to launch gemm without dummy_memset.
 https://github.com/ROCmSoftwarePlatform/MIOpen/blob/6fd907bb51fd974c083cf01aeaf52aa7d6b707f4/src/ocl/convolutionocl.cpp#L1067-L1068

But it's not clear why ``CallGemmTimeMeasure`` with ``time_precision=true`` can't be used outside of Find mode.

**Comment by asroy** [comment]
#554 removes dummy_memset
