### ISSUE TITLE
Post-merge review of #423

### ISSUE THREAD

**Issue by atamazov** [ROCmSoftwarePlatform/MIOpen#426]
- [x] https://github.com/ROCmSoftwarePlatform/MIOpen/pull/423#discussion_r486680472

**Comment by aserio** [comment]
@atamazov, @daniellowell What is the status of this post-merge review?

**Comment by atamazov** [comment]
@aserio As you can see, this issue is open, which means that review is not resolved yet, right?

**Comment by aserio** [comment]
@atamazov form the looks of things no one is doing any work on this ticket, and according to you the work is important, easy to complete and affects performance and quality. So I think following up on the status is warranted.

**Comment by atamazov** [comment]
Absolutely.

**Comment by atamazov** [comment]
Review comments resolved.
