### ISSUE TITLE
MIOpen should have a miopenGetErrorString method.

### ISSUE THREAD

**Issue by Jorghi12** [ROCmSoftwarePlatform/MIOpen#43]
In C++, it's not possible to convert enum values back into their corresponding names since all the symbols are discarded in compiling. 

Having a method to display the error at run-time seems pretty important.

```
const char* miopenGetErrorString(miopenStatus_t status) {
    switch (status) {
    case miopenStatusSuccess:
        return "miopenStatusSuccess";

    case miopenStatusNotInitialized:
        return "miopenStatusNotInitialized";

    case miopenStatusInvalidValue:
        return "miopenStatusInvalidValue";

    case miopenStatusBadParm:
        return "miopenStatusBadParm";

    case miopenStatusAllocFailed:
        return "miopenStatusAllocFailed";

    case miopenStatusInternalError:
        return "miopenStatusInternalError";

    case miopenStatusNotImplemented:
        return "miopenStatusNotImplemented";

    case miopenStatusUnknownError:
        return "miopenStatusUnknownError";

    default:
        return "Unrecognized Status Code";
    }
}
```

**Comment by pfultz2** [comment]
> Having a method to display the error at run-time seems pretty important.

Details about the error is always printed to error stream. If you want to print the enum as a string you can always use a function like the one you've written above.

**Comment by sclarkson** [comment]
While the default logging may be good for debugging, basically everybody building an application on top of MIOpen is going to want finer control than that.

Also note that cudnn includes this function https://docs.nvidia.com/deeplearning/sdk/cudnn-developer-guide/index.html#cudnnGetErrorString

**Comment by pfultz2** [comment]
> While the default logging may be good for debugging, basically everybody building an application on top of MIOpen is going to want finer control than that.

Yea, and you can use a function like what you showed above to convert the enums to a string.

**Comment by dagamayank** [comment]
@Jorghi12 @sclarkson We will add this API in the next MIOpen release.

**Comment by daniellowell** [comment]
Added API in 1.4.0, see documentation:
```
const char* miopenGetErrorString(miopenStatus_t error);
```
