### ISSUE TITLE
Memory exception on virtual address 0x7f863d000, node id 1 : Page not present

### ISSUE THREAD

**Issue by oleid** [ROCmSoftwarePlatform/MIOpen#436]
It would seem I'm having trouble with MIOpen in Tensorflow on my R470 GPU. I'm using ArchLinux, rocm-3.7 and kernel 5.8 (mainline).

Although I'm using the rocm port of tensorflow, this looks like a miopen-problem to me.

Here a short excerpt of the messages:

```
$ HIP_TRACE_API=2 HCC_SERIALIZE_COPY=3 HCC_SERIALIZE_KERNEL=3 HIP_DB=api+copy+mem  HSAKMT_DEBUG_LEVEL=7  python minimal.py
[...]
Memory exception on virtual address 0x7f863d000, node id 1 : Page not present
Address does not belong to a known buffer
Memory access fault by GPU node-1 (Agent handle: 0x55a6d1166420) on address 0x7f863d000. Reason: Page not present or supervisor privilege.
Nearby memory map:
0x7461000, 0x9f000, System
0x7531000, 0x2cf000, System
0x900d00000, 0x80000, System

[hsaKmtQueryPointerInfo] pointer 0x7461000
PtrInfo:
        Address: 0x7461000-0x7500000/0x7461000-0x7500000
        Size: 0x9f000
        Type: 1
        Owner: 0x55a6d111c370
        CanAccess: 1
                0x55a6d1166420
        In block: 0x7461000, 0x9f000
[hsaKmtQueryPointerInfo] pointer 0x7531000
PtrInfo:
        Address: 0x7531000-0x7800000/0x7531000-0x7800000
        Size: 0x2cf000
        Type: 1
        Owner: 0x55a6d111c370
        CanAccess: 1
                0x55a6d1166420
        In block: 0x7531000, 0x2cf000
[hsaKmtQueryPointerInfo] pointer 0x900d00000
PtrInfo:
        Address: 0x900d00000-0x900d80000/0x900d00000-0x900d80000
        Size: 0x80000
        Type: 1
        Owner: 0x55a6d111c370
        CanAccess: 1
                0x55a6d1166420
        In block: 0x900d00000, 0x80000
python: /build/hsa-rocr/src/ROCR-Runtime-rocm-3.7.0/src/core/runtime/runtime.cpp:1214: static bool rocr::core::Runtime::VMFaultHandler(hsa_signal_value_t, void*): Assertion `false && "GPU memory access fault."' failed.
```

I'm seeing messages like the following via dmesg:

```
[ 2200.821623] amdgpu 0000:08:00.0: amdgpu:   VM_CONTEXT1_PROTECTION_FAULT_ADDR   0x007FBAFA
[ 2200.821625] amdgpu 0000:08:00.0: amdgpu:   VM_CONTEXT1_PROTECTION_FAULT_STATUS 0x310C4002
[ 2200.821627] amdgpu 0000:08:00.0: amdgpu: VM fault (0x02, vmid 8, pasid 32777) at page 8370938, write from 'TC3' (0x54433300) (196)
[ 2200.821632] amdgpu 0000:08:00.0: amdgpu: GPU fault detected: 147 0x0b384802 for process python pid 9023 thread python pid 9023
[ 2200.821634] amdgpu 0000:08:00.0: amdgpu:   VM_CONTEXT1_PROTECTION_FAULT_ADDR   0x007FB526
[ 2200.821635] amdgpu 0000:08:00.0: amdgpu:   VM_CONTEXT1_PROTECTION_FAULT_STATUS 0x31084002
[ 2200.821637] amdgpu 0000:08:00.0: amdgpu: VM fault (0x02, vmid 8, pasid 32777) at page 8369446, write from 'TC7' (0x54433700) (132)
[ 2200.821642] amdgpu 0000:08:00.0: amdgpu: GPU fault detected: 147 0x0940c802 for process python pid 9023 thread python pid 9023
[ 2200.821643] amdgpu 0000:08:00.0: amdgpu:   VM_CONTEXT1_PROTECTION_FAULT_ADDR   0x007F206F
[ 2200.821645] amdgpu 0000:08:00.0: amdgpu:   VM_CONTEXT1_PROTECTION_FAULT_STATUS 0x100C8002
[ 2200.821647] amdgpu 0000:08:00.0: amdgpu: VM fault (0x02, vmid 8, pasid 32777) at page 8331375, read from 'TC2' (0x54433200) (200)
[ 2200.821652] amdgpu 0000:08:00.0: amdgpu: GPU fault detected: 147 0x01e8c802 for process python pid 9023 thread python pid 9023
[ 2200.821653] amdgpu 0000:08:00.0: amdgpu:   VM_CONTEXT1_PROTECTION_FAULT_ADDR   0x007F6A99
[ 2200.821654] amdgpu 0000:08:00.0: amdgpu:   VM_CONTEXT1_PROTECTION_FAULT_STATUS 0x100C4002
[ 2200.821657] amdgpu 0000:08:00.0: amdgpu: VM fault (0x02, vmid 8, pasid 32777) at page 8350361, read from 'T
```

I have a self-contained example to reproduce the problem (with bigger convolutions) to reproduce the problem and a smaller net with non-public data. The latter has a inception-inspired architecture with very little parameter count, but it has the same problem. Naturally, CPU training works fine.

```python
import tensorflow as tf

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv1D, Conv1DTranspose, Flatten, Dropout, BatchNormalization
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.preprocessing import image

import os
import numpy as np

img_width, img_height = 28, 28
batch_size = 32
epochs = 30
input_shape = (img_width* img_height, 1)

###########

def prepare_image(im):
  return im.reshape(-1) / 255.0

###########
def log_n(x, n=10):
    """
    Compute log_n(x), i.e. the log base `n` value of `x`.
    :param x:   Input tensor
    :param n:   Value of the log base
    :return:    Log result
    """
    log_e = tf.math.log(x)
    div_log_n = tf.math.log(tf.constant(n, dtype=log_e.dtype))
    return log_e / div_log_n

def psnr(img_a, img_b, max_img_value=255):
    """
    Compute the PSNR (Peak Signal-to-Noise Ratio) between two images.
    The Peak Signal-to-Noise Ration (PSNR) is commonly used, as it measures the quality of a corrupted or
    recovered signal/image compared to its original version. The higher the value, the closer to the original image...
    (the value is in decibels, i.e. following a logarithmic scale).
    :param img_a:           Image A
    :param img_b:           Image B
    :param max_img_value:   Maximum possible pixel value of the images
    :return:                PSNR value
    """
    mse = tf.reduce_mean((img_a - img_b) ** 2)
    return 20 * log_n(max_img_value, 10) - 10 * log_n(mse, 10)

import functools

psnr_metrics = functools.partial(psnr, max_img_value=1.)
psnr_metrics.__name__ = 'psnr'


def norm_l2(img_a, img_b):
    return tf.nn.l2_loss(img_a - img_b) / batch_size

#####

(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

x_train = np.expand_dims(np.stack([prepare_image(im.reshape(28,28)) for im in x_train]), axis=-1)
x_test = np.expand_dims(np.stack([prepare_image(im.reshape(28,28)) for im in x_test]), axis=-1)

y_train = x_train # np.array([relabel_as_odd_or_even(i) for i in y_train])
y_test = x_test # np.array([relabel_as_odd_or_even(i) for i in y_test])

model = Sequential([
#  Dense(128, activation='relu', input_shape=input_shape),
#  Dense(128, activation='relu'),
#  Dense(1, activation='sigmoid'),
	Conv1D(32, 5, activation='relu', strides=2, input_shape=input_shape, padding="same"),
	BatchNormalization(),
	Conv1D(64, 5, activation='relu', strides=2, padding="same"),
	BatchNormalization(),
	Conv1D(128, 5, activation='relu', strides=2, padding="same"),
	BatchNormalization(),
	Conv1D(256, 5, activation='relu', strides=2, padding="same"),
	BatchNormalization(),
	Dropout(0.2),
	Conv1DTranspose(256, 5, activation='relu', strides=2, padding="same"),
	BatchNormalization(),
	Conv1DTranspose(128, 5, activation='relu', strides=2, padding="same"),
	BatchNormalization(),
	Conv1DTranspose(64, 5, activation='relu', strides=2, padding="same"),
	BatchNormalization(),
	Conv1DTranspose(32, 5, activation='relu', strides=2, padding="same"),
	BatchNormalization(),
	Conv1DTranspose(1, 1, activation='sigmoid', strides=1, padding="same"),
])

model.compile(optimizer='adam',
		loss=norm_l2,
		metrics=[psnr_metrics])

model.summary()

model.fit(
	x_train,
	y_train, 
	steps_per_epoch = len(x_train) // batch_size,
	validation_data = (x_test, y_test), 
	validation_steps = len(x_test) // batch_size,
	epochs = epochs)
```

[2020-09-15-minimal.txt](https://github.com/ROCmSoftwarePlatform/MIOpen/files/5222990/2020-09-15-minimal.txt)
[2020-09-15-inception-inspired.txt](https://github.com/ROCmSoftwarePlatform/MIOpen/files/5223001/2020-09-15-inception-inspired.txt)

I'm about to buy a new GPU and I'm currently evaluating if I can do TF experiments with ROCm (and thus get RNDA2 once it's available).  Any pointers would be highly appreciated. I'm happy to do any debugging / try whatever git versions you suggest :)

**Comment by oleid** [comment]
This, by the way, seems not to have anything to do with ArchLinux. I get the same result with the minimal example in the docker-ed version of rocm3.7:

[2020-09-15-minimal-docker.txt](https://github.com/ROCmSoftwarePlatform/MIOpen/files/5223096/2020-09-15-minimal-docker.txt)

**Comment by oleid** [comment]
It would seem using the official ROCm-3.7 kernel module (with Linux-5.4) doesn't change anything:

[2020-09-15-minimal-linux_lts+rocm-37_kernel_mod.txt](https://github.com/ROCmSoftwarePlatform/MIOpen/files/5223202/2020-09-15-minimal-linux_lts%2Brocm-37_kernel_mod.txt)

**Comment by daniellowell** [comment]
Hello, can you run your minimal example with the environment variables set as:
MIOPEN_LOG_LEVEL=6
MIOPEN_ENABLE_LOGGING_CMD=1

and then post the log results?
This will help us narrow down the exact layer that is causing this issue.

**Comment by oleid** [comment]
Uh, I missed  `MIOPEN_ENABLE_LOGGING_CMD`, that explains why this option was of no use when I tried it!

Here you are, hope that helps finding out what is wrong!

[2020-09-23-minimal.txt](https://github.com/ROCmSoftwarePlatform/MIOpen/files/5266281/2020-09-23-minimal.txt)
[2020-09-23-inception-inspired.txt](https://github.com/ROCmSoftwarePlatform/MIOpen/files/5266285/2020-09-23-inception-inspired.txt)

Would running ROCm 3.8 or a git version of MIOpen help? Then I try to compile the docker images myself (it would seem the pre-compiled images are not up-to-date).

**Comment by oleid** [comment]
Ah, I missed stdout -- these logs are better:

[2020-09-23-inception-inspired.txt](https://github.com/ROCmSoftwarePlatform/MIOpen/files/5266322/2020-09-23-inception-inspired.txt)
[2020-09-23-minimal.txt](https://github.com/ROCmSoftwarePlatform/MIOpen/files/5266324/2020-09-23-minimal.txt)

**Comment by daniellowell** [comment]
Looks like this is the issue:
```MIOpen(HIP): Info [FindConvBwdDataAlgorithm] miopenConvolutionBwdDataAlgoImplicitGEMM	0.432802	0
MIOpen(HIP): Info [FindConvBwdDataAlgorithm] BWD Chosen Algorithm: ConvHipImplicitGemmBwdDataV1R1 , 0, 0.432802
MIOpen(HIP): Command [LogCmdConvolution] ./bin/MIOpenDriver conv -n 128 -c 64 -H 1 -W 17 -k 32 -y 1 -x 7 -p 0 -q 2 -u 1 -v 2 -l 1 -j 1 -m conv -g 1 -F 2 -t 1
MIOpen(HIP): Info [ConvolutionBackwardData] algo = 5, workspace = 0
MIOpen(HIP): Info2 [GetKernels] 1 kernels for key: SubTensorOpWithScalar1d "set 1 139264"
Memory exception on virtual address 0x9f241b000, node id 1 : Page not present
Address does not belong to a known buffer
Memory access fault by GPU node-1 (Agent handle: 0x55e0321dd320) on address 0x9f241b000. Reason: Page not present or supervisor privilege.
```

@asroy @zjing14 I believe #457 will resolve this issue. Can you guys comment?

**Comment by atamazov** [comment]
The problem happens with gfx803 with 32 CUs. Do we fully support this HW?

**Comment by oleid** [comment]
> Looks like this is the issue:
> @asroy @zjing14 I believe #457 will resolve this issue. Can you guys comment?

Just tried that one here (built && installed MIOpen from that branch, the rest is at ROCM-3.7 lvl -- hope that is okay).
The issue is the same:

[2020-09-24-minimal+457.txt](https://github.com/ROCmSoftwarePlatform/MIOpen/files/5273777/2020-09-24-minimal%2B457.txt)

**Comment by daniellowell** [comment]
>The problem happens with gfx803 with 32 CUs. Do we fully support this HW?

Not fully. Our support is really for 64CU count SKUs with gfx803. 
@oleid you can try filtering out that algorithm to make sure it does not get picked.
Try setting the environment variable: `MIOPEN_DEBUG_CONV_IMPLICIT_GEMM=0`
Details on this process are here:
https://rocmsoftwareplatform.github.io/MIOpen/doc/html/DebugAndLogging.html#filtering-by-algorithm

You can disable the algorithms until your platform is stable. Convolutions have a fallback underpinned by our GEMM library MIOpenGEMM, which should work for most cases, so there shouldn't be gaps.

**Comment by oleid** [comment]
> > The problem happens with gfx803 with 32 CUs. Do we fully support this HW?
> 
> Not fully. Our support is really for 64CU count SKUs with gfx803.
> @oleid you can try filtering out that algorithm to make sure it does not get picked.
> Try setting the environment variable: `MIOPEN_DEBUG_CONV_IMPLICIT_GEMM=0`

That actually makes it run for both networks, great!

> You can disable the algorithms until your platform is stable. Convolutions have a fallback underpinned by our GEMM library MIOpenGEMM, which should work for most cases, so there shouldn't be gaps.

If I've seen correctly, MIOpenGEMM isn't currently used by MIOpen as distributed in the docker images (and probably in ubuntu). Would you suggest to build MIOpen with MIOpenGEMM support?

If I read the debug output of MIOpen correctly, instead of  `ConvHipImplicitGemmBwdDataV1R1` now `ConvOclDirectFwd1x1` is used. Are the Ocl ones which are "okay"-ish to use?

**Comment by daniellowell** [comment]
If you're using the OpenCL backend use MIOpenGEMM. If you're using the HIP backend, use rocBLAS as the GEMM library.
I might have made the assumption that you're using the OpenCL backend in my previous comment.

**Comment by daniellowell** [comment]
@asroy @zjing14 can you please put on your task list to disable iGEMM for gfx803 with 32CUs.

**Comment by oleid** [comment]
I'm using hip, I presume, since I'm using tensorflow.

**Comment by daniellowell** [comment]
>If I read the debug output of MIOpen correctly, instead of ConvHipImplicitGemmBwdDataV1R1 now ConvOclDirectFwd1x1 is used. Are the Ocl ones which are "okay"-ish to use?

OpenCL kernels are fine, it isn't an issue between HIP kernels versus OpenCL kernels, it is more that there is a bug in one of our HIP kernel algorithms. 

Let us know if you  need additional support.

**Comment by atamazov** [comment]
@daniellowell I thought it is a compiler bug.

**Comment by oleid** [comment]
@daniellowell  I tested today with latest miopen git version (2.7.0-14-g807c08e63) as well as the aforementioned branch. There is a change in behavior, probably due to upgrading my system with ROCm 3.8. Training now starts and does things. In the branch, however, training stops at some point with the same error.
