### ISSUE TITLE
Unnecessary a.out file created

### ISSUE THREAD

**Issue by sclarkson** [ROCmSoftwarePlatform/MIOpen#44]
When running MIOpen code, an `a.out` file confusingly appears in your current directory. This function appears to be the culprit.

https://github.com/ROCmSoftwarePlatform/MIOpen/blob/08114baa029a519ea12b52c5274c0bd8f4ad0d26/src/ocl/gcn_asm_utils.cpp#L251-L268

Since it looks like it is just testing for a compiler bug and the compiled output isn't necessary, adding `-o /dev/null` to the arguments should prevent this.

**Comment by pfultz2** [comment]
Thats a good point. Lets try to add that to the arguments.
