### ISSUE TITLE
Is it possible to install miopen on CUDA machines? (opencl is included in CUDA)

### ISSUE THREAD

**Issue by ghostplant** [ROCmSoftwarePlatform/MIOpen#45]
Is it possible to install miopen on CUDA machines? (opencl is included in CUDA)

Since I don't have ATI card at the moment, I just want to test whether MIOpen can work well using Nvidia OpenCL.

**Comment by dagamayank** [comment]
NO, MIOpen is not supported and designed to run on CUDA platforms.

**Comment by dagamayank** [comment]
> Since I don't have ATI card at the moment

I can try to fix that, please contact me directly.
