### ISSUE TITLE
Support for 3D convolutions

### ISSUE THREAD

**Issue by odellus** [ROCmSoftwarePlatform/MIOpen#46]
LIDAR is cheap. We need support for 3D convolutions.

**Comment by dagamayank** [comment]
@odellus Thanks for feature request. We will add it to list of desirable features for the next release.

**Comment by maxzoech** [comment]
Have you got any news on this?

**Comment by dagamayank** [comment]
I apologize we had to put this on the back burner due to other higher priority issues. Right now this is looking like a 2019 first half feature.

**Comment by daniellowell** [comment]
Implemented.

**Comment by odellus** [comment]
N I C E ! ! !
