### ISSUE TITLE
Disable iGEMM for some gfx803 architectures.

### ISSUE THREAD

**Issue by daniellowell** [ROCmSoftwarePlatform/MIOpen#464]
Regarding issue #436 
iGEMM should be disabled for gfx803 with compute unit count != 64.

**Comment by atamazov** [comment]
Do you mean kernels written in HIP? IIRC there are some iGemm Solvers that produce assembly kernels.

**Comment by atamazov** [comment]
@daniellowell Ping

**Comment by oleid** [comment]
Was that already disabled in master? `2.7.0-14-g807c08e63` + rocm3.8 doesn't have those problems, anymore.

**Comment by daniellowell** [comment]
@asroy Status?

**Comment by asroy** [comment]
#553 should fix it
