### ISSUE TITLE
Build from source meet a c++ error

### ISSUE THREAD

**Issue by wormwang** [ROCmSoftwarePlatform/MIOpen#48]
~/ROCm/MIOpen/build# make
[  0%] Building CXX object addkernels/CMakeFiles/addkernels.dir/include_inliner.cpp.o
[  3%] Building CXX object addkernels/CMakeFiles/addkernels.dir/addkernels.cpp.o
[  3%] Linking CXX executable ../bin/addkernels
c++: error: unrecognized command line option ‘-amdgpu-target=gfx803’
c++: error: unrecognized command line option ‘-amdgpu-target=gfx900’
addkernels/CMakeFiles/addkernels.dir/build.make:120: recipe for target 'bin/addkernels' failed
make[2]: *** [bin/addkernels] Error 1
CMakeFiles/Makefile2:382: recipe for target 'addkernels/CMakeFiles/addkernels.dir/all' failed
make[1]: *** [addkernels/CMakeFiles/addkernels.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

cmake parameters:
CXX=/opt/rocm/hcc/bin/hcc cmake -DMIOPEN_BACKEND=HIP -DCMAKE_PREFIX_PATH="/opt/rocm/hcc;/opt/rocm/hip" -DCMAKE_CXX_FLAGS="-isystem /usr/include/aarch64-linux-gnu/"  -DHSA_LIBRARY=/opt/hsa-rocr-dev/lib/libhsa-runtime64.so -DHSA_HEADER=/opt/hsa-rocr-dev/include -DCMAKE_CXX_FLAGS=-Wall  ..

**Comment by wormwang** [comment]
Are there another people try building MIOpen from source?

**Comment by dagamayank** [comment]
Can you please mention your hardware and software environments?

**Comment by wormwang** [comment]
Ubuntu 16.04 ARM64, AMD Vega GPU

**Comment by dagamayank** [comment]
@wormwang Unfortunately, ARM64 is not one of the supported platforms for ROCm. MIOpen depends on ROCm. You can find more info about supported hardware [here](https://rocm.github.io/hardware.html).

**Comment by wormwang** [comment]
I have build ROCm on ARM64 , so I am try building MIOpen at now
I have build all ROCm part successful beside the MIOpen

**Comment by dagamayank** [comment]
Can you please elaborate what are all the parts that you have successfully build?

**Comment by wormwang** [comment]
The  list:
ROCK-Kernel-Driver
ROCR-Runtime
ROCT-Thunk-Interface
ROCm-Device-Libs
rocminfo
HCC compiler
HIP
rocFFT
rocBLAS
hipBLAS
MIOpenGEMM

I apply many patch & some guide from AMD's other team, such as HCC team.

**Comment by dagamayank** [comment]
You will need OpenCL runtime/compiler as well. MIOpen depends on OpenCL for both HIP and OpenCL backends.

**Comment by wormwang** [comment]
sorry. I lost list the OpenCL. I installed OpenCL from Ubuntu.
And I built clang-ocl

**Comment by wormwang** [comment]
After I study the CMakeLists.txt , I can build the source now, by such cmake parameter
CXX=/opt/rocm/hcc/bin/hcc cmake -DCMAKE_CXX_COMPILER=hcc -DMIOPEN_BACKEND=HIP -DCMAKE_PREFIX_PATH="/opt/rocm/hcc;/opt/rocm/hip"  ..

But, new error is linker

[ 96%] Building CXX object src/CMakeFiles/MIOpen.dir/hipoc/hipoc_program.cpp.o
[100%] Linking CXX shared library ../lib/libMIOpen.so
ld: error: wildcard match appears as both global and local in version 'MIOPEN_HIP_1' in script
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)
src/CMakeFiles/MIOpen.dir/build.make:2047: recipe for target 'lib/libMIOpen.so.1' failed
make[2]: *** [lib/libMIOpen.so.1] Error 1
CMakeFiles/Makefile2:1788: recipe for target 'src/CMakeFiles/MIOpen.dir/all' failed
make[1]: *** [src/CMakeFiles/MIOpen.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by wormwang** [comment]
after modify 
~/src/CMakeLists.txt

if(NOT WIN32 AND NOT APPLE)
    file(WRITE ${CMAKE_CURRENT_BINARY_DIR}/lib.def "
MIOPEN_${MIOPEN_BACKEND}_1
{
global:
    *;
#local:
#    *;
};
")

Then , build & link both are successful

**Comment by dagamayank** [comment]
Thanks @wormwang. I would like @pfultz2 to be aware of this.

**Comment by YJessicaGao** [comment]
@wormwang Hi, there. I am trying to build MIOPEN on ARM64. But when I cmake clang-ocl, it says "Can't find opencl". I wonder could you please show me the steps of compiling clang-ocl? Thanks a lot.

**Comment by pfultz2** [comment]
The clang-ocl is a bash script that invokes the clang compiler in our opencl runtime. It looks for the `lib/x86_64/bitcode/opencl.amdgcn.bc` file in /opt/rocm/opencl(or somewhere in the `CMAKE_PREFIX_PATH`).

Did you build rocm opencl? A non-rocm opencl wont provide the compiler and device code needed by MIOpen. From the bash script variables at the top of the file [here](https://github.com/RadeonOpenCompute/clang-ocl/blob/master/clang-ocl.in#L6), you can see it needs clang and llvm-link that supports our GPU and the directory of bitcode files for our GPU device code.

You really only need the compiler built by opencl and not the complete runtime, actually. Then just update the clang-ocl script to point to clang, llvm-link, and the bitcode directory.

**Comment by YJessicaGao** [comment]
I've built ROCm-Device-Libs from the source code (as my server is aarch64, Centos). Is that the rocm opencl I need to build?

**Comment by pfultz2** [comment]
> I've built ROCm-Device-Libs from the source code (as my server is aarch64, Centos). Is that the rocm opencl I need to build?

The compiler you used to build rocm device libs should be capable enough for clang-ocl. You just need to update the bash variables(from [here](https://github.com/RadeonOpenCompute/clang-ocl/blob/master/clang-ocl.in#L6)) to point to where clang, llvm-link, and bitcode directories are. You will need to do that manually as the cmake script is looking for where these file are in a opencl installation. 

Or you could build the entire rocm opencl runtime including the compiler, which is [here](https://github.com/RadeonOpenCompute/ROCm-OpenCL-Runtime).

**Comment by YJessicaGao** [comment]
@pfultz2  Thanks for your help. I successfully built clang-ocl.
However, an error occurs when I build MIOPEN.
After 
`CXX=/opt/rocm/hcc/bin/hcc cmake3 -DCMAKE_CXX_COMPILER=hcc -DMIOPEN_BACKEND=HIP -DCMAKE_PREFIX_PATH="/opt/rocm/hcc;/opt/rocm/hip" -D ..`
and then
`make`
..........
```
[100%] Linking CXX shared library ../lib/libMIOpen.so
ld: cannot find -lhip::device
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libMIOpen.so.1] Error 1
make[1]: *** [src/CMakeFiles/MIOpen.dir/all] Error 2
make: *** [all] Error 2
```

I am not sure whether I don't have a GPU on my server is the reason. Also there are many warnings when cmake.

```
-- hip compiler: /opt/rocm/bin/clang-ocl
-- Build with rocblas
-- HIP backend selected.
-- AMDGCN assembler: MIOPEN_AMDGCN_ASSEMBLER-NOTFOUND
-- Build with miopengemm
-- Boost version: 1.59.0
-- Found the following Boost libraries:
--   filesystem
--   system
-- Clang tidy found: 8.0.0svn
-- Clang tidy checks: *,-cert-env33-c,-android-cloexec-fopen,-cert-msc30-c,-cert-msc50-cpp,-clang-analyzer-alpha.core.CastToStruct,-clang-analyzer-optin.performance.Padding,-clang-diagnostic-deprecated-declarations,-clang-diagnostic-extern-c-compat,-clang-diagnostic-unused-command-line-argument,-cppcoreguidelines-pro-bounds-array-to-pointer-decay,-cppcoreguidelines-pro-bounds-constant-array-index,-cppcoreguidelines-pro-bounds-pointer-arithmetic,-cppcoreguidelines-pro-type-member-init,-cppcoreguidelines-pro-type-reinterpret-cast,-cppcoreguidelines-pro-type-union-access,-cppcoreguidelines-pro-type-vararg,-cppcoreguidelines-special-member-functions,-fuchsia-*,-google-explicit-constructor,-google-readability-braces-around-statements,-google-readability-todo,-google-runtime-int,-google-runtime-references,-hicpp-braces-around-statements,-hicpp-explicit-conversions,-hicpp-no-array-decay,-hicpp-signed-bitwise,-hicpp-special-member-functions,-hicpp-use-equals-default,-hicpp-use-override,-llvm-header-guard,-llvm-include-order,-misc-misplaced-const,-modernize-pass-by-value,-modernize-use-default-member-init,-modernize-use-equals-default,-modernize-use-transparent-functors,-performance-unnecessary-value-param,-readability-braces-around-statements,-readability-else-after-return,-readability-named-parameter,-hicpp-use-auto,-modernize-use-auto,-modernize-use-override,-readability-non-const-parameter
-- Could NOT find LATEX (missing: LATEX_COMPILER)
Latex builder not found. Latex builder is required only for building the PDF documentation for MIOpen and is not necessary for building the library, or any other components. To build PDF documentation run make in /home/jess/rocm_sources/MIOpen/doc/pdf, once a latex builder is installed.
-- MIOpen_VERSION= 1.7.0-8784e34-dirty
-- CMAKE_BUILD_TYPE= Release
-- Librt: /usr/lib64/librt.so
-- Configuring done
CMake Warning (dev) at src/CMakeLists.txt:325 (add_library):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "MIOpen" links to target "hip::device" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?
This warning is for project developers.  Use -Wno-dev to suppress it.

WARNING: Target "MIOpen" requests linking to directory "/opt/rocm/hcc/lib".  Targets may link only to libraries.  CMake is dropping the item.
CMake Warning (dev) at src/CMakeLists.txt:325 (add_library):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "MIOpen" links to target "hip::device" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?
This warning is for project developers.  Use -Wno-dev to suppress it.

WARNING: Target "MIOpen" requests linking to directory "/opt/rocm/hcc/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "MIOpenDriver" requests linking to directory "/opt/rocm/hcc/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "MIOpenDriver" has EXCLUDE_FROM_ALL set and will not be built by default but an install rule has been provided for it.  CMake does not define behavior for this case.
WARNING: Target "test_w_supertensor" requests linking to directory "/opt/rocm/hcc/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test_type_name" requests linking to directory "/opt/rocm/hcc/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test_tensor_transform" requests linking to directory "/opt/rocm/hcc/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test_tensor_test" requests linking to directory "/opt/rocm/hcc/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test_tensor_trans" requests linking to directory "/opt/rocm/hcc/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test_bn_3d_spatial_test" requests linking to directory "/opt/rocm/hcc/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test_activation" requests linking to directory "/opt/rocm/hcc/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test_test_errors" requests linking to directory "/opt/rocm/hcc/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test_bn_spatial_test" requests linking to directory "/opt/rocm/hcc/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test_bn_3d_peract_test" requests linking to directory "/opt/rocm/hcc/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test_soft_max" requests linking to directory "/opt/rocm/hcc/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test_conv_bias" requests linking to directory "/opt/rocm/hcc/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test_cache" requests linking to directory "/opt/rocm/hcc/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test_bn_aux" requests linking to directory "/opt/rocm/hcc/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test_handle_test" requests linking to directory "/opt/rocm/hcc/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test_lrn_test" requests linking to directory "/opt/rocm/hcc/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test_cba_inference" requests linking to directory "/opt/rocm/hcc/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test_pooling_test" requests linking to directory "/opt/rocm/hcc/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test_cbna_inference" requests linking to directory "/opt/rocm/hcc/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test_check_numerics_test" requests linking to directory "/opt/rocm/hcc/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test_include_inliner" requests linking to directory "/opt/rocm/hcc/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test_conv" requests linking to directory "/opt/rocm/hcc/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test_solver" requests linking to directory "/opt/rocm/hcc/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test_custom_allocator" requests linking to directory "/opt/rocm/hcc/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test_gru" requests linking to directory "/opt/rocm/hcc/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test_bn_peract_test" requests linking to directory "/opt/rocm/hcc/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test_lstm" requests linking to directory "/opt/rocm/hcc/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test_main" requests linking to directory "/opt/rocm/hcc/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test_fusion_aux" requests linking to directory "/opt/rocm/hcc/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test_mdgraph" requests linking to directory "/opt/rocm/hcc/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test_na_inference" requests linking to directory "/opt/rocm/hcc/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test_tensor_scale" requests linking to directory "/opt/rocm/hcc/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test_na_train" requests linking to directory "/opt/rocm/hcc/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test_perfdb" requests linking to directory "/opt/rocm/hcc/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test_rnn_vanilla" requests linking to directory "/opt/rocm/hcc/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test_tensor_cast" requests linking to directory "/opt/rocm/hcc/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test_tensor_copy" requests linking to directory "/opt/rocm/hcc/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test_tensor_ops" requests linking to directory "/opt/rocm/hcc/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test_tensor_set" requests linking to directory "/opt/rocm/hcc/lib".  Targets may link only to libraries.  CMake is dropping the item.
-- Generating done
-- Build files have been written to: /home/jess/rocm_sources/MIOpen/build
```

**Comment by 0hanghang** [comment]
@wormwang  hi I saw you compile rocminfo on arm64 ,then I got the error:
\[ 50%] Building CXX object CMakeFiles/rocminfo.dir/rocminfo.cc.o
/usr/bin/c++  -DDEBUG -DLITTLEENDIAN_CPU=1 -D__linux__ -I/include  -std=c++11  -fexceptions -fno-rtti -fno-math-errno -fno-threadsafe-statics -fmerge-all-constants -fms-extensions -Werror -Wall -m64 -ggdb -O0 -g   -o CMakeFiles/rocminfo.dir/rocminfo.cc.o -c /home/ubuntu/opencl/rocm/rocminfo/rocminfo.cc
c++: error: unrecognized command line option ‘-m64’
CMakeFiles/rocminfo.dir/build.make:65: recipe for target 'CMakeFiles/rocminfo.dir/rocminfo.cc.o' failed
make[2]: *** [CMakeFiles/rocminfo.dir/rocminfo.cc.o] Error 1
make[2]: Leaving directory '/home/ubuntu/opencl/rocm/rocminfo/build'
CMakeFiles/Makefile2:70: recipe for target 'CMakeFiles/rocminfo.dir/all' failed
make[1]: *** [CMakeFiles/rocminfo.dir/all] Error 2
make[1]: Leaving directory '/home/ubuntu/opencl/rocm/rocminfo/build'
Makefile:154: recipe for target 'all' failed
make: *** [all] Error 2

how can I get around this ? thank you

**Comment by wormwang** [comment]
‘-m64’ is option for x86-64, u must change it.

**Comment by 0hanghang** [comment]
@wormwang you mentioned above that you have compile opencl ,is that the rocm opencl runtime?
https://github.com/RadeonOpenCompute/ROCm-OpenCL-Runtime  on what branch?
when I compiled it from source ,I got many errors like this:
/opt/rocm/hcc/lib/clang/11.0.0/include/stddef.h:41:39: error: missing binary operator before token "("
 #if !defined(_SIZE_T) || __has_feature(modules)
                                       ^
/opt/rocm/hcc/lib/clang/11.0.0/include/stddef.h:55:42: error: missing binary operator before token "("
      !defined(_RSIZE_T)) || __has_feature(modules)
                                          ^
In file included from /home/ubuntu/opencl/rocm/opencl/api/opencl/khronos/headers/opencl2.2/CL/opencl.h:47:0,
                 from /home/ubuntu/opencl/rocm/opencl/runtime/top.hpp:22,
                 from /home/ubuntu/opencl/rocm/opencl/runtime/device/rocm/roccounters.hpp:7,
                 from /home/ubuntu/opencl/rocm/opencl/runtime/device/rocm/roccounters.cpp:5:
/home/ubuntu/opencl/rocm/opencl/api/opencl/khronos/headers/opencl2.2/CL/cl.h:111:5: error: ‘size_t’ does not name a type; did you mean ‘__ssize_ ’?
     size_t                  image_width;
     ^~~~~~
     __ssize_t
/home/ubuntu/opencl/rocm/opencl/api/opencl/khronos/headers/opencl2.2/CL/cl.h:112:5: error: ‘size_t’ does not name a type; did you mean ‘__ssize_ ’?
     size_t                  image_height;
     ^~~~~~
     __ssize_t
/home/ubuntu/opencl/rocm/opencl/api/opencl/khronos/headers/opencl2.2/CL/cl.h:113:5: error: ‘size_t’ does not name a type; did you mean ‘__ssize_ ’?
     size_t                  image_depth;
     ^~~~~~
     __ssize_t
/home/ubuntu/opencl/rocm/opencl/api/opencl/khronos/headers/opencl2.2/CL/cl.h:114:5: error: ‘size_t’ does not name a type; did you mean ‘__ssize_ ’?
     size_t                  image_array_size;
     ^~~~~~

cmake parameter:
    cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DLLVM_INCLUDES=/opt/rocm/hcc/lib/clang/11.0.0/include/ -DCMAKE_PREFIX_PATH=/home/ubuntu/opencl/rocm/ROCm-CompilerSupport/lib/comgr/build/lib/cmake/amd_comgr/ -DUSE_COMGR_LIBRARY=yes ..

any help ? thank you !

**Comment by tonysy** [comment]
Hi, I found though the build process of MIOpen 2.4.0 is successful. There have some issues for the test process.

When I conduct `./MIOpenDriver --version` to check the MIOpenDriver, I get the following erros:

```
>MIOpen-2.4.0/build/bin 21:42:26]$./MIOpenDriver --version
./MIOpenDriver: relocation error: ./MIOpenDriver: symbol _ZN6miopen5debug15FindModeDisableE, version MIOPEN_HIP_1 not defined in file libMIOpen.so.1 with link time reference
```

I have searched the MIOpen repo but don't find solutions. Could you give some hints or ideas? Thanks

I use the 2.4.0 release version of MIOpen and the build command is :
```
CXX=/public/software/compiler/rocm/rocm-3.3.0/bin/hcc \
cmake -DMIOPEN_BACKEND=HIP \
-DCMAKE_PREFIX_PATH="/public/software/compiler/rocm/rocm-3.3.0/hcc;/public/software/compiler/rocm/rocm-3.3.0/hip;/public/home/ssct050t/local_envs" \
-DCMAKE_INSTALL_PREFIX=/public/home/ssct050t/softwares/rocm3.3.0_miopen2.4.0 \
-DBOOST_ROOT=/public/home/ssct050t/local_envs/include/ \
-DBoost_NO_BOOST_CMAKE=ON ..
```
