### ISSUE TITLE
Winograd Kernels Source Code?

### ISSUE THREAD

**Issue by artyom-beilis** [ROCmSoftwarePlatform/MIOpen#480]
I'm trying to understand how MIOpen's Winograd convolution kernels work - to be able to convert the specific code to generic opencl (even with embedded assembly) so it can run on non-ROCm platform or at least understand how kernel's flow works.

I've tried to look into source code, for example

<https://github.com/ROCmSoftwarePlatform/MIOpen/blob/develop/src/kernels/Conv_Winograd_v21_1_0_gfx9_fp32_stride1.inc>

It isn't source - it is binary.

Please provide original source code for kernels or scripts that generate them from source code. Otherwise MIOpen is yet another closed cuDNN...

**Comment by atamazov** [comment]
Due to historical reasons, for development of Winograd kernels, we use not the assembler that is included in ROCm, but another one (sp3). sp3 is incompatible with our AMDGCN assembler (`clang -x assembler`) w.r.t. directives and other stuff, and, therefore, the library can't assemble the original sp3 source. That is why we had to use the preprocessed source that is, in fact, a binary.

@Kirpich30000 Can we provide @artyom-beilis with Winograd sources? Other options:
- Include normally disassembled Winograd source instead of `.long` stuff?
- Migrate from sp3 to ANDGCN asm?

Please let us know what do you think.

**Comment by artyom-beilis** [comment]
Thanks for the quick response, even at starting point original sources with actual comments would be very helpful - that can explain the order of operations, work groups, data sharing etc.

Even if it can't be modified/converted to current inline "binary"

Thanjs

**Comment by artyom-beilis** [comment]
@atamazov Does it mean that no kernels for RDNA were written?

RDNA is quite different  for example all dpp/b/permute work only on wave32 base and I assume the conversion isn't straight forward

**Comment by atamazov** [comment]
AMDGCN assembler supports RDNA. However IIRC MIOpen does not officially support  it yet, so no asm kernels for RDNA were written. And yes, conversion is not straightforward at all.

**Comment by artyom-beilis** [comment]
Any updates on that issue? I'm trying to implement my own Winograd kernel and somewhat struggle to get decent performance.

 I would at least like to understand general data flow etc. i.e. how to optimally separate the load between different threads/work items. Layout of local memory for intermediate results. etc.

**Comment by artyom-beilis** [comment]
I'd rather meant the code that was converted to this assembly. Because without labels and single line of comment it is useless. 

I'm not looking into development of winograd kernels For MIOpen but rather use them on non rocm platforms like standard amd drives on Linux or windows

**Comment by atamazov** [comment]
@artyom-beilis 

> to be able to convert the specific code to generic opencl (even with embedded assembly)

None of existing high-level languages support the execution model that our Winograd kernel implements.

> so it can run on non-ROCm platform or at least understand how kernel's flow works.

IIRC, the kernels do not contain anything ROCM-specific, and therefore do not require modifications to run on a different platform. 

Please contact me by mail, if you need more assistance.

**Comment by atamazov** [comment]
@artyom-beilis Notice that some Winograd kernels are coming with the original source code. See these Solvers:
- ConvMPBidirectWinograd
- ConvMPBidirectWinograd_xdlops
- ConvWinograd3x3MultipassWrW
