### ISSUE TITLE
RCP tool fails to generate output for ROCm DeepBench 

### ISSUE THREAD

**Issue by srikantAmd** [ROCmSoftwarePlatform/MIOpen#50]
Trying to collect performance counters for DeepBench apps of the ROCm repo here:
https://github.com/ROCmSoftwarePlatform/DeepBench

The applications run correctly with the following command line. Example:
`rcprof -t ./conv_bench`
But fail to generate any output:
`Failed to generate profile result path/to/out.atp`

Further, if we try to run it with the HSA mode of RCP, the application totally fails to run. Example:
```
$ rcprof -A ./conv_bench
Radeon Compute Profiler V5.3.0 is enabled
Failed to generate profile result path/to/out.atp
```

**Comment by dagamayank** [comment]
Closing this issue as it is not related to MIOpen.
