### ISSUE TITLE
Port-merge review of PR 441

### ISSUE THREAD

**Issue by atamazov** [ROCmSoftwarePlatform/MIOpen#503]
The most of review comments are code clarity/quality related, but there are some more important performance-related comments.
- [x] https://github.com/ROCmSoftwarePlatform/MIOpen/pull/441#pullrequestreview-504338519
- [x] https://github.com/ROCmSoftwarePlatform/MIOpen/pull/441#pullrequestreview-506013678

These reviews should have been resolved prior to merging #441 so `high_priority`. I am sorry for delaying the review.

Most likely, similar review comments also apply to PR #442.

**Comment by carlushuang** [comment]
@shaojiewang @fronteer @jane-zxy we need some modification accoriding to @atamazov 's review. let's discuss offline

cc: @sabreshao

**Comment by jane-zxy** [comment]
create a pr to resolve this: [pr508](https://github.com/ROCmSoftwarePlatform/MIOpen/pull/508)

**Comment by atamazov** [comment]
#508 merged in
