### ISSUE TITLE
Is xnack enabled on GPU

### ISSUE THREAD

**Issue by shurale-nkn** [ROCmSoftwarePlatform/MIOpen#506]
- To create correct asm kernels with xnack support, required a function that determines whether xnack is enabled or disabled on the GPU.
- Also require access to this information from the IsApplicable() functions to disable unsupported kernels.

related to #505

**Comment by atamazov** [comment]
Right now we support only GPUs that have XNACK = OFF.

**Comment by atamazov** [comment]
XNACK is available as `target.Xnack()` in
```C++
std::string AmdgcnAssemble(const std::string& source,
                           const std::string& params,
                           const miopen::TargetProperties& target)
```
and in all other necessary places.
