### ISSUE TITLE
Fwd gemm is crashing with int8 and group_count > 1

### ISSUE THREAD

**Issue by DrizztDoUrden** [ROCmSoftwarePlatform/MIOpen#519]
Here are 3 driver commands:
```Powershell
> bin/MIOpenDriver convint8 -F 1 -x 1 -y 1 -c 8 -g 1 #int8, group_count == 1
> bin/MIOpenDriver conv -F 1 -x 1 -y 1 -c 8 -g 4 #float, group_count > 1
> bin/MIOpenDriver convint8 -F 1 -x 1 -y 1 -c 8 -g 4 #int8, group_count > 1
```

The first and second run just fine. The third one crashes on the run stage. I have found this behavior because I have actually found the code responsible for that.

On the find stage, we have an `int8` check on the outside with no `group_count` check in the `int8` case.
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/5edf26d95e3840b21e9137e08d5e0661f91ad851/src/ocl/convolutionocl.cpp#L499

On the run stage, we have a `group_count` check on the outside with no `int8` check in the `group_count > 1` case.
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/5edf26d95e3840b21e9137e08d5e0661f91ad851/src/ocl/convolutionocl.cpp#L1129

So for `int8 && group_count > 1` case we have an evaluation inconsistent with run. Moreover, run treats it as a `float` case, I think.

It is fixed in #473.

Here are the logs for the commands:
[g1log.txt](https://github.com/ROCmSoftwarePlatform/MIOpen/files/5392249/g1log.txt) - int8, group_count == 1, works fine
[fp_g4log.txt](https://github.com/ROCmSoftwarePlatform/MIOpen/files/5392245/fp_g4log.txt) - float, group_count > 1, works fine
[g4log.txt](https://github.com/ROCmSoftwarePlatform/MIOpen/files/5392250/g4log.txt) - int8, group_count > 1, crashes

**Comment by atamazov** [comment]
@ce1adon Please have a look. This holds GEMM solvers/invokers work, which is important. Thanks.

**Comment by ce1adon** [comment]
@atamazov Did you enable or disable cache?

**Comment by atamazov** [comment]
BUILD_DEV=On, so binary cache is disabled. @DrizztDoUrden to confirm.

**Comment by DrizztDoUrden** [comment]
I didn't enable cache manually, but I have DUILD_DEV=On, so it should be disabled.

**Comment by ce1adon** [comment]
@atamazov  int8 && group>1 is a new feature to us. You can disable it at this point and request in issues.

**Comment by DrizztDoUrden** [comment]
So it's not allowed for now?

**Comment by ce1adon** [comment]
> So it's not allowed for now?

Yes, please disable it and then request this feature.

**Comment by atamazov** [comment]
@ce1adon Please confirm that the following issue is fixed in develop:
```
$ ./bin/MIOpenDriver convint8 -F 1 -x 1 -y 1 -c 8 -g 4
```
then remove the `bug` label. Right now the issue still persists:
```
MIOpenDriver convint8 -F 1 -x 1 -y 1 -c 8 -g 4 -V 0
MIOpen(HIP): Warning [SetupFloats] Unsupported data types configuration: INT8xINT8xFP32
MIOpen(HIP): Warning [SetupFloats] Unsupported data types configuration: INT8xINT8xFP32
MIOpen(HIP): Warning [SetupFloats] Unsupported data types configuration: INT8xINT8xFP32
MIOpen Error: /home/atamazov/github/MLOpen1/src/gemm_v2.cpp:990: rocBlas error encountered
RunForwardGPU() failed, rc = 0x5
```

**Comment by atamazov** [comment]
@ce1adon @DrizztDoUrden 
AFAICS this holds GEMM solvers/invokers work, which is important.

**Comment by ce1adon** [comment]
@atamazov int8 with group convolution is not implemented yet. Please request this new feature with issue or ticket.

**Comment by atamazov** [comment]
Yes, but then the library should fail in controllable way, before rocblas. @DrizztDoUrden Could you please make appropriate fix in the library?

**Comment by DrizztDoUrden** [comment]
Do you mean to fix it outside of the gemm solver PR?

**Comment by atamazov** [comment]
I do not care. What is important is to open path for your gemm solver work.
