### ISSUE TITLE
Unable to build MIOpen on nvidia

### ISSUE THREAD

**Issue by pradeepisro** [ROCmSoftwarePlatform/MIOpen#52]
The following is the error I am getting while building MIOpen in Nvidia

    CMake Error at CMakeLists.txt:45 (find_package):
     Could not find a package configuration file provided by "ROCM" with any of
     the following names:

       ROCMConfig.cmake
       rocm-config.cmake

     Add the installation prefix of "ROCM" to CMAKE_PREFIX_PATH or set
     "ROCM_DIR" to a directory containing one of the above files.  If "ROCM"
     provides a separate development package or SDK, be sure it has been
     installed.

**Comment by daniellowell** [comment]
Please view the README. You need to install rocm-cmake:
ROCm cmake modules can be installed from here:
https://github.com/RadeonOpenCompute/rocm-cmake
