### ISSUE TITLE
Test handle test architecture check failure on gfx10

### ISSUE THREAD

**Issue by muralinr** [ROCmSoftwarePlatform/MIOpen#524]
The architecture check fails on GFX10.  We need to fix this issue.  Here are details..

root@rocm-framework-nv21-4:/testx/MIOpen/build# ./bin/test_handle_test --all -v
error_hip.cpp:2:56: error: use of undeclared identifier 'num'
extern "C" { __global__ void write(int* data) { data[num] *= 2;}}
^
1 error generated when compiling for gfx1030.
error_hip.cpp:2:56: error: use of undeclared identifier 'num'
extern "C" { __global__ void write(int* data) { data[num] *= 2;}}
^
1 error generated when compiling for gfx1030.
tinygemm.cl:1:48: error: use of undeclared identifier 'i'
__kernel void write(__global int* data) { data[i] = 0; }
^
1 error generated.
tinygemm.cl:1:48: error: use of undeclared identifier 'i'
__kernel void write(__global int* data) { data[i] = 0; }
^
1 error generated.
FAILED: std::any_of( known_arch.begin(), known_arch.end(), [&](std::string arch) { return arch == this_arch; }): /testx/MIOpen/test/handle_test.cpp: 198
Aborted (core dumped)

**Comment by daniellowell** [comment]
This test is meant to fail intentionally.
