### ISSUE TITLE
Unguarded array access using subscript operator can lead to segfault

### ISSUE THREAD

**Issue by jithunnair-amd** [ROCmSoftwarePlatform/MIOpen#54]
In `src/ocl/convolutionocl.cpp:1389` (and similarly line 1000):
```
            auto&& kernels = handle.GetKernels("miopenConvolutionFwdAlgoDirect", network_config);
#if(!defined(__GNUC__) || defined(__clang__)) // w/a for segfault in gcc 5.4.0
            const
#endif
                auto num_kernels = kernels.size();
            auto kernel          = kernels[0];
```
There needs to be a check that the num_kernels is not 0, otherwise accessing `kernel[0]` leads to a segfault. This check is present in a similar situation in line 3362 in the same file.

The reason why there was no kernel found in my case was probably because the `handle` had an improper value:
```(gdb) p handle
$21 = (miopen::Handle &) @0x7ffefdfe9c00: {<miopenHandle> = {<No data fields>}, impl = std::unique_ptr<miopen::HandleImpl> containing 0x7ffefdff43e0, geo_map = std::unordered_map with 0 elements}
```

However, there still needs to be a check to prevent the segfault and have a more graceful exit.

**Comment by atamazov** [comment]
This problem will never occur if MIOpen is used in documented way - FindConvolution() and then Convolution(). We'll fix that, however when time permits.

**Comment by dagamayank** [comment]
@jithunnair-amd please try again with the latest MIOpen and report back.
