### ISSUE TITLE
results errors

### ISSUE THREAD

**Issue by xqch1983** [ROCmSoftwarePlatform/MIOpen#55]
Hi,
 there is one  error when i run test case by MIOpenDriver as following command and parameters.
  ./bin/MIOpenDriver conv  -m trans  -W 4 -H 4 -c 6 -k 4 -x 1 -y 1 -p 2 -q 2 -u 1 -v 1 -s 0 -F 0

error:0.625378
Forward Convolution Failed: 0.625378
Backward Convolution Data Failed: 0.304246
Backward Convolution Weights Failed: 0.860219

**Comment by ce1adon** [comment]
Fix in MIOpen PR #1278 @daniellowell 
https://github.com/AMDComputeLibraries/MLOpen/pull/1278
