### ISSUE TITLE
build issue with requiring sqlite3 even though it is installed

### ISSUE THREAD

**Issue by ggghamd** [ROCmSoftwarePlatform/MIOpen#551]
Seeing following error when cmake is issued. I can see sqlite3 is installed, wondering anything else needs to be done? 

root@sriov-guest:~/ROCm/MIOpen# cmake -DMIOPEN_BACKEND=OpenCL -DMIOPEN_HIP_COMPILER=/opt/rocm/llvm/bin/clang++
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
-- Checking for module 'sqlite3'
--   No package 'sqlite3' found
CMake Error at /usr/share/cmake-3.10/Modules/FindPkgConfig.cmake:415 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPkgConfig.cmake:593 (_pkg_check_modules_internal)
  CMakeLists.txt:60 (pkg_check_modules)

-- Configuring incomplete, errors occurred!
See also "/root/ROCm/MIOpen/CMakeFiles/CMakeOutput.log".
root@sriov-guest:~/ROCm/MIOpen# dpkg -l  | grep sqlite3
ii  libsqlite3-0:amd64                         3.22.0-1ubuntu0.4                            amd64        SQLite 3 shared library
ii  sqlite3                                    3.22.0-1ubuntu0.4                            amd64        Command line interface for SQLite 3
root@sriov-guest:~/ROCm/MIOpen#

**Comment by carlushuang** [comment]
@ggghamd here is a quick one-line command-line to fix the sqlite:
```
# in some temp directory
wget https://sqlite.org/2017/sqlite-autoconf-3170000.tar.gz && tar -xf sqlite-autoconf-3170000.tar.gz && cd sqlite-autoconf-3170000 && ./configure && make -j`nproc` && make install
```

**Comment by ggghamd** [comment]
no it is already installed, you shoudl try on your end before making statement here.

**Comment by carlushuang** [comment]
Yes I compared my printout with yours then found out the missing packages, here is the printout of my machine:
```
# dpkg -l | grep sqlite3
ii  libsqlite3-0:amd64                     3.11.0-1ubuntu1.5                       amd64        SQLite 3 shared library
ii  libsqlite3-dev:amd64                   3.11.0-1ubuntu1.5                       amd64        SQLite 3 development files
ii  sqlite3                                3.11.0-1ubuntu1.5                       amd64        Command line interface for SQLite 3
```
From your print out log `libsqlite3-dev:amd64` is missing
