### ISSUE TITLE
ConvOclBwdWrW53 fails on gfx10

### ISSUE THREAD

**Issue by daniellowell** [ROCmSoftwarePlatform/MIOpen#559]
Large number of numerical validation issues. Likely a compiler issue.

**Comment by atamazov** [comment]
ROCm 3.9, Navi21

**Comment by daniellowell** [comment]
@atamazov redirecting this to @zjing14

**Comment by zjing14** [comment]
@daniellowell Could you point me to the log of failures or show me which configs? Cannot get failures with @atamazov 's cmd (ROCm 4.0 on Navi21).

**Comment by atamazov** [comment]
Perhaps compiler issue is fixed in 4.0

**Comment by daniellowell** [comment]
Works in latest build.

**Comment by atamazov** [comment]
@daniellowell 
> Works in latest build.

Could you please identify the build?
