### ISSUE TITLE
Please allow OpenCL and HIP users to shared  on the same system

### ISSUE THREAD

**Issue by davidcarver** [ROCmSoftwarePlatform/MIOpen#56]
Please allow OpenCL and HIP users to shared  on the same system, and not require separate systems for miopen-OpenCL and miopen-HIP.  Also, currently each dedicated miopen-opencl and miopen-hip  system requires a GPU.

"Installing MIOpen with pre-built packages
MIOpen can be installed on Ubuntu using apt-get.

For OpenCL backend: apt-get install miopen-opencl

For HIP backend: apt-get install miopen-hip
Currently both the backends cannot be installed on the same system simultaneously. If a different backend other than what currently exists on the system is desired, please remove the existing backend completely and then install the new backend."

**Comment by dagamayank** [comment]
Thanks for this feature request. Can you please explain why and when would you want both the backends to co-exist at the same time?

**Comment by junliume** [comment]
Reference: #1664
