### ISSUE TITLE
Environment variables should not be read multiple times in the program

### ISSUE THREAD

**Issue by ZPEthanWen** [ROCmSoftwarePlatform/MIOpen#570]
Environment variables should be read only once at startup, otherwise, the risk caused by modifying the value of environment variables during program running cannot be prevented.

**Comment by atamazov** [comment]
This is already so.

**Comment by atamazov** [comment]
But the reason is performance

**Comment by ZPEthanWen** [comment]
Oh, sorry, I didn't notice the "static const" before the variables in functions.
