### ISSUE TITLE
Fusion layers with BatchNorm

### ISSUE THREAD

**Issue by JosephGeoBenjamin** [ROCmSoftwarePlatform/MIOpen#59]
Hi,
I am working on inference code with Fusion layers, in which combinations **Conv-bias-Activ** and **BatchNorm-Activ** fusing are working fine. 
But when I try inference with **Conv-Bias-BatchNorm-Activ**  I'm getting **Bad param status** at the miopenCompileFusionPlan() call.

Here the parameters are same as the working combinations.

Thanks in Advance!

**Comment by daniellowell** [comment]
What are the configs?

**Comment by JosephGeoBenjamin** [comment]
> What are the configs?

I suppose you are asking for the library and GPU specs;

**OS**: Ubuntu 16.04.5 LTS (GNU/Linux 4.15.0-36-generic x86_64)
**HIP-backend**
Package: hip_hcc
Version: 1.5.18353
Priority: optional
Section: devel
Maintainer: Maneesh Gupta <maneesh.gupta@amd.com>
Installed-Size: 15.3 MB
Depends: hip_base (= 1.5.18353), hcc (= 1.2.18354)
Download-Size: 5,337 kB

**rocm-libs**
Package: rocm-libs
Version: 1.9.211
Priority: optional
Section: devel
Maintainer: Advanced Micro Devices Inc.
Installed-Size: 1,024 B
Depends: rocfft, rocrand, hipblas, rocblas
Homepage: https://github.com/RadeonOpenCompute/ROCm
Download-Size: 772 B

**MIOpen**
Package: miopen-hip
Version: 1.5.0-e1f0433
Priority: optional
Section: devel
Maintainer: Paul Fultz II <paul.fultz@amd.com>
Installed-Size: 48.9 MB
Depends: openssl, rocm-opencl-dev, rocm-utils, hip_hcc, miopengemm
Download-Size: 2,834 kB

**HSA System Attributes**    
Runtime Version:         1.1
System Timestamp Freq.:  1000.000000MHz
Sig. Max Wait Duration:  18446744073709551615 (number of timestamp)
Machine Model:           LARGE                              
System Endianness:       LITTLE                             
             
  Name:                    gfx803                             
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128                                
  Queue Min Size:          4096                               
  Queue Max Size:          131072                             
  Queue Type:              MULTI                              
  Node:                    1                                  
  Device Type:             GPU                                
  Cache Info:              
    L1:                      16KB                               
  Chip ID:                 29440                              
  Cacheline Size:          64                                 
  Max Clock Frequency (MHz):1000                               
  BDFID:                   256                                
  Compute Unit:            64                                 
  Features:                KERNEL_DISPATCH 
  Fast F16 Operation:      FALSE                              
  Wavefront Size:          64                                 
  Workgroup Max Size:      1024                               
  Workgroup Max Size Per Dimension:
    Dim[0]:                  67109888                           
    Dim[1]:                  16778240                           
    Dim[2]:                  3698327552                         
  Grid Max Size:           4294967295                         
  Waves Per CU:            40                                 
  Max Work-item Per CU:    2560                               
  Grid Max Size per Dimension:
    Dim[0]:                  4294967295                         
    Dim[1]:                  4294967295                         
    Dim[2]:                  4294967295                         
  Max number Of fbarriers Per Workgroup:32                                 
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    4194304KB                          
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Acessible by all:        FALSE                              
    Pool 2                   
      Segment:                 GROUP                              
      Size:                    64KB                               
      Allocatable:             FALSE                              
      Alloc Granule:           0KB                                
      Alloc Alignment:         0KB                                
      Acessible by all:        FALSE                              
  ISA Info:                
    ISA 1                    
      Name:                    amdgcn-amd-amdhsa--gfx803          
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE                               
      Workgroup Max Dimension: 
        Dim[0]:                  67109888                           
        Dim[1]:                  1024                               
        Dim[2]:                  16777217                           
      Workgroup Max Size:      1024                               
      Grid Max Dimension:      
        x                        4294967295                         
        y                        4294967295                         
        z                        4294967295                         
      Grid Max Size:           4294967295                         
      FBarrier Max Size:       32                                 
*** Done ***

**Comment by daniellowell** [comment]
Sorry, I was using jargon. What are the fusion configurations you’re attempting, which succeed, but then fail? Input tensors, filter sizes and strides. Also please post an output log of the failure.

**Comment by JosephGeoBenjamin** [comment]
It is failing for CBNA fusion combination, and for CBA and NA it is working
**Error message**
``` 
MIOpen Error: /home/mcw/jgeob/rocm/MIOpen/src/fusion.cpp:433: 
Error on line 234: Status 3
```
with below code error can reproduced. Commenting the  two batchNorm API the code runs flawlessly for CBA combination. (All the config info can be found in the code)

Please do point out any mistake in handling the API params

```
/*
 * The program is created with intention of testing MIOpen-fusion calls in AMD
 */

#include "/opt/rocm/miopen/include/miopen/miopen.h"
#include <iomanip>
#include <iostream>
#include <cstdlib>
#include <vector>
#include "hip/hip_runtime_api.h"
#include "hip/hip_runtime.h"
#include <cassert>
#include <cstdlib>
#include <cstdio>

#define MIO_CHECK(expression)                                                   \
  {                                                                             \
    miopenStatus_t status = (expression);                                       \
    if (status != miopenStatusSuccess) {                                        \
      std::cerr << "Error on line " << __LINE__ << ": "                         \
                << "Status " << status << std::endl;                            \
      std::exit(EXIT_FAILURE);                                                  \
    }                                                                           \
  }

#define HIP_CALL(f) {                                                           \
  hipError_t err = (f);                                                         \
  if (err != hipSuccess) {                                                      \
    std::cout                                                                   \
        << "    Error occurred: " << err << std::endl;                          \
    std::exit(1);                                                               \
  }                                                                             \
}


__global__ void dev_const(hipLaunchParm lp, float *px, float k) {
  int tid = hipThreadIdx_x + hipBlockIdx_x * hipBlockDim_x;
  px[tid] = k;
}

__global__ void dev_iota(hipLaunchParm lp, float *px) {
  int tid = hipThreadIdx_x + hipBlockIdx_x * hipBlockDim_x;
  px[tid] = tid;
}

__global__ void dev_bias(hipLaunchParm lp, float *px, float *k, int t) {
  int tid = hipThreadIdx_x + hipBlockIdx_x * hipBlockDim_x;
  if(tid < 9)
  px[tid] =2;
  else
  px[tid]= 0;
}

void print(const float *data, int n, int c, int h, int w) {
  std::vector<float> buffer ( 1 << 20 );
  HIP_CALL(hipMemcpy( buffer.data(), data,
                      n * c * h * w * sizeof(float),
                      hipMemcpyDeviceToHost));
  int a = 0;
  for (int i = 0; i < n; ++i) {
    for (int j = 0; j < c; ++j) {
      std::cout << "n=" << n << ", c=" << c << ":" << std::endl;
      for (int k = 0; k < h; ++k) {
        for (int l = 0; l < w; ++l) {
          std::cout << "\t"<<  std::setw(4) << std::right << buffer[a];
          ++a;
        }
        std::cout << std::endl;
      }
    }
  }
  std::cout << std::endl;
}

int main() {

    miopenHandle_t miopen_handle;
    MIO_CHECK(miopenCreate(&miopen_handle));
    std::cout << "Handle:" <<miopen_handle<<std::endl;

    //------------------- input
    const int in_n = 1;
    const int in_c = 1;
    const int in_h = 10;
    const int in_w = 10;
    miopenTensorDescriptor_t in_desc;
    MIO_CHECK(miopenCreateTensorDescriptor(&in_desc));
    MIO_CHECK(miopenSet4dTensorDescriptor(
          in_desc, miopenFloat,
          in_n, in_c, in_h, in_w));
    float *in_data;
    HIP_CALL(hipMalloc(&in_data, in_n * in_c * in_h * in_w * sizeof(float)));
    hipLaunchKernel(dev_iota, in_w * in_h, in_n * in_c , 0, 0 ,in_data);

    std::cout << "in_n: " << in_n << std::endl;
    std::cout << "in_c: " << in_c << std::endl;
    std::cout << "in_h: " << in_h << std::endl;
    std::cout << "in_w: " << in_w << std::endl;
    std::cout << "in_data:" << std::endl;
    print(in_data, in_n, in_c, in_h, in_w);
    std::cout << std::endl;

    //----------------------- filter
    const int filt_k = 1;
    const int filt_c = 1;
    const int filt_h = 5;
    const int filt_w = 5;
    miopenTensorDescriptor_t filt_desc;
    MIO_CHECK(miopenCreateTensorDescriptor(&filt_desc));
    MIO_CHECK(miopenSet4dTensorDescriptor(
          filt_desc, miopenFloat,
          filt_k, filt_c, filt_h, filt_w));
    float *filt_data;
    HIP_CALL(hipMalloc( &filt_data, filt_k * filt_c * filt_h * filt_w * sizeof(float)));
    hipLaunchKernel(dev_const, filt_w * filt_h, filt_k * filt_c , 0, 0 ,filt_data, 1.f);

    std::cout << "filt_k: " << filt_k << std::endl;
    std::cout << "filt_c: " << filt_c << std::endl;
    std::cout << "filt_h: " << filt_h << std::endl;
    std::cout << "filt_w: " << filt_w << std::endl;
    std::cout << std::endl;
    print(filt_data, filt_k, filt_c, filt_h, filt_w);
    std::cout << std::endl;

    //----------------------- convolution-set
    const int pad_h = 0;
    const int pad_w = 0;
    const int str_h = 1;
    const int str_w = 1;
    const int dil_h = 1;
    const int dil_w = 1;
    float alphaC = 1.f;
    float betaC = 0.f;
    miopenConvolutionDescriptor_t conv_desc;
    MIO_CHECK(miopenCreateConvolutionDescriptor(&conv_desc));
    MIO_CHECK(miopenInitConvolutionDescriptor(
          conv_desc,miopenConvolution,
          pad_h, pad_w, str_h, str_w, dil_h, dil_w ));

    std::cout << "Convolution-Creation:"<<conv_desc<< std::endl;
    std::cout << "pad_h: " << pad_h << std::endl;
    std::cout << "pad_w: " << pad_w << std::endl;
    std::cout << "str_h: " << str_h << std::endl;
    std::cout << "str_w: " << str_w << std::endl;
    std::cout << "dil_h: " << dil_h << std::endl;
    std::cout << "dil_w: " << dil_w << std::endl;
    std::cout << std::endl;

    //-------------------------output
    int out_n;
    int out_c;
    int out_h;
    int out_w;
    MIO_CHECK(miopenGetConvolutionForwardOutputDim(
          conv_desc, in_desc, filt_desc,
          &out_n, &out_c, &out_h, &out_w));
    miopenTensorDescriptor_t out_desc;
    MIO_CHECK(miopenCreateTensorDescriptor(&out_desc));
    MIO_CHECK(miopenSet4dTensorDescriptor(
          out_desc, miopenFloat,
          out_n, out_c, out_h, out_w));
    float *out_data;
    HIP_CALL(hipMalloc( &out_data, out_n * out_c * out_h * out_w * sizeof(float)));

    std::cout << "out_n: " << out_n << std::endl;
    std::cout << "out_c: " << out_c << std::endl;
    std::cout << "out_h: " << out_h << std::endl;
    std::cout << "out_w: " << out_w << std::endl;
    std::cout << std::endl;

    //--------------------------------- bias
    miopenTensorDescriptor_t bias_desc;
    MIO_CHECK(miopenCreateTensorDescriptor(&bias_desc));
    MIO_CHECK(miopenSet4dTensorDescriptor(bias_desc, miopenFloat,
          out_n, out_c, out_h, out_w));
    float *bias_data;
    HIP_CALL(hipMalloc( &bias_data, out_n * out_c * out_h * out_w * sizeof(float)));
    hipLaunchKernel(dev_const, out_n * out_c ,out_h * out_w , 0, 0 ,bias_data, 2.f);
    float alphaB = 1.f;
    float betaB = 0.f;

    //---------------------- BatchNorm Inference

    miopenBatchNormMode_t bn_mode = miopenBNSpatial;
    float alphaN = 1.f;
    float betaN = 0.f;
    miopenTensorDescriptor_t bnScaleBiasMeanVarDesc;
    MIO_CHECK(miopenCreateTensorDescriptor(&bnScaleBiasMeanVarDesc));
    MIO_CHECK(miopenSet4dTensorDescriptor(bnScaleBiasMeanVarDesc,  miopenFloat,
        1, out_c, 1, 1));
    float* bnScale;
    HIP_CALL(hipMalloc(&bnScale, 1*out_c*1*1*sizeof(float)));
    hipLaunchKernel(dev_const, 1*out_c, 1*1, 0, 0 ,bnScale ,1.f);
    float* bnBias;
    HIP_CALL(hipMalloc(&bnBias, 1*out_c*1*1*sizeof(float)));
    hipLaunchKernel(dev_const, 1*out_c, 1*1, 0, 0 ,bnBias ,0.f);
    float* estimatedMean;
    HIP_CALL(hipMalloc(&estimatedMean, 1*out_c*1*1*sizeof(float)));
    hipLaunchKernel(dev_const, 1*out_c, 1*1, 0, 0 ,estimatedMean ,0.f);
    float* estimatedVariance;
    HIP_CALL(hipMalloc(&estimatedVariance, 1*out_c*1*1*sizeof(float)));
    hipLaunchKernel(dev_const, 1*out_c, 1*1, 0, 0 ,estimatedVariance ,2.f);
    double epsilon = 2.f; // Minimum 1e-5

    //--------------------- Activation
    float alphaA = 1.f;
    float betaA = 0.f;
    miopenActivationDescriptor_t activationDesc;
    miopenActivationMode_t act_mode = miopenActivationRELU;
    double coef = 0;
    double reluCeilingOrAlpha=0;
    double activBeta=0;
    double activExp=0;
    MIO_CHECK(miopenCreateActivationDescriptor(&activationDesc));
    MIO_CHECK(miopenSetActivationDescriptor(activationDesc, act_mode,
        reluCeilingOrAlpha, activBeta, activExp));

    //----------------------------------------Fusion
    hipFree(out_data); // free previous out data
    HIP_CALL(hipMalloc( &out_data, out_n * out_c * out_h * out_w * sizeof(float)));
    miopenFusionPlanDescriptor_t fusePlanDesc;
    miopenFusionDirection_t fuseDirection = miopenVerticalFusion;
    MIO_CHECK(miopenCreateFusionPlan( &fusePlanDesc, fuseDirection, in_desc));
    std::cout<<"\nCreate Fusion Plan:"<< fusePlanDesc;

    miopenFusionOpDescriptor_t convOp;
    miopenFusionOpDescriptor_t biasOp;
    miopenFusionOpDescriptor_t activOp;
    miopenFusionOpDescriptor_t bnOp;
    MIO_CHECK(miopenCreateOpConvForward( fusePlanDesc, &convOp, conv_desc, filt_desc));
    MIO_CHECK(miopenCreateOpBiasForward(fusePlanDesc, &biasOp, bias_desc));
    MIO_CHECK(miopenCreateOpBatchNormInference(fusePlanDesc, &bnOp, bn_mode, bnScaleBiasMeanVarDesc));
    MIO_CHECK(miopenCreateOpActivationForward(fusePlanDesc,  &activOp, act_mode));
    MIO_CHECK(miopenCompileFusionPlan( miopen_handle, fusePlanDesc));

    miopenOperatorArgs_t args;
    MIO_CHECK(miopenCreateOperatorArgs( &args));
    MIO_CHECK(miopenSetOpArgsConvForward(args, convOp, &alphaC, &betaC, filt_data));
    MIO_CHECK(miopenSetOpArgsBiasForward(args, biasOp, &alphaB, &betaB, bias_data));
    MIO_CHECK(miopenSetOpArgsBatchNormInference(args, bnOp, &alphaN, &betaN, bnScale, bnBias,
                            estimatedMean, estimatedVariance, epsilon));
    MIO_CHECK(miopenSetOpArgsActivForward(args, activOp, &alphaA, &betaA,
                reluCeilingOrAlpha, activBeta, activExp));

    MIO_CHECK(miopenExecuteFusionPlan( miopen_handle, fusePlanDesc, in_desc,
            in_data, out_desc, out_data, args));
    std::cout << "\nAfter fusion exec out_data:" << std::endl;
    print(out_data, out_n, out_c, out_h, out_w);

    //-------------------- final free up
    hipFree(in_data);
    miopenDestroyTensorDescriptor(in_desc);
    hipFree(filt_data);
    miopenDestroyTensorDescriptor(filt_desc);
    hipFree(out_data);
    miopenDestroyTensorDescriptor(out_desc);
    miopenDestroyConvolutionDescriptor(conv_desc);
    hipFree(bias_data);
    miopenDestroyTensorDescriptor(bias_desc);
    hipFree(bnScale);
    hipFree(bnBias);
    hipFree(estimatedMean);
    hipFree(estimatedVariance);
    miopenDestroyTensorDescriptor(bnScaleBiasMeanVarDesc);
    miopenDestroyActivationDescriptor(activationDesc);
    miopenDestroyOperatorArgs(args);
    miopenDestroyFusionPlan(fusePlanDesc);
    miopenDestroy(miopen_handle);

return 0 ;}
```

**Comment by JosephGeoBenjamin** [comment]
And Digging deep into the source codes and test codes, I suppose the CBNA implementation is not supported as of now ??

**Comment by JosephGeoBenjamin** [comment]
Thanks for your responses @daniellowell and @JehandadKhan
