### ISSUE TITLE
MIOpen failed half(5/10) of it's test on non AMD OpenCL platforms.

### ISSUE THREAD

**Issue by marty1885** [ROCmSoftwarePlatform/MIOpen#6]
Hello. I found that MIOpen can be built with the OpenCL backed without ROCm. Doing so on a non ROCm OpenCL (nvidia/intel OpenCL to be pacific) platform will make MIOpen to fail half of it's test. Applying #5 's fix will let MIOpen pass 8 tests(test 5 and 6 failed). 
Here is the [log](https://gist.github.com/marty1885/5c3ea7ffb70d47afde8b94f068f46cde).

Is there any chance that this can be fixed so that MIOpen can run on non AMD hardware? I think that it will be a great feature for MIOpen to have. With a cross platform MIOpen, developers can get descent performance via MIOpen on any hardware. Thus make the life of developers easier. And make more people use MIOpen,

**Comment by dagamayank** [comment]
@marty1885 Thank you for your question.

At this time MIOpen is planned to be supported _only_ on AMD GPUs. 

Having said that, MIOpen is open-source and we very much welcome contributions from the community. Those contributions can be related to improving the existing functionality or adding the support for new platforms.
