### ISSUE TITLE
Sample MIOpen code

### ISSUE THREAD

**Issue by aryamazaheri** [ROCmSoftwarePlatform/MIOpen#60]
Is there any sample code for running a simple convolution using MIOpen? It would be much easier to start developing using a sample code than trying to read the whole API pages.

**Comment by dagamayank** [comment]
Please check here - https://rocmsoftwareplatform.github.io/MIOpen/doc/html/

**Comment by dagamayank** [comment]
You can also check all the `MIOpenDriver` code - https://github.com/ROCmSoftwarePlatform/MIOpen/blob/master/driver/conv_driver.hpp

MIOpenDriver is a simple driver/app to test and run bunch of different layers in a neural network.
