### ISSUE TITLE
Backward Convolution Weights failed.

### ISSUE THREAD

**Issue by zpwenjh** [ROCmSoftwarePlatform/MIOpen#600]
My software environment is rocm3.9+miopen2.8, I set `MIOPEN_FIND_MODE=1` and `MIOPEN_FIND_ENFORCE=3`. 
Then, run the following commands:
```
rm -rf ~/.config/miopen/
rm -rf ~/.cache/miopen/
rm -rf /tmp/*
./MIOpenDriver conv -F 4 --batchsize 16 --in_channels 64 --out_channels 256 --iter 1
```
finally, the backward convolution weights failed. The info is as follows:
```
MIOpen(HIP)   0.095: Info [FindConvBwdWeightsAlgorithm] BWrW Chosen Algorithm: ConvWinograd3x3MultipassWrW<3-5> , 39337984, 0.556194
MIOpen(HIP)   0.590: Info [ConvolutionBackwardWeights] algo = 3, workspace = 39337984
MIOpen(HIP)   0.139: Info2 [GetKernels] 3 kernels for key: miopenConvolutionBwdWeightsAlgoWinograd "256x30x30x3x3x64x32x32x16xNCHWxFP32x0x0x1x1x1x1x1x0"
MIOpen(HIP)   0.200: Info2 [CallGemmStridedBatched] gemm_desc: {isColMajor 0, transA 0, transB 1, m 64, n 256, k 576, lda 576, ldb 576, ldc 256, batch_count 49, strideA 36864, strideB 147456, strideC 16384, alpha 1, beta 0, dataType 1}
Backward Convolution Weights Failed: 0.969269 > 2e-05
```
I run these commands several times. Sometimes, the `BWrW Chosen Algorithm` is `ConvOclBwdWrW53` but the problem is remains.
But if I set `MIOPEN_FIND_MODE=3` and `MIOPEN_FIND_ENFORCE=1`, run the same commands as above, the result is success. I don't figure it out how this happened.

**Comment by atamazov** [comment]
Not reproducible with current develop, ROCm 4.0, gfx906.
