### ISSUE TITLE
Running a specific convolution algorithm

### ISSUE THREAD

**Issue by aryamazaheri** [ROCmSoftwarePlatform/MIOpen#61]
Is it possible to run a specific convolution algorithm without searching through all the algorithms? I noticed that running `miopenConvolutionForwardGetWorkSpaceSize()` is mandatory before calling `miopenConvolutionForward` but this prevents me from running a convolution with a specific algorithm that I have in mind. What is the alternative way?

**Comment by dagamayank** [comment]
@aryamazaheri No, not right now. We are actively working to implement this feature. As an alternative you can try disabling some algorithms as mentioned [here](https://github.com/ROCmSoftwarePlatform/MIOpen/wiki/MIOpen-Environment-Variables).

**Comment by aryamazaheri** [comment]
Thanks. Apparently, it is not possible to solely keep Winograd algorithm enabled! :(
There is no flag devised for disabling GEMM conv.

**Comment by dagamayank** [comment]
>  There is no flag devised for disabling GEMM conv.

Right, there is no flag for GEMM. However, you can follow a somewhat contrived method to disable GEMM completely. This requires you to build MIOpen from source and use the following options at the `cmake` configure step:
`cmake -DCMAKE_DISABLE_FIND_PACKAGE_miopengemm=TRUE -DMIOPEN_USE_ROCBLAS=false..`

Note: once the above is done you may notice some convolutions to fail as the default fallback, i.e., GEMM is now removed. Therefore, use it at your own risk.

Instructions on how to build MIOpen from source can be found in the [README](https://github.com/ROCmSoftwarePlatform/MIOpen/blob/master/README.md).
