### ISSUE TITLE
[Legacy OCL] Kernel cache in the binary cache is not hit for the "best" kernel after tuning.

### ISSUE THREAD

**Issue by ZPEthanWen** [ROCmSoftwarePlatform/MIOpen#616]
In the tuning process, there is a problem.
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/a6003098c1f042581b5ed13d7ebb0a6bfaf1c6b1/src/solver/conv_ocl_dir2Dfwd_exhaustive_search.cpp#L170-L185
We can see this line:
```
std::string compiler_options = params.general_compile_options + kernel_params.comp_options;
```
This compiler options is used by `handle.AddKernel()` later, this solution with the additional compiler options will be compiled and cache the kernel in the memory and kernel database. Then after the tuning process finished, the function `PrecompileSolutions` receives a solution that doesn't include the additional compiler options. So, it will be compiled and cached.
But Actually, if a solver can be tuned, the `general_compile_options` is already included in solutions by calling the member function `GetSolution`. Especially, the code listed above exists in template function `MeasurePerfConfig`, the template variable of this function is only `ConvOclDirectFwd1x1` or `ConvOclDirectFwd` currently. Those two solvers' solutions also include the `general_compile_options`.
That is to say, the `general_compile_options` repeated twice when compiled in tuning process. The cached kernel in tuning process and `PrecompileSolutions` is actually one kernel, but it compiled twice.

**I've verified what I said. The compile options as follows:**
```
[SystemCmd] /opt/rocm/bin/clang-ocl  -DMIOPEN_USE_FP16=0 -DMIOPEN_USE_FP32=1 -DMIOPEN_USE_INT8=0 -DMIOPEN_USE_INT8x4=0 -DMIOPEN_USE_BFP16=0 -DMIOPEN_USE_INT32=0 -DMIOPEN_USE_RNE_BFLOAT16=1 -DMLO_HW_WAVE_SZ=64 -DMLO_DIR_FORWARD=1 -DMLO_FILTER_SIZE0=3 -DMLO_FILTER_SIZE1=3 -DMLO_FILTER_PAD0=0 -DMLO_FILTER_PAD1=0 -DMLO_FILTER_STRIDE0=1 -DMLO_FILTER_STRIDE1=1 -DMLO_N_OUTPUTS=256 -DMLO_N_INPUTS=64 -DMLO_BATCH_SZ=16 -DMLO_OUT_WIDTH=30 -DMLO_OUT_HEIGHT=30 -DMLO_OUT_BATCH_STRIDE=230400 -DMLO_OUT_CHANNEL_STRIDE=900 -DMLO_OUT_STRIDE=30 -DMLO_IN_WIDTH=32 -DMLO_IN_HEIGHT=32 -DMLO_IN_BATCH_STRIDE=65536 -DMLO_IN_CHANNEL_STRIDE=1024 -DMLO_IN_STRIDE=32 -DMLO_IN_TILE0=16 -DMLO_IN_TILE1=16 -DMLO_GRP_TILE0=16 -DMLO_GRP_TILE1=16 -DMLO_OUT_TILE0=1 -DMLO_OUT_TILE1=1 -DMLO_N_STACKS=1 -DMLO_N_OUT_TILES=1 -DMLO_N_OUT_TILES_PERSTACK=1 -DMLO_N_IN_TILES_PERSTACK=1 -DMLO_N_READ_PROCS=256 -DMLO_ALU_VTILE0=16 -DMLO_ALU_VTILE1=16 -DMIOPEN_USE_FP16=0 -DMIOPEN_USE_FP32=1 -DMIOPEN_USE_INT8=0 -DMIOPEN_USE_INT8x4=0 -DMIOPEN_USE_BFP16=0 -DMIOPEN_USE_INT32=0 -DMIOPEN_USE_RNE_BFLOAT16=1 -DMLO_CONV_BIAS=0 
                                     -DMIOPEN_USE_FP16=0 -DMIOPEN_USE_FP32=1 -DMIOPEN_USE_INT8=0 -DMIOPEN_USE_INT8x4=0 -DMIOPEN_USE_BFP16=0 -DMIOPEN_USE_INT32=0 -DMIOPEN_USE_RNE_BFLOAT16=1 -mcpu=gfx906 -Wno-everything -Xclang -target-feature -Xclang +code-object-v3 MIOpenConvDirUni.cl -o /tmp/miopen-MIOpenConvDirUni.cl-0f4d-a272-a518-2f54/MIOpenConvDirUni.cl.o
```

**Comment by ZPEthanWen** [comment]
This problem has been avoided by the PR #619 , so, if PR #619 is accepted, there is no need to accept the PR #617 again.

**Comment by atamazov** [comment]
Nice finding ;)

**Comment by atamazov** [comment]
> This problem has been avoided by the PR #619 , so, if PR #619 is accepted, there is no need to accept the PR #617 again.

Even if #617 is a one-liner, it worth dedicated PR. I recommend removing this change from #619.

**Comment by atamazov** [comment]
Please note that during tuning kernels are not stored (and should NOT be stored) in kcache (kernel cache). Persistent binary cache is another story.

**Comment by ZPEthanWen** [comment]
> Please note that during tuning kernels are not stored (and should NOT be stored) in kcache (kernel cache). Persistent binary cache is another story.

I agree with you. But the `Search` function in solver will call 'Handle::AddKernel' before run the kernel, and then `Handle::AddKernel` will call 'KernelCache::AddKernel`. This function has code as follows:
```
ProcessParams(params);

    const std::pair<std::string, std::string> key = std::make_pair(algorithm, network_config);
    if(!network_config.empty() || !algorithm.empty()) // Don't log only _empty_ keys.
        MIOPEN_LOG_I2("Key: " << key.first << " \"" << key.second << '\"');

    Program program;

    auto program_it = program_map.find(std::make_pair(program_name, params));
    if(program_it != program_map.end())
    {
        program = program_it->second;
    }
    else
    {
        if(!is_kernel_miopengemm_str) // default value
            is_kernel_miopengemm_str = algorithm.find("ImplicitGEMM") == std::string::npos &&
                                       algorithm.find("GEMM") != std::string::npos;

        if(miopen::IsLogging(miopen::LoggingLevel::Info2))
        {
            AddKernelDumpKernelParams(is_kernel_miopengemm_str
                                          ? std::string("(source provided by miopengemm)")
                                          : program_name,
                                      kernel_name,
                                      vld,
                                      vgd,
                                      params);
        }
        program = h.LoadProgram(program_name, params, is_kernel_miopengemm_str, kernel_src);
        program_map[std::make_pair(program_name, params)] = program;
    }
```
I can see if there is no program in the memory cache, then miopen will call `Handle::LoadProgram` to load program and add it to the memory cache.

**Comment by ZPEthanWen** [comment]
> > Please note that during tuning kernels are not stored (and should NOT be stored) in kcache (kernel cache). Persistent binary cache is another story.
> 
> I agree with you. But the `Search` function in solver will call 'Handle::AddKernel' before run the kernel, and then `Handle::AddKernel` will call 'KernelCache::AddKernel`. This function has code as follows:
> 
> ```
> ProcessParams(params);
> 
>     const std::pair<std::string, std::string> key = std::make_pair(algorithm, network_config);
>     if(!network_config.empty() || !algorithm.empty()) // Don't log only _empty_ keys.
>         MIOPEN_LOG_I2("Key: " << key.first << " \"" << key.second << '\"');
> 
>     Program program;
> 
>     auto program_it = program_map.find(std::make_pair(program_name, params));
>     if(program_it != program_map.end())
>     {
>         program = program_it->second;
>     }
>     else
>     {
>         if(!is_kernel_miopengemm_str) // default value
>             is_kernel_miopengemm_str = algorithm.find("ImplicitGEMM") == std::string::npos &&
>                                        algorithm.find("GEMM") != std::string::npos;
> 
>         if(miopen::IsLogging(miopen::LoggingLevel::Info2))
>         {
>             AddKernelDumpKernelParams(is_kernel_miopengemm_str
>                                           ? std::string("(source provided by miopengemm)")
>                                           : program_name,
>                                       kernel_name,
>                                       vld,
>                                       vgd,
>                                       params);
>         }
>         program = h.LoadProgram(program_name, params, is_kernel_miopengemm_str, kernel_src);
>         program_map[std::make_pair(program_name, params)] = program;
>     }
> ```
> 
> I can see if there is no program in the memory cache, then miopen will call `Handle::LoadProgram` to load program and add it to the memory cache.

@atamazov Sorry, I am wrong for current develop branch.

**Comment by ZPEthanWen** [comment]
> Please note that during tuning kernels are not stored (and should NOT be stored) in kcache (kernel cache). Persistent binary cache is another story.

@atamazov , Handle::AddKernel will cache the program to memory cache

**Comment by atamazov** [comment]
@ZPEthanWen FYI some details about `KernelCache::AddKernel()`. If algorithm or network_config is not provided, then the function does not add kernel to the kcache. The run-time object that represents the kernel will be freed as soon as the `Kernel` instance (returned) by `KernelCache::AddKernel()`) is destroyed. This frees GPU memory from temporary kernels.

**Comment by atamazov** [comment]
@ZPEthanWen Notice that _Programs_ are different from _Kernels_ and are handled in different way. IIRC Programs are HIP/OCL runtime objects that do not consume memory on GPU. That is why the library always holds these objects (stores the owning pointers in a per-handle store, the so-called "kernel cache").
