### ISSUE TITLE
[Legacy OCL] The ConvOclDirectFwdLegacyExhaustiveSearch:Search is still serial compilation for solutions

### ISSUE THREAD

**Issue by zpwenjh** [ROCmSoftwarePlatform/MIOpen#618]
The `ConvOclDirectFwdLegacyExhaustiveSearch:Search` is calling `SearchImpl` function to tune the parameters. In the `SearchImpl`, the number of solutions is up to five hundred. But it still performs serial compilation for all solutions by calling `MeasurePerfConfig` function. This is very inefficient, will take a long time to complete.

**Comment by atamazov** [comment]
@junliume Can you please remind which PR resolves this? Thanks!

**Comment by junliume** [comment]
@atamazov we are closing a few legacy related tickets. If we confirm this is legacy OCL only, then most likely we won't be fixing it.
CC: @JehandadKhan

**Comment by atamazov** [comment]
@junliume Thanks for explanation. We can use https://github.com/ROCmSoftwarePlatform/MIOpen/labels/wontfix and/or close as "not planned" (but textual description is the most important of course 😉) 

![image](https://user-images.githubusercontent.com/12697412/196806115-dfbec39f-28f7-4923-88da-29ce37b35cd3.png)
