### ISSUE TITLE
Remove ConvOclDirectFwd3x3

### ISSUE THREAD

**Issue by JehandadKhan** [ROCmSoftwarePlatform/MIOpen#647]
The legacy `ConvOclDirectFwd3x3` solver has serious correctness issues pertaining to large buffer sizes. Since this solver is rarely picked by MIOpen for convolution operations, this solver may be removed altogether. 

@daniellowell Thoughts ?

**Comment by atamazov** [comment]
How to reproduce: https://github.com/ROCmSoftwarePlatform/MIOpen/pull/642#issue-533029738

**Comment by atamazov** [comment]
#642
