### ISSUE TITLE
Example of use and/or documentation

### ISSUE THREAD

**Issue by jianlongf** [ROCmSoftwarePlatform/MIOpen#651]
HI， I wanna integrete MIOpen into my framework( call the MIOpen kernel implementation) that uses OpenCL kernel implementation.  In order to make it, I have to transfer data to MIOpen and get back compute result. But I have not found the guide  or example about that yet.  Could you please give me one.

**Comment by daniellowell** [comment]
You have a new OpenCL kernel you want to integrate into MIOpen?

**Comment by atamazov** [comment]
@daniellowell AFAICS @jianlongf simply wants to use MIOpen normally, as a library, and asks for assistance -- examples and/or documentation.

@jianlongf First [install MIOpen on your system](https://rocmsoftwareplatform.github.io/MIOpen/doc/html/install.html), then look into miopen API ([docs](https://rocmsoftwareplatform.github.io/MIOpen/doc/html/apireference.html) and [public header file](https://github.com/ROCmSoftwarePlatform/MIOpen/blob/develop/include/miopen/miopen.h)). I am not aware if we have simple examples, but you can look at the [MIOpenDriver sources](https://github.com/ROCmSoftwarePlatform/MIOpen/tree/develop/driver) (but these are not simple).

**Comment by jianlongf** [comment]
Ok, thank you for your help. I have found the sample I need. [https://qiita.com/syoyo/items/2a2038d665499f1f6df1](url). It should be useful for someone who meet the same question.
