### ISSUE TITLE
Build fails with boost 1.75

### ISSUE THREAD

**Issue by tpkessler** [ROCmSoftwarePlatform/MIOpen#658]
When compiling MIOpen 4.0.0 from source with boost 1.75 on Arch Linux I get multiple error messages regarding `noinline`, for instance:

```
/usr/include/boost/container/vector.hpp:2722:4: error: type name does not allow function specifier to be specified
/usr/include/boost/container/detail/workaround.hpp:116:37: note: expanded from macro 'BOOST_CONTAINER_NOINLINE'
   #define BOOST_CONTAINER_NOINLINE BOOST_NOINLINE#      define BOOST_NOINLINE __attribute__ ((__noinline__))

                                    ^                                             ^

/usr/include/boost/config/detail/suffix.hpp:626:46: /opt/rocm/hip/include/hip/hcc_detail/host_defines.h:note75: :37expanded from macro 'BOOST_NOINLINE': 
note: expanded from macro '__noinline__'
#      define BOOST_NOINLINE __attribute__ ((__noinline__))
                                             ^
/opt/rocm/hip/include/hip/hcc_detail/host_defines.h:75:37: note: expanded from macro '__noinline__'
#define __noinline__ __attribute__((noinline))
                                    ^
#define __noinline__ __attribute__((noinline))

```

MIOpen compiles fine however when I downgrade boost to 1.72.

**Comment by daniellowell** [comment]
Our requirements pin the boost version 1.72. I'll update our documentation to reflect that.

You can install the minimal requirements for MIOpen using the command:
`cmake -P install_deps.cmake --minimum --prefix /some/local/dir`

and then configure with:
`CXX=/opt/rocm/llvm/bin/clang++ cmake -DMIOPEN_BACKEND=HIP -DCMAKE_PREFIX_PATH="/some/local/dir" ..`

See more information here:
https://rocmsoftwareplatform.github.io/MIOpen/doc/html/install.html#installing-minimum-dependencies-in-rocm-environment

**Comment by daniellowell** [comment]
Documentation has been updated in our develop branch. Please feel free to reopen if you have additional questions.

**Comment by pfultz2** [comment]
Actually, this is a bug in HIP, as its defining a `__noinline__` macro and boost is trying to use the attribute `__noinline__` causing the error. I think we should file a ticket with the HIP team.

**Comment by tpkessler** [comment]
> Documentation has been updated in our develop branch.

Thank you! Installing `boost 1.72` via `cmake` does the trick for me.

> Actually, this is a bug in HIP

That's interesting. Thank you for the information.

**Comment by ipdemes** [comment]
>Actually, this is a bug in HIP, as its defining a __noinline__ macro and boost is trying to use the attribute __noinline__ causing the error. 

Do anyone know is the ticket was created for HIP. I have got similar error today with the recent hip and boost

**Comment by junliume** [comment]
Ping @pfultz2 who may know more about if HIP side is working on a fix or not.

**Comment by atamazov** [comment]
I guess that HIP compiler bugs can be reported at https://github.com/ROCm-Developer-Tools/HIP/issues
