### ISSUE TITLE
[cmake][OCL BE] "HIP compiler flags" are missing some options.

### ISSUE THREAD

**Issue by atamazov** [ROCmSoftwarePlatform/MIOpen#666]
Found with ROCm 4.1 RC. Reproducible with ROCm 3.5.

The following flags are missing from `HIP Compiler Flags` when OCL backend is used:
- `-mllvm -amdgpu-early-inline-all=true`
- `-mllvm -amdgpu-function-calls=false`

The side effect is **_huge_** performance drop of HIP kernels with OCL BE.

Example (Radeon VII, ROCm 3.5):
- Config `conv -x 3 -y 3 -W 17 -H 17 -c 192 -n 128 -k 192 -p 0 -q 0 -u 2 -v 2 -l 1 -j 1 -g 1 -F 1 -V 0 -w 1 -t 1 -i 6`
- Solver `ConvHipImplicitGemmV4R1Fwd`:
  - HIP backend: 0.8 ms
  - OCL backend: 27.3 ms

**Comment by atamazov** [comment]
Notice nice issue number :smiling_imp:

**Comment by atamazov** [comment]
Guys, any ideas why this happens?

**Comment by pfultz2** [comment]
This is an issue with the hip-config.cmake. It seems to drop these flags if CXX compiler is not clang.

**Comment by atamazov** [comment]
@pfultz2 The reason is https://github.com/ROCm-Developer-Tools/HIP/pull/2035

**Comment by atamazov** [comment]
https://github.com/ROCm-Developer-Tools/HIP/issues/2233 created.

**Comment by atamazov** [comment]
Some discussion can be found at http://ontrack-internal.amd.com/browse/SWDEV-271886
