### ISSUE TITLE
[RNN] Wall-clock time elapsed much longer then GPU kernel time elapsed

### ISSUE THREAD

**Issue by zpwenjh** [ROCmSoftwarePlatform/MIOpen#667]
lstm forward training:
```bash
MIOpenDriver rnn -n 64 -W 1024 -H 1024 -l 1 -b 0 -m lstm -p 0 -r 0 -k 75 -c 0 -F 1 -t 1 -w 1 -V 0 -i 10
GPU Kernel Time Forward RNN Elapsed: 16.870262 ms
Wall-clock Time Forward RNN Elapsed: 25.463526 ms
```
lstm backward data:
```bash
MIOpenDriver rnn -n 64 -W 1024 -H 1024 -l 1 -b 0 -m lstm -p 0 -r 0 -k 75 -F 2 -t 1 -w 1 -V 0 -i 10
GPU Kernel Time Backward Data RNN Elapsed: 18.176170 ms
Wall-clock Time Backward Data RNN Elapsed: 26.701023 ms
```
lstm backward weights:
```bash
MIOpenDriver rnn -n 64 -W 1024 -H 1024 -l 1 -b 0 -m lstm -p 0 -r 0 -k 75 -F 4 -t 1 -w 1 -V 0 -i 10
GPU Kernel Time Backward Weights RNN Elapsed: 8.174283 ms
Wall-clock Time Backward Weights RNN Elapsed: 8.451336 ms
```
The Wall-clock time elapsed much longer then GPU kernel time elapsed in LSTM forward and backward data process. That's to say, a lot of time is spent on CPU rather than GPU computing.
[fwd_cached.log](https://github.com/ROCmSoftwarePlatform/MIOpen/files/5762852/fwd_cached.log)
[bwd_data_cached.log](https://github.com/ROCmSoftwarePlatform/MIOpen/files/5762853/bwd_data_cached.log)
[bwd_weights_cached.log](https://github.com/ROCmSoftwarePlatform/MIOpen/files/5762854/bwd_weights_cached.log)

**Comment by ce1adon** [comment]
@ZPEthanWen Which version are you testing?

**Comment by ZPEthanWen** [comment]
@ce1adon I'm using `miopen-develop` at `b86f3a1acce8766d6e72a7c450dbfd173ee76d4d` in rocm-3.9，the gemm algorithm in RNN is performed by rocBLAS.

**Comment by ce1adon** [comment]
@zpwenjh What graphic card and CPU do you have?

**Comment by ce1adon** [comment]
@zpwenjh I tested your cases and the rate of kernel time to wall time is 73.8%, 80.2% and 95.3% for forward, backward and weight (yours are 66%, 68%, and 97%). May I know your expectation?
