### ISSUE TITLE
MIOpen Error: /home/dlowell/MIOpenPrivate/src/include/miopen/hipoc_kernel.hpp:200: Failed to get function: Im2Col from /home/username/.cache/miopen/1.7.0/4d8ca72dd191276335b17fe1d88f6f76/MIOpenUtilKernels.cl.o hipErrorNotFound

### ISSUE THREAD

**Issue by greatken999** [ROCmSoftwarePlatform/MIOpen#67]
I get this error info after apt upgrade:
MIOpen Error: /home/dlowell/MIOpenPrivate/src/include/miopen/hipoc_kernel.hpp:200: Failed to get function: Im2Col from /home/ken/.cache/miopen/1.7.0/4d8ca72dd191276335b17fe1d88f6f76/MIOpenUtilKernels.cl.o hipErrorNotFound

**Comment by daniellowell** [comment]
@greatken999 Please make sure you have upgraded rocm-clang-ocl as well AND delete your program caches if the exist. Typically the cache is located in ~/.cache/miopen

https://rocmsoftwareplatform.github.io/MIOpen/doc/html/cache.html

**Comment by greatken999** [comment]
@daniellowell  thanks .
rocm-clang-ocl/now 0.3.0-7997136 amd64
is this last version?
after  rm -rf .cache/miopen/1.7.0/
get this error info 
MIOpen Error: /home/dlowell/MIOpenPrivate/src/include/miopen/hipoc_kernel.hpp:200: Failed to get function: Im2Col from /tmp/miopen-MIOpenUtilKernels.cl-a0b8-4f23-6b8a-09b0/MIOpenUtilKernels.cl.o hipErrorNotFound
problem still there ,how can i do ?

**Comment by daniellowell** [comment]
`rocm-clang-ocl-0.3.0-688fe5d` is the latest version. The version you have is causing this issue.

Uninstall your old version and do `sudo apt update`,  `sudo apt install rocm-clang-ocl` then delete your cache. THEN make sure your path is pointing to /opt/rocm/bin first.
That shoild fix things.

**Comment by greatken999** [comment]
it's ok now us rocm-clang-ocl-0.3.0-688fe5d
thanks @daniellowell

**Comment by daniellowell** [comment]
No problem!

**Comment by mnvmld** [comment]
I can't install rocm-clang-ocl
If I try it, I get:

> Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 mivisionx : Depends: miopen-opencl but it is not going to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

What is it? Please help

**Comment by daniellowell** [comment]
Looks like you previously had mivisionx installed but you do not now? Did you try purging mivisionx, or running `apt autoremove`?

**Comment by mnvmld** [comment]
> Looks like you previously had mivisionx installed but you do not now? Did you try purging mivisionx, or running `apt autoremove`?

I removed mivisionx and after that all are OK. Thanks! But...
I try use Mirrored Strategy for MultyGPU, but I get error:

> WARNING:tensorflow:Using temporary folder as model directory: /tmp/tmpszzzlis4
INFO:tensorflow:Using config: {'_save_checkpoints_steps': None, '_device_fn': None, '_is_chief': True, '_train_distribute': <tensorflow.contrib.distribute.python.mirrored_strategy.MirroredStrategy object at 0x7ff9da20a470>, '_save_checkpoints_secs': 600, '_keep_checkpoint_every_n_hours': 10000, '_model_dir': '/tmp/tmpszzzlis4', '_num_ps_replicas': 0, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7ff9da20a3c8>, '_tf_random_seed': None, '_session_config': None, '_global_id_in_cluster': 0, '_keep_checkpoint_max': 5, '_evaluation_master': '', '_service': None, '_task_type': 'worker', '_master': '', '_num_worker_replicas': 1, '_save_summary_steps': 100, '_log_step_count_steps': 100, '_task_id': 0}
INFO:tensorflow:Device is available but not used by distribute strategy: /device:CPU:0
INFO:tensorflow:Device is available but not used by distribute strategy: /device:XLA_CPU:0
INFO:tensorflow:Configured nccl all-reduce.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:batch_all_reduce invoked for batches size = 2 with algorithm = nccl and num_packs = 1
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.

---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
~/.conda/envs/py35/lib/python3.5/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1321     try:
-> 1322       return fn(*args)
   1323     except errors.OpError as e:

~/.conda/envs/py35/lib/python3.5/site-packages/tensorflow/python/client/session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1304       # Ensure any changes to the graph are reflected in the runtime.
-> 1305       self._extend_graph()
   1306       return self._call_tf_sessionrun(

~/.conda/envs/py35/lib/python3.5/site-packages/tensorflow/python/client/session.py in _extend_graph(self)
   1339       with self._graph._lock:  # pylint: disable=protected-access
-> 1340         tf_session.ExtendSession(self._session)
   1341     else:

InvalidArgumentError: No OpKernel was registered to support Op 'NcclAllReduce' with these attrs.  Registered devices: [CPU,GPU,XLA_CPU], Registered kernels:
  <no registered kernels>

	 [[Node: NcclAllReduce_1 = NcclAllReduce[T=DT_FLOAT, num_devices=2, reduction="sum", shared_name="c0", _device="/device:GPU:1"](split_1)]]

Why  <no registered kernels> ???
