### ISSUE TITLE
How does a CL app call the API algorithm from MIOpen-opencl?

### ISSUE THREAD

**Issue by ghostplant** [ROCmSoftwarePlatform/MIOpen#69]
I take the following API as an example which is relu activation forward:
```sh
miopenActivationForward(handle, desc, &alpha, shapeX, x, &beta, shapeY, y);
```
Regardless the field of `handle, desc, alpha, beta, shapeX, shapeY` which is easy to fill,
I don't know how my OpenCL application can create a memory pointer `x, y` as input/output space?

I am not using HIP so `hipMalloc()` is not accessible to me.
Would `clCreateBuffer()` work for it?

**Comment by pfultz2** [comment]
> Would clCreateBuffer() work for it?

Yes. The objects should be `cl_mem` objects(but not pointers to `cl_mem` objects):

```cpp
cl_mem x = clCreateBuffer(ctx, CL_MEM_READ_ONLY, 4 * sz, nullptr, nullptr);
cl_mem y = clCreateBuffer(ctx, CL_MEM_READ_ONLY, 4 * sz, nullptr, nullptr);
miopenActivationForward(handle, desc, &alpha, shapeX, x, &beta, shapeY, y);
```

**Comment by ghostplant** [comment]
Nice example! I'll try that~

**Comment by ghostplant** [comment]
Thank you! @pfultz2
