### ISSUE TITLE
Default find mode is not checking IsApplicable()

### ISSUE THREAD

**Issue by asroy** [ROCmSoftwarePlatform/MIOpen#693]
The default find mode is not checking IsApplicable(), therefore, these ENV would not disable the solvers if they are in find-DB

```
export MIOPEN_DEBUG_CONV_IMPLICIT_GEMM_HIP_WRW_V4R4_XDLOPS=0 
export MIOPEN_DEBUG_CONV_IMPLICIT_GEMM_HIP_WRW_V4R4=0 
export MIOPEN_DEBUG_CONV_IMPLICIT_GEMM_HIP_WRW_V4R4_PADDED_GEMM_XDLOPS=0 
export MIOPEN_DEBUG_CONV_IMPLICIT_GEMM_HIP_BWD_V4R1=0 
export MIOPEN_DEBUG_CONV_IMPLICIT_GEMM_HIP_BWD_V1R1=0 
export MIOPEN_DEBUG_CONV_IMPLICIT_GEMM_HIP_BWD_V1R1_XDLOPS=0 
export MIOPEN_DEBUG_CONV_IMPLICIT_GEMM_HIP_BWD_V4R1_XDLOPS=0 
export MIOPEN_DEBUG_CONV_IMPLICIT_GEMM_HIP_FWD_V4R4_XDLOPS=0 
export MIOPEN_DEBUG_CONV_IMPLICIT_GEMM_HIP_FWD_V4R4_PADDED_GEMM_XDLOPS=0 
export MIOPEN_DEBUG_CONV_IMPLICIT_GEMM_HIP_FWD_V4R4=0 
export MIOPEN_DEBUG_CONV_IMPLICIT_GEMM_HIP_FWD_V4R1=0 
export MIOPEN_DEBUG_CONV_IMPLICIT_GEMM_HIP_WRW_V4R1=0 
export MIOPEN_DEBUG_CONV_IMPLICIT_GEMM_HIP_FWD_V4R5_XDLOPS=0 

declare -x MIOPEN_DEBUG_CONV_IMPLICIT_GEMM_ASM_BWD_GTC_XDLOPS="0" 
declare -x MIOPEN_DEBUG_CONV_IMPLICIT_GEMM_ASM_BWD_V4R1="0" 
declare -x MIOPEN_DEBUG_CONV_IMPLICIT_GEMM_ASM_FWD_GTC_XDLOPS="0" 
declare -x MIOPEN_DEBUG_CONV_IMPLICIT_GEMM_ASM_FWD_V4R1="0" 
declare -x MIOPEN_DEBUG_CONV_IMPLICIT_GEMM_ASM_FWD_V4R1_1X1="0" 
declare -x MIOPEN_DEBUG_CONV_IMPLICIT_GEMM_ASM_WRW_GTC_XDLOPS="0" 
declare -x MIOPEN_DEBUG_CONV_IMPLICIT_GEMM_ASM_WRW_V4R1="0" 
```

**Comment by atamazov** [comment]
This should not be so. Please let me know how to reproduce the issue.

**Comment by asroy** [comment]
QA found they cannot disable HIP-iGEMM and ASM-iGEMM with above ENV and default find mode, when we are debugging this ticket http://ontrack-internal.amd.com/browse/SWDEV-264323

It's still a hypothesis that when there is entry in find-db, IsApplicable() will be bypassed, I will update this issue when it's confirmed. Right now We are just debugging the convergence issue itself

**Comment by atamazov** [comment]
> It's still a hypothesis that when there is entry in find-db, IsApplicable() will be bypassed

The library was intentionally designed to check IsApplicable even when find-db entry is found, because we want to support individual switches like `MIOPEN_DEBUG_CONV_IMPLICIT_GEMM_HIP_WRW_V4R1` etc. However, bugs are always possible.

**Comment by atamazov** [comment]
@asroy Please reopen if issue is reproducible.
