### ISSUE TITLE
GEMM verify failed

### ISSUE THREAD

**Issue by chenyongqing270** [ROCmSoftwarePlatform/MIOpen#702]
./MIOpenDriver gemm -n 700 -m 161 -k 32 -F 1 -V 1 -t 1 -i 1
MIOpenDriver gemm -n 700 -m 161 -k 32 -F 1 -V 1 -t 1 -i 1
MIOpen(HIP): Info [Handle] stream: 0x293ccc0, device_id: 0
MIOpen(HIP): Info2 [CallGemm] gemm_desc: {isColMajor 0, transA 0, transB 0, m 161, n 700, k 32, lda 32, ldb 700, ldc 700, batch_count 1, strideA 5152, strideB 22400, strideC 112700, alpha 1, beta 0, dataType 0}
GPU Kernel Time Gemm Elapsed: 13077.966797 ms
Forward GEMM Failed: nan

**Comment by chenyongqing270** [comment]
I tested on the gfx906 platform, on the develop branch。rocm-4.0.0, rocm-3.9.0platform  both failed。

**Comment by junliume** [comment]
@chenyongqing270  could you try on new releases on ROCm? Please comment and reopen if the issue still persists.
Close for now due to inactivity.
