### ISSUE TITLE
[GRU] The implementation of GRU seems problematic

### ISSUE THREAD

**Issue by zpwenjh** [ROCmSoftwarePlatform/MIOpen#716]
I am analyzing the implementation of GRU by  `RNNForwardTraining`. Here is the implementation step in `RNNForwardTraining`:
Suppose R = Reservespace.
![image](https://user-images.githubusercontent.com/63989327/106262417-f3669900-625d-11eb-832f-8358968b84a9.png)
The following is principle of GRU.
![image](https://user-images.githubusercontent.com/63989327/106261546-a9c97e80-625c-11eb-86bb-cdea4a93a5d2.png)
And then, the next process is wrong too.

**Comment by ce1adon** [comment]
@zpwenjh 
There are two GRU prototypes based on how the update gate controls cell gate. 
One is _W*(r*h)_, while _r_ and _h_ are vectors, as you mentioned above.
The other one, which is also adopted by cuDNN, is _r*(W*h)_.
The calculation results of these two prototypes are different, yet the basic idea is the same: using update gate to control cell gate.
We chose the latter one to be consistent to cuDNN implementations. Please request the other feature if needed.

**Comment by ce1adon** [comment]
@zpwenjh 
Please find a reference from cuDNN here. More details (https://docs.nvidia.com/deeplearning/cudnn/api/index.html).
```
it = σ(Wixt + Riht-1)
rt = σ(Wrxt + Rrht-1)
h't = tanh(Whxt + rt ◦ (Rhht-1))
ht = (1 - it) ◦ h't + it ◦ ht-1
```

**Comment by zpwenjh** [comment]
@ce1adon I get it. Thank you.
