### ISSUE TITLE
Performce of miopenFindConvolutionForwardAlgorithm bad when input is small

### ISSUE THREAD

**Issue by qili93** [ROCmSoftwarePlatform/MIOpen#717]
When input size if 1x3x128x128, then the time cost for miopenConvolutionForwardGetWorkSpaceSize and miopenFindConvolutionForwardAlgorithm is small.

```bash
# input {1, 3, 128, 128} filter {8, 3, 3, 3}
miopenConvolutionForwardGetWorkSpaceSize cost: 0.065767 s
miopenFindConvolutionForwardAlgorithm cost: 0.068357 s
```

And after I change the input size to 1x3x8x8, the time cost increase significantly as following:

```bash
# input {1, 3, 8, 8} filter {8, 3, 3, 3}
miopenConvolutionForwardGetWorkSpaceSize cost: 0.067701 s
miopenFindConvolutionForwardAlgorithm cost: 1.76785 s
```

And change to 1x3x2x2, then time cost becomes huge

```bash
# input {1, 3, 2, 2} filter {8, 3, 3, 3}
miopenConvolutionForwardGetWorkSpaceSize cost: 0.064997 s
miopenFindConvolutionForwardAlgorithm cost: 10.2737 s <==== more than 10 seconds here
```

I'm using ROCM 3.5 on amdgpu-target=gfx906, any idea to improve the performance for small input? This really impact when my input is not so large. And my code as following:

```c++
      int perf_count;
      int best_algo_idx = 0;
      std::unique_ptr<perf_t[]> perf_results(new perf_t[kNUM_CUDNN_FWD_ALGS]);

      size_t workspace_size = 0;

      timeline.Start();
      PADDLE_ENFORCE_CUDA_SUCCESS(
          platform::dynload::miopenConvolutionForwardGetWorkSpaceSize(
              args.handle, args.wdesc.desc(), args.idesc.desc(),
              args.cdesc.desc(), args.odesc.desc(), &workspace_size));
      timeline.Pause();
      VLOG(0) << "==== miopenConvolutionForwardGetWorkSpaceSize cost: " << timeline.ElapsedSec() << " s";

      VLOG(3) << "workspace_size_limit is " << workspace_size_limit;
      VLOG(3) << "Get miopenConvolutionForwardGetWorkSpaceSize is " << workspace_size;

      platform::Workspace cudnn_workspace(workspace_size);
      timeline.Start();
      PADDLE_ENFORCE_CUDA_SUCCESS(
          platform::dynload::miopenFindConvolutionForwardAlgorithm(
              args.handle, 
              args.idesc.desc(), static_cast<const void *>(args.x->data<T>()), 
              args.wdesc.desc(), static_cast<const void *>(args.w->data<T>()),
              args.cdesc.desc(), 
              args.odesc.desc(), static_cast<void *>(const_cast<T*>(args.o->data<T>())),
              kNUM_CUDNN_FWD_ALGS, &perf_count,
              perf_results.get(), cudnn_workspace.data,
              workspace_size, false));
      timeline.Pause();
      VLOG(0) << "==== miopenFindConvolutionForwardAlgorithm cost: " << timeline.ElapsedSec() << " s";
```

**Comment by atamazov** [comment]
(1) Please give full information for reproducing this. 
- Padding, strides and dilation info is missing
- Do you use FP32?
- 
If you give options for MIOpenDriver, it would be the best.

**Comment by atamazov** [comment]
> And change to 1x3x2x2, then time cost becomes huge

Most likely, this is due to the time that the library spends for building HIP kernels. If you are using the library in the usual way (building the release version without "-DBUILD_DEV=on" and then installing the library into your system), then it should have the binary caching feature enabled. The binary cache should avoid rebuilding kernels, thereby saving the time of `Find()` calls. Please try "small" convolution second time and let us know if the host-side overhead has been reduced.

**Comment by qili93** [comment]
@atamazov Thanks for your quick resposne :)

The input and attributes of the conv2d is following, and I just change the `input_height` and `intput_width` in the following code. And the data type used is `float32`。And I have not set any options for MIOpenDriver, just load it form the header here: https://github.com/qili93/Paddle/blob/rocm_dev_0127/paddle/fluid/platform/dynload/miopen.h

```c++
  // input
  const int batch_size = 1;
  const int input_channel = 3;
  const int input_height = 128;
  const int input_width = 128;
  framework::DDim input_dims({batch_size, input_channel, input_height, input_width});
  size_t input_numel = static_cast<size_t>(framework::product(input_dims));
  // filter
  const int output_channel = 8;
  const int groups = 1;
  const int kernel_h = 3;
  const int kernel_w = 3;
  framework::DDim filter_dims({output_channel, static_cast<int>(input_channel/groups), kernel_h, kernel_w});
  size_t filter_numel = static_cast<size_t>(framework::product(filter_dims));
  // attr
  const int conv_stride = 2;
  const int conv_padding = 1;
  const int conv_dilation = 1;
  // output
  const int output_height = static_cast<int>((input_height + 2 * conv_padding - (conv_dilation * (kernel_h - 1) + 1)) / conv_stride + 1);
  const int output_width = static_cast<int>((input_width + 2 * conv_padding - (conv_dilation * (kernel_w - 1) + 1)) / conv_stride + 1);
  framework::DDim output_dims({batch_size, output_channel, output_height, output_width});
  // size_t output_numel = static_cast<size_t>(framework::product(output_dims));
```

**Comment by atamazov** [comment]
https://github.com/ROCmSoftwarePlatform/MIOpen/issues/717#issuecomment-769784801 updated

**Comment by qili93** [comment]
@atamazov I have tried twice and seems the time cost is still huge

```bash
# first run
miopenConvolutionForwardGetWorkSpaceSize cost: 0.065267 s
miopenFindConvolutionForwardAlgorithm cost: 8.04244 s

# second run
miopenConvolutionForwardGetWorkSpaceSize cost: 0.074937 s
miopenFindConvolutionForwardAlgorithm cost: 8.0638 s
```

And I install miopen by the yum repo install commands。

**Comment by qili93** [comment]
@atamazov LOG here:

(base) [root@j20r4n12 operators]# export MIOPEN_LOG_LEVEL=5
(base) [root@j20r4n12 operators]# export MIOPEN_ENABLE_LOGGING_CMD=1
(base) [root@j20r4n12 operators]# export MIOPEN_ENABLE_LOGGING_ELAPSED_TIME=1

```bash
[==========] Running 3 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 2 tests from test_conv2d_op
[ RUN      ] test_conv2d_op.cpu_place
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0129 12:59:52.953267 18347 conv_op_test.cc:93] Op(conv2d), inputs:{Filter[Filter:float[8, 3, 3, 3]({})(CPUPlace)], Input[Input:float[1, 3, 2, 2]({})(CPUPlace)]}, outputs:{Output[Output:[0]({})()]}.
I0129 12:59:52.962688 18347 conv_op_test.cc:99] Op(conv2d), inputs:{Filter[Filter:float[8, 3, 3, 3]({})(CPUPlace)], Input[Input:float[1, 3, 2, 2]({})(CPUPlace)]}, outputs:{Output[Output:float[1, 8, 1, 1]({})(CPUPlace)]}.
[       OK ] test_conv2d_op.cpu_place (146 ms)
[ RUN      ] test_conv2d_op.gpu_place
W0129 12:59:52.962774 18347 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 90.6, Driver API Version: 313.0, Runtime API Version: 3.3
W0129 12:59:53.982673 18347 device_context.cc:376] device: 0, MIOpen Version: 2.4.0
MIOpen(HIP)   0.001: Info [Handle] stream: 0, device_id: 0
I0129 12:59:54.449084 18347 conv_op_test.cc:93] Op(conv2d), inputs:{Filter[Filter:float[8, 3, 3, 3]({})(CUDAPlace(0))], Input[Input:float[1, 3, 2, 2]({})(CUDAPlace(0))]}, outputs:{Output[Output:[0]({})()]}.
MIOpen(HIP) 464.800: Info [Handle] stream: 0, device_id: 0
I0129 12:59:55.161859 18347 conv_op_test.cc:99] Op(conv2d), inputs:{Filter[Filter:float[8, 3, 3, 3]({})(CUDAPlace(0))], Input[Input:float[1, 3, 2, 2]({})(CUDAPlace(0))]}, outputs:{Output[Output:float[1, 8, 1, 1]({})(CUDAPlace(0))]}.
[       OK ] test_conv2d_op.gpu_place (2212 ms)
[----------] 2 tests from test_conv2d_op (2358 ms total)

[----------] 1 test from test_conv2d_cudnn_op
[ RUN      ] test_conv2d_cudnn_op.gpu_place
CUDNN version is: 240
MIOpen(HIP) 725.149: Info [Handle] stream: 0, device_id: 0
I0129 12:59:55.179939 18347 conv_op_test.cc:93] Op(conv2d), inputs:{Filter[Filter:float[8, 3, 3, 3]({})(CUDAPlace(0))], Input[Input:float[1, 3, 2, 2]({})(CUDAPlace(0))]}, outputs:{Output[Output:[0]({})()]}.
MIOpen(HIP)   5.469: Info [ForwardGetWorkSpaceSize]
MIOpen(HIP)  39.337: Info [HipGetHccVersionImpl] HCC base: 3.2.0
MIOpen(HIP)   0.041: Info [AmdRocmMetadataVersionDetect] ROCm MD version AMDHSA_COv2_COv3, MIOpen version 2.4.0.8035-rocm-rel-3.5-34-bd4a3307
I0129 12:59:55.260107 18347 conv_cudnn_helper.h:284] ==== miopenConvolutionForwardGetWorkSpaceSize cost: 0.080014 s
MIOpen(HIP)  40.726: Info [FindConvFwdAlgorithm] requestAlgoCount = 7, workspace = 108
MIOpen(HIP)   0.603: Info [TryLoad] Find-db regenerating.
MIOpen(HIP)   0.155: Info [KernDb] database not present
MIOpen(HIP)8055.199: Info [SetValues] 3-2-2-3x3-8-1-1-1-1x1-2x2-1x1-0-NCHW-FP32-F, content inserted: miopenConvolutionFwdAlgoGEMM:gemm,0.096905,108,rocBlas,<unused>
MIOpen(HIP)   0.134: Info [FindSolutionImpl] ConvBinWinogradRxSf2x3
MIOpen(HIP)   0.725: Info [FindSolutionImpl] Perf Db: record not found for: ConvBinWinogradRxSf2x3
MIOpen(HIP)   0.025: Info [GetPerformanceConfig] 1
MIOpen(HIP)   3.305: Info [EvaluateInvokers] ConvBinWinogradRxSf2x3: miopenSp3AsmConv_group_20_5_23_M_stride2: 0.036299 < 3.40282e+38
MIOpen(HIP)   0.033: Info [EvaluateInvokers] Selected: ConvBinWinogradRxSf2x3: miopenSp3AsmConv_group_20_5_23_M_stride2: 0.036299, workspce_sz = 0
MIOpen(HIP)   0.016: Info [SetValues] 3-2-2-3x3-8-1-1-1-1x1-2x2-1x1-0-NCHW-FP32-F, content inserted: miopenConvolutionFwdAlgoWinograd:ConvBinWinogradRxSf2x3,0.036299,0,miopenConvolutionFwdAlgoWinograd,<unused>
MIOpen(HIP)   0.056: Info [FindSolutionImpl] ConvOclDirectFwdGen (not searchable)
MIOpen(HIP)   0.113: Info [FindSolutionImpl] ConvOclDirectFwd
MIOpen(HIP)   0.521: Info [FindSolutionImpl] Perf Db: record not found for: ConvOclDirectFwd
MIOpen(HIP)   4.095: Info [EvaluateInvokers] ConvOclDirectFwdGen: MIOpenCDFGen: 0.019829 < 3.40282e+38
MIOpen(HIP)   0.098: Info [EvaluateInvokers] ConvOclDirectFwd: MIOpenConvUni: 0.019029 < 0.019829
MIOpen(HIP)   0.019: Info [EvaluateInvokers] Selected: ConvOclDirectFwd: MIOpenConvUni: 0.019029, workspce_sz = 0
MIOpen(HIP)   0.011: Info [SetValues] 3-2-2-3x3-8-1-1-1-1x1-2x2-1x1-0-NCHW-FP32-F, content inserted: miopenConvolutionFwdAlgoDirect:ConvOclDirectFwd,0.019029,0,miopenConvolutionFwdAlgoDirect,<unused>
MIOpen(HIP)  13.940: Info [FindConvFwdAlgorithm] miopenConvolutionFwdAlgoDirect	0.019029	0
MIOpen(HIP)   0.030: Info [FindConvFwdAlgorithm] miopenConvolutionFwdAlgoWinograd	0.036299	0
MIOpen(HIP)   0.007: Info [FindConvFwdAlgorithm] miopenConvolutionFwdAlgoGEMM	0.096905	108
MIOpen(HIP)   0.039: Info [FindConvFwdAlgorithm] FW Chosen Algorithm: ConvOclDirectFwd , 0, 0.019029
I0129 13:00:03.339351 18347 conv_cudnn_helper.h:302] ==== miopenFindConvolutionForwardAlgorithm cost: 8.07916 s
MIOpen(HIP)   0.071: Info [ForwardGetWorkSpaceSize]
MIOpen(HIP)   0.118: Command [LogCmdConvolution] ./bin/MIOpenDriver conv -n 1 -c 3 -H 2 -W 2 -k 8 -y 3 -x 3 -p 1 -q 1 -u 2 -v 2 -l 1 -j 1 -m conv -g 1 -F 1 -t 1
MIOpen(HIP)   0.015: Info [ConvolutionForward] algo = 1, workspace = 108
I0129 13:00:03.339727 18347 conv_op_test.cc:99] Op(conv2d), inputs:{Filter[Filter:float[8, 3, 3, 3]({})(CUDAPlace(0))], Input[Input:float[1, 3, 2, 2]({})(CUDAPlace(0))]}, outputs:{Output[Output:float[1, 8, 1, 1]({})(CUDAPlace(0))]}.
[       OK ] test_conv2d_cudnn_op.gpu_place (8167 ms)
[----------] 1 test from test_conv2d_cudnn_op (8167 ms total)

[----------] Global test environment tear-down
[==========] 3 tests from 2 test cases ran. (10525 ms total)
[  PASSED  ] 3 tests.
```

**Comment by atamazov** [comment]
> `Info [KernDb] database not present`

Binary cache seems non-functional in your system. Please check documentation, https://github.com/ROCmSoftwarePlatform/MIOpen/blob/develop/doc/src/cache.md

Also please send me the MIOpen's cmake command line.

> `MIOpen version 2.4.0`

I highly recommend updating to the latest release of MIOpen. We maintain backward compatibility with older ROCm versions, so it should work.

[FYI] If log is very long, please _attach_ it. Github is able to attach text files to comments.

**Comment by atamazov** [comment]
I've tested your smallest config on my system with recent MIOpen and ROCm 4.0 and found even in the best case the overhead is ~1500ms which is ridiculous. Further investigation shows that almost all this time is spent in the `hipMemsetAsync()` HIP runtime call, invoked from MIOpen's `dummy_memset()`. This happens during execution of GEMM algorithm. With `MIOPEN_DEBUG_CONV_GEMM=0`, the library's overhead is ~8ms.

Most likely this should be addressed to the GEMM algorithm developers and/or to the HIP runtime team.

## Logs (binary cache enabled):
- Logs at level 6 with timestamps
  - [overhead-01.txt](https://github.com/ROCmSoftwarePlatform/MIOpen/files/5894265/overhead-01.txt) - 1st run, compilations
  - [overhead-02.txt](https://github.com/ROCmSoftwarePlatform/MIOpen/files/5894266/overhead-02.txt) - 2nd run, kernels read from binary cache
  - [overhead-03.txt](https://github.com/ROCmSoftwarePlatform/MIOpen/files/5894267/overhead-03.txt) - 3rd run
- Logs at level 6, no timestamps, good for diffing
  - [overhead-notime-01.txt](https://github.com/ROCmSoftwarePlatform/MIOpen/files/5894268/overhead-notime-01.txt)
  - [overhead-notime-02.txt](https://github.com/ROCmSoftwarePlatform/MIOpen/files/5894270/overhead-notime-02.txt)
  - [overhead-notime-03.txt](https://github.com/ROCmSoftwarePlatform/MIOpen/files/5894271/overhead-notime-03.txt)
  - [overhead-notime-02-nogemm.txt](https://github.com/ROCmSoftwarePlatform/MIOpen/files/5894273/overhead-notime-02-nogemm.txt) - with GEMM disabled

## Example MIOpenDriver command:
```bash
MIOPEN_ENABLE_LOGGING_ELAPSED_TIME=1 \
MIOPEN_LOG_LEVEL=6 \
./bin/MIOpenDriver conv -n 1 -c 3 -H 2 -W 2 -k 8 -x 3 -y 3 -p 1 -q 1 -u 2 -v 2 -V 0 -w 2 -t 1 -i 2 -F 1 \
2>&1 | tee ~/mio/overhead-01.txt
```

**Comment by atamazov** [comment]
Questions:
- Is it possible to avoid `hipMemsetAsync()` and use some kernel for that?
- Is it possible to improve performance of `hipMemsetAsync()`

**Comment by atamazov** [comment]
The performance loss is so huge that I am assigning the `bug` label.

**Comment by atamazov** [comment]
@qili93 Recommendations for you:
- Upgrade to the recent MIOpen release
- Make sure that binary cache is working
- Use the Hybrid Find mode (this is the default in the recent MIOpen). After the 1st run, it spends time for the fastest algorithm only, so it would completely avoid GEMM when it is not the fastest. I am getting ___host time overhead ~50 ms___ with these settings.

**Comment by qili93** [comment]
Thank you @atamazov so much for your help :)

I will follow your suggestions and try to upgrade to the latest version of ROCM.

**Comment by qili93** [comment]
> > `Info [KernDb] database not present`
> 
> Binary cache seems non-functional in your system. Please check documentation, https://github.com/ROCmSoftwarePlatform/MIOpen/blob/develop/doc/src/cache.md
> 
> Also please send me the MIOpen's cmake command line.
> 
> > `MIOpen version 2.4.0`
> 
> I highly recommend updating to the latest release of MIOpen. We maintain backward compatibility with older ROCm versions, so it should work.
> 
> [FYI] If log is very long, please _attach_ it. Github is able to attach text files to comments.

I did not compile MIOpen from source, but installed it by the following command lines in dockerfile:

```bash
# ROCM
ARG ROCM_VERSION
RUN yum install -y kmod wget openblas-devel epel-release
RUN echo "[ROCm]" > /etc/yum.repos.d/rocm.repo && \
    echo "name=ROCm" >> /etc/yum.repos.d/rocm.repo && \
    echo "baseurl=http://repo.radeon.com/rocm/yum/${ROCM_VERSION}" >> /etc/yum.repos.d/rocm.repo && \
    echo "enabled=1" >> /etc/yum.repos.d/rocm.repo && \
    echo "gpgcheck=0" >> /etc/yum.repos.d/rocm.repo
RUN yum install -y rocm-dev rocm-utils rocfft miopen-hip rocblas hipsparse rocrand rccl hipcub rocthrust rocprofiler-dev roctracer-dev
```

**Comment by atamazov** [comment]
Please let us know if upgrading to the recent ROCm helps.

**Comment by qili93** [comment]
Hi @atamazov 

After upgrading to ROCM 3.9.1 and the performance got much better. It only tasks about 75ms for small input. Thanks so much for your help :)

**Comment by atamazov** [comment]
Good!
