### ISSUE TITLE
Implicit gemm solvers fail Jenkins in some cases.

### ISSUE THREAD

**Issue by DrizztDoUrden** [ROCmSoftwarePlatform/MIOpen#719]
On MI100 with HIP and
`-DMIOPEN_TEST_BFLOAT16=On -DMIOPEN_TEST_GFX908=On -DMIOPEN_TEST_ALL=On -DBUILD_DEV=On -DMIOPEN_GPU_SYNC=On`
the command line 
`bin/test_immed_conv2d --bfloat16 --cmode conv --pmode default --group-count 1 --enable-fdb 0 --input 1, 3, 224, 224 --weights 1, 3, 7, 7 --pads_strides_dilations 0 0 1 1 1 1 --trans_output_pads 0 0`
and many other test_immed_conv2d cases produse log like these:
```
MIOpen(HIP): Info [GetForwardSolutions]
MIOpen(HIP): Info [EuristicInit] 16,64,4,16,16,8,16,64,16,0,1,8
MIOpen(HIP): Info [BackwardWeightsGetWorkSpaceSize]
MIOpen(HIP): Info [GetWrwSolutions]
MIOpen(HIP): Info [EuristicInit] All attempts failed
MIOpen(HIP): Info [EuristicInit] 256,256,8,128,128,8,0,1
MIOpen(HIP): Info [EuristicInit] 16,64,4,16,16,4,16,64,16,0,1
MIOpen(HIP): Info [GetForwardSolutionCount]
```
That causes CTest to find a `failed` line and mark the whole test as failed.
https://github.com/ROCmSoftwarePlatform/MIOpen/pull/709 resolves Jenkins failures, but I don't know if the whole situation causing the message is OK.

This fails Jenkins in the gemm invokers branch (PR #473), and I have reproduced it in `develop` 98fb10e69bbe463f34f36ea9af9da6a372a2d02a.

**Comment by atamazov** [comment]
#709 resolves the immediate CI problem by changing "failed" with "unsuccessful". However it seems worth double-checking if this is expected behavior for ImplicitGemm solvers.

**Comment by atamazov** [comment]
@DrizztDoUrden 
> I have reproduced it in both gemm branch and develop as described above...

What is git hash of develop?

**Comment by DrizztDoUrden** [comment]
Updated header

**Comment by atamazov** [comment]
via #709

**Comment by atamazov** [comment]
via #709
