### ISSUE TITLE
Invalid Work Group Size for Incorrect `local_work_dim` Value

### ISSUE THREAD

**Issue by ghostplant** [ROCmSoftwarePlatform/MIOpen#74]
While the MiOpen-opencl program is calling:
```sh
   miopenActivationForward(handle, activate, &alpha, tDesc, data_in, &beta, tDesc, data_out);
```
I got an error: `Running kernel failed:  Invalid Work Group Size`.

By enabling debugging log I saw the global_work_dim = { 1, 1, 1 } is smaller than local_work_dim = { 256, 1, 1 },
which could be found in the logs below.

```sh
CL_DEVICE_MAX_WORK_GROUP_SIZE: 1024
MIOpen(OpenCL): Info2 [GetKernels] 0 kernels for key: miopenActivationForward "1113111"
MIOpen(OpenCL): Info2 [AddKernel] Key: miopenActivationForward "1113111"
MIOpen(OpenCL): Info2 [AddKernelDumpKernelParams] runcl MIOpenNeuron.cl -k MIOpenActiveFwdLite -dumpilisa -r 10 if#0: if#0: if#0: iv#0 1,1,1/256,1,1  -DLITE -DMIOPEN_READ_UNIT=1 -DMIOPEN_READ_TYPE=_FLOAT -DMIOPEN_NRN_OP_ID=3 -DMIOPEN_USE_FP16=0 -DMIOPEN_USE_FP32=1
MIOpen(OpenCL): Info [Invoke] MIOpenActiveFwdLite
MIOpen(OpenCL): Info2 [run] kernel_name = MIOpenActiveFwdLite, work_dim = 3, global_work_offset = { 0, 0, 0 }, global_work_dim = { 1, 1, 1 }, local_work_dim = { 256, 1, 1 }
MIOpen Error: /home/admin/Desktop/MIOpen-master/src/ocl_kernel.cpp:81: Running kernel failed:  Invalid Work Group Size
```

If I modify the source code to change the value of global_work_dim to { 256, 1, 1 }, the program would finish correctly:
```sh
...
MIOpen(OpenCL): Info [Invoke] MIOpenActiveFwdLite
MIOpen(OpenCL): Info2 [run] kernel_name = MIOpenActiveFwdLite, work_dim = 3, global_work_offset = { 0, 0, 0 }, global_work_dim = { 256, 1, 1 }, local_work_dim = { 256, 1, 1 }
Result Output = 1.000000 -0.000000 3.000000 -0.000000 (Correct)
```

So why global_work_dim would be {1, 1, 1} which is smaller than local_work_dim, is the meaning of `global_work_dim` and `local_work_dim` in AMD GPU different with standard OpenCL definition?

**Comment by ghostplant** [comment]
I think the reasonable work group configuration in OpenCL should be either:
`global_work_dim = { 256, 1, 1 }, local_work_dim = { 256, 1, 1 }`
or
`global_work_dim = { 256, 1, 1 }, local_work_dim = { 1, 1, 1 }`

and I don't think `global_work_dim = { 1, 1, 1 }, local_work_dim = { 256, 1, 1 }` is correct.

**Comment by atamazov** [comment]
We need to know how to reproduce this. Please give us a suitable MIOpenDriver command line OR attach the console log obtained with `MIOPEN_ENABLE_LOGGING=1` and `MIOPEN_LOG_LEVEL=6` set in the environment. Thanks,

**Comment by ghostplant** [comment]
The single-file source code is:
```sh
#include <stdio.h>
#include <assert.h>
#include <miopen/miopen.h>

int main() {
    miopenHandle_t handle;
    miopenAcceleratorQueue_t stream;
    assert(0 == (int)miopenCreate(&handle));
    assert(0 == (int)miopenGetStream(handle, &stream));

    cl_context ctx;
    clGetCommandQueueInfo(stream, CL_QUEUE_CONTEXT, sizeof(cl_context), &ctx, nullptr);

    cl_device_id device_id;
    clGetCommandQueueInfo(stream, CL_QUEUE_DEVICE, sizeof(cl_device_id), &device_id, nullptr);
    size_t maxWorkItemPerGroup;
    clGetDeviceInfo(device_id, CL_DEVICE_MAX_WORK_GROUP_SIZE, sizeof(maxWorkItemPerGroup), &maxWorkItemPerGroup, NULL);

    const int W = 4;
    float in[W] = {}, out[W] = {};
    for (int i = 0; i < W; ++i) {
        in[i] = i;
        if ((i & 1) == 0)
            in[i] = -in[i];
    }

    cl_mem data_in = clCreateBuffer(ctx, CL_MEM_READ_WRITE, sizeof(in), nullptr, nullptr);
    cl_mem data_out = clCreateBuffer(ctx, CL_MEM_READ_WRITE, sizeof(out), nullptr, nullptr);
    clEnqueueWriteBuffer(stream, data_in, CL_TRUE, 0, sizeof(in), in, 0, nullptr, nullptr);

    miopenActivationDescriptor_t activate;
    assert(0 == (int)miopenCreateActivationDescriptor(&activate));
    assert(0 == (int)miopenSetActivationDescriptor(activate, miopenActivationRELU, 0, 0, 0));
    miopenTensorDescriptor_t tDesc;
    assert(0 == (int)miopenCreateTensorDescriptor(&tDesc));
    assert(0 == (int)miopenSet4dTensorDescriptor(tDesc, miopenFloat, W, 1, 1, 1));

    float alpha = 1.0f, beta = 0.0f;
    assert(0 == (int)miopenActivationForward(handle, activate, &alpha, tDesc, data_in, &beta, tDesc, data_out));

    clEnqueueReadBuffer(stream, data_out, CL_TRUE, 0, sizeof(out), out, 0, nullptr, nullptr);
    for (int i = 0; i < W; ++i)
        printf("%g ", out[i]);
    puts("");
    return 0;
}
```

The MIOpen version is build from current latest master branch.

The program output is:
```sh
Device Name: Oclgrind Simulator
CL_DEVICE_MAX_WORK_GROUP_SIZE: 1024
MIOpen(OpenCL): Info2 [GetKernels] 0 kernels for key: miopenActivationForward "1113411"
MIOpen(OpenCL): Info2 [AddKernel] Key: miopenActivationForward "1113411"
MIOpen(OpenCL): Info2 [AddKernelDumpKernelParams] runcl MIOpenNeuron.cl -k MIOpenActiveFwdLite -dumpilisa -r 10 if#0: if#0: if#0: iv#0 1,1,1/256,1,1  -DLITE -DMIOPEN_READ_UNIT=4 -DMIOPEN_READ_TYPE=_FLOAT4 -DMIOPEN_NRN_OP_ID=3 -DMIOPEN_USE_FP16=0 -DMIOPEN_USE_FP32=1
MIOpen(OpenCL): Info [Invoke] MIOpenActiveFwdLite
MIOpen(OpenCL): Info2 [run] kernel_name = MIOpenActiveFwdLite, work_dim = 3, global_work_offset = { 0, 0, 0 }, global_work_dim = { 1, 1, 1 }, local_work_dim = { 256, 1, 1 }
MIOpen Error: /home/admin/Desktop/MIOpen-master/src/ocl_kernel.cpp:81: Running kernel failed:  Invalid Work Group Size
a.out: main.cc:40: int main(): Assertion `0 == (int)miopenActivationForward(handle, activate, &alpha, tDesc, data_in, &beta, tDesc, data_out)' failed.
```

I think the expected local_dims should be { 1, 1, 1 }.

**Comment by asroy** [comment]
@ghostplant Could you run following from command line and post the output? It uses MIOpenDriver to run the config that you are seeing the failure. I ran it but didn't see the failure you are seeing.

```/PATH/TO/MIOPEN/bin/MIOpenDriver activ -n 4 -c 1 -H 1 -W 1```

**Comment by pfultz2** [comment]
You have to do `make MIOpenDriver` to build the driver.

**Comment by ghostplant** [comment]
```sh
github/MIOpen/build/bin$ oclgrind ./MIOpenDriver activ -n 4 -c 1 -H 1 -W 1
MIOpenDriver: activ -n 4 -c 1 -H 1 -W 1
Device Name: Oclgrind Simulator
MIOpen(OpenCL): Info [Invoke] MIOpenActiveFwdLite
MIOpen Error: /home/admin/Desktop/github/MIOpen/src/ocl_kernel.cpp:81: Running kernel failed:  Invalid Work Group Size
Difference in neuron layer: 1.36075 too large at 0 x = 1.36075  c_v = 1.36075 vs g_val = 0 tolerance = 9.53674e-06
MIOpen(OpenCL): Info [Invoke] MIOpenActiveBwdLite
MIOpen Error: /home/admin/Desktop/github/MIOpen/src/ocl_kernel.cpp:81: Running kernel failed:  Invalid Work Group Size
Difference in neuron back-propagation: 0.411647 too large at 0 dy = 0.411647 x = 1.36075 y = 0  c_v = 0.411647 vs g_val = 0 tolerance = 9.53674e-06
```

**Comment by asroy** [comment]
@ghostplant Which GPU are you using? Can you do ``` /opt/rocm/opencl/bin/x86_64/clinfo ``` and post the output?

**Comment by ghostplant** [comment]
@asroy Hi, I am using both standard OpenCL simulator and NVIDIA OpenCL interfaces, not AMD OpenCL interfaces. I found that both of the former interfaces failed to execute MIOpen-opencl for same reason as has been described above - a wrong calculation of LocalWorkDim.

So it seems MIOpen calculates the value of LocalWorkDim using some native AMD devices properties which makes standard OpenCL platform generate wrong LocalWorkDim value in non AMD devices, is it true?

**Comment by pfultz2** [comment]
> So it seems MIOpen calculates the value of LocalWorkDim using some native AMD device properties which makes standard OpenCL platform generate wrong LocalWorkDim value in non AMD devices, is it true?

No. In OpenCL 2.0, the local workitems does not need to be multiple of the global workitems, and we did not pass in the `-cl-uniform-work-group-size` flag to enforce uniform work group sizes, either. From [`clEnqueueNDRangeKernel`](https://www.khronos.org/registry/OpenCL/sdk/2.0/docs/man/xhtml/clEnqueueNDRangeKernel.html) documentation:

> CL_INVALID_WORK_GROUP_SIZE if the program was compiled with –cl-uniform-work-group-size and the number of work-items specified by global_work_size is not evenly divisible by size of work-group given by local_work_size.

**Comment by ghostplant** [comment]
@pfultz2 I think it would be better if it is well compatible with OpenCL 1.2 which would be more useful and friendly.

**Comment by daniellowell** [comment]
Please reopen if you would need further assistance.
