### ISSUE TITLE
Update OS and ROCm on CI nodes

### ISSUE THREAD

**Issue by JehandadKhan** [ROCmSoftwarePlatform/MIOpen#745]
Once PR #738  is merged we can update the OS and ROCm version on our CI nodes.

The blocking issue is that MIOpen Jenkinsfile as well as the Dockerfile depend on `hcc` which does not exist in newer versions of ROCm.

**Comment by JehandadKhan** [comment]
@pfultz2  Can you comment on this, since MIGraphX shares some of these nodes ?

**Comment by atamazov** [comment]
[Side note] The DKMS driver (even 5.6.0 in ROCm 4.0) still has issues that prevent HIP & OCL runtime correctly report SRAMECC state. QA are using DKMS driver (version > 5.9) from the mainline. I do not know is it safe to upgrade our CI to it.

```bash
# rocm-smi --showdriverversion
...
========================= Version of System Component ==========================
Driver version: 5.6.0
```

**Comment by pfultz2** [comment]
> Can you comment on this, since MIGraphX shares some of these nodes ?

MIGraphX uses a specific version of rocm in the docker so its not an issue to upgrade the nodes.

When MIOpen updates the jenkinsfile then I can install either rocm 3.7 or 4.1 on the CI nodes. We can see how it works and if there is an issue I can roll it back.
