### ISSUE TITLE
Logging when kernel is added to kcache

### ISSUE THREAD

**Issue by atamazov** [ROCmSoftwarePlatform/MIOpen#747]
`AddKernelDumpKernelParams()` has been removed in #674, see https://github.com/ROCmSoftwarePlatform/MIOpen/pull/674/files#r579298182. However we still need some logging of global/local work sizes, kernel name etc (at level 6), because this information may be important for triaging issues.

/cc @JehandadKhan @DrizztDoUrden @ce1adon

**Comment by DrizztDoUrden** [comment]
Right now, most kernels are not added to kcache, only built through it. They are only stored in the invoker.

**Comment by atamazov** [comment]
It looks like this feature it's not needed.
