### ISSUE TITLE
[Reduction] Follow-ups of of #727

### ISSUE THREAD

**Issue by atamazov** [ROCmSoftwarePlatform/MIOpen#757]
Follow-up of #727

## Testing and minor coding style issue

Resolve https://github.com/ROCmSoftwarePlatform/MIOpen/pull/727#pullrequestreview-602895628

## NORM1/2 question

From https://github.com/ROCmSoftwarePlatform/MIOpen/pull/727#issuecomment-790251637:

@fronteer 
> Another thing about NORM1 and NORM2 should be said that:
> 
>     * For NORM1, our calculation is as  `Sum(abs(X0), abs(X1) ... abs(Xn)) / n`
> 
>     * For NORM2, our calculation is as  `sqrt( Sum(square(X0), square(X1), ... square(Xn)) / n )`
> 
> But from the document of cudnnTensorReduce() API, I could not know whether **dividing by n** is included in their implementation. So, should we some how shows the users how our implementation exactly is ?

----
<details><summary><b><i>Original description</i></b></summary><hr>

ROCm 4.0, gfx906: test_reduce_test fails with NORM1 and NORM2 operation types. Operatons disabled.

Logs of testing of commits 293bf7482 (tip of this branch) and 178a35d44 (just prior massive review related changes) are identical. Attached below.
- [test_reduce_test.release.hip-clang.178a35d44.console.txt](https://github.com/ROCmSoftwarePlatform/MIOpen/files/6050284/test_reduce_test.release.hip-clang.178a35d44.console.txt)
- [test_reduce_test.release.hip-clang.178a35d44.txt](https://github.com/ROCmSoftwarePlatform/MIOpen/files/6050287/test_reduce_test.release.hip-clang.178a35d44.txt)
- [test_reduce_test.release.hip-clang.293bf7482.console.txt](https://github.com/ROCmSoftwarePlatform/MIOpen/files/6050288/test_reduce_test.release.hip-clang.293bf7482.console.txt)
- [test_reduce_test.release.hip-clang.293bf7482.txt](https://github.com/ROCmSoftwarePlatform/MIOpen/files/6050289/test_reduce_test.release.hip-clang.293bf7482.txt)

_Originally posted by @atamazov in https://github.com/ROCmSoftwarePlatform/MIOpen/issues/727#issuecomment-786689932_
<hr></details>

**Comment by atamazov** [comment]
Blocker for 4.3

**Comment by atamazov** [comment]
See also https://github.com/ROCmSoftwarePlatform/MIOpen/pull/727#issuecomment-787062727 and below

**Comment by fronteer** [comment]
For solving this issue, should I submit new P.R or continue to work on [#727](https://github.com/ROCmSoftwarePlatform/MIOpen/pull/727#issuecomment-787062727) ?

**Comment by atamazov** [comment]
Description updated.

**Comment by atamazov** [comment]
Description updated.

**Comment by atamazov** [comment]
@fronteer 
> Another thing about NORM1 and NORM2 ...
> But from the document of cudnnTensorReduce() API, I could not know whether **dividing by n** is included in their implementation. So, should we some how shows the users how our implementation exactly is ?

I think we shall follow the commonly adopted implementation.

**Comment by fronteer** [comment]
> @fronteer
> 
> > Another thing about NORM1 and NORM2 ...
> > But from the document of cudnnTensorReduce() API, I could not know whether **dividing by n** is included in their implementation. So, should we some how shows the users how our implementation exactly is ?
> 
> I think we shall follow the commonly adopted implementation.

Which one is the commonly adopted implementation?  Our implementation is consistent with the mathematical concept of NORM1 and NORM2. But the comments from cudnn API document is really confusing.

**Comment by atamazov** [comment]
> Which one is the commonly adopted implementation? 

Without division.

Closed via #774
