### ISSUE TITLE
Infinite loops of conv kernel compilation

### ISSUE THREAD

**Issue by syoyo** [ROCmSoftwarePlatform/MIOpen#76]
# How to reproduce

Follow #72 and apply patch to avoid assertion.

It looks MIOpen goes info infinite loop for searching conv kernel.

Attached is a log with logging enabled(up to roughly 10 mins log).

[miopen-infinite-loop-issue.txt](https://github.com/ROCmSoftwarePlatform/MIOpen/files/2767203/miopen-infinite-loop-issue.txt)

**Comment by atamazov** [comment]
There is no need of applying patch from #72 to avoid assertion; just use Release build.

**Comment by atamazov** [comment]
@syoyo Unfortunately I am unable to see loop in the log attached. Neither can't derive the problematic config from the log. Could you please attach log obtained with MIOPEN_ENABLE_LOGGING=1 and MIOPEN_LOG_LEVEL=6 (or 5).

I suspect there is a Tachotron or ROCm's OpenCL compiler issue.

**Comment by syoyo** [comment]
> I suspect there is a Tacotron or ROCm's OpenCL compiler issue.

@atamazov Thank you for looking at log file. So it looks like the issue is not in MIOpen but in ROCm or other upper layer. I'll try to narrow down this issue and post it appropriate place.
