### ISSUE TITLE
Test_mdgraph fails on gfx1030 due to unsupported fused kernels

### ISSUE THREAD

**Issue by zjing14** [ROCmSoftwarePlatform/MIOpen#763]
- test_mdgraph fails with unsupported fused kernels for gfx1030 - miopenConvolutionWinogradBiasActiv and miopenConvolutionDirectBiasActivAsm

```
./bin/test_mdgraph --all
FAILED: krn_name == "miopenSp3AsmConvRxSU_CBA": /dockerx/MIOpen/test/mdgraph.cpp: 118
Aborted (core dumped)
```

**Comment by atamazov** [comment]
@zjing14 Well, I would generalize the description of the issue. `test_mdgraph` is a unit test that should be aware of the implementation. Specifically, it must "know" which fused algorithms _and_ kernel names are supported on which GPUs. And that knowledge should be used in the test to avoid testing of unsupported algorithms/kernels. Do you agree?

**Comment by zjing14** [comment]
@atamazov But the logic of test_mdgraph is to make sure fused algorithms supported on all GPUs.

**Comment by zjing14** [comment]
@atamazov Let us refactor the test_mdgraph as you suggested in a separate PR.

**Comment by atamazov** [comment]
Test refactored in #813
