### ISSUE TITLE
MIOpen for HIP fail to pass rnn & gemm tests

### ISSUE THREAD

**Issue by ghostplant** [ROCmSoftwarePlatform/MIOpen#78]
Hi,

I am using AMD Vega GPU, and logs below are generated by MIOpenDriver which pass CNN layers like conv/pool but only fail to pass rnn and gemm testcases.

```sh
[root@ubuntu:~/rocm_src/MIOpen/build/bin#] ./MIOpenDriver bnorm
MIOpenDriver: bnorm
Forward batch norm verification passed on output
Forward Batch Norm Verifies on CPU and GPU.

[~/rocm_src/MIOpen/build/bin#] ./MIOpenDriver gemm
MIOpenDriver: gemm
terminate called after throwing an instance of 'miopen::Exception'
  what():  /root/rocm_src/MIOpen/src/gemm_v2.cpp:278: rocBlas error encountered
Aborted (core dumped)

[root@ubuntu:~/rocm_src/MIOpen/build/bin#] ./MIOpenDriver rnn
MIOpenDriver: rnn
MIOpen Error: /root/rocm_src/MIOpen/src/gemm_v2.cpp:278: rocBlas error encountered
verify rnn fwd
Forward RNN Failed: 0.386381
final hidden state Failed: 0.386381
MIOpen Error: /root/rocm_src/MIOpen/src/gemm_v2.cpp:278: rocBlas error encountered
MIOpen Error: /root/rocm_src/MIOpen/src/gemm_v2.cpp:278: rocBlas error encountered
verify rnn bwddata
Backward RNN Data Failed: 0.370053
difference at inital hidden state Failed: 0.46384
verify rnn bwdwei
Backward RNN Weights Failed: 0.515348
```

The OS doesn't have MIOpen_gemm installed and the error above failed at this line:
`rb_status        = rocblas_gemm_ex( .. )`
and I got  `rb_status = rocblas_status_internal_error` when calling `rocblas_gemm_ex`.

**Comment by daniellowell** [comment]
@ghostplant Is there a reason you cannot install MIOpenGEMM on your system? What version of rocBLAS is installed?

**Comment by ghostplant** [comment]
@daniellowell If I install MIOpenGEMM on my system and rebuild MIOpen, such cases will pass, but if it is not installed, the above cases will fail, and the rocBlas is compiled from the current latest master branch.

**Comment by ghostplant** [comment]
Considering MIOpenGEMM can make these cases pass and solve my problem, I just close this PR since then. Thanks! @daniellowell

**Comment by daniellowell** [comment]
Ok, thanks for your input, these issues help us improve our library.
