### ISSUE TITLE
[Driver] Invalid base input argument while input "--help" in MIOpenDriver

### ISSUE THREAD

**Issue by zpwenjh** [ROCmSoftwarePlatform/MIOpen#781]
```
$ ./bin/MIOpenDriver --help                                                                                                                                                                                         
Invalid Base Input Argument
Usage: ./driver *base_arg* *other_args*
Supported Base Arguments: conv[fp16|int8|bfp16], CBAInfer[fp16], pool[fp16], lrn[fp16], activ[fp16], softmax[fp16], bnorm[fp16], rnn[fp16], gemm, ctc, dropout[fp16], tensorop[fp16], reduce[fp16]
```
The argument "--help" is "Invalid Base Input Argument". But it should be recognized logically. The ParseBaseArg function has some problems.
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/b7630f76dad1926e224a23d5e470e44987d84fc3/driver/driver.hpp#L137-L162

**Comment by atamazov** [comment]
This is intentional. The list of supported options ("help") depends on the "base argument". For example, pooling and convolutions have substantially different options.

I recommend closing this.

**Comment by zpwenjh** [comment]
@atamazov I've learned that, thank you.
