### ISSUE TITLE
Proposal: Override the launch parameter from kernels built by mlir

### ISSUE THREAD

**Issue by jerryyin** [ROCmSoftwarePlatform/MIOpen#803]
## Background: MLIR Build

We added MLIR to be a new backend for kernel compilations. When a solver populates a kernel file that end with `mlir-cpp`, hipoc_program will choose the MLIR backend to build the kernel. Then the hipoc_program will be used similarly as built with any other backend. So far, this has been proven working well with MLIR built kernels.

https://github.com/ROCmSoftwarePlatform/MIOpen/blob/3917634a62dd06a86868303b48b15e853efffc38/src/hipoc/hipoc_program.cpp#L253-L258

## Issue Statement

There is a mismatch between launching parameters of an MLIR kernel versus a regular MIOpen kernel. Let's suppose that we disable perfdb for the below argument. 

When a regular MIOpen solver does not find the problem config in perfdb, it went through `EuristicInit()` to regress on an array of performance config, until finding the coherent set of parameters. In finding the coherent set of performance config, launching parameters are decided as well. The launching parameters decided by solver are later used to launch the kernel.

However, the `EuristicInit()` process is not necessary for MLIR kernels. Instead, MLIR backend is capable of making its own decisions in compiling its kernels. In its process, it also decide on a coherent set of parameters including the launch parameters.

Refer to the following for how MIOpen side of MLIR solver decide launch parameters:
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/3917634a62dd06a86868303b48b15e853efffc38/src/solver/conv_hip_implicit_gemm_mlir_cpp_fwd.cpp#L70-L76

Since both the MLIR solver and the MLIR backed try to compute the launching parameters at the same time, there is a likelihood such that the decision made by MIOpen side of MLIR solver, and the MLIR backend are different. It becomes a problem when the launching parameters does become different, ranging from wrong values or GPU VM fault.

In the short term, we prevent this from happening by synchronizing the source code of `EuristicInit` between MLIR and MIOpen, such that both components make the same decisions. However, this source level dependency should be deprecated because of code coupling in the two independent software components:

- Changing one end of logic becomes impossible because the other end is dependent on it
- We do unnecessary computation in MIOpen end to make sure it derive the same launching parameters. The most of computation are wasted on calculation of checking if the performance config are coherent, rather than computing launch parameters.

## Solution

To solve this problem, we need to stop making MIOpen MLIR solvers to do EuristicInit(), or calculating the launch parameters. The robust way to address this is such that MIOpen use the launch parameters from MLIR instead of try to build those locally.

### MLIR API: miirGetExecutionDims

In preparing for solving this solution, we come up with a new MLIR API:

https://github.com/ROCmSoftwarePlatform/llvm-project-mlir/blob/afd99d48dd587565f20cd68e2d5534d5d5571db4/mlir/tools/mlir-miopen-lib/Miir.h#L76-L83

```cpp
/*! @brief Get the global and local size for Dispatch
 *  @param handle MLIR handle
 *  @param global_size Pointer to global size storage (1 dimension)
 *  @param local_size Pointer to local size storage (1 dimension)
 */
extern "C" MiirStatus miirGetExecutionDims(MiirHandle handle,
                                           size_t *global_size,
                                           size_t *local_size);
```

The problem of using this API is such that `global_size` and `local_size` are only available after the binary lowering is completely done, in other words, after mlir builds are finished. This creates a distinct problem because all non-MLIR solver are able to come up with launch parameters at `pre-build` time, in solvers. Whereas MLIR solver can only know the launch parameters in `post-build` time.

### Override the launch parameters from hipoc_program

A natural solution is to follow the MLIR build flow, and store the launch parameters of `vld` and `gld` as `boost::optional`. Then, at the time we are about to populate the kernel into the kernel_cache, we override a kernel's `vld/gld` with the values from `hipoc_program`, if the two optional data members exist.

https://github.com/ROCmSoftwarePlatform/MIOpen/blob/3917634a62dd06a86868303b48b15e853efffc38/src/kernel_cache.cpp#L132-L144

Instead, this becomes:

```cpp
    Kernel kernel{};
    const char* const arch = miopen::GetStringEnv(MIOPEN_DEVICE_ARCH{});
    if(arch != nullptr && strlen(arch) > 0)
    {
        kernel = Kernel{program, kernel_name};
    }
    else if ((program.vld) && (program.gld))
    {
        kernel = Kernel{program, kernel_name, program.vld.get(), program.gld.get()};
    }
    else {
        kernel = Kernel{program, kernel_name, vld, vgd};
    }
```
With this, MIOpen end is guaranteed to launch a kernel with correct `vld` and `gld` from the build process of MLIR kernels, rather than from the MLIR solvers. On the other hand, MLIR solvers logic can be largely minimized to just preparing the compilation parameters of MLIR, and not worry about anything else.

### Alternatives

Below I listed several sub-optimal solutions from my perspective:

#### Alternative 1: Make MLIR solver to comply and populate launch parameters

The idea is straightforward: If MLIR solver is able to populate the launch parameters, then there's no need to make additional changes in hipoc_program or kernel_cache. 

The problem with this approach is that solvers are strictly pre-build stage component. It is not aware of anything happens in or after a build. There is no way to find back the solver once the program finished build. Since the MLIR launch parameter is only available after build is done, this solution is not viable unless more significant changes in MIOpen is done, such that build time constructs also keep track of solver information.

#### Alternative 2: Create a specialized `mlir_program` instead of reusing `hipoc_program`

The idea is such that instead of creating two optional data member `vld/gld` in hipoc_program, I create a `mlir_program` who hold two non-optional data member and is responsible of invoking `MlirBuildViaHip()`.

https://github.com/ROCmSoftwarePlatform/MIOpen/blob/3917634a62dd06a86868303b48b15e853efffc38/src/hip/handlehip.cpp#L412-L413

Becomes:

```cpp
        HIPOCProgram *p;
        if(miopen::EndsWith(program_name, ".mlir-cpp"))
        {
            MLIRProgram program = MLIRProgram{
            program_name, params, is_kernel_str, this->GetTargetProperties(), kernel_src};
            p = &program;
        }
        else 
        {
            HIPOCProgram program = HIPOCProgram{
            program_name, params, is_kernel_str, this->GetTargetProperties(), kernel_src};
            p = &program;
        }
        ...
        return p;
```

Then in kernel cache, try a dynamic cast to MLIRProgram. If it succeed, grab the `vld/gld` member and override.

This approach can be an overall cleaner approach than proposed solution. However, I put this as alternative solution due to the following reasons:
 - I don't see `dynamic_cast` being used much throughout MIOpen repository. 
 - Much larger amount of code changes: 
   - At every instance of `LoadProgram`, we make it return a pointer instead of the object.
   - Have to mostly duplicate HIPOCProgram to create a MLIRProgram.

## Summary

This issue proposed a solution to decouple MLIR backend from MIOpen solver, making both program more robust. Please let me know what your thoughts are. Once we arrive at the same page, I will make the changes mentioned here in a new PR.

**Comment by whchung** [comment]
really, can we fix the typo of `EuristicInit`?

**Comment by jerryyin** [comment]
@whchung I want to get rid of it as bad as you do. But this `EuristicInit()` has been practically all over the place in solver.hpp, [here](https://github.com/ROCmSoftwarePlatform/MIOpen/blob/3917634a62dd06a86868303b48b15e853efffc38/src/include/miopen/solver.hpp). I was afraid of changing it in my documentation to `HeuristicInit()` will make reader don't follow what function it is.

**Comment by pfultz2** [comment]
> A natural solution is to follow the MLIR build flow, and store the launch parameters of vld and gld as boost::optional. 

It doesn't need to be stored as `boost::optional`. If the vectors are empty we can ignore them.

I like this approach, the only catch is that we need to update both the opencl and hip program to have this field(otherwise it wont compile on the opencl backend).

I suggest this is done through methods rather than exposing a field directly. This way OCLKernel doesn't need to store launch parameters is can just return an empty vector.

**Comment by jerryyin** [comment]
@pfultz2 Thanks!

> It doesn't need to be stored as boost::optional. If the vectors are empty we can ignore them.

Sounds good to me.

> I suggest this is done through methods rather than exposing a field directly. 

That's what I plan on to do. I write it to expose the field directly, just for readability of this document. I'll implement two getters for vld and gld.

**Comment by atamazov** [comment]
@jerryyin Thanks for extensive explanation of the problem and thanks @pfultz2 @whchung  for participation.

Let me begin with high-level concepts. Shall we use vector or std::options is an implementation detail.

Indeed, one of the limitations of current _architecture_ is that it implies that the Solver must know the grid size _before_ compilation of kernels. And the high level question is how to pass grid size from "builder" (a "place" where program is being built) to Invoker.

Architectural changes are always serious ones. Let me think for a while about it.

[Side note] `EuristicInit` is not a part of the Solver/Solution/Invoker architecture. It's an internal detail of implementation a solver. (And the fact that this function is named incorrectly everywhere -- actually a consequence of _one_ typo (mine), -- certifies that we widely use the modern copy-paste software design methodology.) I recommend removing all mentions of it from the Issue Statement.

@jerryyin Please set an urgency label.

**Comment by jerryyin** [comment]
@atamazov Appreciate your response. That' right, it took me a while to realize this is an architectural change. Then pondered on it for quite a while to document this for a thorough discussion. I'm sorry about not being able to recognize this as an important one before this point. The cpp backend should be *mostly* safe at this point in reaching the same launch parameter with MLIR end. However, without running through the entire Resnet50 model configs I can't be sure. Because of this, it is the highest priority item for me.

Would it be realistic for us to reach at an agreement by the end of this week? In the mean time, I can switch my focus back to invokers. Once we agreed on the way to address this, I will code it up ASAP.

**Comment by JehandadKhan** [comment]
> really, can we fix the typo of `EuristicInit`?

MIOpen's original sin :/

**Comment by atamazov** [comment]
@jerryyin Does MLIR backend generate dynamic kernels?

**Comment by atamazov** [comment]
@jerryyin Right now we assume that grid size depend only on problem description and Solver's implementation. We build binary kernels, and construct Kernels objects from that binaries and take grid sizes from `Solver.GetSolution()` (see `Handle::PrepareInvoker()` and `static Invoker PrepareInvoker()` in convolutionocl.cpp).

If kernel was already built, we re-use binary from cache and use `Solver.GetSolution()` to obtain grid size. But if we can't take grid size from solution, because it is generated during the build process, then ___we need to store it (grid size) in the binary cache___, together with the binary.

This is feasible.

The problem, however, is that now we have additional dependency: grid size becomes dependent on MLIR backend. This means that dynamic kernels cannot be implemented without extra invocation of MLIR backend. Right now, if kernel is dynamic, then we simply re-read it from the binary cache and obtain grid size from the Solver (which is fast). But for MLIR backend, if approach won't change, we'll have to invoke backend to get grid size. ___This makes MLIR-generated dynamic kernels useless.___

So the question is: is it possible to _really quickly_ obtain grid size (and only grid size, no need to generate a binary) from the MLIR backend? Is it _capable_ of that (API is not a problem)?

The further steps depend on the answer of this question.

**Comment by jerryyin** [comment]
> Does MLIR backend generate dynamic kernels?

Not now or in June demo, but yet, dynamic kernels is in the roadmap.

> Right now, if kernel is dynamic, then we simply re-read it from the binary cache and obtain grid size from the Solver (which is fast). But for MLIR backend, if approach won't change, we'll have to invoke backend to get grid size.

Is it possible to obtain the grid size not from the solver, but from either `hipoc_program` or `kernel_cache`? Both hold true copies of the grid_size when kernel is compiled.

**Comment by atamazov** [comment]
> Is it possible to obtain the grid size not from the solver, but from either hipoc_program or kernel_cache? Both hold true copies of the grid_size when kernel is compiled.

No. These objects are not persistent. An edge case: An application is restarted. All kernels reside in the persistent binary cache, so no build happens. Where can we get information about grid size?

**Comment by jerryyin** [comment]
> So the question is: is it possible to really quickly obtain grid size (and only grid size, no need to generate a binary) from the MLIR backend? Is it capable of that (API is not a problem)?

@atamazov It is not possible unless we do some partial lowering. My understanding is that once the lowering get started, the build process has begun and we are done with solver stage.

If we do partial lowering inside of the solver, that makes it very strange too. Because then this MLIR solver will have to do part of the build process.

**Comment by jerryyin** [comment]
> But for MLIR backend, if approach won't change, we'll have to invoke backend to get grid size. This makes MLIR-generated dynamic kernels useless.

There's a third approach here: We are still dependent on MLIR backend to get the grid size. However, we don't do full lowering or build again to figure it out. If we can construct the MLIR handle, we can do just enough amount of lowering to get the grid size without a full MLIR backend compilation. This is suppose to be much cheaper than doing full lowering.

**Comment by atamazov** [comment]
> There's a third approach here: We are still dependent on MLIR backend to get the grid size. However, we don't do full lowering or build again to figure it out. If we can construct the MLIR handle, we can do just enough amount of lowering to get the grid size without a full MLIR backend compilation. This is suppose to be much cheaper than doing full lowering in existing mlir build.

That's exactly I am talking about. Is it possible? Could it be really fast?

**Comment by jerryyin** [comment]
> That's exactly I am talking about. Is it possible? Could it be really fast?

Yes! Look, it only require the cheapest first three lowering steps:

https://github.com/ROCmSoftwarePlatform/llvm-project-mlir/blob/afd99d48dd587565f20cd68e2d5534d5d5571db4/mlir/tools/mlir-miopen-lib/mlir-miopen-lib.cpp#L268-L270

```cpp
  pm.addPass(mlir::miopen::createLowerMIOpenOpsStep1Pass());
  pm.addPass(mlir::miopen::createAffineTransformPass());
  pm.addPass(mlir::miopen::createAffixTuningParametersPass(0, 0));
```
The rest of 12 additional stages of lowering can all be skipped. To do this, we will need to invent another API to make it possible to do a subset of `miirLowerBin()`

**Comment by atamazov** [comment]
Let's agree on that.

**Comment by atamazov** [comment]
Hmm...

> If kernel was already built, we re-use binary from cache and use `Solver.GetSolution()` to obtain grid size. But if we can't take grid size from solution, because it is generated during the build process, then ___we need to store it (grid size) in the binary cache___, together with the binary.

It is questionable if a dynamic kernel can be always run with the same grid size.

**Comment by atamazov** [comment]
(but Winograd assembly kernels do that)

**Comment by jerryyin** [comment]
> It is questionable if a dynamic kernel can be always run with the same grid size.

I have no idea. @asroy Could you help clarify that an igemm based dynamic kernel always run with similar or different grid size?

**Comment by atamazov** [comment]
@jerryyin So far, I propose such a plan: Make a new API call, use it in GetSolution().

[Off-topic] Note that we need to discuss generation of dynamic kernels with MLIR, specifically --  how to avoid binary cache misses. There is a pitfall that is easy to overlook.

**Comment by jerryyin** [comment]
@atamazov That's probably not possible to have just the solver to create a MLIR handle and be able to lower through first 4 lowering steps. The solver does not have `num_cu` and `arch` information, which is essential in deriving tuning parameters. See below:

https://github.com/ROCmSoftwarePlatform/MIOpen/blob/3917634a62dd06a86868303b48b15e853efffc38/src/hip/handlehip.cpp#L394-L398

I don't see a easy way to pass through those information to solver as well.

**Comment by carlushuang** [comment]
The grid size of dynamic kernel is always computed from N, C, H, W, K....(`GetSolution`) with its block_size, m_per_block/n_per_block (aka kernel configs), so @jerryyin is it possible that we store in MIOpen solver the information of a kernel's config, or just have a quick approach to querry from MLIR the information, then let solver to compute the gridsize for you?

**Comment by atamazov** [comment]
@carlushuang 
> The grid size of dynamic kernel is always computed from N, C, H, W, K...

Not really. As I said, some Winograd kernels have truly constant grid size. Your comment fixed.

**Comment by atamazov** [comment]
@carlushuang 
>  store in MIOpen solver...

Solvers are stateless objects by design. I think you meant Solutions.

**Comment by atamazov** [comment]
@jerryyin 
> The solver does not have num_cu and arch information...

It has access to everything, just take it. I can show when necessary.

**Comment by jerryyin** [comment]
@atamazov Wants to clarify the new approach here: instead of making changes in `kernel_cache` or `hipoc_program` as mentioned in the `Solution` section, we are making changes in all MLIR solvers, such that:
  - For each solver, it locally it construct MLIR handle and lower the first 3 steps of pipeline, then destroy the handle
    - From there, MLIR solver is able to derive the global/local size, making it behave no different than any other solver
  - Nothing else changes, including MLIR build logic

I'd be fine with this approach as long as:
  - You are not concerned with creating && tossing away the MLIR handle in solver behavior
  - There's a way to pass the runtime information to the `GetSolution()` call, including `num_cu` and `arch`

The only part I'm unclear of how is to pass `num_cu` and `arch` to `GetSolution()`. Is there anything else I should be careful with? Would you think a meeting is necessary? If not for both questions, please comment out the approach just so that I can turn description into code in the next PR.

**Comment by DrizztDoUrden** [comment]
We can also store `function(vector<size_t>(some args like handle probably))` in solution instead of `vector<size_t>` for grid size and implement it in MLIR solvers doing some MLIR calls rather than returning POD value. But that would require writing A LOT of trivial copy-paste code like `[=](auto& handle){ return vld; }`. We could also manually type-erase that to something implicitly initialized from `vector<size_t>` with std::function alternative to skip minor changes in literally every solver.

**Comment by DrizztDoUrden** [comment]
One more option would be to use type erasure instead of `KernelInfo` in the solution with some builder object which defaults to old KernelInfo logic and may be overridden with custom logic like fetching grid size. That would be more friendly to possible future changes to the build process.

**Comment by pfultz2** [comment]
> We may store function(vector<size_t>(some args like handle probably)) in solution instead of vector<size_t>

It will probably need to be `function<std::pair<vector<size_t>, vector<size_t>>(Handle&)>` as it should probably return both global and local together. Although, we should consider making `std::pair<vector<size_t>, vector<size_t>>` a struct.

> for grid size and implement it in MLIR solvers doing some MLIR calls rather than returning POD value. But that would require writing A LOT of trivial copy-paste code like [=](auto& handle){ return vld; }.

I think you can add setters to `KernelInfo` that can set the params with `[=](auto& handle){ return vld; }` rather than having the solvers do this everywhere. The solver will still need to be refactored to do `construction_parameters.set_launch_params({config.BlockSize, 1, 1}, {config.BlockSize * grid_size, 1, 1})` instead of setting them directly.

**Comment by pfultz2** [comment]
> One more option would be to use type erasure instead of KernelInfo in the solution with some builder object which defaults to old KernelInfo logic

That is an interesting options as well. It would reduce the changes needed in all the solvers. However, I think most of the non-MLIR solvers will probably still need to be updated to explicitly construct the old KernelInfo class instead of relying on it being constructed in the solution.

**Comment by DrizztDoUrden** [comment]
There is `std::vector<KernelInfo> construction_params` and it's usually used like `result.construction_params.push_back(construction_params);` so it shouldn't require any changes with implicit ctor allowed.

**Comment by atamazov** [comment]
@jerryyin 
> @atamazov Wants to clarify the new approach here: instead of making changes in `kernel_cache` or `hipoc_program`... we are making changes in all MLIR solvers...

Exactly.

> I'd be fine with this approach as long as:
> * You are not concerned with creating && tossing away the MLIR handle in solver behavior

No, if this is inexpensive in terms of time. Else we can, for example, create a MLIR handle in, say, MIOpen Handle, and use it in Solvers when necessary.

> * There's a way to pass the runtime information to the `GetSolution()` call, including `num_cu` and `arch`

```C++
ConvSolution
FooSolver::GetSolution(const ConvolutionContext& ctx) const
{
    const auto num_cu = ctx.GetStream().GetHardwareComputeUnits(); // or GetMaxHardwareComputeUnits 
                                                                   // depending on your needs
    const auto device_name = ctx.GetStream().GetDeviceName(); // XNACK and SRAMECC are also availalble.
    ...
}
```

**Comment by jerryyin** [comment]
I and @atamazov synced offline. Will address this issue in two steps:

1. Work out an additional lowering pipeline that does just enough lowering to get launch parameters, block size and grid size
2. In MIOpen side, make MLIR solvers to use the new API and populate both parameters as a normal solver does

**Comment by pfultz2** [comment]
> There is std::vector<KernelInfo> construction_params and it's usually used like result.construction_params.push_back(construction_params);

But the elements to `construction_params` needs to be declared as `LegacyKernelInfo`(or whatever we want to call old KernelInfo), because I assume `KernelInfo` is the type erased class.

Nice thing about the type erased approach is that the launch parameters are only computed when the kernel will be launched, and not when calling `GetSolution`. This seems like it would be important for immediate mode, as users can get a list of solutions and then may pick the non-MLIR kernel(which means computing the launch params wouldn't be necessary).

**Comment by atamazov** [comment]
> Nice thing about the type erased approach is that the launch parameters are only computed when the kernel will be launched, and not when calling `GetSolution`.

Yes, this is nice. However we should call GetSolution only when we are going to build and run the kernel(s). Which is basically so now (and if this is not so, then it should be fixed).

**Comment by DrizztDoUrden** [comment]
> But the elements to `construction_params` needs to be declared as `LegacyKernelInfo`(or whatever we want to call old KernelInfo), because I assume `KernelInfo` is the type erased class.

Even if we decide to name type erased class `KernelInfo`, we would only need to apply a trivial text replacing change to solvers, so it doesn't matter much. Otherwise, we won't need any.

**Comment by jerryyin** [comment]
Please note: https://github.com/ROCmSoftwarePlatform/MIOpen/pull/811 filed to address this issue. Please give review comments in the PR if you have any concerns. Otherwise, I will close the issue when PR is merged.

**Comment by jerryyin** [comment]
Closing the issue as #811 is merged.
