### ISSUE TITLE
Implement ResizeNearestNeighbor operation

### ISSUE THREAD

**Issue by dtarakanov1** [ROCmSoftwarePlatform/MIOpen#82]
A TensorFlow operation description looks like:
```JSON
{
  "name": "ResizeNearestNeighbor",
  "op": "ResizeNearestNeighbor",
  "input": [
    "inputs",
    "ResizeNearestNeighbor/size"
  ],
  "attr": {
    "_output_shapes": {
      "list": {
        "shape": [
          {
            "dim": [
              {
                "size": "1"
              },
              {
                "size": "6"
              },
              {
                "size": "6"
              },
              {
                "size": "2"
              }
            ]
          }
        ]
      }
    },
    "align_corners": {
      "b": false
    },
    "T": {
      "type": "DT_FLOAT"
    }
  }
}
```

**Comment by dagamayank** [comment]
@dtarakanov1 Can you elaborate your use-case a bit? Isn't the TensorFlow kernel working for you?

**Comment by dtarakanov1** [comment]
We are implementing an engine that loads a TensorFlow graph and runs it using MIOpen API.
TensorFlow has the ResizeNearestNeighbor operation implemented. But I cannot find anything similar in the MIOpen API.

The TF node definition above is to show the which parameters the operation has.

**Comment by dagamayank** [comment]
@dtarakanov1 MIOpen is not supposed to have a 1:1 mapping to every TensorFlow operator. I believe you can simply implement a HIP kernel for `ResizeNearestNeighbor` if needed. There no plans to currently implement this in MIOpen.
