### ISSUE TITLE
What is kernel text like `gfx900_64.cd.pdb.txt` used for?

### ISSUE THREAD

**Issue by ghostplant** [ROCmSoftwarePlatform/MIOpen#83]
Hi,

I see files like that exist in the path `MIOpen/src/kernels/` and it is configured for different GPU archs.
How could this file help to improve the performance of Conv2D algorithm?

I need something like gfx902_11.pdb.txt but it is not provided yet, and seems like the Conv2D performance on gfx902 is also not very decent.

**Comment by dagamayank** [comment]
@ghostplant You may want to review [this](https://rocmsoftwareplatform.github.io/MIOpen/doc/html/perfdatabase.html) section of the documentation.

The `pdb.txt` file essentially contains auto-tuned parameters for popular convolution configs for a few GPU architectures which ROCm supports. 

Hope this helps.

**Comment by ghostplant** [comment]
@dagamayank Thanks. Is it OK to provide a version for `gfx902_11`?
Or any documentation related to pdb.txt that I can refer to write one for gfx902_11?

**Comment by dagamayank** [comment]
>  Or any documentation related to pdb.txt that I can refer to write one for gfx902_11?

The link I referred above will help you create one for `gfx902_11`. Please refer to that.

**Comment by ghostplant** [comment]
@dagamayank Hi, I actually didn't understand the format of the pdb file. Such as the explaination of `512-28-28-3x3-512-28-28-4-1x1-1x1-1x1-0-NCHW-FP16-F=ConvOclDirectFwdFused:8,32,32,32,4,1,8,2,1;ConvOclDirectFwd:8,32,32,32,4,1,8,2,2`?

**Comment by ghostplant** [comment]
What if I just make a copy of `gfx906_64.cd.pdb.txt` and rename it to `gfx902_11.cd.pdb.txt`?

**Comment by dagamayank** [comment]
> What if I just make a copy of `gfx906_64.cd.pdb.txt` and rename it to `gfx902_11.cd.pdb.txt`?

Yes, that is one way to hack -- it may improve performance from what you see right now but does _not_ guarantee best performance on your platform.

**Comment by ghostplant** [comment]
@dagamayank Does `auto-generated` mean I just need to do nothing even if `gfx902_11.pdb.txt` doesn't exist?

Briefly, I really wish to find out a best performance configuration on my platform gfx902, so what should I do to achieve this purpose? Such as doing nothing, or something to enumerate, e.g.?

**Comment by dagamayank** [comment]
Did you go through the document I mentioned earlier in this thread? First try that out please.

**Comment by ghostplant** [comment]
Yes, but I think I misunderstood the meaning of pdb file, as I though it is a full configuration set containing **all candidates** to try tuning from, and lacking it would cause no candidates to select for tuning and caching the results to other places like `./cache/miopen`.

However, it is just used for memorizing the past tuning result, right?

Just a confirm, if I set the following variables:

```sh
export MIOPEN_FIND_ENFORCE=SEARCH
export MIOPEN_FIND_ENFORCE_SCOPE=ALL
```

would it ensure to find out the **BEST performance configuration**?

**Comment by dagamayank** [comment]
Yes, that would find the best performance for the configs you tuned for. If some other "unknown" configs are encountered in the future then best performance is not guaranteed for them.

**Comment by ghostplant** [comment]
Thanks!
