### ISSUE TITLE
error: expecting exactly one host target but got 0

### ISSUE THREAD

**Issue by Mullich123** [ROCmSoftwarePlatform/MIOpen#840]
Complete error information:

error: expecting exactly one host target but got 0.
MIOpen Error: /root/driver/MLOpen/src/tmp_dir.cpp:47: Can't execute cd /tmp/miopen-gridwise_convolution_backward_data_implicit_gemm_v1r1_nchw_kcyx_nkhw.cpp-89b1-f313-bbb6-980e; /opt/rocm/llvm/bin/clang-offload-bundler --type=o --targets=hip-amdgcn-amd-amdhsa-gfx906 --inputs=/tmp/miopen-gridwise_convolution_backward_data_implicit_gemm_v1r1_nchw_kcyx_nkhw.cpp-89b1-f313-bbb6-980e/gridwise_convolution_backward_data_implicit_gemm_v1r1_nchw_kcyx_nkhw.cpp.o --outputs=/tmp/miopen-gridwise_convolution_backward_data_implicit_gemm_v1r1_nchw_kcyx_nkhw.cpp-89b1-f313-bbb6-980e/gridwise_convolution_backward_data_implicit_gemm_v1r1_nchw_kcyx_nkhw.cpp.o.hsaco --unbundle
2021-04-01 17:45:01.638742: F tensorflow/stream_executor/rocm/rocm_dnn.cc:3572] call to miopenFindConvolutionBackwardDataAlgorithm failed: miopenStatusUnknownError

I am using TensorFlow with rocm and encountered this error.I don't know how to solve the problem.I would appreciate it if you could give me some advice

**Comment by atamazov** [comment]
What type of GPU do you have?

Where did you get TensorFlow for ROCm? You may need to consult there. Note that TensorFlow must be no older than ROCm.

**Comment by atamazov** [comment]
> error: expecting exactly one host target but got 0

This error message is not from MIOpen

**Comment by Mullich123** [comment]
> What type of GPU do you have?
> 
> Where did you get TensorFlow for ROCm? You may need to consult there. Note that TensorFlow must be no older than ROCm.

Well my GPU is ROCm AMD GPU ISA: gfx906,TensorFlow is 2.3.3 and Rocm is 3.9.0

**Comment by Mullich123** [comment]
> > error: expecting exactly one host target but got 0
> 
> This error message is not from MIOpen

I can't find the cause of the error,do you know something about it?

**Comment by atamazov** [comment]
No. Please try to address your problem to https://github.com/ROCmSoftwarePlatform/tensorflow-upstream.

**Comment by Mullich123** [comment]
Thanks a lot
