### ISSUE TITLE
Not enough memory to compile MIOpen

### ISSUE THREAD

**Issue by stmuxa** [ROCmSoftwarePlatform/MIOpen#848]
Generated kernel files are too big
```
./build/include/miopen_kernel.h 
./build/include/miopen_kernel_includes.h 
```
Error while compiling
```
[ 93%] Building CXX object src/CMakeFiles/MIOpen.dir/__/kernel.cpp.o
virtual memory exhausted: Cannot allocate memory
```
Tag: 2.10.0
OS: Ubuntu 18.04
RAM: 8 GB
gcc: 7.5.0

Similar issue on Windows7 with 16 GB RAM and Windows10 with 32 GB RAM under MSVC 2017

**Comment by atamazov** [comment]
Windows is not officially supported.

For Linux, I highly recommend adding 8GB of RAM. Or increase the size of swap file at least. 40GB should be enough (I have 16 ram + 32 swap).

We'll think about splitting the kernel files.

**Comment by stmuxa** [comment]
Linux build succeeded on 16 GB RAM/32 GB swap machine.
As for windows we gonna try MSVC 2019, since MSVC 2017 still has 32bit compiler.

**Comment by stmuxa** [comment]
MSVC 2019 has no issues compiling generated kernels, although has other issues.
