### ISSUE TITLE
Define MIOpen Review Process

### ISSUE THREAD

**Issue by aserio** [ROCmSoftwarePlatform/MIOpen#851]
In order to improve and clarify the MIOpen review process, I am requesting that we discuss and record our policy on reviewing and accepting PRs. My first attempt to capture our current policy can be found here: [MIOPen PR Review Process](http://confluence.amd.com/display/MLSE/MIOpen+PR+Review+Process), however Artem has suggested that we may want to include additional components from the [GitLab Code Review Guidelines](https://docs.gitlab.com/ee/development/code_review.html).

Please discuss the strategies which will best benefit our team keeping in mind:

- The process should be easy to follow
- The process should encourage new team members to participate

**Comment by junliume** [comment]
@aserio @atamazov The above link is not accessible for external users. Here is the wiki page edited by Adrian:
https://github.com/ROCmSoftwarePlatform/MIOpen/wiki/MIOpen-PR-Review-Process
