### ISSUE TITLE
[MI100] Split huge dynamic assembly kernels

### ISSUE THREAD

**Issue by atamazov** [ROCmSoftwarePlatform/MIOpen#854]
Huge assembly kernels must be split. Otherwise both assembly time and load time (from the binary cache) are too long, which negatively affects the performance. See use case and explanations at https://github.com/ROCmSoftwarePlatform/MIOpen/pull/680#issuecomment-804873603.

- [ ] [igemm_fwd_gtc_gfx908.s](https://github.com/ROCmSoftwarePlatform/MIOpen/blob/1207f907a16c6ed39f61c5caf0952bd6f0e70215/src/kernels/dynamic_igemm/igemm_gtc_fwd/igemm_fwd_gtc_gfx908.s) -- 367 kernels
- [ ] [igemm_bwd_gtc_gfx908.s](https://github.com/ROCmSoftwarePlatform/MIOpen/blob/1207f907a16c6ed39f61c5caf0952bd6f0e70215/src/kernels/dynamic_igemm/igemm_gtc_bwd/igemm_bwd_gtc_gfx908.s) -- 122 kernels
- [ ] [igemm_wrw_gtc_gfx908.s](https://github.com/ROCmSoftwarePlatform/MIOpen/blob/1207f907a16c6ed39f61c5caf0952bd6f0e70215/src/kernels/dynamic_igemm/igemm_wrw_gtc_gfx908/igemm_wrw_gtc_gfx908.s) -- 122 kernels

**Comment by shaojiewang** [comment]
I will do it after #691 and #710 was merged.

**Comment by atamazov** [comment]
Ping.

**Comment by junliume** [comment]
@shaojiewang @atamazov are we only tracking this effort on GitHub? Do we have an internal ticket on this performance and quality enhancement?

**Comment by shaojiewang** [comment]
I will create PR to fix this by the end of this week. I was just fully occupied by writing nhwc wrw kernels during the last month. @junliume We do not create a ticket.

**Comment by atamazov** [comment]
via #957
