### ISSUE TITLE
[Testing][Bug]Testing is stuck, boost can't be download

### ISSUE THREAD

**Issue by shurale-nkn** [ROCmSoftwarePlatform/MIOpen#856]
Rocm recipes is outdated, link on boost library is broken, access forbidden
https://dl.bintray.com/boostorg/release/1.72.0/source/boost_1_72_0.tar.bz2

Need to fix dockerfile. Change the way to install boost or to change boost source location.

**Comment by junliume** [comment]
It seems that Bintray, where Ubuntu/Debian and boost.org host packages, is limiting downloads and their account quota has been hit ... "usually" it will be back within a day or so (not in our control) :(

[reproduce]
https://dl.bintray.com/boostorg/release/1.72.0/source/

[ref] 
https://github.com/boostorg/boost/issues/375
https://github.com/boostorg/boost/issues/299

[Temporary Bypass]
Use https://sourceforge.net/projects/boost/files/boost/1.72.0/boost_1_72_0.tar.bz2

![image](https://user-images.githubusercontent.com/7841904/114421112-d279c880-9b69-11eb-9ff1-6cbb6a60cd30.png)

**Comment by shurale-nkn** [comment]
I'm worried that this method may soon cease to exist.
On main page `https://bintray.com/` `Attention: All Bintray services will be deprecated and your accounts will be disabled on May 1st 2021.`

**Comment by pfultz2** [comment]
I updated rocm-recipe to use the URL from sourceforge: 

https://github.com/pfultz2/rocm-recipes/blob/master/recipes/boost/1.72/package.txt

**Comment by junliume** [comment]
@pfultz2 sounds like this issue has been fixed? Usually what's the process and who is gonna verify and close it please? Thanks!

> I updated rocm-recipe to use the URL from sourceforge:
> 
> https://github.com/pfultz2/rocm-recipes/blob/master/recipes/boost/1.72/package.txt

**Comment by grandopener** [comment]
Found this issue searching for my own Boost problem, and I want to share some research.

While source forge is an okay temporary workaround, the official recommendation from boost (not part of their docs yet weirdly/unfortunately) is to use a new URL provided by jfrog: https://lists.boost.org/boost-users//2021/04/90899.php

Most relevant portion quoted:

> So instead of downloading from: 
>         https://dl.bintray.com/boostorg/release/1.76.0/source/boost_1_76_0.tar.gz 
> 
> You should download from: 
>         https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.gz 

Note also that the new link they provide uses redirects so use `-L` with curl or whatever the equivalent is for your particular situation.

**Comment by atamazov** [comment]
@grandopener Thanks!
