### ISSUE TITLE
MIOpen v2.11 

### ISSUE THREAD

**Issue by xudy-cdcs** [ROCmSoftwarePlatform/MIOpen#859]
Where can i get the source code of MIOpen v2.11?

**Comment by xuhuisheng** [comment]
The 2.11 didn't release yet. It would be released with ROCm-4.2.
Please refer the rocm-4.2.x branch <https://github.com/ROCmSoftwarePlatform/MIOpen/tree/rocm-4.2.x>.

**Comment by xudy-cdcs** [comment]
Okay, Thanks!

**Comment by junliume** [comment]
@xudy-cdcs @xuhuisheng MIOpen v2.11.0 is released
https://github.com/ROCmSoftwarePlatform/MIOpen/releases/tag/2.11.0
