### ISSUE TITLE
[implicit GEMM] CalculateGemmSize() should not be a public member function of a Solver

### ISSUE THREAD

**Issue by atamazov** [ROCmSoftwarePlatform/MIOpen#867]
- Solver does not have any member data, so `static` or unnamed namespace should work in the most cases.
- If you need inheritance, make it `private` at least.

Solver design must comply the #866.

**Comment by averinevg** [comment]
@atamazov @junliume Fixed in https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1438

**Comment by atamazov** [comment]
@averinevg 👍
