### ISSUE TITLE
[OpenCL Backend] Build failed

### ISSUE THREAD

**Issue by zpwenjh** [ROCmSoftwarePlatform/MIOpen#872]
Enviroment: ROCm-4.1.0, No GPU，at the newest develop `[HOTFIX] Made kernel sources inlined as multiple files`(5ee21784e3671c1edda336e75c540e69b6c4c36a).
HIP backend build successfully，but the opencl backend failed.
```
[ 31%] Building CXX object src/CMakeFiles/MIOpen.dir/dropout.cpp.o
/home/src/solver/gemm_bwd.cpp:85:6: error: ‘GemmBwdBase’ has not been declared
   85 | bool GemmBwdBase::IsApplicable(const ExecutionContext&,
      |      ^~~~~~~~~~~
/home/src/solver/gemm_bwd.cpp:85:38: error: ‘ExecutionContext’ does not name a type
   85 | bool GemmBwdBase::IsApplicable(const ExecutionContext&,
      |                                      ^~~~~~~~~~~~~~~~
/home/src/solver/gemm_bwd.cpp:86:38: error: ‘conv’ does not name a type; did you mean ‘lconv’?
   86 |                                const conv::ProblemDescription& problem) const
      |                                      ^~~~
      |                                      lconv
```

**Comment by atamazov** [comment]
@zpwenjh Thanks for this finding! Please show your cmake command line.

**Comment by zpwenjh** [comment]
@atamazov Here is my cmake command line:
```
cmake -DMIOPEN_HIP_COMPILER=$ROCM_INSTALL_DIR/llvm/bin/clang++ \
-DCMAKE_PREFIX_PATH="${ROCM_INSTALL_DIR};${ROCM_INSTALL_DIR}/hip;${ROCM_INSTALL_DIR}/llvm;${ROCM_INSTALL_DIR}/rocblas;${ROCM_INSTALL_DIR}/hsa;${ROCM_INSTALL_DIR}/opencl" \
-DMIOPEN_BACKEND=OpenCL \
-DCLANG_TIDY_EXTRA_ARGS="--extra-arg='--rocm-path=${ROCM_INSTALL_DIR}'" \
-DCMAKE_SHARED_LINKER_FLAGS='-Wl,--disable-new-dtags' \
-DCMAKE_EXE_LINKER_FLAGS='-Wl,--disable-new-dtags' \
-DHALF_INCLUDE_DIR=$HALF_DIR/include \
-DBOOST_ROOT=$BOOST_DIR \
-DBOOST_INCLUDEDIR=$BOOST_DIR/include \
-DBoost_USE_STATIC_LIBS=ON \
-DCMAKE_BUILD_TYPE=Release \
-DCMAKE_INSTALL_PREFIX=$INSTALL_DIR/develop/miopen-opencl-rocm4.1.0-release $SOURCE_DIR
```

**Comment by zpwenjh** [comment]
@atamazov In the `gemm_bwd.cpp`，I found this:
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/00d57548c25399186eb201eb2e0e6f7480915c48/src/solver/gemm_bwd.cpp#L50-L61
but in `gemm.cpp`, the `miopen` and `solver` namespace is outside the `#if`.
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/00d57548c25399186eb201eb2e0e6f7480915c48/src/solver/gemm.cpp#L50-L61
That's why error occured while I build MIOpen with opencl backend. I didn't spacify rocblas, miopengemm or miopentensile in cmake command line. If the same in hip backend, rocblas is required Mandatorily.

**Comment by atamazov** [comment]
@zpwenjh Thanks for triaging and fixing this.
