### ISSUE TITLE
[test/ctc] Code quality: undefined-behavior

### ISSUE THREAD

**Issue by shurale-nkn** [ROCmSoftwarePlatform/MIOpen#873]
ctc.cpp:130: The ctc_alpha_cpu function contains write access to an array by negative offset. This code leads to undefined behavior and should be fixed.

https://github.com/ROCmSoftwarePlatform/MIOpen/blob/develop/test/ctc.cpp#L130-L144

To reproduce:
```
CXX=/opt/rocm/llvm/bin/clang++ CXXFLAGS='-Werror'  cmake -DMIOPEN_TEST_FLAGS=' --disable-verification-cache ' -DCMAKE_BUILD_TYPE=debug -DCMAKE_CXX_FLAGS_DEBUG='-g -fno-omit-frame-pointer -fsanitize=undefined -fno-sanitize-recover=undefined ' -DBUILD_DEV=On .. 
make check
```

```
...
/MLOpen/test/ctc.cpp:130:28: runtime error: addition of unsigned offset to 0x000001e4b630 overflowed to 0x000001e4b628
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /MLOpen/test/ctc.cpp:130:28 in 
CMake Error at test_test_ctc.cmake:7 (message):
...
```

**Comment by shurale-nkn** [comment]
The problem is that outside of the function is not aware of such restrictions. And the method of setting arguments does not require passing a pointer not to the beginning of the array. Someone else can use it and get an error.

**Comment by ce1adon** [comment]
Check #886

**Comment by atamazov** [comment]
@shurale-nkn Please specify urgency label for this issue and for #886
