### ISSUE TITLE
[GRU] Redundant copy in RNNForwardTraining

### ISSUE THREAD

**Issue by zpwenjh** [ROCmSoftwarePlatform/MIOpen#880]
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/00d57548c25399186eb201eb2e0e6f7480915c48/src/ocl/rnnocl.cpp#L2256-L2266
Here copy a `hy_h` tensor from `static_cast<int>(offset) + 2 * hy_h + ri * wei_len` to `static_cast<int>(offset) + hid_off + ri * hy_h + static_cast<int>(nLayers) * batch_n * hy_stride` but nerver use the dst position.

**Comment by ce1adon** [comment]
@zpwenjh 
Thank you for your feedback! This copy is part of the calculation.
