### ISSUE TITLE
Constantly spawning clang and LLVM

### ISSUE THREAD

**Issue by emerth** [ROCmSoftwarePlatform/MIOpen#89]
This may be the wrong place for my question. If so, could you point me to the right place?

Generally speaking if I run anything that is built on miopen (rocm tensorflow, rocm caffe, others), when I watch the process listing using top and ps, I see my miopen-based job constantly spawning Clang and various bits of LLVM. 

Also I can see hundreds to thousands of directories in /tmp created, containing .cl files and object files. These directories have names like "/tmp/miopen-tinygemm.cl-ffd9-8066-abab-a8c8/".

This makes for really, reeeeally reeeeaaaally slow execution of my graphs. 

So my question(s) are:

1) Can I make miopen use ROCm/HCC not openCL?
2) Can I make miopen just compile the silly graphs ONCE and then reuse the compiled code?

Thanks very much. I like ROCm/HCC, and miopen looks promising and I hope to use Radeon/Vega  for my work, if I can get the system to work fast.

**Comment by newling** [comment]
This doesn't answer either of your 2 questions, but I can try and explain where the .cl files are from. They are generated by the MIOpenGEMM library, which is one of the libraries which MIOpen uses for GEMMs and convolutions when OpenCL is the backend. The first time a GEMM with new matrix dimensions appears in your graph, a .cl kernel in generated, compiled and cached. This process can be slow, but subsequent calls to GEMM with the same dimensions should be fast as they use the cached kernel. If your graph is "static" (matrix dimensions are unchanged between passes), the first pass through the graph will be slow, but subsequent passes will be fast. If the graph is "dynamic" (calls to GEMMs with different dimensions appear in different passes), subsequent passes might still be slow as new GEMMs kernels are compiled.

**Comment by emerth** [comment]
@newling, thanks! Every piece of info helps toward a solution.

**Comment by atamazov** [comment]
@emerth Please avoid calling miopenFindConvolution*() APIs in the loop (wilth the same dimensions).

**Comment by emerth** [comment]
@atamazov - Hi, & thanks! I will try to do avoid that. Can you give me a brief insight into why I want to avoid that?

**Comment by atamazov** [comment]
During this call miopen finds all available algorithms capable to do the job, compiles them (only if necessary; there is persistent cache within miopen) and runs all these algos to evaluate performance. This function returns a sorted list of available algorithms to the caller.

Once app have this list, it can use algorithm IDs from this list to run convolution(s) found. There is no need to call *Find*() more than once during the application lifetime.

**Comment by emerth** [comment]
Thanks, atamazov!

**Comment by emerth** [comment]
@atamazov - sorry for silly question: if a given algorithm is going to be invoked X number of times but each time with different sized inputs, does that cause miopen to compile the algorithm X times?
