### ISSUE TITLE
Array Access Out of Bounds in OCL Kernel MIOpenConvUniC

### ISSUE THREAD

**Issue by marty1885** [ROCmSoftwarePlatform/MIOpen#9]
Hello. Further looking into the crash of MIOpen on my system (#5). I found that the OCL kernel function `MIOpenConvUniC` is the cause of MIOpen failing tests on my system.
The following code exists in function `Conv` inside `MIOpenConvUniC.cl`. 
```C++
    uint wei_stg_off = wei_stg_base_off +
        o_c * MLO_N_IN_TILES_PERSTACK * MLO_FILTER_SZ +
        k_act * MLO_FILTER_SIZE0;
    for(uint i = 0; i < MLO_FILTER_SIZE0; ++i)
    {
        pvt_wei_stage[i] = lcl_wei[wei_stg_off + i];
    }
```
Where the array `lcl_wei` has size `MLO_WEIGHTS_SZ` (3200 in test 5). But `wei_stg_off` can go up to 6395(again, in test 5). This behavior can be shown by adding the following snippet before the for loop and comment the loop out (Else OpenCL crashes and the printf buffer will not be displayed).
```C++
    if(wei_stg_off+MLO_FILTER_SIZE0 >= MLO_WEIGHTS_SZ)
    {
        printf("%d\n",wei_stg_off);
    }
```

Tested on Intel OpenCL SDK with OpenCL CPU Device / Nvidia OpenCL (tested on both).

**Comment by dagamayank** [comment]
@marty1885 Thanks for digging in more.

Can you provide the input configs that is triggering this crash? We would like to see if we can reproduce this on our end. I would like reiterate supporting non-AMD platforms is not in our plans at the moment.

You can set this env. variable to dump some debug info. Please send the last outputs just before the crash.
`export MIOPEN_ENABLE_LOGGING=1`

**Comment by dagamayank** [comment]
>  I doubt that this is the case where it won't crash on a AMD GPU but will on others

All the tests work fine on AMD GPUs. We will double-check again based on your log. Thanks for it.

> BTW, what counts as a AMD Platform?

The README clearly outlines the Prerequisites for MIOpen.

Prerequisites
    A ROCm enabled platform, more info here
    Base software stack, which includes
        OpenCL - OpenCL libraries and header files
        HIP -
            HIP and HCC libraries and header files
            clang-ocl -- required
    MIOpen relies on the miopengemm library to enable several functionalities that require GEMM. miopengemm is recommended but not required.
    ROCm cmake modules can be installed from here

**Comment by gstoner** [comment]
@marty1885  I want to thank you for all of your enthusiasm for MIOpen,  but the current version of MIOpen in Generation 1 is targeted at ROCm Driver and ROCm enabled AMDGPUpro driver.   

It is not a design failure it does not support other platforms, right now with the resource we have on the project for development and test, we need to focus on our hardware first and current software stacks first and formost.   Aslo we have  acompititve situation with cuDNN, right now they use asembly kernel to make there solution run fast, OpenCL alone is not solution to to compete with this..  

You may also want to look at Intel clDNN library which only runs on Intel's Hardware  I know it currently does not support AMD GPU or NVIDIA GPU's   

Also I saw you had issue installing ROCm in your blog, but then I see you do not have hardware that supports the ROCm stack in the forum.  If you have issue  please log it at https://github.com/RadeonOpenCompute/ROCm/issues .
