### ISSUE TITLE
[OCL][BatchNorm] Verification failed

### ISSUE THREAD

**Issue by zpwenjh** [ROCmSoftwarePlatform/MIOpen#915]
The following params of `bnorm` of `bnormfp16` will cause presicion verification failure.
```
MIOpenDriver bnorm -n 38 -c 128 -H 80 -W 80 -m 1 --forw 0 -b 1 -r 1 -V 1
MIOpenDriver bnormfp16 -n 38 -c 128 -H 80 -W 80 -m 1 --forw 0 -b 1 -r 1 -V 1
MIOpenDriver bnormfp16 -n 38 -c 256 -H 20 -W 20 -m 1 --forw 0 -b 1 -r 1 -V 1
MIOpenDriver bnormfp16 -n 38 -c 32 -H 160 -W 160 -m 1 --forw 0 -b 1 -r 1 -V 1
MIOpenDriver bnormfp16 -n 38 -c 512 -H 20 -W 20 -m 1 --forw 0 -b 1 -r 1 -V 1
MIOpenDriver bnormfp16 -n 38 -c 64 -H 160 -W 160 -m 1 --forw 0 -b 1 -r 1 -V 1
MIOpenDriver bnormfp16 -n 38 -c 64 -H 80 -W 80 -m 1 --forw 0 -b 1 -r 1 -V 1
MIOpenDriver bnormfp16 -n 64 -c 256 -H 20 -W 20 -m 1 --forw 0 -b 1 -r 1 -V 1
MIOpenDriver bnormfp16 -n 64 -c 512 -H 20 -W 20 -m 1 --forw 0 -b 1 -r 1 -V 1
```

@atamazov UPDATE: More failing configs here: https://github.com/ROCmSoftwarePlatform/MIOpen/pull/916#issuecomment-840199623

**Comment by atamazov** [comment]
@zpwenjh Thank you!

**Comment by ce1adon** [comment]
@muralinr @atamazov 
See PR https://github.com/zpwenjh/MIOpen/pull/14 for these configures.

**Comment by atamazov** [comment]
> @muralinr @atamazov
> See PR [zpwenjh#14](https://github.com/zpwenjh/MIOpen/pull/14) for these configures.

Would you like me or Murali to add regression tests?

**Comment by ce1adon** [comment]
@atamazov @muralinr 
Please go ahead and add regression tests, with also these reported configures: https://github.com/ROCmSoftwarePlatform/MIOpen/pull/916#issuecomment-840199623

**Comment by atamazov** [comment]
@junliume Could you please assign the owner of BN primitive to add regressions tests? Thanks!

**Comment by muralinr** [comment]
> @junliume Could you please assign the owner of BN primitive to add regressions tests? Thanks!

@atamazov I will add these failures to regression tests.

**Comment by atamazov** [comment]
@muralinr Wow! It's you)) Thanks! :+1:
