### ISSUE TITLE
Does miopenPoolingAverage algorithm count padding cells?

### ISSUE THREAD

**Issue by ghostplant** [ROCmSoftwarePlatform/MIOpen#93]
CUDNN has two different algorithm for PoolingAvg:
CUDNN_POOLING_AVERAGE_COUNT_EXCLUDE_PADDING;
CUDNN_POOLING_AVERAGE_COUNT_INCLUDE_PADDING;

However, MIopen only has one miopenPoolingAverage, so which one above correspond with this unique miopenPoolingAverage?

**Comment by daniellowell** [comment]
Inclusive will be part of 1.8 release.

**Comment by ghostplant** [comment]
@daniellowell What about SoftmaxForward? What is it currently implemented for, CUDNN_SOFTMAX_MODE_INSTANCE, or CUDNN_SOFTMAX_MODE_CHANNEL?

**Comment by daniellowell** [comment]
Likely the softmax change will be in the release after.

**Comment by ghostplant** [comment]
@daniellowell So is MIOpen 1.8 incrementally updated in this master branch?

**Comment by daniellowell** [comment]
Master branch will be updated relatively soon. I'll also tag a 1.8 release.

**Comment by ghostplant** [comment]
Confirmed miopenPoolingAverageInclusive.
