### ISSUE TITLE
Failure - Install Dependency

### ISSUE THREAD

**Issue by kiritigowda** [ROCmSoftwarePlatform/MIOpen#938]
Using `cmake -P install_deps.cmake --minimum` to install deps fails due to boost source location change to - `https://boostorg.jfrog.io/artifactory/main/release/1.72.0/source/boost_1_72_0.tar.bz2`

```
Downloading https://dl.bintray.com/boostorg/release/1.72.0/source/boost_1_72_0.tar.bz2
CMake Error at /usr/local/share/cmake/cmakeget/CMakeGet.cmake:151 (message):
  Download failed: "HTTP response code said error":
  https://dl.bintray.com/boostorg/release/1.72.0/source/boost_1_72_0.tar.bz2;/tmp/cget-19-32-58-Qau9p-1/download/boost_1_72_0.tar.bz2;SHOW_PROGRESS
Call Stack (most recent call first):
  /usr/local/share/cmake/cmakeget/CMakeGet.cmake:293 (cget_download)
  /usr/local/share/cmake/cmakeget/CMakeGet.cmake:394 (cget_fetch)
  /usr/local/share/cmake/cmakeget/CMakeGet.cmake:461 (cmake_get)
  /usr/local/share/cmake/cmakeget/CMakeGet.cmake:383 (cmake_get_from)
  /usr/local/share/cmake/cmakeget/CMakeGet.cmake:461 (cmake_get)
  install_deps.cmake:106 (cmake_get_from)
```

**Comment by junliume** [comment]
@kiritigowda @JehandadKhan 
bintray has sunset support for download boost since May 1st, please refer to the below comment for new link
https://github.com/ROCmSoftwarePlatform/MIOpen/issues/856#issuecomment-827003984

I thought it was fixed already in MIOpen or should we try again?

**Comment by JehandadKhan** [comment]
@junliume The cmake based command still needs to be fixed and @pfultz2 has taken up that task. Alternatively @kiritigowda can use the same commands used in our docker to install dependencies.

**Comment by junliume** [comment]
> @junliume The cmake based command still needs to be fixed and @pfultz2 has taken up that task. Alternatively @kiritigowda can use the same commands used in our docker to install dependencies.

Hi @pfultz2, @kiritigowda mentioned the issue is still persistent in https://github.com/ROCmSoftwarePlatform/MIOpen/issues/965 

Do we have a permanent fix for the issue please?

**Comment by kiritigowda** [comment]
DockerFile to Reproduce the issue - [miopenDeps.txt](https://github.com/ROCmSoftwarePlatform/MIOpen/files/6601277/miopenDeps.txt)

**Comment by atamazov** [comment]
2.11 does not contain #922. I recommend the following:
- Merging `v2.11_fix` to `master`
- Then, cherry-picking #922 to `master`
- Moving the `2.11` label to the tip of `master`
- Updating [2.11 release](https://github.com/ROCmSoftwarePlatform/MIOpen/releases/tag/2.11.0) & its assets

**Comment by atamazov** [comment]
Alternatively, the 2.11.1 "patch" release can be created.

**Comment by junliume** [comment]
> Alternatively, the 2.11.1 "patch" release can be created.

@JehandadKhan 2.11.1 sounds like an easier path, is there any issues which might be holding us back? e.g. if it is easier to change 2.11 itself than to change scripts used everywhere else in the ROCm suite? :)

**Comment by atamazov** [comment]
It seems more logical to create 2.11.1 and it looks more logical than updating 2.11. Release is something that shouldn't be changed after, um, releasing.

**Comment by junliume** [comment]
@kiritigowda The issue seems to be not reproducible on my end. To be safe I pulled a fresh docker ubuntu 18.04 and started from completely fresh:

   apt update
   apt install wget
   wget https://github.com/ROCmSoftwarePlatform/MIOpen/archive/2.12.0.zip && unzip 2.12.0.zip
   apt install unzip
   unzip 2.12.0.zip
   cd MIOpen-2.12.0/
   apt install cmake
   **apt-get install python3-venv**
   apt-get install clang
   **export LC_ALL=C.UTF-8
   export LANG=C.UTF-8**
   cmake -P install_deps.cmake --minimum

and the dependency install (minimal) is successful. Could you check the above **marked** region and try again? A log would be useful for diagnostics too. Thanks!

**Comment by kiritigowda** [comment]
@junliume thanks for looking into this. I am attaching 2 docker files to reproduce this issue on CentOS 7 & Ubuntu 18.04. I would appreciate it if you could find a fix or maybe find the problem with my docker file that I am missing.

* On CentOS 7 - [miopen-test-centos.dockerfile.txt](https://github.com/ROCmSoftwarePlatform/MIOpen/files/6971338/miopen-test-centos.dockerfile.txt)

**build** - `sudo docker build -f miopen-test-centos.dockerfile.txt -t miopen-test-centos .`

**error-log**
```
Successfully installed cget-0.1.9 click-8.0.1 importlib-metadata-4.6.3 six-1.16.0 typing-extensions-3.10.0.0 zipp-3.5.0
You are using pip version 9.0.3, however version 21.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Traceback (most recent call last):
  File "/usr/local/bin/cget", line 11, in <module>
    load_entry_point('cget==0.1.9', 'console_scripts', 'cget')()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1043, in main
    _verify_python_env()
  File "/usr/local/lib/python3.6/site-packages/click/_unicodefun.py", line 100, in _verify_python_env
    raise RuntimeError("\n\n".join(extra))
RuntimeError: Click will abort further execution because Python was configured to use ASCII as encoding for the environment. Consult https://click.palletsprojects.com/unicode-support/ for mitigation steps.

This system lists some UTF-8 supporting locales that you can pick from. The following suitable locales were discovered: en_US.utf8
1
CMake Error at install_deps.cmake:7 (message):
  Process failed:
  COMMAND;/usr/local/bin/cget;-p;/usr/local;init;-DCMAKE_INSTALL_RPATH=/usr/local/lib
Call Stack (most recent call first):
  install_deps.cmake:100 (cget_exec)
  install_deps.cmake:112 (cget)
```

* On Ubuntu 18.04 - [miopen-test-ubuntu.dockerfile.txt](https://github.com/ROCmSoftwarePlatform/MIOpen/files/6971347/miopen-test-ubuntu.dockerfile.txt)

**build** - `sudo docker build -f miopen-test-ubuntu.dockerfile.txt -t miopen-test-ubuntu .`

**error-log**

```
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt-get install python3-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: ['/usr/local/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']

1
CMake Error at install_deps.cmake:7 (message):
  Process failed: COMMAND;/usr/bin/python3;-m;venv;/usr/local
Call Stack (most recent call first):
  install_deps.cmake:51 (cget_exec)
  install_deps.cmake:57 (virtualenv_create)
  install_deps.cmake:65 (virtualenv_install)
```

**Comment by junliume** [comment]
[miopen-test-ubuntu.dockerfile.txt](https://github.com/ROCmSoftwarePlatform/MIOpen/files/6977169/miopen-test-ubuntu.dockerfile.txt)
@kiritigowda the slightly modified dockerfile worked on Ubuntu (I have tested locally). We suspect centOS is very similar issue.
Please remove the part:
>> wget https://sourceforge.net/projects/half/files/half/1.12.0/half-1.12.0.zip && \
        unzip half-1.12.0.zip -d half-files && sudo cp half-files/include/half.hpp /usr/local/include/
since it is also part of the MIOpen install_deps process. 
Thanks!

**Comment by atamazov** [comment]
@kiritigowda Please confirm that issue is fixed, thanks!
