### ISSUE TITLE
Evaluate Igemm algorithm tuning effectiveness

### ISSUE THREAD

**Issue by jerryyin** [ROCmSoftwarePlatform/MIOpen#939]
## Purpose

Provide support to decide whether it is necessary to implement tuning for MLIR igemm solvers.

## Setup

The experimentation will be carried upon resnet50 configs, base driver: ROCm 4.0. Container: ROCm 3.7.

MIOpen: Same latest commit, on develop branch.

Solvers selections – we pick the **cpp** solvers where MLIR solvers prototyped from:
 - Fwd: NCHW, v4r4, ConvHipImplicitGemmV4R4Fwd
 - Bwd: NCHW, v4r1, ConvHipImplicitGemmBwdDataV4R1Xdlops
 - WrW: NCHW, v4r4, ConvHipImplicitGemmV4R4WrW

*Note: I selected above as a mixture list as I don’t find non-xdlops version of bwd path or xdlops version of fwd/wrw path. Though it does represent a fair set of solvers where MLIR prototyped from.*

Machine – gfx908, as it is capable to running both xdlops and non-xdlops

Batch size: 256

## Experiments:
 - Baseline group: Run with perfdb disabled (Heuristically come up with tuning parameters)
 - Perfdb group: Run with perfdb enabled

## Evaluation:

We will evaluate the performance gap % between the perfdb group and baseline group, in gpu kernel time only. We set 5%~10% as the performance threshold:
 - If performance gap is above 10% in general for all igemm resnet50 config, we will implement tuning for igemm mlir solvers
 - If performance gap is between 5% ~ 10%, we will likely implement tuning. Pending approval from @junliume and @mvermeulen.
 - If performance gap is below 5% in general, we will **NOT** implement tuning.

**Comment by atamazov** [comment]
None objections. Questions:
- What is the purpose of evaluation? (I know but let's inform all others)
- Pre-requisites? I see gfx908, but what is supposed ROCm version, base driver version? Are you going to use DEV build or installed build of MIOpen?
- How are you going to evaluate the performance? Does the host-side overhead important or only GPU time should be taken into account?

**Comment by jerryyin** [comment]
>     * What is the purpose of evaluation? (I know but let's inform all others)

It was in the evaluation section but I agree it is not explicit. I have added the first section to be explicit.

>     * Prerequisites? I see gfx908, but what is supposed ROCm version, base driver version? Are you going to use DEV build or installed build of MIOpen?

Updated in the ticket description. The key is that both experiment group and control group are from same environment, same machine, same setup, except use of perfdb.

>     * How are you going to evaluate the performance? Does the host-side overhead important or only GPU time should be taken into account?

Updated in the evaluation section. I'm going to use MIOpenDriver reported GPU kernel time.

**Comment by JehandadKhan** [comment]
@jerryyin To assess the effectiveness of tuning it might be more enlightening if we select configs that are not ResNet/ResNext variants since usually the defaults baked in the solvers are selected by keeping these networks in mind. Would you agree ?

**Comment by jerryyin** [comment]
> @jerryyin To assess the effectiveness of tuning it might be more enlightening if we select configs that are not ResNet/ResNext variants since usually the defaults baked in the solvers are selected by keeping these networks in mind. Would you agree ?

Good point, I don't think I have a good enough understanding of the tuning process. From what you mentioned seem to indicate that we only record the entry in perfdb when it is the best algorithm for the config. (and do not record those secondary but also available algorithms). 

If that is the case, then I should selected the configs which I can make sure there are entries from the perfdb. I'd say select 20 entries each from perfdb and execute those. Would that be a better baseline, or you have any additional suggestions?

**Comment by atamazov** [comment]
[Off-topic]
> From what you mentioned seem to indicate that we only record the entry in perfdb when it is the best algorithm for the config. (and do not record those secondary but also available algorithms).

No. Tuna optimizes ALL the applicable Solvers, including those that are not the best within Algorithm. For example, is we have two tunable Direct solvers, then Tuna ensures that optimal values are produced (and written into db) for both. Only after all applicable Solvers are tuned, we can find the best one.

**Comment by atamazov** [comment]
> I'd say select 20 entries each from perfdb and execute those. 

@jerryyin Good idea. However I would recommend not 20 but about of 100 entries (per each solver).

@JehandadKhan Can you retrieve some data from the Tuna DB? I mean lists of problem configs for which Tuna DB contains optimized PerformanceConfigs for the solvers in question? The first is for ConvHipImplicitGemmV4R4Fwd, the second is for ConvHipImplicitGemmV4R1Xdlops, the third is for ConvHipImplicitGemmV4R4WrW. If these lists comply the MIOpenDriver command line format (I need only options), then I can quickly make a bash script that runs these solvers and writes performance data to csv files for later analysis.

**Comment by jerryyin** [comment]
@atamazov Thanks for the explanation.

> then Tuna ensures that optimal values are produced (and written into db) for both

Okay, since db has the entry anyways I don't see why we should not use `Resnet50` configs. They might not be the optimal amongst all algorithms, however, this is a comparison of the same algorithm against itself. Thus the two topics are orthogonal.

> However I would recommend not 20 but about of 100 entries (per each solver).

Agreed. It is more representative with a larger problem set.

> then I can quickly make a bash script that runs these solvers and writes performance data to csv files for later analysis.

That does sounds like a useful tool-set and can be used not only in evaluation but trimming of the perfdb if necessary.

**Comment by jerryyin** [comment]
To make sure we do not duplicate our effort, this is to let you know that I'm WIP in the execution scripts. For the first round of evaluation I will write the script, which is flexible enough to consume MIOpenDriver configs. I will be using resnet50 for the evaluation because I already have those configs. Then when it is done, I will share the script as well as instructions so that we can easily take the second round of evaluation of 100 configs if necessary.

**Comment by jerryyin** [comment]
### Evaluation Result for Resnet50

Scripts: In this [repository](https://github.com/jerryyin/MIOpenDriver-eval).

| Flavor        | Average Runtime | no perfdb/perfdb |
| ------------- | --------------- | ---------------- |
| fwd no perfdb | 3.205941909     |                  |
| fwd perfdb    | 3.162810295     | 1.013637117      |
| bwd no perfdb | 2.341242818     |                  |
| bwd perfdb    | 2.168455773     | 1.079627304      |
| wrw no perfdb | 89.7853120455   |                  |
| wrw perfdb    | 30.58054759091  | 2.936026956      |

### Results summary

 - Very limited performance performance improvement in fwd
 - Reasonable improvement in bwd
 - Significant improvement in wrw, configs execution time in general improved by 2x ~ 3x

**Comment by atamazov** [comment]
@jerryyin Please attach the lists of configs for Fwd/Bwd/Wrw, in MIOpenDriver compatible option format, if possible. Thanks.

**Comment by jerryyin** [comment]
@atamazov Sure, I have already shared in a public repository, [here](https://github.com/jerryyin/MIOpenDriver-eval/blob/master/resnet50-miopen-configs).

**Comment by jerryyin** [comment]
Closing the ticket as we decide tuning is still necessary especially based on `wrw` result.
