### ISSUE TITLE
Remove W/A that disables ConvAsmImplicitGemmGTCDynamicBwdXdlops

### ISSUE THREAD

**Issue by atamazov** [ROCmSoftwarePlatform/MIOpen#948]
Let's thoroughly check FP16 correctness, resolve all found correctness issues by fixing the root reason of those, verify that https://ontrack-internal.amd.com/browse/SWDEV-286774 remains fixed, and remove W/A introduced in #945 and updated in #949.

~Most likely, only FP16 has correctness issues, but I am not sure (so W/A disables both FP32 and FP16). Perhaps this is an overkill and only FP16 has issues. If so, then please first create a PR that narrows the W/A to FP16 only.~

The solver is originated from #441, FP16 has been added in #710.

**Comment by atamazov** [comment]
Please note that `test_conv_igemm_dynamic_xdlops_bwd` is not allowed for HALF.

**Comment by atamazov** [comment]
[Informative] Right now I am trying to narrow `WORKAROUND_SWDEV_286774` to FP16 configs only.

**Comment by carlushuang** [comment]
This is bwd fp16 NCHW kernel for asm igemm. @carlushuang @shaojiewang
