### ISSUE TITLE
Update cmake version to 3.15.1

### ISSUE THREAD

**Issue by ce1adon** [ROCmSoftwarePlatform/MIOpen#960]
This issue intends to discuss and solve the following problem:

Tensile with version >= 4.2 requires a cmake version >= 3.15.1 to build.
Do we want to:
1. allow version selection based on rocm version in Dockerfile;
2. Simply update cmake in Dockerfile to 3.15.1;
3. Other thoughts and concern

**Comment by junliume** [comment]
https://github.com/ROCmSoftwarePlatform/MIOpen/pull/961#discussion_r644240132

**Comment by atamazov** [comment]
I am not an expert in this field.

**Comment by junliume** [comment]
Closed by #961 and #978
