### ISSUE TITLE
[Build Error] Miir.h not found

### ISSUE THREAD

**Issue by zpwenjh** [ROCmSoftwarePlatform/MIOpen#964]
When build miopen-develop([4f48facd](https://github.com/ROCmSoftwarePlatform/MIOpen/commit/4f48facd76f26d7939fa53f16ba44086e8c58d43)) on ROCm-3.9.1, using the following compilation parameters:
![image](https://user-images.githubusercontent.com/63989327/120582631-5dd35400-c45f-11eb-9b01-b500f79af5f0.png)

Error log as follows:
![image](https://user-images.githubusercontent.com/63989327/120582009-5495b780-c45e-11eb-9a9f-253016cf5b69.png)

How can I build successfully?

**Comment by junliume** [comment]
@zpwenjh Thank you for raising the issue, have you checked if MIOPEN_USE_MLIR is accidentally turned on? 
The issue is directly related to:
https://github.com/ROCmSoftwarePlatform/MIOpen/issues/908
https://github.com/ROCmSoftwarePlatform/MIOpen/pull/909 

cc: @jerryyin @atamazov

**Comment by junliume** [comment]
@carlushuang Issue is reproducible using user provided docker file, could you take a look?

**Comment by junliume** [comment]
Hi @zpwenjh, have you tested on version after fixes in #909? If the issue is no longer observed, please close this issue. Thanks!

**Comment by atamazov** [comment]
4f48facd includes #909. @jerryyin Please look into this issue, thanks.

**Comment by zpwenjh** [comment]
@atamazov  I'm sorry that I got the wrong version. I didn't use [4f48facd](https://github.com/ROCmSoftwarePlatform/MIOpen/commit/4f48facd76f26d7939fa53f16ba44086e8c58d43)

**Comment by atamazov** [comment]
@zpwenjh Okay, no problem!
