### ISSUE TITLE
Wrong results for miopenTransformTensor() from MIOpen 1.8

### ISSUE THREAD

**Issue by ghostplant** [ROCmSoftwarePlatform/MIOpen#98]
Using `miopenTransformTensor()` to compute `y = 0.4 * y + 0.7 * x`, and the answer is just not correct. By simple profiling, no any compute kernel is even launched on GPU when calling this API.

**Comment by daniellowell** [comment]
How was this test run? Via MIOpenDriver?

**Comment by ce1adon** [comment]
There is a ctest for tensor_transform. Currently we only support alpha = 1, beta =0 cases. 
I will work on supporting arbitrary alpha/beta.

**Comment by ghostplant** [comment]
@ce1adon OK.. It means this API just supports y = x ..?

**Comment by ce1adon** [comment]
Currently yes @ghostplant

**Comment by ce1adon** [comment]
@ghostplant 
Hey I'm working on this issue by providing better functionality and documentation. Would you like to describe a few more details or examples that you need from miopenTransformTensor()? What logic are you expecting this function to fulfill? Are you working on y = b * y + a * x with x and y in the same dimension, or you expecting some format transform in x and y at the same time (some details would be great)?

Thanks!

**Comment by ghostplant** [comment]
@ce1adon Hi, mostly includes b = [-1, 0, 1], a = [-1, 0, 1].

For example, I wanted to it for self-add and self-minus in the past.
Although `miopenOpTensor()` can do the similar thing, but it is 2-input based, so it is not always cheap to compute in terms of resource occupation.

I didn't feed y and x to be of different shapes before, but that function is supposed to accept cases like doing broadcast add/...

**Comment by daniellowell** [comment]
MIOpen needs a broadcast operation for sure. I think this specific change may be more narrow at first to encompass transforms on tensors of the same dimension. We can do another pass to implement broadcast tensor op.

**Comment by ce1adon** [comment]
@ghostplant @daniellowell 
Thank you!
Let's make your expectation high priority and focus on fulfill it.

**Comment by ghostplant** [comment]
@ce1adon Thanks!

**Comment by ce1adon** [comment]
@ghostplant Do you mean something similar to TensorFlow's broadcast function?

**Comment by ghostplant** [comment]
yes, also similar to cudnnAddTensor.

**Comment by ce1adon** [comment]
We do have similar function: miopenOpTensor().
The difference of it with cudnnAddTensor() is that miopenOpTensor() handle a more general case c= beta* c + alpha1* a + alpha2* b. 
You can also perform multiple(), min() and max() using this function.

To mimic cudnnAddTensor() behavior, you can arrange as below. Make sure those dimensions you want to broadcast equal to 1 and other dimensions matches the cTensor.
```
float alpha1 = 0;
miopenOpTensor(handle,
miopenTensorOpAdd,
&alpha1,
cDesc,
C,
&alpha,
aDesc,
A,
&beta,
cDesc,
C);
```

**Comment by ghostplant** [comment]
@ce1adon Hi, according to https://github.com/ROCmSoftwarePlatform/MIOpen/blob/master/src/ocl/tensorocl.cpp#L1192,
it doesn't support broadcast, and the runtime error output is:
```sh
MIOpen Error: /root/driver/MLOpen/src/ocl/tensorocl.cpp:1194: A and C Tensors do not match
terminate called after throwing an instance of 'std::runtime_error'
  what():
error: miopenOpTensor(global_cudnn_handle, miopenTensorOpAdd, &alpha, in_desc, input0, &beta, out_desc, output0, &beta, out_desc, output0) failed with error
file: /host/root/nnfusion_rt/rocm_codegen/nnfusion_rt.cpp
line: 441
msg: miopenStatusUnknownError
```

**Comment by ghostplant** [comment]
@ce1adon Sorry, I just verified that the input tensor to broadcast must be as the 2rd input argument.
