### ISSUE TITLE
[TESTS] Implement detection of GPU type

### ISSUE THREAD

**Issue by atamazov** [ROCmSoftwarePlatform/MIOpen#985]
This could be implemented in CMake. According to that, the default values of CMake variables like `MIOPEN_TEST_GFX908` should be set.

Right now we at MIOpen use node labeling for that. However, the users can't simply run "make check", they need to check the GPU type and set a CMake variable accordingly.

This is not good, especially for our CQE, who use the same script for all GPU types. For now, I am recommending the following W/A in the testing script:
```bash
tempcmd="/opt/rocm/opencl/bin/clinfo | grep gfx908"; eval "$tempcmd"; if [[ $? -ne 0 ]] ; then export MIOPEN_TEST_GFX908_VALUE=Off; else export MIOPEN_TEST_GFX908_VALUE=On; fi
...
cmake ... -DMIOPEN_TEST_GFX908=${MIOPEN_TEST_GFX908_VALUE} ...
```

Originated from https://ontrack-internal.amd.com/browse/SWDEV-290980?focusedCommentId=7474697&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-7474697

**Comment by JehandadKhan** [comment]
How about checking the GPU type from the handle in the test and return success with a message which says that the test is skipped since there is no GPU for it.

**Comment by atamazov** [comment]
This wouldn't work for "custom" tests, which are basically sets of executables with options...

**Comment by atamazov** [comment]
@pfultz2 Can you please advice how can we detect GPU type from CMake?

**Comment by pfultz2** [comment]
> Can you please advice how can we detect GPU type from CMake?

You can run `execute_process` to run a command that shows what gpus are installed via rocminfo. Of course, I dont know how easy it is to parse that.

Alternatively, we could update the test driver to only run on certain archs. We could add a flag like `--only-arch` that will skip the tests if the arch doesn't match. Such a flag can be added to the custom tests.

**Comment by atamazov** [comment]
@pfultz2 
> You can run `execute_process` to run a command that shows what gpus are installed via rocminfo. Of course, I dont know how easy it is to parse that.

Thanks for the recommendation. Theoretically we can grep output and check the status code, but I am now aware of CMake-specific implementation details.

> Alternatively, we could update the test driver to only run on certain archs. We could add a flag like `--only-arch` that will skip the tests if the arch doesn't match. Such a flag can be added to the custom tests.

Unfortunately, this won't work in all cases because we have custom tests. Those are are basically sets of executables with GPU-specific options... See `test_conv_igemm_dynamic_xdlops_bwd`, for example.

**Comment by junliume** [comment]
@atamazov @pfultz2 
If not resolved, we might keep getting reports like [SWDEV-292684](https://ontrack-internal.amd.com/browse/SWDEV-292684)
Maybe something similar to this? https://stackoverflow.com/a/37995691/6889542

**Comment by junliume** [comment]
@atamazov @pfultz2 @JehandadKhan this issue is popping up a lot. We can continue this _whack a mole game_ till we have a more permanent fix from this PR.
ref:  [SWDEV-290980](https://ontrack-internal.amd.com/browse/SWDEV-290980)
related: [SWDEV-289452](https://ontrack-internal.amd.com/browse/SWDEV-289452)  [SWDEV-293077](https://ontrack-internal.amd.com/browse/SWDEV-293077)  [SWDEV-292684](https://ontrack-internal.amd.com/browse/SWDEV-292684)
Meanwhile, in parallel, I have requested to see if CQE can test on specific ASICs, so that we do not have more tickets waiting in line, and can have some more breath room for this PR to mature.

**Comment by atamazov** [comment]
I am starting to work on this.

**Comment by atamazov** [comment]
via #1024
