### ISSUE TITLE
Add regression tests for #989

### ISSUE THREAD

**Issue by atamazov** [ROCmSoftwarePlatform/MIOpen#993]
Regression test is missing. I am not going to delay merging this PR (and cherry-picking it to 4.3), for the sake of speed. But if this PR does not contain a regression test, then I'll open a high priority ticket for this.

_Originally posted by @atamazov in https://github.com/ROCmSoftwarePlatform/MIOpen/issues/989#issuecomment-864414465_

**Comment by carlushuang** [comment]
will add a test case for this issue till https://github.com/ROCmSoftwarePlatform/MIOpen/pull/991 is merged

**Comment by atamazov** [comment]
@carlushuang #991 is merged
